### ISSUE TITLE
As Zofar-User I want a rearranged version of a SingleChoice-Matrix (Comparison)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#100]
The usual SingleChoice-Matrix should be rearranged in the way where the items are defined in columns and answer options are defined in rows (in Zofar terms it is a 'comparison')

**Comment by dzhwmeisner** [comment]
Investigating Dimension of necessary  development to realize static version of Comparison.
Is this separable from responsive version (css, javascript, breakpoints)?
Is a basic version of renderer for html5 structure already there and complete?
