### ISSUE TITLE
As developer I need a definition of done for the question export

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#101]
We need a definition of done for a questions export such as

- zofar: code according to code conventions #103 
- zofar asks fdz and inserts in export
   - `DataAcquisitionProjekt-ID` 
   - `instrumentNumber`
   - `instrumentTitle`  
   - `surveyNumber`?
   - something else?
- zofar: review 
- zofar: run automatic export
- zofar: send to fdz

**Comment by andreaschu** [comment]
will be relevant after #98 , #103 and #107.
