### ISSUE TITLE
process description for new questiontypes

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#109]
For developing new question types developer need a process that describe all steps that has been done for developing and implementing an new question type or other new features.
- definition of qml structure (plugin, verifier)
- definiton of html structure (renderer, css, javascript)
- testing  on several devices
- accessability (Barrierefreiheit)
- code convention
- documentation
- showroom 
- mdm export: developing and testing

**Comment by UteH** [comment]
As I said before, I wan't sure if the defintion of done for the mdm team is current. I noticed that René edited it in the last days, thus I assume it is current. In case you are interested:
https://github.com/dzhw/metadatamanagement/wiki/Definition-of-Done
