### ISSUE TITLE
the project SiD needs a workaround for questions for responsive Design

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#112]
'Studieren in Deutschland' needs for several questions a workaround for questions that are not responsive yet. Look here: \\faust.dzhw.local\Abt4\Service\Servicebereich_Onlineforschung\02_Service\Befragungen\Sozialerhebung (SE)\PerSe\repsDesign\SE22_Umsetzbarkeit_2018_10_29.xlsx

**Comment by Miktarbad** [comment]
- contains 20 pages to be coded

**Comment by Miktarbad** [comment]
Sprint 19 used points ~1
