### ISSUE TITLE
NACAPS (first wave)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#113]
following steps has to be done: 
- [x] programming content of questionnaire (@Miktarbad)  
- [x] programming transitions of questionnaire (@Miktarbad)
- [x] releasing the survey on the presentation server with ci via jenkins (@vdick)
- [x] programming additional hei (higher education institution) -specific question
- [x] debugging 
- [x] translation export
- [x] implementing pictures
- [x] Token generating  
- [x] translation import and test
- [x] hei specific cockpit
- [x] load test

**Comment by Miktarbad** [comment]
first draft of survey released on presentation server, without ci because the jumpserver not available

**Comment by UteH** [comment]
please make sure that questionNumber #87 is in QML :speak_no_evil:
