### ISSUE TITLE
SLC

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#115]
The SLC project scheduled two E-Mail reminder, which need to be processed.

### **- Monday / 26.11.18 / 1. Charge Hisbus + NRW**  

- [x] Export Token (@vdick  )
- [x] Matching Token (@andreaschu: who could do it?)
- [x] Sending E-Mails (@Miktarbad )

### **- Monday / 10.12.18 / 2. Charge Hisbus**  

- [x] Export Token (@Miktarbad )
- [x] Matching Token (@andreaschu )
- [x] Sending E-Mails (@Miktarbad )

**Comment by andreaschu** [comment]
The SLC project wants a data export with paradata.
@dzhwmeisner or @vdick?

**Comment by Miktarbad** [comment]
Export needs to be tested

**Comment by dzhwmeisner** [comment]
- [ ] reminder
- [ ] go offline
- [ ] export
- [ ] screenshots
- [ ] archiving

**Comment by andreaschu** [comment]
@dzhwmeisner can you go offline and start the final **export with paradata and history**?

**Comment by dzhwmeisner** [comment]
Survey offline.

**Comment by kastirke** [comment]
Please generate screenshots.

**Comment by kastirke** [comment]
The project team has questions on variables within SLC "Bildungsverlauf" data. Please answer them asap.

1. Which user agent string is stored in the dataset? (The one users' device sended when first entering the startgpage? What happendend if participants reenter the startpage?)

2. Was is the definition of "lastpage"? (The last page that was visited? The last page where data was persisted?)

3. While programming the survey we were asked to prevent the possibility to go back after reaching the endpage. How was this implemented? Did we use a very short session timeout? Were "back"-buttons hidden? Background: Timestamps show that in spite of endpage visits some participants have been entered previous pages afterwards. 

4. When are timestamps set? When entering the survey page or when pushing the forward or backward buttons?

I will answer their fourth question as follows: Timestamps are always set when entering the survey page.
Additional info: "forward" and "back" persist the survey data and don't influence the setting of the timestamps directly. Am I right?

**Comment by kastirke** [comment]
I need a new data export of "Bildungsverlauf" (SLC-pretest) that contains all comment fields.

**Comment by kastirke** [comment]
Andrea was able to answer two of your questions.

1. The user agent string that users' device sended when first entering the survey is stored. To date Zofar doesn't restore this datum or record device switches during the survey. 

-> BUT the access logs from the server contain every request and enables such analyses. Please contact me, Nadin, if you need them.

2. The variable "lastpage" is the last page that was visited by the participant (is derived from the last timestamp that has been set). Often (not always) it is the last page where data was persisted.

@dzhwmeisner / @vdick : Please confirm.
