### ISSUE TITLE
SPanel 18-2

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#116]
- [x] meeting with Silina to layout the questionnaire (Fr.) 
- [x] deploy on productive system
- [x] token with preloads
- [x] lasttest
- [x] golive (Wendsday?!)
- [x] Mailing the invitations for 8000 users on 18.12.

- further invitation via project

### SPanel 18.2 wants to send an announcement via E-Mail for around ~350 participants.

**- Wednesday / 12.12.18** 
- [x] Mailingtexts
- [x] Participantlist
- [x] creating mail
- [x] testing
- [x] sending e-Mail

**Comment by Miktarbad** [comment]
Additional Task: 
- Mailing the invitations for 8000 users on 18.12.

Checklist:
- [ ] Mailinglist
- [ ] Mailadress + password
- [ ] Mailingtext

**Comment by dzhwmeisner** [comment]
- [ ] reminder
- [ ] go offline
- [ ] export
- [ ] screenshots
- [ ] archiving

**Comment by andreaschu** [comment]
@dzhwmeisner please create a screenshot

**Comment by dzhwmeisner** [comment]
Screenshots done

[studienberechtigenpanel2018-2.pdf](https://github.com/dzhw/zofar/files/3275582/studienberechtigenpanel2018-2.pdf)
[studienberechtigenpanel2018-2.zip](https://github.com/dzhw/zofar/files/3275583/studienberechtigenpanel2018-2.zip)

**Comment by SilinaKowalewski** [comment]
Screenshots inkl. dynamics done

[studienberechtigenpanel2018-2.pdf](https://github.com/dzhw/zofar/files/3296749/studienberechtigenpanel2018-2.pdf)
[studienberechtigenpanel2018-2.zip](https://github.com/dzhw/zofar/files/3296750/studienberechtigenpanel2018-2.zip)
