### ISSUE TITLE
Abs 13-2: survey termination (Jan 19) 

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#118]
### **the survey ends on 02.01.19**

- [x] final return statistic (@andreaschu )
- [x] reroute the link (@vdick or @dzhwmeisner )
- [x] undeploy survey (@vdick or @dzhwmeisner )
- [x] prepare export (@andreaschu )

**Comment by dzhwmeisner** [comment]
Screenshots done 
[absolventen2013-2.zip](https://github.com/dzhw/zofar/files/2811839/absolventen2013-2.zip)
