### ISSUE TITLE
SPanel 12-3

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#119]
The fielding begins at **10.12.2018**

Following steps has to be done: 
- [x] programming content of questionnaire (@FineCordua): Text Changes, adding bridge pages
- [x] layouting the questionnaire (@Miktarbad): layouting tableau, implementing pictures on bridge pages
- [x] arrange access to QML for Heike Sp. (@vdick)

- [x] Token generating  (@andreaschu)
- [x] redirecting from panel2012.de (Ruth C.)
- [x] releasing the survey on the prod system
- [x] Lasttest
- [x] response statistics

**Comment by Miktarbad** [comment]
- [ ] images will be outsourced onto the loadbalancer @dzhwmeisner

**Comment by Miktarbad** [comment]
Sprint 19 used points ~5

**Comment by Miktarbad** [comment]
Survey ready for lasttest process. 
@vdick @dzhwmeisner 

Please Check:
- [ ] if the Addon works properly 
- [ ] jump Main to Addon
- [ ] preloads are all imported
- [ ] etc.

Tokens etc can be found in the projects.

**Comment by vdick** [comment]
lastest is running

**Comment by vdick** [comment]
survey is ready to go live

**Comment by Miktarbad** [comment]
- [ ] *HOTFIX* @vdick external Cockpit needs to be set up at Heike's computer and Verena Jahn's pc (i couldn't get it running - sorry)

**Comment by vdick** [comment]
fixed

**Comment by dzhwmeisner** [comment]
- [ ] reminder
- [ ] go offline
- [ ] export
- [ ] screenshots
- [ ] archiving

**Comment by andreaschu** [comment]
@dzhwmeisner please create a screenshot

**Comment by dzhwmeisner** [comment]
Screenshots done

[studienpanel123.pdf](https://github.com/dzhw/zofar/files/3275560/studienpanel123.pdf)
[studienpanel123.zip](https://github.com/dzhw/zofar/files/3275561/studienpanel123.zip)

**Comment by SilinaKowalewski** [comment]
Screenshots inkl. dynamics done

[studienpanel123.pdf](https://github.com/dzhw/zofar/files/3296752/studienpanel123.pdf)
[studienpanel123.zip](https://github.com/dzhw/zofar/files/3296753/studienpanel123.zip)
