### ISSUE TITLE
Review nacaps2019 with regard to code conventions

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#123]
As nacaps is a major project for the DZHW we need to test if the QML of nacaps2019 #113 is in line with the code conventions (#103) and improve if neccessary. 

Only this way the export for the mdm will work properly.

In the QML the fdz question (definition: project question according to pv) must be marked (#87)

**Comment by Miktarbad** [comment]
First draft of NACAPS Questionnaire is finished and will be available on presentation.dzhw.eu tomorrow morning.
University specific questions will be added later and the contact/contest section(F01-F06) is still unclear.

A first Review can be done @dzhwmeisner

**Comment by UteH** [comment]
:speak_no_evil: do we already have the code conventions #103 ?
