### ISSUE TITLE
Updating the dzhw Logo in the archetype

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#127]
The DZHW Logo within the template should be updated to the logo without the small text.

For general use, it should be implemented in both archetypes. 

Logos can be found here: http://dizi.dzhw.eu/logos-des-dzhw/

**Comment by andreaschu** [comment]
please use this: https://dizi.dzhw.eu/wp-content/uploads/2016/04/Logo_DZHW_ohne-Text_transpHG.png
