### ISSUE TITLE
Eurostudent VII

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#130]
Microdata collection

- [ ] programming core questionnaire
- [x] checking zofar for several writings
- [x] adapting data protection - Technische und Organisatorische Maßnahmen (TOM) 
- [x] adapting service specification
- [ ] developing core questionnaire adaption file 

[EUROSTUDENTVII_draft_2_20181121_final_Zofar.docx](https://github.com/dzhw/zofar/files/2694433/EUROSTUDENTVII_draft_2_20181121_final_Zofar.docx)
[EUROSTUDENTVII_draft_2_20181121_final_Zofar.pdf](https://github.com/dzhw/zofar/files/2694442/EUROSTUDENTVII_draft_2_20181121_final_Zofar.pdf)

**Comment by dzhwmeisner** [comment]
[page03_18] add open Matrix

**Comment by dzhwmeisner** [comment]
[page05_4] remove pipes

**Comment by dzhwmeisner** [comment]
[page03_9] fix disturbed layout

**Comment by dzhwmeisner** [comment]
[page03_10] remove pipes and reduce space between radiobuttons

**Comment by dzhwmeisner** [comment]
[page05_6] fix layout

**Comment by dzhwmeisner** [comment]
[page05_11] mark last answeroption as missing to interrupt pipe

**Comment by dzhwmeisner** [comment]
http://vmtest.dzhw.local:8080/Eurostudent2-0.0.1-SNAPSHOT

[page03_9]  fixed by downsizing font and rotating labels
[page03_10]  done

[page05_4] done
[page05_6]  done
[page05_11] done

[page06_0] done. distance between columns reduced

**Comment by dzhwmeisner** [comment]
working token is part1

**Comment by dzhwmeisner** [comment]
[page03_18] done
http://vmtest.dzhw.local:8080/Eurostudent2-0.0.1-SNAPSHOT/p03_18.html

need to be reviewed

**Comment by andreaschu** [comment]
Kannst Du das #61 aktualisieren?

Von: Christian Meisner [mailto:notifications@github.com]
Gesendet: Montag, 14. Januar 2019 15:36
An: dzhw/zofar
Cc: Schulze, Andrea; Assign
Betreff: Re: [dzhw/zofar] Eurostudent VII (#130)


[page03_18] done
http://vmtest.dzhw.local:8080/Eurostudent2-0.0.1-SNAPSHOT/p03_18.html

need to be reviewed

**Comment by dzhwmeisner** [comment]
Eurostudent Malta:
Jenkins: http://vmbuild.dzhw.local:8080/job/Eurostudent2-Malta
Testserver: http://vmtest.dzhw.local:8080/Eurostudent2-Malta/index.html
Subversion: https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Eurostudent2-Malta

**Comment by dzhwmeisner** [comment]
Presentation: https://presentation.dzhw.eu/Eurostudent2-Malta-0.0.1-SNAPSHOT

**Comment by andreaschu** [comment]
@vdick: Please create a project for Eurostudent-Ireland by duplicating EurostudentVII.

**Comment by vdick** [comment]
Eurostudent-Ireland:
Testserver: http://vmtest.dzhw.local:8080/Eurostudent-Ireland/
Subversion: https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Eurostudent-Ireland

**Comment by andreaschu** [comment]
- [ ] @dzhwmeisner please drop progress bar (same for #149 and #148)
- [ ] @dzhwmeisner please make the last checkboxes (p04_11 and p04_12) exclusive only for the lines/items (same for #149 and #148)
- [ ] p03_04: split in two pages --> p03_04a for mobile phones (screen width less than 400) and p03_04b for bigger screens
