### ISSUE TITLE
OHO-teilnehmer

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#131]
Project: Offene Hochschulen
- [x] creating a project (@dzhwmeisner) 
- [x] programming first draft of questionnaire: [Fragebogen_TN2019.docx](https://github.com/dzhw/zofar/files/2755328/Fragebogen_TN2019.docx)
- [x] testing and correcting
- [x] going online
- [x]  Screenshots
- [ ]  Archivierung
- [x]  Export of Data

**Comment by dzhwmeisner** [comment]
is an addon needed?

**Comment by andreaschu** [comment]
as far as i know it is not needed.

**Comment by dzhwmeisner** [comment]
Project: Offene Hochschulen
- [x] creating a project (@dzhwmeisner)  --> 
http://vmtest.dzhw.local:8080/oho-teilnehmer
- [ ] programming first draft of questionnaire

**Comment by kastirke** [comment]
Please integrate OHO logos sended by Jonas Koopmann.
[OHO_Logos.zip](https://github.com/dzhw/zofar/files/2860010/OHO_Logos.zip)

order: OHO, DZHW, BMBF
See here: 
[LOGO_KOOP_Screenshots_fullscreen.pdf](https://github.com/dzhw/zofar/files/2860015/LOGO_KOOP_Screenshots_fullscreen.pdf)

**Comment by dzhwmeisner** [comment]
OHO Teilnehmer rolled out as Pretest and DB cleared:

https://presentation.dzhw.eu/oho-teilnehmer

**Comment by dzhwmeisner** [comment]
[13_03_19_Fragebogen_TN2019_Anmerkungen_FB_Rückmeldung_Pretest.docx](https://github.com/dzhw/zofar/files/2965416/13_03_19_Fragebogen_TN2019_Anmerkungen_FB_Ruckmeldung_Pretest.docx)
[Datenschutzhinweise_Startseite.pdf](https://github.com/dzhw/zofar/files/2965418/Datenschutzhinweise_Startseite.pdf)

**Comment by andreaschu** [comment]
- [ ] Export of Data

**Comment by dzhwmeisner** [comment]
- [ ] Screenshots

**Comment by dzhwmeisner** [comment]
- [ ] Archivierung

**Comment by andreaschu** [comment]
transfered the last comments into the first one, so that the tasks are counted in statistics

**Comment by andreaschu** [comment]
Screenshots including transitions:
[oho-teilnehmer_screenshot.zip](https://github.com/dzhw/zofar/files/3296971/oho-teilnehmer_screenshot.zip)
[oho-teilnehmer_screenshot.pdf](https://github.com/dzhw/zofar/files/3296972/oho-teilnehmer_screenshot.pdf)

**Comment by andreaschu** [comment]
@vdick please add survey in exporter

**Comment by mattenko** [comment]
Archiving done
