### ISSUE TITLE
Bug: horizontal SC - labels

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#138]
Labels are displayed underneath the values and are not fully displayed in mobile mode.
Furthermore values mostly are displayed with "( )" if there is a label.

![screenshot_horizontal-sc-labelbug](https://user-images.githubusercontent.com/29864065/49863590-e9c11380-fe00-11e8-9664-d788c62858a8.png)

Can be tested at: https://presentation.dzhw.eu/nacaps-haupt1/B34.html

**Comment by andreaschu** [comment]
It's fixed.
