### ISSUE TITLE
Promopanel W5

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#139]
Project Promoviertenpanel (fifth wave):
- [x] @dzhwmeisner: Please create a project for the fifth wave of Promoviertenpanel 
- [x] @dzhwmeisner: Please insert the questionnaire of the fourth wave
- [x] programming changes ([Fragebogen_W5_v6.docx](https://github.com/dzhw/zofar/files/2695511/Fragebogen_W5_v6.docx))
- [x] debugging
- [x] Token generating
- [x] Export
- [x] Export of Add-on
- [x] Screenshot (@dzhwmeisner)

**Comment by dzhwmeisner** [comment]
Project Promoviertenpanel (fifth wave):
- [ ] @dzhwmeisner: Please create a project for the fifth wave of Promoviertenpanel 
 
done.
Subversion
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/PromoWelle5-2019
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/PromoWelle5-2019-addon

Testserver
http://vmtest.dzhw.local:8080/PromoWelle5-2019

- [ ] @dzhwmeisner: Please insert the questionnaire of the fourth wave

done.

- [ ] programming changes ([Fragebogen_W5_v6.docx](https://github.com/dzhw/zofar/files/2695511/Fragebogen_W5_v6.docx))
- [ ] debugging
- [ ] Token generating

**Comment by dzhwmeisner** [comment]
http://vmtest.dzhw.local:8080/PromoWelle5-2019

converted to old layout

**Comment by andreaschu** [comment]
the first draft is nearly done. @dzhwmeisner and @vdick one of you has to 
- [ ] write page 81d
- [ ] check calendar (page5)
- [ ] and layout the questionnaire.
[Fragebogen_W5_v6.docx](https://github.com/dzhw/zofar/files/2769285/Fragebogen_W5_v6.docx)

**Comment by kastirke** [comment]
Test cases with preloads were created by Steffen. Please amend them to the project so transitions can be checked.
 
[Testzugänge.xlsx](https://github.com/dzhw/zofar/files/2837010/Testzugange.xlsx)

**Comment by kastirke** [comment]
Programmers' questions were answered by Steffen. Please complete the programming with respect to these answeres. (Notes to page8_15 is unclear to me and the project team and, therefore, has to be discussed with Andrea and Parmida.)

[Notes_06.02.2019.xlsx](https://github.com/dzhw/zofar/files/2837211/Notes_06.02.2019.xlsx)

**Comment by andreaschu** [comment]
@vdick can't do export for add-on, because of "Not Found". Can you have correct this or give me the export of the add-on?

**Comment by vdick** [comment]
@andreaschu please try again, should be working now

**Comment by andreaschu** [comment]
Nope.
![grafik](https://user-images.githubusercontent.com/30111489/57443224-d9954f00-724d-11e9-892d-d524c1ff3847.png)

**Comment by vdick** [comment]
@andreaschu once again please

**Comment by andreaschu** [comment]
![grafik](https://user-images.githubusercontent.com/30111489/57444062-a0f67500-724f-11e9-9b5c-e0fb9994c35d.png)

**Comment by andreaschu** [comment]
Data-Export:
**P:\abs\dta\Promoviertenpanel\original\promopanel_w5_2019-05-14** 
- [ ] bei PLZ-Variablen müssen führende Nullen erhalten bleiben,
- [ ] die Stringvariablen bitte nicht abschneiden,
- [ ] eine korrekte Darstellung von Umlauten,
- [ ] die Beibehaltung der Originalangaben beim Einkommen (Unterscheidung von Dezimalstellen und Tausendertrennzeichen).

**Comment by andreaschu** [comment]
@dzhwmeisner please create a screenshot of the questionnaire

**Comment by dzhwmeisner** [comment]
Screenshots done

[PromoWelle5-2019.pdf](https://github.com/dzhw/zofar/files/3275592/PromoWelle5-2019.pdf)
[PromoWelle5-2019.zip](https://github.com/dzhw/zofar/files/3275593/PromoWelle5-2019.zip)

**Comment by SilinaKowalewski** [comment]
Screenshots inkl. dynamics done

[PromoWelle5-2019.pdf](https://github.com/dzhw/zofar/files/3296742/PromoWelle5-2019.pdf)
[PromoWelle5-2019.zip](https://github.com/dzhw/zofar/files/3296743/PromoWelle5-2019.zip)
