### ISSUE TITLE
MDM export for abs2005-3

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#143]
FDZ wants an export of the metadata (with new screenshots) for the project Absolventen 2005-3:
- [x] Hauptbefragung
- [x] Vertiefungsbefragung 1
- [x] Vertiefungsbefragung 2
- [x] Vertiefungsbefragung 3

**Comment by anneweber** [comment]
@UteH said that you need the following information for the export:
- DataAcquisitionProjekt-ID: gra2005
- instrumentNumber:
  - Hauptbefragung: 3
  - Vertiefungsbefragung 1: 4
  - Vertiefungsbefragung 2: 5
  - Vertiefungsbefragung 3: 6
- instrumentTitle:
  - Hauptbefragung: Zehn Jahre nach dem Studienabschluss
  - Vertiefungsbefragung 1: -
  - Vertiefungsbefragung 2: -
  - Vertiefungsbefragung 3: -
- surveyNumber: (in Klärung)

**Comment by UteH** [comment]
Hi @andreaschu :) do you think the export will be ready in time (within the sprint)?
(I took over the zofar metadata export for gra2005.3 from Anne)

**Comment by UteH** [comment]
@dzhwmeisner in this issue we listet the information for the export. If you need any further information, do not hesitate to contanct me :)!

**Comment by dzhwmeisner** [comment]
Hauptbefragung results in an error while Import to MDM for the Calendar on Page 9.1, because a calendar have no Question Text.

[Absolventen2005.3.zip](https://github.com/dzhw/zofar/files/2957313/Absolventen2005.3.zip)

**Comment by UteH** [comment]
@dzhwmeisner thank you! I am investigating it! looks good at first sight!
btw do you have [instrument (Gesamtscreenshotdokument)](https://github.com/dzhw/zofar/issues/143#issuecomment-458125300) aswell?

**Comment by dzhwmeisner** [comment]
Here comes the Instrument.
[instrument_de.pdf](https://github.com/dzhw/zofar/files/2960762/instrument_de.pdf)

**Comment by UteH** [comment]
Hi, thank you!

here our feedback!
The export was fine, the third wave is released 🎉 ! 

here, some minor remarks:

### 1 instrument/pages (questions)
- Die Benennung der pages ist unterschiedlich, obwohl beides Mal das gleiche Objekt (page) gemeint ist 
  - Instrument
  - Pages (questions)

instrument | pages (questions)
-- | --
page28 | 28.1
page28a | 28a.1
 

→ inkonsistent 
**-->Wichtig ist uns nur, dass es konsistent ist.**


## 2 Questions (pages)
- **index.1**: kein questiontext
- **end**: gibt es nicht (aber bei instrument vorhanden) (nicht tragisch, aber inkonsistent)
- **9.1**: questiontext steht bei topic
- **25a** und **28a**: questionText falsch
- Folgefragen fehlen
  - **6.1:** 7.1, 9.1 (fehlt 9.1 )
  - **8.1:** 9.1
  - **11.1:** 12.1, 14.1, 25.1 (fehlt 14.1; eigentlich 14a.1, aber das war nur ein Zwischentext, daher gibt es dazu keine jsons)
  - **13.1:** 14.1 (eigentlich 14a.1, aber das war nur ein Zwischentext, daher gibt es dazu keine jsons)
- Keine topics
- bei uns gibt es keine `studyID` bei questions (ist im JSON enthalten, wir ignorieren aktuell einfach)


### 3 Variables
Als questionNumber wurde die ID der question (question) angegeben nicht die ID der questions (pages)
**-->	inkonsistent**


For all I care, the issue can be closed :)
