### ISSUE TITLE
OHO-Kooperationspartner

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#144]
Project: Offene Hochschulen
Field start: **22.05.2019**
- [x] creating a project (oho-koop) (not responsive, no add on)
- [x] programming first draft of questionnaire: [Fragebogen_Koop2019_BMBF_PT_fin.docx](https://github.com/dzhw/zofar/files/2755322/Fragebogen_Koop2019_BMBF_PT_fin.docx)
- [x] testing and correcting
- [x] going online
- [x]  Screenshots
- [x]  Archivierung
- [x]  Export of Data

**Comment by dzhwmeisner** [comment]
Project created
http://vmtest.dzhw.local:8080/oho-koop
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/oho-koop

**Comment by kastirke** [comment]
Please integrate OHO logos sended by Jonas Koopmann.
[OHO_Logos.zip](https://github.com/dzhw/zofar/files/2860010/OHO_Logos.zip)

order: OHO, DZHW, BMBF
See here: 
[LOGO_KOOP_Screenshots_fullscreen.pdf](https://github.com/dzhw/zofar/files/2860015/LOGO_KOOP_Screenshots_fullscreen.pdf)

**Comment by andreaschu** [comment]
- [ ] Export of Pretest-Data

**Comment by andreaschu** [comment]
- [ ] Projektname von VP4: „work#study“ in „work&study“ umbenennen

**Comment by andreaschu** [comment]
Index:
- [ ] Logos fehlen (see above)
- [ ] Verlinkung zu den Email-Addys funktionieren nicht
- [ ] Datenschutzhinweis (inkl. Verlinkung) aktualisieren

P207:
- [ ] Einbauen eines zweiten Exclusiv-Befehls für die Antwortmöglichkeit „Es ist bisher kein konkreter Beitrag geplant.“

P208:
- [ ] Kann man die Antwort aus dem Freitextfeld auf 2.07 in das Dropdown-Menü in 2.08 integrieren?

P216:
- [ ] „Stellen (in Vollzeitäquivalenten).“ bitte hinter das Freifeldtext setzen.

P222:
- [ ] „Arbeitsgruppen.“ bitte hinter das Freitextfeld setzen.

P224:
- [ ] Kann man die Freitextfelder festsetzen, sodass sie nicht in Abhängigkeit von der Antwortlänge in den Freitextfelder auf P223 variieren? (z.B. in dem man die Freitextfelder eine Zeile unter der Antwortmöglichkeit festsetzt?)  
- [ ] **LAYOUT** Problem der Felderanzeige bei mobiler Ansicht mit Tablet:
![grafik](https://user-images.githubusercontent.com/30111489/57918309-c9f1b800-7896-11e9-9870-c68c1c943470.png)

**Comment by andreaschu** [comment]
**Sammel-Issue:** 
Es sollte entweder das Freitextfeld ausfüllbar oder „Kann ich nicht beurteilen“ anklickbar sein. Es sollte jedoch nicht beides gleichzeitig anwählbar sein.
- [ ] P209
- [ ] P211
- [ ] P307
- [ ] P308
- [ ] P309 ("Entweder das Freitextfeld, die Option „Keine Entwicklungen können dies beeinflussen“ oder  „Kann ich nicht beurteilen“.")
- [ ] P310
- [ ] P215

**Comment by andreaschu** [comment]
**LAYOUT** 
Beschriftung der Achse kollidiert
![grafik](https://user-images.githubusercontent.com/30111489/57917945-18eb1d80-7896-11e9-8699-1d684c889d37.png)
- [ ] P213 
- [ ] P221
- [ ] P225
- [ ] P301
- [ ] P305
- [ ] P306
- [ ] P403
- [ ] P406

**Comment by andreaschu** [comment]
- [ ] **LAYOUT** Vordere Beschriftung der Achse verschwindet:
![grafik](https://user-images.githubusercontent.com/30111489/57918624-6b790980-7897-11e9-9ea4-6387ce13b85c.png)

**Comment by andreaschu** [comment]
Hallo Erik,
kannst Du mir eine Übersicht für die Anzahl von Token entweder gesamt (dann müsstet Ihr die Preloads zuordnen) oder pro Kombination von  Projekt, Projektart und Hochschule geben?

Hier eine Beispieltabelle für die zweite Variante:

Projekt-ID | Hochschul-ID | Projektart | Anz. Token
-- | -- | -- | -- 
EP_01 |  56 | EP | 50
EP_26 |  81 | EP | 70

**Comment by koopmann1896** [comment]
@andreaschu 

Name für den Koop-Befragungslink: oh-kooperationspartner

**Comment by dzhwSchwartz** [comment]
> Hallo Erik,
> kannst Du mir eine Übersicht für die Anzahl von Token entweder gesamt (dann müsstet Ihr die Preloads zuordnen) oder pro Kombination von Projekt, Projektart und Hochschule geben?
> 
> Hier eine Beispieltabelle für die zweite Variante:
> 
> Projekt-ID	Hochschul-ID	Projektart	Anz. Token
> EP_01	56	EP	50
> EP_26	81	EP	70

Hey Andrea, nachfolgend die angeforderte Liste: 
[01_Tokenverteilung_Gesamt_Koop.xlsx](https://github.com/dzhw/zofar/files/3197886/01_Tokenverteilung_Gesamt_Koop.xlsx)

**Comment by dzhwSchwartz** [comment]
![Startseite Koop](https://user-images.githubusercontent.com/50824476/58022524-e8adb400-7b0d-11e9-8a1e-44b02e7b5f72.png)

Irgendwie verrutscht aktuell auf der Startseite der Satz hinter der Ankreuzkästchen

**Comment by dzhwSchwartz** [comment]
Weitere allgemeine Arbeitshinweise:

- [ ] Anmerkungsfelder des Pretests müssen deaktiviert werden

- [ ] Logos bitte noch etwas vergrößeren. (Logo des Bmbf so klein, das Schrift nicht zu erkennen ist)

- [ ] E-Mail-Addys auf der Startseite leiten immer noch nirgendwo hin

**Comment by dzhwSchwartz** [comment]
![2 16](https://user-images.githubusercontent.com/50824476/58096698-fb8bbb80-7bd5-11e9-902c-02916d9a493c.png)
![Screenshot_20190521-141859_Firefox](https://user-images.githubusercontent.com/50824476/58096704-ffb7d900-7bd5-11e9-8674-586e4782ec7e.jpg)

2.16 bzw. 2.22 sitzen nicht hinter dem Freitextfeld

**Comment by koopmann1896** [comment]
![DZLS5209](https://user-images.githubusercontent.com/50742367/58098460-f3357f80-7bd9-11e9-98df-2ab9b3a68d22.JPG)
![ECTE0089](https://user-images.githubusercontent.com/50742367/58098461-f3357f80-7bd9-11e9-83bd-5c0c87a46bea.JPG)
![EIEQ8681](https://user-images.githubusercontent.com/50742367/58098462-f3357f80-7bd9-11e9-8ac9-ec33baa11bb9.JPG)
![IHXQ8598](https://user-images.githubusercontent.com/50742367/58098463-f3ce1600-7bd9-11e9-9a62-e1f0e80e09fd.JPG)
![QKPB2896](https://user-images.githubusercontent.com/50742367/58098464-f3ce1600-7bd9-11e9-87ac-f9c8aed0cf80.JPG)
![UFBW7654](https://user-images.githubusercontent.com/50742367/58098465-f3ce1600-7bd9-11e9-8734-8d35277f68f2.JPG)
![YDOM5037](https://user-images.githubusercontent.com/50742367/58098466-f466ac80-7bd9-11e9-8f32-4ef4161e19f4.JPG)

**Comment by dzhwSchwartz** [comment]
Achsen kippen bei mobiler Ansicht (Probleme teilweise in den Screenshots im Post von Jonas dokumentiert) :
- [ ] p213 (singlechoice)
- [ ] p221 (sc)
- [ ] p225 (matrixsinglechoice)
- [ ] p302 (matrixsinglechoice)
- [ ] p3021 (matrixsinglechoice)
- [ ] p305 (sc)
- [ ] p306 (sc)
- [ ] p402 (msc)
- [ ] p403 (sc)
- [ ] p406 (sc)

Handyansicht von 216 und 222 immer noch problematisch (Verlauf vorher gelöscht / beides Chrome):
![IMG-20190521-WA0010](https://user-images.githubusercontent.com/50824476/58099650-5d4f2400-7bdc-11e9-830c-4da6a2ef1f76.jpg)
![Screenshot_20190521-151924_Chrome](https://user-images.githubusercontent.com/50824476/58099657-617b4180-7bdc-11e9-8583-234941034c97.jpg)

**Comment by dzhwSchwartz** [comment]
Beim letztmaligen Überprüfen von allen Übergängen habe ich noch einen Filter-Fehler entdeckt, den ich nicht selbst beheben kann. Bisher war bei den Tokens zum VP04 der Name "work#study“ hinterlegt. Das Projekt heißt eigentlich "work&study". Ich gehe mal davon aus, dass die von euch generierten Tokens und Links den richtigen Namen dieses Projekts enthalten. Für die Funktionalität des Pretests und aufgrund des Umstands, dass mir der Verifyer immer mehrere Fehler angezeigt hat, wenn ich den richtigen Namen des Projekts angegeben habe ("vermutlich wegen dem &), heißt der Projektname in meinem PreloadFilter von p2 auf p201 noch immer "work#study". Das müsste noch verändert werden. Ruft mich gerne zurück, falls das Problem noch nicht klar ist.

**Comment by dzhwSchwartz** [comment]
So, wir haben alle Änderungen und Bearbeitungen überprüft und sind bereit für den Lasttest. Vielen Dank

**Comment by dzhwmeisner** [comment]
- [ ] Export
- [ ] Screenshots
- [ ] Archivierung

**Comment by andreaschu** [comment]
transfered the last comment into the first one, so that the tasks are counted in statistics

**Comment by andreaschu** [comment]
@dzhwSchwartz 
screenshots including transitions:
[oho-koop_screenshot.pdf](https://github.com/dzhw/zofar/files/3296999/oho-koop_screenshot.pdf)
[oho-koop_screenshot.zip](https://github.com/dzhw/zofar/files/3297000/oho-koop_screenshot.zip)

**Comment by andreaschu** [comment]
@vdick  please add survey in exporter

**Comment by vdick** [comment]
survey is offline

**Comment by mattenko** [comment]
Archiving done
