### ISSUE TITLE
Abs13-2, "soziale Partizipation"

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#145]
Project: Absolventen 2013 (2. Vertiefungsbefragung 'soziale Partizipation'), 
**Feldstart: 07.03.2019**
- [x] creating a project (abs13-2_sozpart) (responsive?, add on?)
- [ ] programming first draft of questionnaire (Parmida)

**Comment by kastirke** [comment]
[Variablenübersicht_TB2_2013.2_003.xlsx](https://github.com/dzhw/zofar/files/2791474/Variablenubersicht_TB2_2013.2_003.xlsx)
![flussdiagramm_abs13 2_tb2_002](https://user-images.githubusercontent.com/30147532/51675558-4c96f480-1fd4-11e9-9b0e-4114d750d1d8.png)
[Abs2013.2_TB.2_PV_2019-01-14_008.docx](https://github.com/dzhw/zofar/files/2791475/Abs2013.2_TB.2_PV_2019-01-14_008.docx)

**Comment by kastirke** [comment]
[Abs2013.2_TB.2_AddOn_PV_2019-01-24_001.docx](https://github.com/dzhw/zofar/files/2791484/Abs2013.2_TB.2_AddOn_PV_2019-01-24_001.docx)

**Comment by kastirke** [comment]
Sorry. Github und ich kämpfen gerade.
