### ISSUE TITLE
Eurostudent-Malta

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#148]
questionnaire for Eurostudent-Malta:
Link: https://presentation.dzhw.eu/Eurostudent2-Malta-0.0.1-SNAPSHOT
Field start: **03.04.2019**

- [x] creating a project 
- [x] programming first draft of questionnaire
- [x] testing and correcting
- [x] going online
- [x] feedback (weekly)
- [x]  screenshots
- [ ]  archiving
- [x]  export of Data

**Comment by dzhwmeisner** [comment]
- [ ]  feedback
- [ ] screenshots
- [ ] export (incl. SPSS)
- [ ] archiv

**Comment by andreaschu** [comment]
@Eurostudent-RN, here you find the dataset: https://myshare.dzhw.eu/index.php/s/Ln51HmK7AFfopvq/authenticate

**Comment by andreaschu** [comment]
@Eurostudent-RN here are the screenshots:
https://myshare.dzhw.eu/index.php/s/kSbpLWEHKVXLjZt 
https://myshare.dzhw.eu/index.php/s/BsNt4FGsWFGTr6a
