### ISSUE TITLE
Eurostudent-Ireland

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#149]
questionnaire for Eurostudent Ireland.
Field start: **03.04.2019**

**Comment by Eurostudent-RN** [comment]
I quess it should be better if every issue was posted once... right...
[Questionnaire Ireland test.docx](https://github.com/dzhw/zofar/files/3009063/Questionnaire.Ireland.test.docx)

**Comment by andreaschu** [comment]
- [ ] @vdick please remove the translation button
- [ ] @vdick please have a look at the layout of p04_11 (reduce the distance of item/line 2 and 3)
- [ ] @vdick please have a look at the layout of p04_12 (reduce the distance of item/line 1 and 2)
- [ ] @vdick the scale of p03_02 is missing

**Comment by vdick** [comment]
fixed, please check the new version/build on server

**Comment by Eurostudent-RN** [comment]
Looks good! Can you change the language of the buttons to English?

**Comment by andreaschu** [comment]
- [ ] @dzhwmeisner  please have a look at the layout of p04_11 (reduce the distance of item/line 2 and 3)
- [ ] @dzhwmeisner  please have a look at the layout of p04_12 (reduce the distance of item/line 1 and 2)

**Comment by andreaschu** [comment]
Most of issues are corrected, some questions are still open. Have a look at the comments.
[Questionnaire.Ireland.test-corrections_as.docx](https://github.com/dzhw/zofar/files/3019585/Questionnaire.Ireland.test-corrections_as.docx)

**Comment by andreaschu** [comment]
> 
> 
> Looks good! Can you change the language of the buttons to English?

'chosen' language (default is german) is now saved for the used tester-token. It is now english for unused token.

**Comment by andreaschu** [comment]
[Questionnaire.Ireland.test-corrections_as20190329.docx](https://github.com/dzhw/zofar/files/3024102/Questionnaire.Ireland.test-corrections_as20190329.docx)

- [ ] No actual link to www.dpo.ie in consent download page
--> the link 'here' (to: http://www.dataprotection.ie/) still doesn't work and I didn't managed to do so. Maybe you send me a pdf-document of it.

**Comment by Eurostudent-RN** [comment]
ENTRY page: 
"entryUrl : https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/special/login.html;jsessionid=CF61E7D4614D7892975E46CFB75546CB.zofar3"
Still jargon on this page upon entry, 
- also the warning needs to read “Unfortunately it is not possible to participate without consent to the Privacy 
- All scales should be reversed! Example p03_02, p03_06, 03_07, : do not agree (left)  - strongly agree (right) -> in excel file the order of labels was reversed…
- Please double check p07_01: needs less space AND soft warning does not function
- P03_04 according to core questionnaire. Please do add a letter -> mo into mon, tu into tue etc.

**Comment by Eurostudent-RN** [comment]
1.	As for the price draw they want to include the following text at the welcome page and at the last page (as a last sentence): [Everyone who completes the survey can enter a prize draw for: 5 HP STREAM LAPTOPS and 100 x €25 AMAZON VOUCHERS].
2.	Please include the following sentence in p04_17b: "Your total monthly expenses add up to the following amount(s) (tuition fees excluded). If this is not correct, please go back to previous page and adjust."
3.	Attached is a new informed consent with working link. Could you please upload this one
4.	Please add to the last page: “Thanks for participation, by pressing next, your answers will be submitted. If you want to change something, please go back in the survey".

**Comment by Eurostudent-RN** [comment]
> 
> 
> [Questionnaire.Ireland.test-corrections_as20190329.docx](https://github.com/dzhw/zofar/files/3024102/Questionnaire.Ireland.test-corrections_as20190329.docx)
> 
>     * [ ]  No actual link to [www.dpo.ie](http://www.dpo.ie) in consent download page
>       --> the link 'here' (to: http://www.dataprotection.ie/) still doesn't work and I didn't managed to do so. Maybe you send me a pdf-document of it.

[ESVII Informed Consent for Zofar (updated 29 March 2019).docx](https://github.com/dzhw/zofar/files/3028629/ESVII.Informed.Consent.for.Zofar.updated.29.March.2019.docx)

**Comment by andreaschu** [comment]
- [ ]     As for the price draw they want to include the following text at the welcome page and at the last page (as a last sentence): [Everyone who completes the survey can enter a prize draw for: 5 HP STREAM LAPTOPS and 100 x €25 AMAZON VOUCHERS].
- [ ]     Please include the following sentence in p04_17b: "Your total monthly expenses add up to the following amount(s) (tuition fees excluded). If this is not correct, please go back to previous page and adjust."
- [x]     Attached is a new informed consent with working link. Could you please upload this one
- [x]     Please add to the last page: “Thanks for participation, by pressing next, your answers will be submitted. If you want to change something, please go back in the survey".
- [ ] exit-page: Could you please add a previous button to the group of students wo is routed out of the  questionnaire 
--> _it is about the text, there is already a button. if i should add text, i need one_
- [x] This question (p01_02) should be mandatory along with all weighting variables, gender, age, formas status (FT/PT) and degree/qualification, plus current main study programme.  Please ensure this is applied. 
- [x] AS: You already made V1_4_2 mandatory, could you do the same with p01_04_1, p01_06, 	p01_05?

**Comment by Eurostudent-RN** [comment]
> @Eurostudent-RN it is about the text, there is already a button. if i should add text, i need one

"Unfortunately you are not part of the target group for this survey.
Thank you for your willingness to participate.
You can close this page now or go back and amend your answer".

**Comment by Eurostudent-RN** [comment]
@andreaschu As for the informed consent (first page)... please change to   O Yes, I consent to the processing of my responses in the questionnaire for the purpose of research on the social and economic conditions of students. In anonymised form, my responses can be made available worldwide to other data users as indicated in the information on data protection and consent [document download]. Accordingly, my consent also applies to responses regarding my health and ethnic origin, if given. My consent can be withdrawn at any time.

**Comment by Eurostudent-RN** [comment]
Momentan steht auf der letzten Seite “by pressing next, your answers will be submitted.”. Es gibt aber keinen „Next“ Button… könnt ihr noch einen einbauen`?

**Comment by andreaschu** [comment]
- country-lists changed
- soft forcings changed for the item grids (only visible for mobile devices and if from second item on every item is missing)
- MO --> Monday …

**Comment by Eurostudent-RN** [comment]
p03_04 -> please show transposed for the big screen and ad a third letter to all days of the week-> mo = mon, tu = tue, we = wed, th = thu, fr = fri, sa = sat, su = sun

**Comment by Eurostudent-RN** [comment]
p04_16a: could you change "Total monthly amount" in Total monthy amount (in euro's)"
p04_17c: Didn't this page also add up the "paid by others" AND is summs the costs of both pages (p04_17b and p04_17a). However... it needs to summ only the amounts entered in p04_17b.

**Comment by Eurostudent-RN** [comment]
![screenshot](https://user-images.githubusercontent.com/48948929/55382763-cd1f2780-5526-11e9-9dcd-8fa1c9a52ad7.jpg)
any ideas on this?

**Comment by Eurostudent-RN** [comment]
p06_10 -> please change in not mandatory

**Comment by Eurostudent-RN** [comment]
p04_17a-> please remove bracket ")" -> [except medical insurance])
Last page -> please correct "clothing this page" in "closing this page"

**Comment by Eurostudent-RN** [comment]
p04_11:
please change: 
Do your family or partner regularly provide you with money in cash/ bank transfers?
Do your family or partner pay bills for you regularly and directly?
Do your family or partner regularly provides you with any non-monetary material support?

into:
Does your family or partner regularly provide you with money in cash/ bank transfers?
Does your family or partner pay bills for you regularly and directly?
Does your family or partner regularly provides you with any non-monetary material support?

**Comment by Eurostudent-RN** [comment]
Can’t continue from this page 
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p04_28.html HTTP Status 500 - /p05_01.xhtml @10,118 rendered="#{V4_20_2.value and !V4_20_1.value and !V4_20_3.value)}" Failed to parse the expression [#{V4_20_2.value and !V4_20_1.value and !V4_20_3.value)}]

**Comment by Eurostudent-RN** [comment]
In the mobile version... some pages do not work as they should work...
So could yo please check the folowing pages:
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p01_02.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_09.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_10.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p03_08.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p04_18.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p06_13.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_02.html
https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_01.htm

**Comment by Eurostudent-RN** [comment]
p04_10 -> please change in not mandatory

**Comment by Eurostudent-RN** [comment]
We see you changed p06_10 in not mandatory. If the do not fill this one in they should skip the impairment questions and go to 07.01 (not to 6.11)

**Comment by andreaschu** [comment]
> 
> 
> In the mobile version... some pages do not work as they should work...
> So could yo please check the folowing pages:
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p01_02.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_09.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_10.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p03_08.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p04_18.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p06_13.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_02.html
> https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_01.htm

When the questionnaire is entered with a mobile device the soft reminder will be triggered when the carousel (button) is not used.

**Comment by Eurostudent-RN** [comment]
* Can we include the Irish flag (where the German flag used to be)?
* Can we place in blue bold text below (And at end page):  5 HP STREAM LAPTOPS and 100 x €25 AMAZON VOUCHERS
* Upon completion, can you ask the respondent for their name, institution and email address please (not address).  Upon completion of this they should be told:
“Thank you for your entry, we’ll be in touch in early June should you be a winner”.  Please contact us at eurostudent@insightsc.ie if you have any queries or otherwise.

**Comment by andreaschu** [comment]
add on:
index: 

> If you wish to enter into the prize draw, please enter your name, institution and email address below.


label: 
1. name, 
2. institution
3. email address

end: 

> Thank you for your entry, we’ll be in touch in early June should you be a winner. 
> Please contact us at eurostudent@insightsc.ie if you have any queries or otherwise.

**Comment by Eurostudent-RN** [comment]
> 
> 
> > In the mobile version... some pages do not work as they should work...
> > So could yo please check the folowing pages:
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p01_02.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_09.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_10.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p03_08.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p04_18.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p06_13.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_02.html
> > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_01.htm
> 
> When the questionnaire is entered with a mobile device the soft reminder will be triggered when the carousel (button) is not used.

It is not the soft reminder... it is this: ![screenshot](https://user-images.githubusercontent.com/48948929/55409908-30c74600-5563-11e9-9167-65df94daac54.jpg)

**Comment by andreaschu** [comment]
> 
> 
> > > In the mobile version... some pages do not work as they should work...
> > > So could yo please check the folowing pages:
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p01_02.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_09.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p02_10.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p03_08.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p04_18.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p06_13.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_02.html
> > > https://presentation.dzhw.eu/Eurostudent2-Ireland-0.0.1-SNAPSHOT/p07_01.htm
> > 
> > 
> > When the questionnaire is entered with a mobile device the soft reminder will be triggered when the carousel (button) is not used.
> 

There is a message at the beginning that they may should switch the display to landscape mode when respondents enter the questionnaire with a mobile device. There is nothing else we can do about that now.

**Comment by Eurostudent-RN** [comment]
> There is a message at the beginning that they may should switch the display to landscape mode when respondents enter the questionnaire with a mobile device. There is nothing else we can do about that now.

ok

**Comment by andreaschu** [comment]
change add-on login page-text to: 

> To participate in the draw please click "start here"

**Comment by andreaschu** [comment]
> To participate in the prize draw, please click "start here". The information for the prize draw is stored separately from your survey responses and cannot be linked to them.

**Comment by andreaschu** [comment]
@dzhwmeisner please export the data:
- without paradata
- with history
- no empty sets
