### ISSUE TITLE
Eurostudent-Czech

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#153]
questionnaire for Eurostudent Czech Republic.
Field start: **24.04.2019**

- [x] creating a project 
- [x] programming first draft of questionnaire: [ZOFAR_file_CZ_Confirmed_corrected_spelling V1a.xlsx](https://github.com/dzhw/zofar/files/3083874/ZOFAR_file_CZ_Confirmed_corrected_spelling.V1a.xlsx)
- [x] testing and correcting
- [x] going online
- [x] feedback (weekly)
- [x]  screenshots
- [x]  archiving
- [x]  export of Data

Testlink: https://presentation.dzhw.eu/Eurostudent-Czech/
Token: tester1-tester100
@dzhwmeisner: please add the following variables to the response statistic in the cockpit:

- [x] V1_4_2
- [x] V1_5
- [x] V2_6month
- [x] V2_6year

**Comment by andreaschu** [comment]
@dzhwmeisner please change ' to " in page p05_01 for variables  V5_1_3 and V5_1_4.

**Comment by dzhwmeisner** [comment]
fixed

Am 16.04.19 um 11:46 schrieb andreaschu:

**Comment by andreaschu** [comment]
- [ ] @dzhwmeisner please change german flag to czech flag
- [ ] @dzhwmeisner please change texts of buttons and footer (see below)

When | Translation   first language_CZECH
-- | --
Button next: | Další
Button previous: | Předchozí
Footer on every page | Ministerstvo   školství, mládeže a tělovýchovy  České   republiky

**Comment by andreaschu** [comment]
- [ ] @dzhwmeisner please have a look at the layout of the second question on page p07_01

**Comment by andreaschu** [comment]
from e-mail from deVries (Do 18.04.2019, 17:03):

- [ ] P01_05: Check the question tree. Now for every ‘fakulty’ the same degrees are shown, while these differ in the question tree. Respondents can pick a degree which does not exist in that faculty. When they continue the questionnaire, they can not pick a study programme. (‘jiný postgraduální (např. MBA), ale nikoliv doktorský’ and ‘doktorský studijní program (PhD.)’ don’t exist at any of the faculties). 
- [ ]  P01_08 and P01_09 are missing
- [ ]  P02_03: After answering P02_02, the respondent should be sent to P02_04. However, this is not the case and question P02_03 is shown. 
- [ ]  P03_02, P03_03, P03_05, P03_06, P03_07, P03_09, P04_03, P04_07, P04_10, P06_05, V06_10, V06_12, P07_01: Please double check missings: No ‘Missing answers’ warning (unlike excel).  
- [ ]  P03_04: The question is missing (Kolik hodin (1 hodina=60 minut) denně během současného semestru obvykle věnujete studiu ve škole a samostudiu?)
- [ ]  P04_13: In case of missing answers, the warning pops up in czech --> Here, ‘Yes’ is in English in stead of Czech. Besides, the respondent cannot go further without choosing one of the answers, even if the respondent checked the box in front of ‘Yes’
- [ ] P05_01: The question is missing, both if v4_20 ==1, v4_20==3 (Byl/a jste někdy na krátkodobém studijním pobytu na zahraniční vysoké škole (tj. mimo ČR) poté, co jste poprvé vstoupil/a do vysokoškolského studia?) and if v4_20==2 (Kromě své zahraniční stáže: Byl/a jste někdy na krátkodobém studijním pobytu na zahraniční vysoké škole (tj. mimo ČR) poté, co jste poprvé vstoupil/a do vysokoškolského studia?)
- [ ] V6_7a through V6_7d are missing (all Czech national question)
- [ ]  End: there is no place for the respondent to enter their contact email.  
- [ ]  End: the following text is missing: Ještě jednou děkujeme za Vaši ochotu i čas a nyní již můžete stránku zavřít.

**Comment by andreaschu** [comment]
Translations for the following texts are missing: 


- Ne,   nezískal/a jsem jej v přímé návaznosti na své středoškolské studium (např.   maturita při zaměstnání, dálkově). (p02_02)
- Uveďte ke každému výroku, jak s ním souhlasíte nebo nesouhlasíte. (p03_09a)
- Prosíme, používejte pouze čísla a čárku k oddělení desetinného čísla. (p04_06)
- Please refer to your current (main) study programme. (p01_06)

- also the text for the addon-questionnaire is missing
![image](https://user-images.githubusercontent.com/30111489/56578277-8a081f80-65cd-11e9-9bf0-7b028c9a85d4.png)

--

**Comment by andreaschu** [comment]
@silinakowalewski please insert the welcome text on the index page ([Welcome_screen_CZ.docx](https://github.com/dzhw/zofar/files/3107673/Welcome_screen_CZ.docx))

**Comment by andreaschu** [comment]
> P03_02, P03_03, P03_05, P03_06, P03_07, P03_09, P04_03, P04_07, P04_10, P06_05, V06_10, V06_12, P07_01: Please double check missings: No ‘Missing answers’ warning (unlike excel).

The soft forces for single choice answer grids should only be visible if the respondents enter the questionnaire via mobile device (screen width less than 768) and up to the second item there is no answer. The idea is that there should be a reminder for the case that the respondents didn't understood the functioning of the socalled 'carousel'. You can assume that the respondent understood this feature when they activated it, at least once. They still may don't want to answer everything.
That is the way it is programmed for Ireland and Malta. If this should be different, then you have to say us how.

**Comment by jorisc** [comment]
- [ ] Welcome page: consent should be active, not pre-filled
- [ ] v2_6a: "o" is missing for several answer categories
- [ ] v2_6b:  „specifikujte“ (please specify), open answer category but no field for open answer
- [ ] v3_04: Text is missing: "uveďte, prosím, průměrný celkový čas, který jim věnujete." <- Added after last instruction text .
- [ ] v3_9ab; Even when all answers are ticked, there is a missing answers message.
- [ ] v3_09b: Filter missing; if v3_09b =5, 6 or 7, skip to v03_09ba
- [ ] v04-12: text not shown properly (trimmed)
- [ ] v04-17: "Školné a jiné poplatky za studium za semestr" should be bold; "poplatky za studium (školné, registrace, zápis) " shouldn't be bold. 
- [ ] v04_17c: Should be "Kč" instead of "Euro"
- [ ] v06_06: Open ended question not included ("jiné, jaké")
- [ ] v06_06a / b/ c / d: nonsense characters/symbols
- [ ]  v06_10: Vyberte všechny odpovědi, které se Vás týkají.“ should be deleted in question (is explanation)
- [ ] v06_13: Option on the right not well visible
- [ ] progress bar missing (but this is standard, right? 
- [ ] v02_07: options should be exclusive. 
- [ ] v03_08:  mnohem lepší – this is not correct, there   has to be „mnohem horší“ (very important)
- [ ] v04_17a: Currently there is: „Uvedl/a jste, že někdo jiný pravidelně platí Vaše některé účty nebo máte nefinanční podporu: Prosíme, odhadněte peněžní částku, kterou je tvořena tato podpora a uveďte ji do druhého sloupce.“ „Sloupce“ should be change into „příslušného políčka- někdo jiný platí za mě nebo dostávám jako nefinanční podporu.“
- [ ] v04_17b: Curently there is: Označil/a jste, že někdo jiný pravidelně platí některé z Vašich účtů a/nebo Vám poskytuje jako nefinanční podporu/pomoc: Prosíme, vložte přibližnou částku (tj. součet účtů a nefinanční podpory) do druhého sloupce.
„Sloupce“ should be change into „příslušného políčka- někdo jiný platí za mě nebo dostávám jako nefinanční podporu.“
- [ ] Also in English version: v04_17a and v04_17b: Column should be "row".

**Comment by andreaschu** [comment]
- [ ] Index: Ministerstvo školství, mládeže a tělovýchovy České republiky is not translated in the EN version (maybe it is on purpose?) 
- [ ] Index: Typo and could you insert more line breaks? 
- [ ] p01_04a: "bitte auswählen" still in German. 
- [ ] p01_08/p01_09: Please check the filter for page – I got it even though I said I am in a BA programme.
- [ ] p02_06a/b/c: are not translated at all 
- [ ] p02_06a/b/c: the layout of the categories are still overlapping with the item lines
- [ ] p02_07: can be made single choice if there is not second yes answer. 
- [ ] p03_04b: Time budget is not working at all 
- [ ] p03_04b: EN translation is missing: 
- [ ] p03_09ac/b: I think that there are some filters missing for the national 
- [ ] p04_08: Please refer to your paid job(s) during the current semestr. – Typo
- [ ] p04_11: is it possible to have a bit more space between the lines 
Is the bracket expression on purpose? I would delete the [exclusive answer] remark
I am asking again I think – mandatory question – please compare to previous field phases?
- [ ] p04_12: line breaks and spaces! Also not mandatory! 
- [ ] p04_13: The soft warning cannot be ignored 
- [ ] p04_16a: spaces are missing. 
- [ ] p04_17: please check filter/visibility conditions and compare it to the previous versions already online … I did not get the partner explanation
- [ ] p04_17: Switch columns and rows. 
- [ ] p04_24: this should be a different question – about internships abroad!
- [ ] p04_25: typo: The following questions focus only on your most recent internship abroad (i.e. outsideo of the Czech Republic).
- [ ] p04_20 – filters are not working properly – please check the previous versions and copy paste it.
- [ ] p05_02 Typo: I havent made any arrangements, but I am intending to go abroad for a temporary study period.
- [ ] p06_07a-d: translation is missing
- [x] p06_06: Open field is missing
- [ ] p07_01a: Why not transpose it? 
- [ ] end: Translation missing: 

- [ ] All income questions are mandatory??? Please correct!
- [ ] Check formatting/underlining throughout the questionnaire – and compare it to the core questionnaire.

**Comment by jorisc** [comment]
> from e-mail from deVries (Do 18.04.2019, 17:03):
> 
> * [ ]  P01_05: Check the question tree. Now for every ‘fakulty’ the same degrees are shown, while these differ in the question tree. Respondents can pick a degree which does not exist in that faculty. When they continue the questionnaire, they can not pick a study programme. (‘jiný postgraduální (např. MBA), ale nikoliv doktorský’ and ‘doktorský studijní program (PhD.)’ don’t exist at any of the faculties).
> * [x]   P01_08 and P01_09 are missing
> * [ ]   P02_03: After answering P02_02, the respondent should be sent to P02_04. However, this is not the case and question P02_03 is shown.
>   @Eurostudent-RN  @jorisc With this transition p02_03 would never be shown. In which case p02_03 should be shown?

@andreaschu  in all cases, the skip can be deleted.

> * [x]   P03_02, P03_03, P03_05, P03_06, P03_07, P03_09, P04_03, P04_07, P04_10, P06_05, V06_10, V06_12, P07_01: Please double check missings: No ‘Missing answers’ warning (unlike excel).
>   --> see answer below
> * [x]   P03_04: The question is missing (Kolik hodin (1 hodina=60 minut) denně během současného semestru obvykle věnujete studiu ve škole a samostudiu?)
>   @dzhwmeisner The qml seems to be right. What happened here?
> * [x]   P04_13: In case of missing answers, the warning pops up in czech --> Here, ‘Yes’ is in English in stead of Czech. Besides, the respondent cannot go further without choosing one of the answers, even if the respondent checked the box in front of ‘Yes’
>   @dzhwmeisner The qml seems to be right. What happened here?
> * [x]  P05_01: The question is missing, both if v4_20 ==1, v4_20==3 (Byl/a jste někdy na krátkodobém studijním pobytu na zahraniční vysoké škole (tj. mimo ČR) poté, co jste poprvé vstoupil/a do vysokoškolského studia?) and if v4_20==2 (Kromě své zahraniční stáže: Byl/a jste někdy na krátkodobém studijním pobytu na zahraniční vysoké škole (tj. mimo ČR) poté, co jste poprvé vstoupil/a do vysokoškolského studia?)
> * [x]  V6_7a through V6_7d are missing (all Czech national question)
> * [ ]   End: there is no place for the respondent to enter their contact email.
>   @Eurostudent-RN @jorisc Requests of personal data must be collected seperatly from the other informations. Therefore we did a "addon"-questionnaire as in Ireland.

@andreaschu see the email I sent you with Czech translations for price draw.
> * [x]   End: the following text is missing: Ještě jednou děkujeme za Vaši ochotu i čas a nyní již můžete stránku zavřít.

**Comment by jorisc** [comment]
> * [x]  Index: Ministerstvo školství, mládeže a tělovýchovy České republiky is not translated in the EN version (maybe it is on purpose?) -> sk: changed whole Index-Page
> * [x]  Index: Typo and could you insert more line breaks? -> sk: changed whole Index-Page
> * [x]  p01_04a: "bitte auswählen" still in German.
> * [ ]  p01_08/p01_09: Please check the filter for page – I got it even though I said I am in a BA programme.
>   @jorisc: In the Excel-template  the transition says: Go To p01_09 if V1_5!=4. That means, that only people with "Other postgraduate degree (e.g. MBA)" will see question p01_08. Is this transition right?

@andreaschu p01_08 and p01_09 should be asked only to master students (p01_05 eq 2 or 3)

> * [x]  p02_06a/b/c: are not translated at all
> * [ ]  p02_06a/b/c: the layout of the categories are still overlapping with the item lines
> * [ ]  p02_07: can be made single choice if there is not second yes answer.
>   @jorisc: Please make a decision.

@andreaschu single choice is ok

> * [x]  p02_08: double line deleted
> * [x]  p03_04b: Time budget is not working at all
> * [x]  p03_04b: EN translation is missing:
> * [ ]  p03_09ac/b: I think that there are some filters missing for the national
>   @jorisc: Could you please check the filters?

@andreaschu  p03_09a only visible if v1_05 eq 1 (ba)

> * [x]  p04_08: Please refer to your paid job(s) during the current semestr. – Typo
> * [ ]  p04_11: is it possible to have a bit more space between the lines
>   --> which lines exactly? Question texts or Items?
> * [x]  p04_11: Is the bracket expression on purpose? I would delete the [exclusive answer] remark
> * [x]  p04_11: I am asking again I think – mandatory question – please compare to previous field phases?
>   -> it's still mandatory like in Ireland and Malta.
> * [x]  p04_12: line breaks and spaces! Also not mandatory!
>   -> it's still mandatory like in Ireland and Malta.
> * [x]  p04_13: The soft warning cannot be ignored
> * [x]  p04_16a: spaces are missing.
> * [x]  p04_17: please check filter/visibility conditions and compare it to the previous versions already online … I did not get the partner explanation
> * [ ]  p04_19: Switch columns and rows.
> * [ ]  p04_24: this should be a different question – about internships abroad!
>   @jorisc: The czech questiontext of p04_22 and p04_24 are the same (A byla tato nejnovější stáž placená nebo neplacená?). Could you please send us the right questiontexts



> * [x]  p04_25: typo: The following questions focus only on your most recent internship abroad (i.e. outsideo of the Czech Republic).
> * [x]  p04_20: filters are not working properly – please check the previous versions and copy paste it.
> * [x]  p05_02 Typo: I havent made any arrangements, but I am intending to go abroad for a temporary study period.
> * [x]  p05_03: translation missing
> * [x]  p06_07a-d: translation is missing
> * [x]  p06_06: Open field is missing
> * [x]  p07_01a: Why not transpose it?
> * [x]  end: Translation missing
> * [ ]  We have again a decimal point problem, please check all open fields.
>   @dzhwmeisner: Can you help?

**Comment by jorisc** [comment]
@andreaschu 
- [ ] P06_06: Values/Labels for languages are different for the Czech and English questionnaire. Can we combine the lists, so both have 9 options (Ukrainian is in both)

**Comment by jorisc** [comment]
@andreaschu 
Information on data protection and consent.
[Informace_ochrana osobních dat.pdf](https://github.com/dzhw/zofar/files/3115877/Informace_ochrana.osobnich.dat.pdf)
[Data protection information.pdf](https://github.com/dzhw/zofar/files/3115878/Data.protection.information.pdf)

**Comment by andreaschu** [comment]
@jorisc regarding the question flow of the national questions (p03_09 --> p03_09bb) we have painted a bit. :o)
![eurostudent_czech_national_questionflow](https://user-images.githubusercontent.com/30111489/56727839-cebcc380-6751-11e9-8d4f-c5914ec7cbc5.jpg)

I hope you can read (and understand) it. This is how it is programmed. Please confirm if it is correct.

**Comment by jorisc** [comment]
Welcome page: 
- [ ] Please notice that to participate without consent to the Privacy Policy the survey unfortunately not possible.- translation for Czech: "Abyste mohl/a začít vyplňovat dotazník, prosíme, zaškrtněte políčko se souhlasem o poskytnutí dat a jejich ochraně."
- [ ] p03_08: English: last answer category should be: "Much worse" 
 - [ ] p02_02: English categories should be as follows (this is similar to Czech categories): 
1- Yes, upon leaving upper secondary school (within 6 months)
2- No, later (7-12 months) after finishing upper secondary school (e.g. I had to repeat maturita)
3- No, later in life (via bridging courses, second chance routes, etc.)

**Comment by jorisc** [comment]
> @jorisc regarding the question flow of the national questions (p03_09 --> p03_09bb) we have painted a bit. :o)
> ![eurostudent_czech_national_questionflow](https://user-images.githubusercontent.com/30111489/56727839-cebcc380-6751-11e9-8d4f-c5914ec7cbc5.jpg)
> 
> I hope you can read (and understand) it. This is how it is programmed. Please confirm if it is correct.
@andreaschu 
Yes, exactly!

**Comment by jorisc** [comment]
Updated banner: 
![image](https://user-images.githubusercontent.com/7701318/56735346-7f808e00-6765-11e9-9f03-0a70ce8dfeed.png)

**Comment by SilinaKowalewski** [comment]
Because there is no progress bar, text on welcome screens deleted: 
A progress bar shows how far you are through the survey. 
Během vyplňování uvidíte na ukazateli, jak daleko do konce dotazníku ještě zbývá.

**Comment by jorisc** [comment]
Got this error on end page (English)
![image](https://user-images.githubusercontent.com/7701318/56807654-c2a73380-682f-11e9-8d33-8a3e80da334f.png)

**Comment by jorisc** [comment]
### English
#### Functional

- [ ] P02_10: I have to scroll to the right to see “Not at all” and fourth and fifth answer circle. 
- [ ] P03_03 didn’t answer any questions but I didn’t get a “missing answers” warning/error. 
- [ ] P04_06: cant enter comma or decimal separator
- [ ] P07_01a: two questions on one page, could this be split? 


#### Typos, text, etc.
- [ ] P02_01 EN : translation missing: Mám českou maturitu
       Translation: 
	I obtained my maturita in the Czech Republic
- [ ] P02_06b5: “secondayry” should be “secondary”
- [ ] P2_07: “Multiple answers possible.” Should be deleted. 
- [ ] P03_9bb_02: typo: “proefessionaly” should be “professionally”. 
- [ ] P03_9bb_03: typo: “degre” should be “degree”
 - [ ] p03_02 a p03_03 p03_05, p03_06, p03_07 a p03_09 p04_03 p04_10 p06_05: No missing answers 
warnings
- [ ] p03_04b p04_15: missing answers warning but not obligatory

**more coming**

**Comment by andreaschu** [comment]
>  P07_01a: two questions on one page, could this be split?
Then the text would be a bit strange

**Comment by jorisc** [comment]
> > P07_01a: two questions on one page, could this be split?
> 
> Then the text would be a bit strange
@andreaschu 
The questions are not directly related. If the second question is like this it should be fine: 
What type of school did you graduate in before your first entry into higher education?

I'll ask for the Czech translation.

**Comment by andreaschu** [comment]
> P02_10: I have to scroll to the right to see “Not at all” and fourth and fifth answer circle.

for mobile device? that is why there is the page after the index-page (offer.html)
![grafik](https://user-images.githubusercontent.com/30111489/56817178-53d4d500-6845-11e9-9579-5cb90bee6fc5.png)

**Comment by andreaschu** [comment]
>  P03_03 didn’t answer any questions but I didn’t get a “missing answers” warning/error.

> p03_02 a p03_03 p03_05, p03_06, p03_07 a p03_09 p04_03 p04_10 p06_05: No missing answers
> warnings

See answer above. 

> The soft forces for single choice answer grids should only be visible if the respondents enter the questionnaire via mobile device (screen width less than 768) and up to the second item there is no answer. The idea is that there should be a reminder for the case that the respondents didn't understood the functioning of the socalled 'carousel'. You can assume that the respondent understood this feature when they activated it, at least once. They still may don't want to answer everything.
> That is the way it is programmed for Ireland and Malta. If this should be different, then you have to say us how.

It works for me this way. If there is something else, please be more detailled.

**Comment by andreaschu** [comment]
- [ ]  @dzhwmeisner "p04_06: cant enter comma or decimal separator" --> only dots are allowed, please change

**Comment by andreaschu** [comment]
> No place for respondentent to enter contact email (in Czech)

- [ ] @dzhwmeisner addon--> translation button is missing (default language = english)

**Comment by andreaschu** [comment]
>  P04_19: Text is in front of where answers should be filled in

- [ ] @dzhwmeisner please have a look at the layout

**Comment by andreaschu** [comment]
> - [ ] Text on email page is wrong: Please contact us at EMaileurostudent@insightsc.ie???MAIL_STOP??? if you have any queries or otherwise. See:

@jorisc I don't understand this comment. Please be more detailled e.g. with page-id or with screenshot

**Comment by andreaschu** [comment]
> P06_07b: Please add hyperlinks: Please rate your command of the foreign language that you command best using the <Common European Framework of Reference for Languages (CEFR)> scale:
> hyperlink: https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?documentId=090000168045bb6d
> 
> "Jak byste ohodnotil/a svou znalost tohoto cizího jazyka, který ovládáte nejlépe, na stupnici dle <Společného evropského referenčního rámce pro jazyky (CEFR)>:
> 
> hyperlink: https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?
> documentId=090000168045bb6d

@jorisc I don't understand this one to. Can you explain different? If not, we should skype about this on monday.

**Comment by andreaschu** [comment]
>  ### errors in question tree; mismatches on values
@andreaschu @dzhwmeisner @SilinaKowalewski --> we have to check for the 'automation' or 'translation of the list'

**Comment by jorisc** [comment]
**Translations:**
- [ ] P_04_15 Czech: Replace "(" with ",". 
- [ ] P_04_15 Czech: Replace "(" with ",". 

- [ ] P06_01 can years be limited to 2003 as highest value? 
- [ ] p06_10: Please change question „Uveďte prosím, jestli máte nějaké zdravotní omezení či dlouhodobé zdravotní problémy, omezení.“ into: „Uveďte prosím, jestli máte nějaké zdravotní omezení či dlouhodobé zdravotní problémy.“
- [ ] P07_02: Please remove in the explanation: "If one or both of your parents is/ are deceased, please refer to their most recent financial situation" / „Pokud jeden nebo oba rodiče/pěstouni již zemřeli, zkuste odpověď vztáhnout k jejich nejaktuálnější životní situaci (tj. předtím, než zemřeli).“

**Comment by jorisc** [comment]
> > P06_07b: Please add hyperlinks: Please rate your command of the foreign language that you command best using the <Common European Framework of Reference for Languages (CEFR)> scale:
> > hyperlink: https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?documentId=090000168045bb6d
> > "Jak byste ohodnotil/a svou znalost tohoto cizího jazyka, který ovládáte nejlépe, na stupnici dle <Společného evropského referenčního rámce pro jazyky (CEFR)>:
> > hyperlink: https://rm.coe.int/CoERMPublicCommonSearchServices/DisplayDCTMContent?
> > documentId=090000168045bb6d
> 
> @jorisc I don't understand this one to. Can you explain different? If not, we should skype about this on monday.

@andreaschu 
They asked if they could add a hyperlink in the question for extra information on the CEFR. I Argued it'd be bad idea since you risk people dropping out since they have to open a different screen, but they still wanted it. So the "Commin European Framework of Reference for Languages (CEFR)" should be a link to the url I mentioned (on a new tab or screen).

**Comment by jorisc** [comment]
> > * [ ]  Text on email page is wrong: Please contact us at [EMaileurostudent@insightsc.ie](mailto:EMaileurostudent@insightsc.ie)???MAIL_STOP??? if you have any queries or otherwise. See:
> 
> @jorisc I don't understand this comment. Please be more detailled e.g. with page-id or with screenshot

https://survey02.dzhw.eu/Eurostudent-Czech-Republic-Addon/end.html

**Comment by jorisc** [comment]
- [ ] There is no "Start here" button on 
`https://survey02.dzhw.eu/Eurostudent-Czech-Republic-Addon/special/login.html?zofar_token=` 
![image](https://user-images.githubusercontent.com/7701318/56881840-03868e80-6a62-11e9-8afc-69b5406db394.png)

**Comment by jorisc** [comment]
**Mismatches question tree:**
In CZ
1.	ŠKODA AUTO Vysoká škola
2.	Slezská univerzita v Opavě
3.	Soukromá vysoká  škola ekonomická Znojmo, s.r.o.

In EN
1.	Silesian University in Opava (i.e. Slezská univerzita v Opavě)
2.	Private College of Economic Studies (i.e. Soukromá vysoká  škola ekonomická Znojmo, s.r.o.
 
3.	SKODA AUTO University

And: 
1.	Česká zemědělská univerzita 
2.	České vysoké učení technické
3.	Cevro Institute
 
BUT order in EN is  (and wrong faculties and study programmes)
 
1.	CEVRO
2.	Czech University of Life Science 
3.	Czech Technical University in Prague

And: 
1) Vysoká škola báňská – Technická univerzita
2) Vysoká škola chemicko-technologická v Praze
3)Vysoká škola ekonomická v Praze
 
In EN wrong order
1) VSB-Technical University Ostrava (Vysoká škola báňská) – this also correct in EN but others no…
2)University of Economics (Vysoká škola ekonomická v Praze)
And all HEIs between

And University of Technology (Vysoká škola Chemicko-technologická v Praze) is completely out of order ….

**Comment by jorisc** [comment]
- [ ] Welcome page Czech: „Pomozte nám získat co nejúplnější obrázek Vašich studentských zkušeností a odpovězte na otázky týkající se důležitých témat vysokoškolského vzdělávání. Jsou to například otázky kolem bydlení, cestování, finančního zabezpečení, zaměstnání při studiu nebo modely studia. Vyplňování Vám zabere přibližně půl hodiny Vašeho času. Některé otázky v dotazníku je nutné vyplnit, protože bez nich by analýza nešla vůbec provést, některé jsou volitelné. Během vyplňování uvidíte na ukazateli, jak daleko do konce dotazníku ještě zbývá.
Please remove last bit(refers to non-existing progress bar): 
**Během vyplňování uvidíte na ukazateli, jak daleko do konce dotazníku ještě zbývá.** 

- [ ] p03_09ac: Filter is wrong, this should only be visible if v1_05 == 2 (instead of 3).

**Comment by andreaschu** [comment]
@jorisc we would like to change the question texts of pages p01_04 and p01_04a (because we splitted them into to pages). Please confirm.
**p01_04:** 
question text change from: _"Name of the higher education institution and faculty if it is appropriate"_
to "_Name of the higher education institution"_ / "_Uveďte jméno vysoké školy"_
delete: "name of university/college: "

**p01_04a:**
question text (new): _"Name of the faculty"_/ _"Uveďte jméno vysoké fakultu"_
delete: "name of faculty:"

**Comment by jorisc** [comment]
> @jorisc we would like to change the question texts of pages p01_04 and p01_04a (because we splitted them into to pages). Please confirm.
> **p01_04:**
> question text change from: _"Name of the higher education institution and faculty if it is appropriate"_
> to "_Name of the higher education institution"_ / "_Uveďte jméno vysoké školy"_
> delete: "name of university/college: "

@andreaschu Correct
> 
> **p01_04a:**
> question text (new): _"Name of the faculty"_/ _"Uveďte jméno vysoké fakultu"_
> delete: "name of faculty:"
@andreaschu  This should be: "Uveďte jméno fakulty"

**Comment by jorisc** [comment]
*minor*
- [ ] p02_09 Mezi placené práce nepočítejte případnou vojenskou službu. Change into „Mezi placené práce nepočítejte případnou povinnou vojenskou službu.“

**Comment by jorisc** [comment]
@andreaschu 
- [ ] no 

> > P03_03 didn’t answer any questions but I didn’t get a “missing answers” warning/error.
> 
> > p03_02 a p03_03 p03_05, p03_06, p03_07 a p03_09 p04_03 p04_10 p06_05: No missing answers
> > warnings
> 
> See answer above.
> 
> > The soft forces for single choice answer grids should only be visible if the respondents enter the questionnaire via mobile device (screen width less than 768) and up to the second item there is no answer. The idea is that there should be a reminder for the case that the respondents didn't understood the functioning of the socalled 'carousel'. You can assume that the respondent understood this feature when they activated it, at least once. They still may don't want to answer everything.
> > That is the way it is programmed for Ireland and Malta. If this should be different, then you have to say us how.
> 
> It works for me this way. If there is something else, please be more detailled.
@andreaschu 
The Czech want to use the warnings for desktop users as well. 
Is it much work to adapt this? It would be for all warnings, no exceptions…

**Comment by jorisc** [comment]
- [ ] Prize draw url for English page is wrong; should be this: 
`https://www.csvs.cz/en/eurostudent-vii/`
![image](https://user-images.githubusercontent.com/7701318/56972389-2cdf1180-6b6b-11e9-8d1d-b26e2525d412.png)

**Comment by jorisc** [comment]
@andreaschu 
On this page, are students supposed to get here? Or would they skip?
In the URL I see the there is no token sent: 
`https://survey02.dzhw.eu/Eurostudent-Czech-Republic-Addon/special/login.html?zofar_token=`

![image](https://user-images.githubusercontent.com/7701318/57059973-e519d080-6cb7-11e9-969b-06ce13f10f56.png)

**Comment by andreaschu** [comment]
> @andreaschu
> On this page, are students supposed to get here? Or would they skip?
> In the URL I see the there is no token sent:

@jorisc they will skip this page and directly send to the index-page. The token are as Preloads in the main survey, so you do not have to know them. (It's even better if you don't, because of data protection issues.)

**Comment by jorisc** [comment]
@andreaschu 
Czech found one translation missing, but it's not that important. 
- [ ] P06_07d: „Please, consider the language you command best.“ Change into: „Máme na mysli jazyk, který ovládáte nejlépe.“

**Comment by jorisc** [comment]
- [ ] p02_09: Two first options in CZ should be changed into this: (no changes in EN version – this is correct) . Ps: BOLD should be underlined (can't do this in markdown). 
- Ano, **soustavně**   jsem pracoval/a alespoň
  jeden rok **minimálně 20 hodin týdně**.
- Ano, **soustavně**   jsem pracoval/a alespoň
jeden rok **méně než 20 hodin týdně**.

**Comment by dzhwmeisner** [comment]
- [ ] feedback
- [ ] screenshots
- [ ] export (incl. SPSS)
- [ ] archiv

**Comment by andreaschu** [comment]
@Eurostudent-RN data from prize draw: https://myshare.his.de/s/st1d0iTtUJqvAyA

**Comment by andreaschu** [comment]
@dzhwmeisner please correct value of **_ao2_** to **_2_** in variable _V5_8_10_

**Comment by dzhwmeisner** [comment]
Screenshots generated. http://vmdevwiki.dzhw.local/public/eurostudentczech/Eurostudent-Czech_screenshots.zip

**Comment by mattenko** [comment]
Archiving done
