### ISSUE TITLE
Eurostudent-Luxembourg

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#154]
**Eurostudent-Luxemburg**

further information:
- field start: **06.05.2019**
- field end: **31.05.2019**
- three languages: French, German, English
- link shall be: https://www.eurostudent.eu/luxembourg 
- there is no prize draw

**To Do's:**
- [x] creating a project (@vdick),name: Eurostudent-Luxemburg 
- [x] programming first draft of questionnaire: [LUX_ZOFAR Excel file 3.4.2019_AH v1.xlsx](https://github.com/dzhw/zofar/files/3093929/LUX_ZOFAR.Excel.file.3.4.2019_AH.v1.xlsx)
- [x] testing and correcting
- [x] going online
- [x] feedback (weekly)
- [x]  screenshots
- [x]  archiving
- [x]  export of Data

**Comment by vdick** [comment]
Testlink: https://presentation.dzhw.eu/Eurostudent-Luxemburg/
Token: tester1-tester100

**Comment by andreaschu** [comment]
@dzhwmeisner please create token and preloads-variables for luxembourg:


Institution   --> #institution | Degree --> #degree | token generated | iid | idid
-- | -- | -- | -- | --
Lycée des Arts   et Métiers | BTS | 200 | 1 | 1
Lycée Josy   Barthel Mamer | BTS | 100 | 2 | 2
Lycée   classique de Diekirch | BTS | 50 | 3 | 3
Lycée   Technique pour Professions de Santé | BTS | 700 | 4 | 4
Ecole   d'Hotellerie et du Tourisme | BTS | 50 | 5 | 5
Lycée   Technique de Bonnevoie | BTS | 50 | 6 | 6
Lycée   Guillaume Kroll | BTS | 50 | 7 | 7
Ecole de   Commerce et de Gestion | BTS | 300 | 8 | 8
Lycée du Nord | BTS | 50 | 9 | 9
Lycée   Technique du Centre | BTS | 50 | 10 | 10
Lycée   Technique d'Ettelbruck | BTS | 50 | 11 | 11
Lycée   classique d'Echternach | Préparation Grandes   Écoles | 50 | 12 | 12
ISEC -   Institut Supérieur de l'Économie | BA | 50 | 13 | 13
  | MA | 50 |   | 14
LUNEX | BA | 300 | 14 | 15
University of   Luxembourg | BA | 5000 | 15 | 16
  | MA | 3000 |   | 17
  | PhD | 2000 |   | 18
  | Sum | 12100 |   |

**Comment by andreaschu** [comment]
- [ ] @dzhwmeisner please import the Logo next to the eurostudent logo
![UL Logo](https://user-images.githubusercontent.com/30111489/56584773-c0996680-65dc-11e9-8e5d-2aeab91f9276.jpg)

**Comment by andreaschu** [comment]
p04_16: doubled answer options and variables :

---
--> V4_16_7b: "Other non-repayable income from private sources (e.g. alimony, private scholarship, income from capital, property, occasional income from sales, gifts)"
--> V4_16_9a:  "Other non-repayable income from private sources (e.g. alimony, private scholarship, income from capital, property, occasional income from sales, gifts)" 

---
--> V4_16_8: "Other repayable income from private sources (e.g. loan, private borrowing)"
--> V4_16_9b: "Other repayable income from private sources (e.g. loan, private borrowing)"

---
Only visible conditions are different. We can do more than one vc for one question. What shall happen here?

**Comment by dzhwmeisner** [comment]
[token_Luxembourg.zip](https://github.com/dzhw/zofar/files/3115996/token_Luxembourg.zip)

Tokens generated

**Comment by jorisc** [comment]
All class préparatoire for grand ecoles are skipped so not part of the survey anymore. 
This means that in **p01_03** answer category 3 can be deleted:
- “preparation class for French grandes écoles”
- “Vorbereitungskurs für eine französiche Grande École»
- «cours de préparation pour une Grande École francaise”
It's also mentioned in intro's for questions but there it can stay.

**Comment by andreaschu** [comment]
@dzhwmeisner --> comma as decimal seperator
- [ ] p04_06 
- [ ] p04_25
- [ ] p05_03

**Comment by andreaschu** [comment]
@jorisc  pZ_02.html - english question text is missing

**Comment by jorisc** [comment]
- [ ] P04_11 is missing (after P04_10 (EN); you will get an 500 error. 
      https://presentation.dzhw.eu/Eurostudent-Luxembourg/p04_11.html

**Comment by jorisc** [comment]
@dzhwmeisner can we get 300 extra tokens for LUNEX (iid 14, idid 15)?

**Comment by dzhwmeisner** [comment]
[tokensFromReserve300419.zip](https://github.com/dzhw/zofar/files/3131722/tokensFromReserve300419.zip)

300 Token assigned to LUNEX incl. Preloads
institution='LUNEX' 
degree='BA'
iid='14'
idid='15'

**Comment by andreaschu** [comment]
@jorisc there are some texts missing for the translation. We made an excel table. Please add the missing texts for German and French.
[missing_translations.xlsx](https://github.com/dzhw/zofar/files/3132090/missing_translations.xlsx)

**Comment by SilinaKowalewski** [comment]
- [ ] p07_01: Mother/   legal guardian 1 & Father/   legal guardian 2
p07_01Z: Father/legal guardian 1 & Mother/legal guardian 2

Shall we unify this?

**Comment by andreaschu** [comment]
updated version of the questionnaire: [LUX_ZOFAR Excel file UPDATE 30042019.xlsx](https://github.com/dzhw/zofar/files/3137785/LUX_ZOFAR.Excel.file.UPDATE.30042019.xlsx)
The changes are made are the following: 
- Question tree has been updated, study program names have been harmonized
- country list includes now priority countries
- question P04_17a: we modified the text of the first answering option and deleted the second item. 
- P04_20 : additional comment in the comment section 
- 07_01Z: we originally had a range of answering categories there but decided to switch to an open question. Accordingly, we also made a small change in the comment text.

**Comment by jorisc** [comment]
> * [ ]  p07_01: Mother/   legal guardian 1 & Father/   legal guardian 2
>   p07_01Z: Father/legal guardian 1 & Mother/legal guardian 2
> 
> @jorisc Shall we unify this?

Yes please; for p07_01z: Mother/ legal guardian 1 & Father/ legal guardian 2

@andreaschu there's also a layout-issue here (on desktop):
![image](https://user-images.githubusercontent.com/7701318/57079229-3940a700-6cf0-11e9-856e-774c160e390a.png)

**Comment by jorisc** [comment]
Translations for the months: 
[LUX_translationsMonths.xlsx](https://github.com/dzhw/zofar/files/3138362/LUX_translationsMonths.xlsx)

**Comment by SilinaKowalewski** [comment]
@jorisc: Unfortunately, the translations are still missing for the following texts. Currently we have added these texts in English also for the German and French translation.

> Thank you for participating in the European survey on studying and living conditions EUROSTUDENT.  Your opinion does matter, as you as a student are an expert on study and living conditions in Luxembourg. You do not need to fill in the questionnaire at once, but you have the option to exit the survey and continue at a later time. Please note that the survey is not optimised for smartphones, please use a laptop or PC.

> Please notice that to participate without consent to the Privacy Policy the survey unfortunately not possible.

> In order to receive the best experience while answering our questionnaire, some questions will require a turning of the display.

**Comment by andreaschu** [comment]
@jorisc the logo of the university is really small because of it's format. Do you know if they have a version without the bottom line ("UNIVERSITÉ DU LUXEMBOURG")? That would provide more space and would be better readable (and still recognizable).
E.G. this:
![grafik](https://user-images.githubusercontent.com/30111489/57130497-f20ef080-6d99-11e9-81d4-0cb97772aa80.png)

or that:
![grafik](https://user-images.githubusercontent.com/30111489/57130514-fc30ef00-6d99-11e9-90b1-650a40c8794c.png)

**Comment by jorisc** [comment]
> @jorisc: Unfortunately, the translations are still missing for the following texts. Currently we have added these texts in English also for the German and French translation.
> 
> > Please notice that to participate without consent to the Privacy Policy the survey unfortunately not possible.
> 
> > In order to receive the best experience while answering our questionnaire, some questions will require a turning of the display.

Please change the EN wording of the 1st sentence to the following: 
Please notice that it is not possible to participate in the survey without consent to the privacy police statement.

Accordingly, the DE version would be: 
Bitte beachten Sie, dass eine Teilnahme an der Befragung ohne Zustimmung der Datenschutzerklärung nicht möglich ist.  

In FR: 
Veuillez noter qu'il est impossible de participer à l'enquête sans consentir à la déclaration de confidentialité de données. 

The 2nd sentence in DE:
Um den Fragebogen reibungslos auszufüllen, müssten Sie bei einigen Fragen das Display drehen.

In FR:
Afin de compléter l'enquête sans difficultés, vous seriez demandé de tourner l’écran afin de répondre à certaines questions.

**Comment by jorisc** [comment]
- [ ] p04_17a: 4 items here, should be 2 (v4_17_12cash and v4_17_12tik only). 

![image](https://user-images.githubusercontent.com/7701318/57131316-4fa43c80-6d9c-11e9-9609-a473d077658b.png)

**Comment by jorisc** [comment]
> @jorisc the logo of the university is really small because of it's format. Do you know if they have a version without the bottom line ("UNIVERSITÉ DU LUXEMBOURG")? That would provide more space and would be better readable (and still recognizable).
> E.G. this:
> ![grafik](https://user-images.githubusercontent.com/30111489/57130497-f20ef080-6d99-11e9-81d4-0cb97772aa80.png)
> 
> or that:
> ![grafik](https://user-images.githubusercontent.com/30111489/57130514-fc30ef00-6d99-11e9-90b1-650a40c8794c.png)
Will this do? 
![Uni LUX_Logo](https://user-images.githubusercontent.com/7701318/57131943-4916c480-6d9e-11e9-8a74-b31e09d0b9af.jpg)

**Comment by andreaschu** [comment]
@jorisc we updated the question tree in the testlink. It looks good, but since there are a lot HEIs with only one possible degree and some with only one possible study programme it looks often quite strange, because in those cases the 'single choice' is not really a 'choice'. I would suggest to skip the questions when there is no choice at all. Please confirm (or not).

**Comment by jorisc** [comment]
- [ ] p01_03: In explanation, remove : "preparation grandes écoles"

**Comment by jorisc** [comment]
> @jorisc we updated the question tree in the testlink. It looks good, but since there are a lot HEIs with only one possible degree and some with only one possible study programme it looks often quite strange, because in those cases the 'single choice' is not really a 'choice'. I would suggest to skip the questions when there is no choice at all. Please confirm (or not).

I'll check, but now students do have more control, so even if it's strange, it's a extra check if they accidentally put in the wrong information, so I doubt it helps much.

**Comment by jorisc** [comment]
- [ ] P04_16: Update for filters
[Kopie van Filters 4_16.xlsx](https://github.com/dzhw/zofar/files/3142320/Kopie.van.Filters.4_16.xlsx)

**Comment by jorisc** [comment]
**French:**
- index: hyperlink: fix #{layout...}, and remove one dot after "...données"
 "Pour plus amples informations sur l#{layout.SQuotes}enquête ainsi que sur la protection des données.."  
- [ ] p01: Only underline "actuellement" (2nd and 3rd lines)
- [ ] p01_03: 3rd item is wrong: now it's "At a lycée/other school (BTS study progrmame)"
   should be: "Dans un lycée/une école (BTS)"
- [ ] p01_03: In explanation remove "Préparation Grandes Écoles/"
- [ ] p03_07: should be: "Pas du tout suffisant", now it's "suffisait-e"
- [ ] p04_13: Missing answer warning is in English: 
       selecting continue anyway does not continue. 
- [ ] p04_09/10/11: There is code visible in the question: p04_09: "Lequel des énoncés suivants décrit ???UNDRLINED_START???au mieux???UNDRLINED_END??? votre situation actuelle?"
- [ ] p05_01: Remove arrows in this question: "«En plus de votre stage à l’étranger: avez-vous déjà participé à l’une des activités temporaires suivantes liées aux études à l’étranger depuis votre entrée dans l’enseignement supérieur au Luxembourg»?"
- [ ] 06_13: layout issue (most right category)
![image](https://user-images.githubusercontent.com/7701318/57183624-f3cad800-6eaf-11e9-8837-4862a23a9867.png)
- [ ] p07_01z: Translation missing

**Comment by jorisc** [comment]
@andreaschu 
**major**:
- [ ] Error in question tree: selecting University of Luxembourg, then Bachelor leads to no programmes. 


- [ ] index: all url's lead to English document

**Comment by SilinaKowalewski** [comment]
@jorisc:
Irina wrote me yesterday:
> •	p02_1Z is missing please include!


In fact, this question exists but due to the filter conditions in template, the question is never displayed.

> Go To   p02_02 if v2_1==1 OR v2_1==2 OR v2_1==3
Go To   p02_03 if v2_1==4

When should the question p02_01Z be displayed?

**Comment by jorisc** [comment]
> @jorisc:
> Irina wrote me yesterday:
> 
> > •	p02_1Z is missing please include!
> 
> In fact, this question exists but due to the filter conditions in template, the question is never displayed.
> 
> > Go To   p02_02 if v2_1==1 OR v2_1==2 OR v2_1==3
> > Go To   p02_03 if v2_1==4
> 
> When should the question p02_01Z be displayed?

Should be visible when:
p02_01 == 1 OR p02_01 == 2 OR p02_01 == 3

**Comment by dzhwmeisner** [comment]
- [ ] feedback
- [ ] screenshots
- [ ] export
- [ ] archiv

**Comment by andreaschu** [comment]
@vdick and @dzhwmeisner survey can go offline

**Comment by vdick** [comment]
@andreaschu  and @dzhwmeisner survey is offline

**Comment by andreaschu** [comment]
@Eurostudent-RN 
The link for the dataset: https://myshare.his.de/s/U11ZwKcZ4OI0jTs

**Comment by mattenko** [comment]
Archiving done
