### ISSUE TITLE
OHO-Projektbeteiligte

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#157]
Link: http://vmtest.dzhw.local:8080/oho-pb/ 
Test-token: tester1-tester100
Field start: **22.05.2019**
- [x] creating a project 
- [x] programming first draft of questionnaire
- [x] testing and correcting
- [x] going online
- [x]  Screenshots
- [x]  Archivierung
- [x]  Export of Data

**Comment by andreaschu** [comment]
@dzhwmeisner on monday morning: 
- [ ] please update the preloads ([PB-Befragung_Preloads.xlsx](https://github.com/dzhw/zofar/files/3165979/PB-Befragung_Preloads.xlsx)) and 
- [ ] clean the data

**Comment by Brochterbeck** [comment]
please update the preloads (PB-Befragung_Preloads.xlsx) and clean the data

--> done

**Comment by andreaschu** [comment]
- [ ] Export of Pretest-Data

**Comment by andreaschu** [comment]
layout: Antwortkategorien sehr weit auseinander, bei horizontaler Ansicht sind nicht beide Antwortkategorien sichtbar, 
Seiten: 
- [ ] 2.01
- [ ] 2.03
- [ ] 2.04
- [ ] 3.01
- [ ] 3.01.1
- [ ] 3.02
- [ ] 3.03
- [ ] 3.04
- [ ] 3.08
- [ ] 4.01
- [ ] 4.03
- [ ] 4.13
- [ ] 4.14
- [ ] 4.15

**Comment by andreaschu** [comment]
layout: Antwortkategorien überlappen sich in mobilen Ansichten 
Seiten:
- [ ] 2.08  
- [ ] 3.07 
- [ ] 4.06 
- [ ] 4.09 
- [ ] 4.13.2 
- [ ] 4.14.2 
- [ ] 4.15.2 
- [ ] 4.15.3
- [ ] 5.01

**Comment by andreaschu** [comment]
- [ ] Die Aufforderung zum Drehen der Anzeige wird nur auf wenigen mobilen Geräten angezeigt, auf den meisten Tablets gar nicht. Wie sind hier die Bedingungen und können diese noch angepasst werden?
- [ ] p1.01: Antwortkategorie ao3 zu nah an ao2, 
- [ ] p1.01: das Freitextfeld sollte wenn möglich dahinter stehen
- [ ] p2.04.1: Bindestrich sollte am Wortteil „externe“ bleiben, also nach dem Absatz und nicht davor stehen
- [ ] p2.04.1.1: Fragetext Größe bitte entsprechend der anderen Fragen anpassen
- [ ] p2.07: Das Textfeld von ao2 sollte wenn möglich unter den Text
- [ ] p5.01: Die Überschrift ist kleiner als Fragestellung, 
- [ ] p5.01: Antwort „nicht Ziel des Projekts“ auch von Skala absetzen

**Comment by andreaschu** [comment]
**Layout:** 
- [ ] 2.07: Bei der mobilen Ansicht verschwindet das Freitextfeld hinter dem Karussell und ist nur schwer auswählbar w
![grafik](https://user-images.githubusercontent.com/30111489/57916344-f1df1c80-7892-11e9-8bd9-a91cb9840f63.png)

**Comment by koopmann1896** [comment]
> layout: Antwortkategorien sehr weit auseinander, bei horizontaler Ansicht sind nicht beide Antwortkategorien 

- [ ] Bitte auch für 2_02 übernehmen

**Comment by andreaschu** [comment]
@koopmann1896 kannst Du mir eine Übersicht für die Anzahl von Token entweder gesamt (dann müsstet Ihr die Preloads zuordnen) oder pro Kombination von  Projekt, Projektart und Hochschule geben?

Hier eine Beispieltabelle für die zweite Variante:

Projekt-ID | Hochschul-ID | Projektart | Anz. Token
-- | -- | -- | -- 
EP_01 |  56 | EP | 50
EP_26 |  81 | EP | 70

**Comment by koopmann1896** [comment]
> @koopmann1896 kannst Du mir eine Übersicht für die Anzahl von Token entweder gesamt (dann müsstet Ihr die Preloads zuordnen) oder pro Kombination von Projekt, Projektart und Hochschule geben?
> 
> Hier eine Beispieltabelle für die zweite Variante:
> 
> Projekt-ID	Hochschul-ID	Projektart	Anz. Token
> EP_01	56	EP	50
> EP_26	81	EP	70


Moin Andrea, hier ist die Liste:
[01_Tokenverteilung_Gesamt.xlsx](https://github.com/dzhw/zofar/files/3197151/01_Tokenverteilung_Gesamt.xlsx)

**Comment by koopmann1896** [comment]
### Änderungen Offen

@SilinaKowalewski @andreaschu 

Hier letzte offen stehende Änderungen:

Allgemein:
- [ ] Anmerkungsfelder des Pretests deaktivieren
- [ ] Preloads zu tester42 bis tester45 haben falsche Bezeichnungen des Projekt: work#study wird angezeigt, sollte aber work&study heißen 

Seitenspezifisch:
- [ ] Login-Seite: Logos sind übereinander und extrem klein
- [ ] Indexseite: Die Befragung  startet bis dato nach abgelaufener Zeit immer wieder auf der Startseite
- [ ] p.2.04.1.1: Fragetext Größe bitte entsprechend der anderen Fragen anpassen
- [ ] p.3.04.1.1: Fragetext Größe bitte entsprechend der anderen Fragen anpassen

in der mobilen Ansicht:
- [ ] Offerseite:  Die Aufforderung zum Drehen der Anzeige wird nur auf wenigen mobilen Geräten angezeigt, auf den meisten Tablets gar nicht. Wie sind hier die Bedingungen und können diese noch angepasst werden?
- [ ] p4.13.2; p4.14.2; p4.15.2: Bei mobiler Ansicht“ Se“ von „Sehr unzufrieden“ abgeschnitten, trotz 

Ausfüllanweisung:
Ausfüllen des Freitextfeldes und Auswahl von „Kann ich nicht beurteilen.“ bzw.  „Es haben sich keine Herausforderungen gezeigt.“ möglich, hier sollte eine Exclusivbedingung eingefügt werden:
- [ ] 1.07
- [ ] 1.08
- [ ] 4.06
- [ ] 4.09
- [ ] [4.11]

**Comment by koopmann1896** [comment]
@andreaschu 
Linkname für die Befragung: oh-projektbeschaeftigte

**Comment by koopmann1896** [comment]
@vdick 

- [ ] Die Logos sind generell noch sehr klein, auf großen Bildschirmen. Lässt sich dies noch anpassen?

**Comment by vdick** [comment]
@koopmann1896 wie bereits telefonisch abgesprochen, Exclusivbedingungen werden aus zeitlichen Gründen nicht umgesetzt.

**Comment by koopmann1896** [comment]
@vdick 

- [ ] Die Links der Email-Adressen auf der Startseite funktionieren noch nicht, beziehungsweise werden leere Browsertabs geöffnet.

**Comment by koopmann1896** [comment]
### Probleme in der mobilen Ansicht bzw. kleinem Fenster:
@vdick 

- [ ] 2.08: Ü von "**Ü**berhaupt nicht*" und t von "kann ich nich**t** beurteilen" abgeschnitten
- [ ] 3.07: Ü von "**Ü**berhaupt nicht" und t von "kann ich nich**t** beurteilen" abgeschnitten
- [ ] 3.08.02: j von "**j**a, vollständig" abgeschnitten
- [ ] 4.06: Se von "**Se**hr unzufrieden" und  n von "Sehr unzufriede**n**" abgeschnitten
- [ ] 4.09: Ü von "**Ü**berhaupt nicht*" und t von "Überhaupt nich**t**" abgeschnitten

**Comment by andreaschu** [comment]
@koopmann1896 bitte noch mal überprüfen, ob die Hochschule mit HS-ID übereinstimmt, ob die Projektnamen stimmen und ob es die richitge Anzahl von Token pro Kombi gibt.
[Oho-PB_Tokenverteilung_Gesamt.xlsx](https://github.com/dzhw/zofar/files/3198507/Oho-PB_Tokenverteilung_Gesamt.xlsx)

**Comment by koopmann1896** [comment]
> @koopmann1896 bitte noch mal überprüfen, ob die Hochschule mit HS-ID übereinstimmt, ob die Projektnamen stimmen und ob es die richitge Anzahl von Token pro Kombi gibt.

erledigt, stimmt alles :)

**Comment by dzhwmeisner** [comment]
- [ ] Export
- [ ] Screenshots
- [ ] Archiv

**Comment by andreaschu** [comment]
@koopmann1896 
screenshots including transitions: 
[oho-pb_screenshot.pdf](https://github.com/dzhw/zofar/files/3296980/oho-pb_screenshot.pdf)
[oho-pb_screenshot.zip](https://github.com/dzhw/zofar/files/3296981/oho-pb_screenshot.zip)

**Comment by andreaschu** [comment]
@vdick  please add survey in exporter

**Comment by mattenko** [comment]
Archiving done
