### ISSUE TITLE
SPSS-Output

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#158]
As a SPSS-User I need an output for defining and labeling variables

**Comment by andreaschu** [comment]
Here is an example for a syntax-file for SPSS 
_(data type is SPS that is not supported by GitHub. That's why I added .txt)_
[data-do-spss_example.SPS.txt](https://github.com/dzhw/zofar/files/3186658/data-do-spss_example.SPS.txt)

**Comment by andreaschu** [comment]
- [ ] Please add header with project name, creation date and glossar for missing values (see in example)
- [ ] don't cut the variable names (even if this would be wrong code for SPSS - I'd rather cut it by my own decision)
- [ ] encoding of the .sps-file is wrong when opening with SPSS --> SPSS seem to need ansi-encoding

**Comment by andreaschu** [comment]
- [ ] please add comment within the line  
> cd '../../csv'.

to:
> cd '../../csv'. /*define your data folder.

**Comment by dzhwmeisner** [comment]
done. rolled out in current exporter. testing needed.
