### ISSUE TITLE
Eurostudent-Netherlands

### ISSUE THREAD

**Issue by vdick** [dzhw/zofar#159]
questionnaire for Eurostudent Netherlands.
Field start: **???**
- prize draw?
- two languages (Dutch, English)

**To Do's**
- [x] creating a project 
- [x] programming first draft of questionnaire: [ZOFAR adaption file_2.3 NL v190524.xlsx](https://github.com/dzhw/zofar/files/3290304/ZOFAR.adaption.file_2.3.NL.v190524.xlsx)
- [x] testing and correcting
- [x] going online
- [x] feedback (weekly)
- [x]  screenshots
- [ ]  archiving
- [x]  export of Data

Project created
**Link: https://presentation.dzhw.eu/Eurostudent-Netherlands/**
Token: _tester1-tester100_

Prize Draw:
Link: https://presentation.dzhw.eu/Eurostudent-Netherlands-addon/

**Comment by andreaschu** [comment]
@vdick the links don't work. Please make a (first) build.

**Comment by vdick** [comment]
@andreaschu  please try again

**Comment by andreaschu** [comment]
@jorisc and @Eurostudent-RN
here are some open issues for the questionnaire:
- [ ] question tree is missing -> not programmed jet
- [ ] country list is missing (only in alphabetical order and on english)
- [ ] welcome text for Index-Page is missing
- [ ] translation of the additional texts are missing
- [ ] 04_16 question text only in dutch
- [ ] 05_08: question text only in dutch
- [ ] 05_08: scale lettering wrong for english
- [ ] 07_01: introduction only in dutch
- [ ] still # in: 04_19, 04_27, 06_04, 07_01, 07_02

**Comment by andreaschu** [comment]
[ZOFAR file_2.3 NL v190618.xlsx](https://github.com/dzhw/zofar/files/3305055/ZOFAR.file_2.3.NL.v190618.xlsx)

- we added the question tree and all other information that was missing.
- All green tabs contain info for ZOFAR.
- You can ignore the red tabs. We have no use for them.
- We also changed or adapted the things you already mentioned in your previous mail.
- We got some feedback from Geli on the translations. 
- I added a column (U) in which I registered and commented on all changes since last version.

**Comment by andreaschu** [comment]
@jorisc and @Eurostudent-RN
Do you have a logo you want to use?

**Comment by andreaschu** [comment]
@SilinaKowalewski please add the logo
![Logo_ministerie_OCW svg](https://user-images.githubusercontent.com/30111489/59861506-3de51b80-9381-11e9-8350-ac5cac48a8e1.png)

**Comment by Eurostudent-RN** [comment]
@andreaschu 
Could you provide us with a list of 200.000 tokens / links for the questionnaire?

**Comment by andreaschu** [comment]
@Eurostudent-RN do the tokens have preloads for the HEIs?

**Comment by Eurostudent-RN** [comment]
> 
> 
> @Eurostudent-RN do the tokens have preloads for the HEIs?

No preloads needed

**Comment by dzhwmeisner** [comment]
Tokens generated 
[preloads.csv.txt](https://github.com/dzhw/zofar/files/3321174/preloads.csv.txt)

**Comment by dzhwmeisner** [comment]
questiontree updated

**Comment by Eurostudent-RN** [comment]
> 
> 
> Tokens generated
> [preloads.csv.txt](https://github.com/dzhw/zofar/files/3321174/preloads.csv.txt)

Thanx! What does the column 'panel' mean in the token list. By the way... list contained 15.000 double tokens / urls. We deleted the double tokens.

**Comment by Eurostudent-RN** [comment]
> 
> 
> questiontree updated

Is it already ready for testing? Cannot see it in test version

**Comment by andreaschu** [comment]
> Is it already ready for testing? Cannot see it in test version
The question tree is updated now.

**Comment by andreaschu** [comment]
> Thanx! What does the column 'panel' mean in the token list. By the way... list contained 15.000 double tokens / urls. We deleted the double tokens.

You can ignore this, because you don't have any Prize Draw.
We double checked the token. There are only doubled cases if you ignore Capitalization. Please ensure that there cannot be any mixed up while sending the invitations. We can do the token again, if you wish, with only lower or only upper cases. The token should then be longer.

**Comment by andreaschu** [comment]
@Eurostudent-RN we need a (or two) data protection file. There is still the Lux version linked.

**Comment by Eurostudent-RN** [comment]
> re are only doubled cases if you ignore Capitalization. Please ensure that there cannot be any mixed up while sending the invitations. We can do the token again, if you wish, with only lower or only upper cases. The token should then be longe

aplogies, already mentioned ;-) Thanx

**Comment by Eurostudent-RN** [comment]
> 
> 
> @Eurostudent-RN we need a (or two) data protection file. There is still the Lux version linked.

Data protection file was send to Daniel, but no reply yet. Attached the files we send.. 
[Privacy statement.pdf](https://github.com/dzhw/zofar/files/3324823/Privacy.statement.pdf)
.

**Comment by Eurostudent-RN** [comment]
Page | Old question/answer option/tekst | New question/ answer   option/tekst | Remark
-- | -- | -- | --
Index | Please find here some more information on the survey and data   protection | In Dutch: "Hier vindt u wat   meer informatie over de enquête en gegevensbescherming" | Please translate this sentence in Dutch
exit.html | Text: "Je kunt deze pagina nu sluiten of ga terug en   wijzig je antwoord." | "Je kunt deze pagina nu   sluiten. Indien je het verkeerde antwoord hebt gegeven ga dan terug en wijzig   je antwoord." |  
almost   all pages | meer' | verder' | Translation button -> next   = verder
P01_01 | Second answer option: "Ja, maar alleen slechts tijdelijk   voor één of twee semesters (bijvoorbeeld vanuit Erasmus+)" | Ja, maar alleen tijdelijk voor   één of twee semesters (bijvoorbeeld vanuit Erasmus+) | Please remove 'slechts',
P01_02 | Text: "Afstandsonderwijs betreft onderwijs waarvij geen   face-to-face interactie met de docent plaatsvindt. ." | Text: Afstandsonderwijs betreft   onderwijs waarbij geen face-to-face interactie met de docent   plaatsvindt. | waarvij=waarbij
p01_03 |   |   | In case of a missing answer, the following warning is shown:   ???p01_03.b.sw.t_0???
p01_04 | Text: Naam van de hoger onderwijs instelling: | Text: Naam van de hogeronderwijsinstelling: | Please make one word of hogeronderwijsinstelling
p01_04 |   |   | After this question, an error is shown in the screen. See   below
p01_05 | 'Anders nl.' | 'Anders, nl.' plus   Possibility to enter an open answer | Please change the order of   categories; Anders nl. (other) has to be last. Could you create an open field   for this "other"?
p01_05 |   |   | No answer categories are shown. See below.
from p01_06 to p01_07 |   |   | Long loading time :-(
p01_07 |   |   | If p01_05 = "anders nl. " this question should only   be an open question: "Aan welke opleiding studeer je?" English:   What study programme are you enrolled in?". Question on "did not   find your study programme can be dropped
P02_04 | Hoe lang na het verlaten van de middelbare school, ben je voor   het eerst begonnen aan een opleiding in het hoger onderwijs?' | Wanneer ben je na de middelbareschool voor het eerst begonnen   aan een opleiding in het hoger onderwijs? | Please change this sentence
p02_04 | ... bent toegelaten op het Hoger onderwijs | ... bent toegelaten op het hoger onderwijs | hoger onderwijs' in the question is written without capital   letter and in the introduction with capital letter.
p02_05 | Wanneer ben je voor het eerst begonnen in het hoger onderwijs? | Wanneer ben je voor het eerst begonnen in het hoger onderwijs | voor het eerst' should be underlined
p02_07 | ???p02_07.b.mc.q_0???     ???p02_07.b.mc.ins_0??? | Is er in uw eerdere toelating   tot het hoger onderwijs expliciet rekening gehouden met eerdere werkervaring   in Nederland?     Meerdere antwoorden mogelijk | Please change
p02_07 |   |   | The question and answercategories are not shown correctly. See   attached.
p03_01 | Ervaar jij binnen in huidige opleiding | Ervaar jij binnen je huidige opleiding | in' should be 'je'
p03_02 |   |   | After this question, an error is shown in the screen.
p03_04b   & p03_05 & p03_06 & p03_07 & p03_09 & p04_07 & p04_13   & p04_14 |   | Missing answer warning is missing
p04_11 | add: 'meerdere antwoorden zijn mogelijk' / more answers are   possible |   |  
p04_03 | Reistijd naar de [universiteit/hogeschool] | Reistijd naar de hogernderwijsinstelling |  
p04_04 | Wat is tijdens het huidg semester | Wat is tijdens het huidig semester | huidg' should be 'huidig
p04_16 | 'Ja, lening via DUO (incl. collegegeldkrediet)' | 'Lening via DUO (incl. collegegeldkrediet) | Please remove 'Ja,'
p04_16a | Komt jouw totale maandelijkse inkomen ongeveer overeen met het   volgende bedrag? Als dit bedrag niet juist is, ga dan terug naar de vorige   pagina en pas je antwoorden aan.Totale maandbedrag 2.0 Euro per maand | Komt jouw totale maandelijkse   inkomen ongeveer overeen met het volgende bedrag? Als dit bedrag niet juist   is, ga dan terug naar de vorige pagina en pas je antwoorden aan.          Totale maandbedrag 2.0 euro per maand | Totale maandbedrag … euro per maand'. -> on a new line.
p04_17 | 'LET OP! Dit bedrag is exclusief collegegeld.' | LET OP! Dit bedrag is exclusief   de uitgave aan collegegeld.' | 'Please add 'de uitgave aan'
p04_18 | Helemaal niet gerelateerd | Helemaal niet | The answer categorie on the left should be 'Helemaal niet'
p04_19 |   |   | The question is missing
p04_20 | 'Heb je sinds je in Nederland bent begonnen met studeren stage   gelopen (tenminste een week, vrijwillig of verplicht)? | ''Heb je sinds je in Nederland bent begonnen met studeren,   stage gelopen (tenminste een week, vrijwillig of verplicht)? | please add a comma
p05_03 | 'Nederland' |   | You can also indicate the   'Netherlands' as an option if you have been abroad, this should not be   possible
p05_08 |   |   | Question is missing
p06_04 & p06_05 |   |   | Moeder/verzorger' en 'Vader/verzorger' are missing
p06_10a | al al zou je persoonlijk liever een andere term gebruiken. | al zou je persoonlijk liever een andere term gebruiken. | al al' is double.
p07_01 |   |   | The introduction to the question is missing (De volgende   vragen gaan over jouw familieachtergrond. De vragen gaan over je vader(s),   moeder(s) of andere personen die je hebben opgevoed.)

![afbeelding](https://user-images.githubusercontent.com/48948929/60114110-6a2edc80-9773-11e9-9f9c-40183170adce.png)

**Comment by Eurostudent-RN** [comment]
**Prize draw**
We do want a prize draw. For the last pages this mean you need some additional information: 
Intro page has to be adjusted: 
English: 
<Welcome to the Eurostudent Survey!
To help us get a full picture of the student experience, this survey asks a series of questions on topics that are currently important in higher education, such as accommodation, travel, finance, workload and study patterns.  

It takes about 15-20 minutes to complete (depending on your circumstances).  Please note that some questions are important for analysis and others are optional. Upon completion you will find that you can enter the prize draw for the Lenovo laptops and Bol.com vouchers.> Followed by the informed consent.

In Dutch:
Welkom bij deze Eurostudent vragenlijst!
Om een goed beeld te krijgen van jouw ervaringen als student , vragen we in deze enquête een reeks vragen over onderwerpen die momenteel belangrijk zijn in het hoger onderwijs, zoals huisvesting, studeren in het buitenland, inkomsten en uitgaven, werkdruk en de toegankelijkheid van het onderwijs. Na het invullen van de vragenlijst kun je aangeven of je kans wil maken op de Lenovo laptops en Bol.com bonnen.>

**Comment by Eurostudent-RN** [comment]
**Prize draw II**
English: 
If you wish to enter into the prize draw, please click “start here”. You will be redirected to a seperate questionnaire.

index:
If you wish to enter into the prize draw, please enter your name and email address below. 
label:
1.	name,
2.	email address

Your name and e-mail address will be stored and processed in a separate file. It is therefore not possible to combine your personal data with the answers you provided in the survey. This information is only used for the prize draw. Your personal details will be destroyed afterwards.
end.

end:
Thank you for your entry, we’ll be in touch in August should you be a winner.
Please contact us at info@researchned.nl if you have any questions or otherwise.

Dutch:
Als je kans wil maken op één van de prijzen klik dan op "start". Je wordt dan doorgeleid naar een aparte vragenlijst.

Index: 
Als je mee wil doen aan de prijstrekking, vul dan hieronder je naam en e-mailadres in. 

label:
1. naam,
2. e-mailadres

Jouw naam en e-mailadres worden in een apart bestand opgeslagen en verwerkt. Het is daarom niet mogelijk om je persoonlijke gegevens te combineren met de door jouw gegeven antwoorden in de enquête. Deze gegevens worden alleen gebruikt voor het verloten van de prijzen. Daarna worden deze gegevens vernietigd. 
end.

Bedankt voor je deelname! Mocht je iets gewonnen hebben, dan nemen we in augustus contact met je op. Mocht je nog vragen of opmerkingen hebben, stuur dan een email naar info@researchned.nl.

**Comment by SilinaKowalewski** [comment]
Changes made: 

- [x] Index
- [x] exit.html
- [x] P01_01
- [x] P01_02
- [x] p01_03
- [x] p01_04 (translation changed)
- [x] P02_04
- [x] p02_04
- [x] p02_05
- [x] p02_07
- [x] p02_07
- [x] p03_01
- [x] p04_11
- [x] p04_03
- [x] p04_04
- [x] p04_16
- [x] p04_16a
- [ ] p04_17
- [x] p04_18
- [x] p04_20
- [x] p05_03
- [x] p06_10a

**Comment by SilinaKowalewski** [comment]
p01_04: Please more detailed. We can't recreate the error. 
p01_05: Please more detailed. We see some categories.
p03_02: Please more detailed. We can't recreate the error. 
p04_19: Please more detailed. We see all texts.
p05_08: Please more detailed. We see all texts.
p06_04 & p06_05: Please more detailed. We see all texts.
p07_01: Please more detailed. We see all texts.

**Comment by SilinaKowalewski** [comment]
- [x] p01_05: adjusted - please check
- [x] p01_07: adjusted - please check

**Comment by SilinaKowalewski** [comment]
- [x] 4_17a 
- [x] 4_16
- [x] 2_1 
- [x] p02_07
- [ ] Could it be that the Zeichensatz is not correctly set?  - **Yes, there seems to be a problem with the delivered questiontree in excel. We will fix that tomorrow**

**Comment by Eurostudent-RN** [comment]
| old | new | remark
-- | -- | -- | --
index | Om een goed beeld te krijgen van jouw ervaringen als student , vragen we   in deze enquête een reeks vragen over onderwerpen die momenteel belangrijk   zijn in het hoger onderwijs, zoals huisvesting, studeren in het buitenland,   inkomsten en uitgaven, werkdruk en de toegankelijkheid van het onderwijs. Na   het invullen van de vragenlijst kun je aangeven of je kans wil maken op de   Lenovo laptops en Bol.com bonnen. | Om een goed beeld te krijgen van   jouw ervaringen als student, stellen we in deze enquête een reeks vragen over   onderwerpen die momenteel belangrijk zijn in het hoger onderwijs, zoals   huisvesting, studeren in het buitenland, inkomsten en uitgaven, werkdruk en   de toegankelijkheid van het onderwijs. Na het invullen van de vragenlijst kun   je aangeven of je kans wil maken op de Lenovo laptops en Bol.com bonnen.
exit | Jij valt helaas niet onder de doelgroep van dit onderzoek. | Jij behoort helaas niet tot de   doelgroep van dit onderzoek.
p01_05 &   p01_07 |   | if p01_05 = other or if question tree leads to "open question"   p01_07 should be an open question with the folowing question text: "Wat   is de naam van je huidige opleiding?" -> "What study programme   are you currently enroled in?"
p01_06 | next button | Is it possible to (just on this page) adjust the "next" button   into "Next… might need some loading time" -> Dutch:   "Volgende… kan eventjes duren…"
p01_07 | Would you be so kind to select yourstudy programm? | Would you be so kind to select your study programme? | add a space and an e
P01_08 |   |   | did not get this question? Wrong filtering?
p01_09 |   |   | did not get this question? Wrong filtering?
p02_01 | quaalifications | qualifications
p02_04 | middelbareschool | middelbare school
p04_03 | hogernderwijsinstelling | hogeronderwijsinstelling

**Comment by SilinaKowalewski** [comment]
- [ ] index
- [ ] exit

- [ ] p01_05 & p01_07

- [ ] p01_06 - Unfortunately this is not possible.
- [ ] p01_07
- [ ] P01_08
- [ ] p01_09
- [ ] p02_01 
- [ ] p02_04 
- [ ] p04_03

**Comment by Eurostudent-RN** [comment]
p01_06 - Unfortunately this is not possible. -> could you create a post question text: 

"Let op! het laden van de volgende pagina kan even duren..."
"Be aware! The loading of the next page can take a while"

**Comment by Eurostudent-RN** [comment]
Page | Old | New | Remark
-- | -- | -- | --
Index | [dowload het document   hier] |   | please remove   text
p02_04 | Wanneer ben je na de   middelbare school voor het eerst begonnen aan een opleiding in het hoger   onderwijs? | Hoe lang na het   verlaten van de middelbare school, ben je voor het eerst begonnen aan een   opleiding in het hoger onderwijs? | Please change   text
p03_02 /   p03_05 / p03_06 / p03_07 / p03_09 / p04_03 / p04_07 / p06_05 / p06_10 /   p06_12 / p07_01 |   |   | Please insert soft   warnings for these questions!
p04_08 &   p04_08 |   |   | Could you please give   the second question a separate page?
p04_11 | Transfers in kind   could be one or more of the following: free accommodation, food, clothes,   phone, car use, or similar goods provided. " | Geld (cash of op de   bank) is elk bedrag dat gebruikt wordt om van te leven of te studeren; Giften   in natura zijn producten die direct aan jou gegeven worden (bijvoorbeeld   onderdak, eten, kleren, telefoon, het gebruik van een auto). Rekeningen   worden voor jou betaald (bijvoorbeeld huur, gas/water/licht, collegegeld,   telefoonrekening) | Please change text
p04_11 | Geef aub aan wat van   toepassing is. Multiple answers possible. Meerdere antwoorden zijn mogelijk. | Geef aub aan wat van   toepassing is.  Meerdere antwoorden   zijn mogelijk. | Please change   text
p04_16 |   |   | Could you please   create some space between pre question text and question text
p04_17 | Als je hebt   aangegeven dat anderen geregeld rekeningen voor jou betalen en/of dat je   geregeld giften in natura ontvangt, vul dan het geschatte bedrag (van de   betaalde rekeningen en giften) in in de tweede kolom. | Als je hebt   aangegeven dat anderen geregeld rekeningen voor jou betalen en/of dat je   geregeld giften in natura ontvangt, vul dan het geschatte bedrag (van de   betaalde rekeningen en giften) in. | Please replace tekst;   it was referring to columns.
p04_17 | Please enter the   approx. amount (i.e. sum of bills and transfers in kind) in the second   column. | Please enter the   approx. amount (i.e. sum of bills and transfers in kind). | Please replace tekst;   it was referring to columns.
p05_07a | Anders nl… | Anders | Please change
p05_07b | Geef alle bronnen aan   die je hebt gebruikt. | Wat was de   belangrijkste financieringsbron? | Please change   text
p05_07b | Anders nl… | Anders | Please change
p06_13 | Als je denkt aan de   beperkingen die je ervaart bij het studeren als gevolg van je beperking… hoe   zou je dan de publieke- en instellingsondersteuning die je hiervoor krijgt   beoordelen? | Als je denkt aan de   belemmeringen die je ervaart bij het studeren als gevolg van je beperking…   hoe zou je dan de publieke- en instellingsondersteuning die je hiervoor   krijgt beoordelen? | Please change   text

**Comment by Eurostudent-RN** [comment]
Two more things:
1. In question p06_06 we forgot to add english as native language (Brexit??)-> could you please add one category -> in Dutch: Engels; in English: English. 
2. Could you make V6_1month & V6_1year mandatory?

**Comment by Eurostudent-RN** [comment]
As for the prize draw. I want to sugest an alternative text for the end page -> 

English:
If you wish to enter into the prize draw or if you want to participate more often in research concerning your studies, please click “start here”. You will be redirected to a seperate questionnaire.

Dutch:
Als je kans wil maken op één van de prijzen of als je vaker deel wil nemen aan dit soort onderzoeken, klik dan op "start". Je wordt dan doorgeleid naar een aparte vragenlijst.

For the prize draw itself it would be great if you could programme one tick box on the index page: 

Yes, I want to participate more often in research concerning my studies. You may use my email address to contact me. 

in Dutch:
Ja, ik wil vaker deelnemen aan onderzoek over die mijn studie in het Hoger onderwijs aangaan. Jullie mogen mijn email adres gebruiken om contact met mij te nemen.


Three more things: 
1. could you please check the allignment on this page?
2. enqu’te in dutch should be enquête
3. Could you make a change in the text: 

  | old | new
-- | -- | --
english | It is therefore not possible to combine your personal data   with the answers you provided in the survey. This information is only used   for the prize draw. Your personal details will be destroyed afterwards. | It is therefore not possible to combine your personal data   with the answers you provided in the survey. If you did not indicate that you want to participate more often in similar   research you email address will only be used for the prize draw and will be   destroyed afterwards. If you do want to participate more often, we will take   good care of your personal information and will only use it for inviting you   for future research.
dutch | Het is daarom niet mogelijk om je persoonlijke gegevens te combineren met   de door jouw gegeven antwoorden in de enqu’te. Deze gegevens worden alleen   gebruikt voor het verloten van de prijzen. Daarna worden deze gegevens   vernietigd. | Het is daarom niet mogelijk om je persoonlijke gegevens te combineren met   de door jouw gegeven antwoorden in de enquête. Als je hebt niet hebt   aangegeven vaker benaderd te willen worden voor sortgelijk onderzoek dan   worden je adresgegevens alleen gebruikt voor het verloten van de prijzen.   Daarna worden ze vernietigd. Als je wel vaker aan onderzoek deel wil nemen,   zullen we zorgvuldig met je email adres omgaan en alleen gebruiken om je voor   toekomstig onderzoek uit te nodigen.

**Comment by Eurostudent-RN** [comment]
@vdick @andreaschu @dzhwmeisner @SilinaKowalewski -> terribly sorry!! 
During testing I encountered a problem withthe question tree. I was missing some bachelor programms. Attached an updated version of the question tree... I used the same lay out as the old one, only added some programmes. I hope this does not cause too much trouble.

Have a nice (sunny) weekend!
Bas
[Question tree NL v2.xlsx](https://github.com/dzhw/zofar/files/3340041/Question.tree.NL.v2.xlsx)

**Comment by Eurostudent-RN** [comment]
p04_19 old: "Ja, iemand anders (ouders, familie, partner enz.) zouden dit direct voor mij kunnen betalen." 
new: "Ja, iemand anders (ouders, familie, partner enz.) zou dit direct voor mij kunnen betalen."

**Comment by Eurostudent-RN** [comment]
Test results from Geli: 

- Filter for 1_8 still does not work (I get the question if I say that I have a BA, and I don’t get it when I indicate a MA), testing is quite frustrating because it takes soooooo long for 1_7 to load … Now I managed to get no dropdown for MA at ERASMUS Rotterdam university… 
- Filtering from 2_09 to 2_10 could be improved – if I don’t answer 2_09 I still get 2_10. 
- Please make 4_05 mandatory (soft warning) 
- P05_07a & P05_07b ->please change "anders nl..." into "anders"
-Filtering from 6_12b to 6_13 the scale was turned but not the filter; filtering should be: Go To p07_01 if (v6_12_2==1)

**Comment by SilinaKowalewski** [comment]
- [ ] Missing Dutch translation for: 
Please notice that it is not possible to participate in the survey without consent to the 						privacy police statement.

**Comment by andreaschu** [comment]
> p03_02 /   p03_05 / p03_06 / p03_07 / p03_09 / p04_03 / p04_07 / p06_05 / p06_10 /   p06_12 / p07_01 |     | Please insert soft   warnings for these questions!
> -- | --  | --

There are softforces for **p03_02, p03_05, p03_06, p03_07, p03_09, p04_03, p04_07, p06_05 and p06_12** . 
The soft forces for single choice answer grids should only be visible if the respondents enter the questionnaire via mobile device (screen width less than 768) and up to the second item there is no answer. The idea is that there should be a reminder for the case that the respondents didn't understood the functioning of the socalled 'carousel'. You can assume that the respondent understood this feature when they activated it, at least once. They still may don't want to answer everything.
That is the way it is programmed for Ireland and Malta. If this should be different, then you have to say us how.

On page **p06_10** was once a hard force. We decided to put it away because it would be too hard to force a health question. Now it is a soft force, but please think about it again.
On page **p07_01** there never was any force because in contrast to the other pages with answer grids, this doesn't split for small screens. So the idea of the force for the grid questions wouldn't make any sense. 

@Eurostudent-RN please give us a feedback what kind of force should be on pages p06_10 and p07_01.

**Comment by andreaschu** [comment]
> In question p06_06 we forgot to add english as native language (Brexit??)-> could you please add one category -> in Dutch: Engels; in English: English.

@Eurostudent-RN and @jorisc on which position should 'English' be?

**Comment by andreaschu** [comment]
Hey @Eurostudent-RN and @jorisc, 
the testlink is updated with the last changes except the question tree, the translation on new forces, the language thing and the filter for p02_10 is not updated yet. Please give us a feedback for the questions.

**Comment by Eurostudent-RN** [comment]
> 
> 
>     * [ ]  Missing Dutch translation for:
>       Please notice that it is not possible to participate in the survey without consent to the 						privacy police statement.

De vragenlijst mag alleen worden afgenomen als de privacyverklaring akkoord is bevonden. Het is dus niet mogelijk om deel te nemen aan de enquête zonder jouw toestemming op de privacyverklaring.

**Comment by Eurostudent-RN** [comment]
> e decided to put it away because it would be too hard to force a health question. Now it is a soft force, but please think about it again.

Carousel items... In contrast to the Irish & Maltese versions we want a soft warning with at every "carousel question".  If they do not want to answer they can click "yes, continue anyway). We have to compare some of these items between the EUROSTUDENT & our studentmonitor. In Studentmonitor students also get a soft reminder. 
As for p6_10 & p07_01 appologies... you are right! no messages

**Comment by Eurostudent-RN** [comment]
> 
> 
> > In question p06_06 we forgot to add english as native language (Brexit??)-> could you please add one category -> in Dutch: Engels; in English: English.
> 
> @Eurostudent-RN and @jorisc on which position should 'English' be?

In between German and other

**Comment by andreaschu** [comment]
last issue/changes done and updated
- [x] question tree updated
- [x] visible condition of question textat page  
- [x] p06_06: add english as native language
- [x] Filtering from 2_09 to 2_10 'improved'
- [x] visible condition of question texts corrected
- [ ] softforces for p03_02, p03_05, p03_06, p03_07, p03_09, p04_03, p04_07, p06_05 and p06_12

**Comment by Eurostudent-RN** [comment]
* [ ] in prize draw in Dutch -> ???index.b.mc.rd.ao1.label??? should be Ja, ik wil vaker deelnemen aan onderzoek over die mijn studie in het Hoger onderwijs aangaan. Jullie mogen mijn email adres gebruiken om contact met mij op te nemen.

**Comment by Eurostudent-RN** [comment]
* [ ] softforce for p03_03

**Comment by andreaschu** [comment]
@Eurostudent-RN here is the link to the preliminary data: https://myshare.his.de/s/wuPkibbRf9XKBtj

**Comment by dzhwmeisner** [comment]
Screenshot generated. http://vmdevwiki.dzhw.local/public/eurostudentnetherlands/Eurostudent-Netherlands_screenshots.zip

**Comment by andreaschu** [comment]
@mattenko, project can be archived
