### ISSUE TITLE
Template 

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#16]
To Do:

- [x]  Test Infrastructure
- [ ]  Formulate Test Cases
- [x]  Write Unit Tests

Used Time: 1

**Comment by kastirke** [comment]
Please use minimal branding (logos only at the index page, minimize font size of "Deutsches Zentrum für...") for mobile devices if possible. Otherwise use minimal branding for all devices.

**Comment by kastirke** [comment]
using iPhone SE, iOS 10.3.3, Safari

Try to reduce inoperable space where possible. 
![img_3947](https://user-images.githubusercontent.com/30147532/28662369-3a1b9054-72ba-11e7-8071-f82ff11a1e78.PNG)

**Comment by dzhwmeisner** [comment]
all logos only on index. DZHW -Logo always. Device independent

**Comment by dzhwmeisner** [comment]
space reduction not possible in this moment

**Comment by kastirke** [comment]
Lieber Christian,

vielen Dank!!! Ich schaue mir das am Mittwoch an.
(Und jetzt gucken wir mal, ob ich dir hierüber überhaupt antworten kann.)

LG Nadin

Von: dzhwmeisner [mailto:notifications@github.com]
Gesendet: Freitag, 28. Juli 2017 17:15
An: dzhw/zofar
Cc: Kastirke, Dr. Nadin; Assign
Betreff: Re: [dzhw/zofar] Template (#16)


space reduction not possible in this moment

**Comment by kastirke** [comment]
👍 
checked "all logos only on index. DZHW -Logo always. Device independent"
accepted "space reduction not possible in this moment"
