### ISSUE TITLE
zofar-showroom should be online

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#165]
the link to the zofar showroom (http://vmtest.dzhw.local:8080/showroom/) doesn't work anymore

**Comment by vdick** [comment]
@andreaschu 
showroom is online
http://vmtest.dzhw.local:8080/showroom-0.0.1-SNAPSHOT/

**Comment by andreaschu** [comment]
@vdick is it possible to use the old link?

**Comment by vdick** [comment]
@andreaschu ready, please test again

**Comment by andreaschu** [comment]
@vdick coolio! Thanks.
