### ISSUE TITLE
carousel: remove shadows of item in mobile view

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#166]
Shall we remove the shadow of every second item of a item grid in mobile view?

![grafik](https://user-images.githubusercontent.com/30111489/59104835-dd8ebc80-8932-11e9-8126-2a465ebdd2f6.png)
linked to: #35

**Comment by kastirke** [comment]
I would be in favor of removing the shading, so that the respondents directly realize that only the item text changes (not the answer options).
