### ISSUE TITLE
carousel: rearrange the item counter 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#167]
(#35) shall we rearrange the item counter to the button of an item?

![grafik](https://user-images.githubusercontent.com/30111489/59105989-89390c00-8935-11e9-8e04-1bf9641ca44a.png)

**Comment by kastirke** [comment]
I prefer a position below the items. If they also serve navigation, it would be more intuitive. In addition, I can remember space problems with double matrices if the counter is placed between item and answer options (labels of scale end points overlayed the counter).

**Comment by andreaschu** [comment]
As there are sometimes a lot of items it is not useful to put the counter to the botton. So this will be closed.
