### ISSUE TITLE
Update Archetype

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#176]
need to update

- [x] POM (Dependencies, Plugins)
- [x] Postgres 
- [x] CSS
- [x] Javascript
- [x] Logos (#127)
- [x] resized Logout-Button-Image

**Comment by vdick** [comment]
@dzhwmeisner please test it once

**Comment by dzhwmeisner** [comment]
Preloaded tokens added

**Comment by dzhwmeisner** [comment]
looks good
