### ISSUE TITLE
SingleChoice Question

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#18]
horizontal / vertical

To Do:

- [x] Test Infrastructure
- [x] Formulate Test Cases
- [x]  Write Unit Tests

Used Time : 8

**Comment by kastirke** [comment]
Test Nadin

**Comment by kastirke** [comment]
Radiobuttons are not centered on the background line. They are a little below.

![grafik](https://user-images.githubusercontent.com/30147532/28656073-15507efc-72a0-11e7-9716-2df4c738fc05.png)

**Comment by kastirke** [comment]
When I slide along the window, the scale width increases and a scrollbar appears.
![unbenannt](https://user-images.githubusercontent.com/30147532/28656311-879b911c-72a1-11e7-9e09-8cc44d064c44.PNG)
![unbenannt](https://user-images.githubusercontent.com/30147532/28656332-ae64a536-72a1-11e7-93ba-f4c88ab2ae93.PNG)

**Comment by kastirke** [comment]
Gray connection line to the non-substantial answers (do not know etc.) has to 
![unbenannt](https://user-images.githubusercontent.com/30147532/28656441-4b330fec-72a2-11e7-8bc0-7bde962d6185.PNG)
disappear.

**Comment by kastirke** [comment]
We should avoid (or reduce) horizontal scrolling where possible.

**Comment by dzhwmeisner** [comment]
Gray connection disappeared

**Comment by FineCordua** [comment]
![fc_chrome_nomus10_singlechoicehorizontal](https://user-images.githubusercontent.com/27995239/29962277-f599a9d8-8f02-11e7-8eca-8600405b309a.png)

- Same problem as mentioned above: display is too short for the answerbuttons which leads to a scrollingoption

**Comment by Miktarbad** [comment]
done.

**Comment by kastirke** [comment]
Mac, OS X 10.9.5, Safari

Answer options shifted to the right.

![mac_1](https://user-images.githubusercontent.com/30147532/31879442-ba1f4346-b7dd-11e7-938f-2a552514c6ec.png)

**Comment by dzhwmeisner** [comment]
Cannot fix Safari Bugs up to now. Only Version 5 of Safari available for Linux

**Comment by kastirke** [comment]
👎 This needs discussion (@andreaschu, @Miktarbad)

**Comment by kastirke** [comment]
Please remove connecting line within vertical SingleChoice Question.

![grafik](https://user-images.githubusercontent.com/30147532/55384554-4caef580-552b-11e9-8116-546066d91493.png)
