### ISSUE TITLE
Abs 2009-3, 3. Teilbefragung

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#180]
To Do's:
- [x]     creating a project
- [x]     programming first draft of questionnaire
- [x]     testing and correcting
- [x]     going online
- [x]     feedback
- [x]     reminder(s)
- [x]     Screenshots
- [x]     Archiving
- [x]     Export of Data

**Comment by andreaschu** [comment]
@dzhwmeisner please create a screenshot (including transition)

**Comment by andreaschu** [comment]
@vdick and @dzhwmeisner survey can go offline

**Comment by vdick** [comment]
@andreaschu  and @dzhwmeisner  survey is offline

**Comment by vdick** [comment]
[absolventen20093m3-addon_screenshots.zip](https://github.com/dzhw/zofar/files/3358656/absolventen20093m3-addon_screenshots.zip)
[absolventen20093m3_screenshots.zip](https://github.com/dzhw/zofar/files/3358657/absolventen20093m3_screenshots.zip)

**Comment by andreaschu** [comment]
@mattenko the survey can be archived

**Comment by andreaschu** [comment]
@mattenko: the project can be archived
