### ISSUE TITLE
SLC: Screenshot

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#181]
- [x] @vdick please clear database while keeping preloads
- [x] screenshots of calendar pages (upright as well as landscape view)
- [x] screenshots of modul starting pages (@jocarstensen can you identify the page-numbers) for different devices (@jocarstensen list the devices)

**Comment by andreaschu** [comment]
[slc_testtoken.xlsx](https://github.com/dzhw/zofar/files/3376842/slc_testtoken.xlsx)
[slc_testtoken.csv.txt](https://github.com/dzhw/zofar/files/3376847/slc_testtoken.csv.txt)

**Comment by jocarstensen** [comment]
>     * [ ]  screenshots of modul starting pages (@jocarstensen can you identify the page-numbers) for different devices (@jocarstensen list the devices)

Page numbers:
- em0001 + emaa01
- jaa01
- u0001 + uaa01
- o0001 + oaa01 + oba01 + oca01 + oda01 + oea01
- sc0001 + scaa02
- v0001 + vaa01
- i0001 + iaa01
- st0001 + staa01

Devices:
- Desktop + Mobile (exact model does not matter, standard iphone size would be ok)

 
>     * [ ]  screenshots of calendar pages (upright as well as landscape view)
> 
Could you try and make shure that the screenshots are taken in a configuration where the names of the months align correctly?

**Comment by dzhwmeisner** [comment]
Screenshots generated
http://vmdevwiki.dzhw.local/public/bildungsverlauf/bildungsverlauf_screenshots.zip

**Comment by jocarstensen** [comment]
[x]  @vdick please clear database while keeping preloads
[x] screenshots of calendar pages (upright as well as landscape view)
[x] screenshots of modul starting pages (@jocarstensen can you identify the page-numbers) for different devices (@jocarstensen list the devices)
