### ISSUE TITLE
ESVII-Turkey: creating a project

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#182]
make a duplicate of eurostudent netherlands

**Comment by vdick** [comment]
Projects created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Eurostudent-Turkey
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Eurostudent-Turkey-addon
Testserver (after first build):
http://vmtest.dzhw.local:8080/Eurostudent-Turkey
http://vmtest.dzhw.local:8080/Eurostudent-Turkey-addon
Presentation-Server (after first build):
http://presentation.dzhw.eu/Eurostudent-Turkey
http://presentation.dzhw.eu/Eurostudent-Turkey-addon
