### ISSUE TITLE
SingleChoice Question Matrix

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#19]
To Do:

- [x]  Test Infrastructure
- [x]  Formulate Test Cases
- [x]  Write Unit Tests

Sprint 3: et used 12

**Comment by andreaschu** [comment]
- item texts disappear when reducing screen size (firefox)
- labels disappear and appear again depending on screen size (firefox)
![firefox_page4_scmatrix_big](https://user-images.githubusercontent.com/30111489/28625830-a8df3e20-721d-11e7-8a15-ceadfcbcc2f6.PNG)
![firefox_page4_scmatrix_small](https://user-images.githubusercontent.com/30111489/28625832-aaef8436-721d-11e7-9625-39b0243b890a.PNG)
![firefox_page4_scmatrix_supersmall](https://user-images.githubusercontent.com/30111489/28625837-ac5edef2-721d-11e7-821d-726ca1fefb76.PNG)

**Comment by kastirke** [comment]
Please put the scale label over the hover selector.

![unbenannt](https://user-images.githubusercontent.com/30147532/28656767-0e68fdb8-72a4-11e7-8669-a001d4c4b7ee.PNG)

**Comment by kastirke** [comment]
using iPhone SE, iOS 10.3.3, Safari

Item labels are missing and two (inoperable?) bars are displayed.

![img_3956](https://user-images.githubusercontent.com/30147532/28663755-8705fbf8-72be-11e7-9031-cc013ab26c79.PNG)

**Comment by dzhwmeisner** [comment]
- Carousel function fixed.
- Responsive Matrix with Units in work

**Comment by DusdalA** [comment]
Labels are missing and the underlying grey line is a tad too long.

![sc matrix](https://user-images.githubusercontent.com/28007144/28922176-58985b58-7859-11e7-8a76-e657de0721c5.png)

**Comment by Miktarbad** [comment]
![screenshot_20170809-125353](https://user-images.githubusercontent.com/29864065/29118504-8155e9cc-7d02-11e7-997c-85b677b8e699.png)

Concerning page 4 - Mobile Device - Android 7.0 // Galaxy S7 - 5,1" // Chrome Mobile

- Top Unit without content
- Unitless Item missing

**Comment by FineCordua** [comment]
Comment

**Comment by FineCordua** [comment]
Comment

**Comment by FineCordua** [comment]
123

**Comment by FineCordua** [comment]
![fc_chrome_nomus10_singlechoicemitunits2](https://user-images.githubusercontent.com/27995239/29962092-201bb97c-8f02-11e7-8450-664b1c21f6a1.png)

- Titles missing when changing to horizontal screen

- Top unit without content

**Comment by dzhwmeisner** [comment]
ready for testing

**Comment by Miktarbad** [comment]
![matrix_loading](https://user-images.githubusercontent.com/29864065/31655620-bbe8d5b0-b329-11e7-9cc0-1cdf5c7e8c97.gif)

Strange behaviour while loading page.
#35 #21 #25

**Comment by kastirke** [comment]
👍 
checked "Please put the scale label above the hover selector."
checked "Item labels are missing and two (inoperable?) bars are displayed."

**Comment by andreaschu** [comment]
checked "Please put the scale label above the hover selector." 👍
checked "Item labels are missing and two (inoperable?) bars are displayed." 👍
checked "Strange behaviour while loading page." 👍

**Comment by kastirke** [comment]
Mac, OS X 10,9.5, Safari

Item is partially hidden by attached open.


![mac_3](https://user-images.githubusercontent.com/30147532/31879979-6a10c5bc-b7df-11e7-9757-6bda3e1d4ddd.png)

**Comment by dzhwmeisner** [comment]
Cannot fix Safari Bugs up to now. Only Version 5 of Safari available for Linux

**Comment by kastirke** [comment]
👎 This needs discussion (@andreaschu, @Miktarbad)

**Comment by dzhwmeisner** [comment]
[Labels are missing and the underlying grey line is a tad too long.] not reproducible. please check again.

**Comment by dzhwmeisner** [comment]
[A] 'strange behavior while loading page II'. No solution available, because real length of grey bar cannot be calculated before page is complete loaded.

**Comment by dzhwmeisner** [comment]
[A] recalculation of pipe now triggered when element completely loaded instead of whole document. Need for testing.

**Comment by andreaschu** [comment]
[A] 'strange behavior while loading page II': 
now length of grey bar as well as size whole of template (Textsize, Buttons …) change after loading page.
(I try to make a video)

**Comment by Miktarbad** [comment]
[ A ] 'strange behavior while loading page II': 
will be a seperate issue.

no further bugs - everything else fixed and approved - closed.
