### ISSUE TITLE
Abs. 2009.3 TB-2: survey

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#192]
questionnaire for Abs. 2009.3 TB-2
field start: **15.08.2019**

Testlink: http://presentation.dzhw.eu/Absolventen2009-3-tb-2/
Token: tester1-tester100

**Planning:**
Lasttest:         09.08.
1. Erinnerung: **29.08.**
2. Erinnerung: **12.09.**
3. Erinnerung: **26.09.**

**Comment by SilinaKowalewski** [comment]
## **data delivery from Torsten Euler at 15.07.2019**

**programming template:**
[Abs2009.3_PV_TB2_007.docx](https://github.com/dzhw/zofar/files/3391483/Abs2009.3_PV_TB2_007.docx)


**flow chart:**
[Pfaddiagramm_Abs20093_TB2_004.pdf](https://github.com/dzhw/zofar/files/3391487/Pfaddiagramm_Abs20093_TB2_004.pdf)


**programming template addon:**
[Abs2009.3_AddOn_PV_TB2_002.docx](https://github.com/dzhw/zofar/files/3391482/Abs2009.3_AddOn_PV_TB2_002.docx)


**screenshots template addon:**

- **browser:**

![Addon-Variante-1_Browser](https://user-images.githubusercontent.com/48087320/61204643-0d796e80-a6ee-11e9-89f4-6eaab56d293e.png)

- **responsive:**

![Addon-Variante-1_responsive](https://user-images.githubusercontent.com/48087320/61204649-110cf580-a6ee-11e9-86da-e7a16af776fa.png)

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 
Bitte nennt und noch den "Namen" der Befragung bzw. der Titel der in der URL zur Befragung angezeigt werden soll.

**Comment by thorsteneuler** [comment]
Da einige Befragte postalisch eingeladen werden, würde ich einen kurzen URL-Namensbestandteil wählen. Also "abs2009tb2": 
http://survey02.dzhw.eu/abs2009tb2/

Im Browserheader/-titel bitte anstelle "Absolventenpanel 2009" "Absolventen 2009.3 Teilbefragung 2" anzeigen. 

Könnt ihr uns dann hier auch schon die spätere URL eintragen, damit wir diese für die Einladungsschreiben in unserer Datenbank einpflegen können bzw. ist diese hier korrekt? (http://survey02.dzhw.eu/abs2009tb2/special/login.html?zofar_token=XXXXXXX)

**Comment by thorsteneuler** [comment]
Schon mal vorsorglich:

Die 3. Erinnerung für TB2 spricht von einer möglichen Teilnahme an der Befragung bis 6.10.19.

Entsprechend würden wir die Befragung gerne ein paar Tage später, am **11.10. schließen** (wir hatten ja auch ein paar Tage später den Feldstart als ursprünglich geplant).
