### ISSUE TITLE
Abs. 2009.3 TB-2: creating a project

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#193]
name of project for svn: 
Absolventenpanel 2009.3 TB 2

**Comment by vdick** [comment]
Survey created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Absolventen2009-3-tb-2/
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Absolventen2009-3-tb-2-Addon/
Jenkins:
http://vmbuild.dzhw.local:8080/job/Absolventen2009-3-tb-2/
On presentation.dzhw.eu will be available after first build:
http://presentation.dzhw.eu/Absolventen2009-3-tb-2/
