### ISSUE TITLE
Abs. 2009.3 TB-2: testing and correcting

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#195]
data check: **08.08.2019**

**Comment by thorsteneuler** [comment]
Für die Testungen habe ich anbei eine Liste der token tester1-tester100 erzeugt und diesen jeweils 0 oder 1 für die beiden Preloads pre_nojob und pre_nomobil zugewiesen. 
[Testerliste_mit_Preloads.xlsx](https://github.com/dzhw/zofar/files/3409914/Testerliste_mit_Preloads.xlsx)

**Comment by andreaschu** [comment]
@dzhwmeisner please import the testing-preloads in data base.
[Testerliste_mit_Preloads.xlsx](https://github.com/dzhw/zofar/files/3426104/Testerliste_mit_Preloads.xlsx)

**Comment by dzhwmeisner** [comment]
preloaded tokens added

**Comment by SilinaKowalewski** [comment]
@thorsteneuler:

Ich habe nun auch alle Bedingungen für die Hilfsvariable eingebaut. Bitte prüft diese möglichst genau.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski  
Bei den ersten Testungen haben wir festgestellt, dass die Preloads noch nicht funktionieren. Tester1, 2 und 11 wurden jeweils auf Seite p102 geführt (was bei pre_nojob=0 im Falle von tester1 und 2 nicht passieren sollte, zudem bekommen alle bei p301ff. die q1-Formulierung angezeigt, obgleich tester2 die Formulierung q2 bekommen müsste. 

- [ ] Bitte Preloads nochmal überprüfen, ob diese korrekt eingebunden sind.

**Comment by SilinaKowalewski** [comment]
Hier sind schon mal vorab die ersten Änderungspunkte für die erste Programmierung:

- [ ] Auf Seite p101 fehlt bei der Instruktion vor "Erwerbstätigkeit" ein "Zur". Bitte nachtragen.
- [ ] Auf Seite p102 in der Instruktion "im Betrieb/der Organisation" durch "im Betrieb/in der Organisation" ersetzen.
- [ ] Auf Seite p104 die Antwortvalidierung so anpassen, dass in allen drei Eingabefeldern nur Zahlen  (≤ dreistellig) eingegeben werden können.
- [ ] Auf Seite p105 fehlt bei ao3 von t2jobarve hinter "Referendariat" die schließende Klammer ")".
- [ ] Auf Seite p106 die Breite der Eingabefelder angleichen (t2jobplz schmaler als t2jobort/t2jobland).
- [ ] Auf Seite p109 in q1 und q2 "Ihr UnternehmenBetrieb/Ihre Organisation Dienststelle" durch "Ihr Betrieb/Ihre Dienststelle" ersetzen.
- [ ] Auf Seite p111 in q "Brutto einkommen" zusammenschreiben.
- [ ] Auf Seite p111 in is Zeilenumbruch vor "Für Erwerbstätige im Ausland" einfügen.
- [ ] Auf Seite p111 die Breite der Eingabefelder angleichen (t2brutto aktuell schmaler als t2bruttodev)
- [ ] Auf Seite p111 den Hinweis "Bitte  runden Sie auf ganze Eurobeträge auf und verzichten auf Nachkommastellen oder Trennzeichen (12345 anstatt 12.345,00)" muss von vornherein immer angezeigt werden. Derzeit kommt dieser nur bei Eingabe von Buchstaben im Nummernfeld von t2brutto (da muss dann aber als av der Verweis auf Nur Zahleneingabe auftauchen). Werden aktuell Zahlen eingegeben, kommt der Hinweis "Bitte  runden Sie..." gar nicht erst - muss aber allen Befragten angezeigt werden.
- [ ] Bei p204 ist kein Itemstamm vorgesehen. Bitte "Bei meiner Haupterwerbstätigkeit …" entfernen.
- [ ] Bei p205 ist kein Itemstamm vorgesehen. Bitte "Bei meiner Haupterwerbstätigkeit …" entfernen.

_Originally posted by @thorsteneuler in https://github.com/dzhw/zofar/issues/196#issuecomment-516308033_

**Comment by SilinaKowalewski** [comment]
Könntet ihr bitte die Time-Out-Grenze etwas nach oben setzen. Aktuell fliegen wir dauernd aus den Sessions raus sobald wir anfangen unsere Anmerkungen zu notieren.

_Originally posted by @thorsteneuler in https://github.com/dzhw/zofar/issues/196#issuecomment-516307189_

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 
Haben alle Änderungen umgesetzt.

Bitte stellt zukünftig eure Änderungen in dieses Issue ein, da "programming first draft" ja nun abgeschlossen ist und wir dieses Issue bereits schließen konnten :)

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Jetzt bin ich im Richtigen ;-)

- [ ] Bei Add-On-Befragung aus Seite end besteht eine doppelte Formulierung. 
Der Satz "Wenn Sie Fragen haben, können Sie uns telefonisch oder per E-Mail erreichen: " ist zuviel und kann gestrichen werden. Der Satz "Wenn Sie Fragen haben, können Sie uns gerne telefonisch oder per E-Mail (absolventen2009@dzhw.eu) erreichen:" bleibt.
- [ ] Bei Add-On-Befragung sollten die Seiten index und p01_a auf einer Seite liegen, um zu vermeiden, dass die Befragten noch einmal zusätzlich weiterklicken müssen.

**Comment by thorsteneuler** [comment]
- [ ] Bei p203 zweiten Punkt hinter "...war ich innovativ.. " bei t2neuinno entfernen (wird angezeigt wenn t2akterw=2)
- [ ] Bei p204 ist kein Itemstamm vorgesehen. Derzeit wird dieser noch angezeigt, wenn t2akterw=2. Bitte "Bei meiner Haupterwerbstätigkeit …" entfernen.
- [ ] Bei p204 zweiten Punkt hinter "Ich fand neue Arbeitsmethoden, Vorgehensweisen oder Arbeitsmittel heraus.. " bei t2neumet entfernen (wird angezeigt wenn t2akterw=2)
- [ ] Bei p205 ist kein Itemstamm vorgesehen. Derzeit wird dieser noch angezeigt, wenn t2akterw=2. Bitte "Bei meiner Haupterwerbstätigkeit …" entfernen.

**Comment by thorsteneuler** [comment]
- [ ] Auf Seite p301 in in2 "2009/2009" durch "2008/2009" ersetzen.
- [ ] Auf den Seiten p302, p303, p304, p305, p306, p307, p308, p309, p310, p311, p312 und p313 bitte bei q2 jeweils "2009/2009" durch "2008/2009" ersetzen.

**Comment by thorsteneuler** [comment]
Bei den Seiten p301, p302, p303, p304, p305, p306, p307, p308, p309, p310, p311, p312 und p313 springt das Design immer wieder um. Teilweise unterscheidet sich auch die gleiche Seite, bei mehrmaligem Aufrufen z.B. durch Vor- und Zurückspringen (siehe Beispiel für tester4, p305)

![grafik](https://user-images.githubusercontent.com/52777773/62210061-84279480-b39b-11e9-9bb5-3c1d4d9147d6.png)
![grafik](https://user-images.githubusercontent.com/52777773/62210072-8b4ea280-b39b-11e9-94db-7b1ca5a94914.png)

**Comment by SilinaKowalewski** [comment]
> Bei den Seiten p301, p302, p303, p304, p305, p306, p307, p308, p309, p310, p311, p312 und p313 springt das Design immer wieder um. Teilweise unterscheidet sich auch die gleiche Seite, bei mehrmaligem Aufrufen z.B. durch Vor- und Zurückspringen (siehe Beispiel für tester4, p305)
> 
> ![grafik](https://user-images.githubusercontent.com/52777773/62210061-84279480-b39b-11e9-9bb5-3c1d4d9147d6.png)
> ![grafik](https://user-images.githubusercontent.com/52777773/62210072-8b4ea280-b39b-11e9-94db-7b1ca5a94914.png)

@dzhwmeisner: kannst du dir dieses Problem mal ansehen?

**Comment by thorsteneuler** [comment]
Ich habe nun alle Testungen der Kolleg(inn)en eingesammt und hier schon mal die Sachen für den ersten Block.

- [ ] Auf der Seite index beim Satz "Ihre Teilnahme an der Befragung...." das doppelte "I" in "IIhre" entfernen.
- [ ] Auf der Seite index hinter der Telefonnummer des Datenschutzbeauftragen "...-491" ein Komma ergänzen.
- [ ] Auf Seite p104 in q1 und q2 "(in Std./Wo.)" durch "(in Stunden/Woche)" ersetzen und bei ao1-ao3 den Suffix "Stunden/Woche" durch "Std./Woche" ersetzen.
- [ ] Auf Seite p104 die av von dreistelligen Zahlen auf vierstellige Zahlen abändern (wegen möglicher Kommaeingaben wie 19,5)
- [ ] Auf Seite p105 bei der unteren/zweiten Frage im Fragetext q1 und q2 "Art des Arbeitsverhältnisses" durch "berufliche Stellung" ersetzen.
- [ ] Auf Seite p105 bei ao1 "(z.B. Abteilungsleiter/in, Prokurist/in, Direktor/in)" durch "(z.B. Abteilungsleiter(in), Prokurist(in), Direktor(in))" ersetzen.
- [ ] Auf Seite p105 und p108 wird auf Mobilgeräten vor den Units ein (korrekterweise) nicht-auswählbarer Radiobutton angezeigt. Kann dieser ausgeblendet werden?
- [ ] Auf Seite p106 wird q2 nicht korrekt angezeigt (vc: SHOW q2 IF t2akterw = 2 ) stattdessen kommt q1
- [ ] Auf Seite p111 in q1 und q2 "aus beruflicher Tätigkeit" streichen. In is1 und is2 "US-Doller" durch "US-Dollar" ersetzen.
- [ ] Auf Seite p112 in q1 und q2 den Satz "Bitte geben Sie an, wie hoch Ihr monatliches Bruttoeinkommen in etwa ist/war." streichen.
- [ ] Auf Seite p120 steht bei ao2b (angezeigt wenn t2akterw=2 derzeit "ein Hochschulabschluss die Regel ist?", muss aber "ein Hochschulabschluss die Regel war?" lauten.

**Comment by thorsteneuler** [comment]
- [ ] Auf Seite p208 werden die nummerischen Werte der Skalenpunkte (im Gegensatz zu p201-207) nicht angezeigt. Bitte ergänzen.
- [ ] Auf Seite p201 Headline und Introduktion etwas voneinander absetzen, wirkt derzeit gestaucht.

**Comment by thorsteneuler** [comment]
- [ ] Beim Introduction-Text auf Seite p301 bitten den Text "Hochqualifizierte sind eine Bevölkerungsgruppe mit besonders hoher Mobilität. Studium, aufbauenden Abschlüsse, der Berufseinstieg, neue Arbeitsstellen, Partnerschaften und Familiengründungen bringen häufig Umbrüche des Wohnorts und der Wohnsituation mit sich." durch "Hochschulabsolvent(inn)en sind eine Bevölkerungsgruppe mit besonders hoher Mobilität durch Studium, neue Arbeitsstellen, Partnerschaften und Familiengründungen."
- [ ] In der Instruction auf p301 bei "Wohnung steht dabei synonym für jede Unterkunft..." den Begriff Wohnung bitte unterstreichen.
- [ ] Auf Seite p301 bei Variable t2wohn1vj die Antwortoptionen in ao2 (betrifft nur Seite p301) ändern in: 
ao2: (t2wohn1vj) 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000 und früher

- [ ] Auf den Seiten 301b-313b jeweils it1 [alleine] als Exklusivkategorie [EK] definieren
- [ ] Auf den Seiten 301b-313b jeweils bei it5 "Stief-/Pflegekind(ern)/Kinder" durch "Stief-/Pflegekind(ern)/Kind(er)" ersetzen
- [ ] Auf den Seiten 301b-313b jeweils bei it6 "(z. B. WG-Mitbewohner)" durch "(z. B. WG-Mitbewohner(in))" ersetzen
- [ ] Auf den Seiten 301e-313e werden auf meinem Smartphone (beim Rest des Teams ebenfalls), die Zwischenüberschriften nicht ordentlich dargestellt und rutschen in die jeweils erste Antwortkategorie) -> siehe Screenshot.

![Zwischenüberschriften_Auszugsgrund](https://user-images.githubusercontent.com/52777773/62296195-e2717780-b46e-11e9-9aa7-d0e83a8bef53.jpg)

**Comment by thorsteneuler** [comment]
- [ ] Bei Seite p301c die Transition anpassen (die Seite p301e soll überfiltert werden wenn auf Seite p301 bei t2wohn1bj ein gültiger Antwortwert (sprich Auszugsjahr) kleiner 2019 steht). Ich habe alle Ausschlussmöglichkeiten unten aufgeführt, die darunterfallen sollten : 
tr: GOTO p301d IF t2wohn1bj = SYSMISS OR t2wohn1bj = 0 OR t2wohn1bj = 2019 OR t2wohn1bj = aktuell wohnhaft
GOTO p301e IF t2wohn1bj <> SYSMISS AND t2wohn1bj <> 0 AND t2wohn1bj <> 2019 AND t2wohn1bj <> aktuell wohnhaft
@SilinaKowalewski: sofern diese Variante als Transition funktioniert, können die nachfolgenden kopiert werden, ich habe dort nur die zugehörigen Seiten- und Variablennnummern angepasst. 

- [ ] Bei Seite p302c die Transition anpassen: 
tr: GOTO p302d IF t2wohn2bj = SYSMISS OR t2wohn2bj = 0 OR t2wohn2bj = 2019 OR t2wohn2bj = aktuell wohnhaft
GOTO p302e IF t2wohn2bj <> SYSMISS AND t2wohn2bj <> 0 AND t2wohn2bj <> 2019 AND t2wohn2bj <> aktuell wohnhaft

- [ ] Bei Seite p303c die Transition anpassen: 
tr: GOTO p303d IF t2wohn3bj = SYSMISS OR t2wohn3bj = 0 OR t2wohn3bj = 2019 OR t2wohn3bj = aktuell wohnhaft
GOTO p303e IF t2wohn3bj <> SYSMISS AND t2wohn3bj <> 0 AND t2wohn3bj <> 2019 AND t2wohn3bj <> aktuell wohnhaft

- [ ] Bei Seite p304c die Transition anpassen: 
tr: GOTO p304d IF t2wohn4bj = SYSMISS OR t2wohn4bj = 0 OR t2wohn4bj = 2019 OR t2wohn4bj = aktuell wohnhaft
GOTO p304e IF t2wohn4bj <> SYSMISS AND t2wohn4bj <> 0 AND t2wohn4bj <> 2019 AND t2wohn4bj <> aktuell wohnhaft

- [ ] Bei Seite p305c die Transition anpassen: 
tr: GOTO p305d IF t2wohn5bj = SYSMISS OR t2wohn5bj = 0 OR t2wohn5bj = 2019 OR t2wohn5bj = aktuell wohnhaft
GOTO p305e IF t2wohn5bj <> SYSMISS AND t2wohn5bj <> 0 AND t2wohn5bj <> 2019 AND t2wohn5bj <> aktuell wohnhaft

- [ ] Bei Seite p306c die Transition anpassen: 
tr: GOTO p306d IF t2wohn6bj = SYSMISS OR t2wohn6bj = 0 OR t2wohn6bj = 2019 OR t2wohn6bj = aktuell wohnhaft
GOTO p306e IF t2wohn6bj <> SYSMISS AND t2wohn6bj <> 0 AND t2wohn6bj <> 2019 AND t2wohn6bj <> aktuell wohnhaft

- [ ] Bei Seite p307c die Transition anpassen: 
tr: GOTO p307d IF t2wohn7bj = SYSMISS OR t2wohn7bj = 0 OR t2wohn7bj = 2019 OR t2wohn7bj = aktuell wohnhaft
GOTO p307e IF t2wohn7bj <> SYSMISS AND t2wohn7bj <> 0 AND t2wohn7bj <> 2019 AND t2wohn7bj <> aktuell wohnhaft

- [ ] Bei Seite p308c die Transition anpassen: 
tr: GOTO p308d IF t2wohn8bj = SYSMISS OR t2wohn8bj = 0 OR t2wohn8bj = 2019 OR t2wohn8bj = aktuell wohnhaft
GOTO p308e IF t2wohn8bj <> SYSMISS AND t2wohn8bj <> 0 AND t2wohn8bj <> 2019 AND t2wohn8bj <> aktuell wohnhaft

- [ ] Bei Seite p309c die Transition anpassen: 
tr: GOTO p309d IF t2wohn9bj = SYSMISS OR t2wohn9bj = 0 OR t2wohn9bj = 2019 OR t2wohn9bj = aktuell wohnhaft
GOTO p309e IF t2wohn9bj <> SYSMISS AND t2wohn9bj <> 0 AND t2wohn9bj <> 2019 AND t2wohn9bj <> aktuell wohnhaft

- [ ] Bei Seite p310c die Transition anpassen: 
tr: GOTO p310d IF t2wohn10bj = SYSMISS OR t2wohn10bj = 0 OR t2wohn10bj = 2019 OR t2wohn10bj = aktuell wohnhaft
GOTO p310e IF t2wohn10bj <> SYSMISS AND t2wohn10bj <> 0 AND t2wohn10bj <> 2019 AND t2wohn10bj <> aktuell wohnhaft

- [ ] Bei Seite p311c die Transition anpassen: 
tr: GOTO p311d IF t2wohn11bj = SYSMISS OR t2wohn11bj = 0 OR t2wohn11bj = 2019 OR t2wohn11bj = aktuell wohnhaft
GOTO p311e IF t2wohn11bj <> SYSMISS AND t2wohn11bj <> 0 AND t2wohn11bj <> 2019 AND t2wohn11bj <> aktuell wohnhaft

- [ ] Bei Seite p312c die Transition anpassen: 
tr: GOTO p312d IF t2wohn12bj = SYSMISS OR t2wohn12bj = 0 OR t2wohn12bj = 2019 OR t2wohn12bj = aktuell wohnhaft
GOTO p312e IF t2wohn12bj <> SYSMISS AND t2wohn12bj <> 0 AND t2wohn12bj <> 2019 AND t2wohn12bj <> aktuell wohnhaft

- [ ] Bei Seite p313c die Transition anpassen: 
tr: GOTO p313d IF t2wohn13bj = SYSMISS OR t2wohn13bj = 0 OR t2wohn13bj = 2019 OR t2wohn13bj = aktuell wohnhaft
GOTO p313e IF t2wohn13bj <> SYSMISS AND t2wohn13bj <> 0 AND t2wohn13bj <> 2019 AND t2wohn13bj <> aktuell wohnhaft

**Comment by thorsteneuler** [comment]
- [ ] Auf Seite p320 bei ao2 "Wochenendpendler(in)" durch "Wochenendpendeln" ersetzen.

- [ ] Auf Seite p401 vertikale statt horizontale ao einstellen (Vermeidung seitlichen Scrollens auf dem Handy)
- [ ] Auf Seite p401 im Introduction Text "bitten, die nichts mit Erwerbstätigkeiten oder Mobilität zu tun haben." durch "zu Politk und Gesellschaft bitten." ersetzen.
- [ ] Auf Seite p403 vertikale statt horizontale ao einstellen (Vermeidung seitlichen Scrollens auf dem Handy)
- [ ] Auf Seite p405 vertikale statt horizontale ao einstellen (Vermeidung seitlichen Scrollens auf dem Handy)

- [ ] Auf Seite p404 die Itemreihenfolge ändern, Rechtschreibfehler ändern und it4 als Exklusivkategorie setzen: 

it1: t2mitgewerk: ...einer Gewerkschaft?
it2: t2mitpartei: ...einer politischen Partei oder Wählervereinigung?
it3: t2mitverein: ...in einem Verein oder einer gemeinnützigen Organisation (ohne Kirchen oder Religionsgemeinschaften)?
it4: t2mitnichts: ...in keiner dieser Organisationen? [EK]

- [ ] Auf Seite end den Text "Wenn Sie Fragen haben, können Sie uns gerne telefonisch oder per E-Mail (absolventen2009@dzhw.eu) erreichen:" nach "erreichen" mit dem Text "Weitere Informationen finden Sie zudem auf unserer [Projekthomepage](www.dzhw.eu/forschung/projekt?pr_id=302):" ergänzen.

@SilinaKowalewski : Gebt uns bitte Bescheid, wenn ihr euch die Hilfsvariable anschauen konntet. Das ist der Punkt, den wir noch nicht abschließend prüfen konnten.

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 
Die Hilfsvariable sollte nun funktionieren 👍

**Comment by thorsteneuler** [comment]
- [ ] Transition von 303d funktioniert nicht. GOTO p303f if t2wohn3derz = 1 [Ja]  greift nicht, sondern führt auf p303e
- [ ] Auf p313f bitte in der Instruction die  ** entfernen (ist ja alles schon kursiv) und “6/2018 bis 1/2019, PLZ = 12345, mit Partner, Hauptwohnung, Auszug wegen neuer Arbeitsstelle” unterstreichen
- [ ] Auf p313f das Eingabefeld etwas breiter anlegen (Breite wie bei p107).
- [ ] Auf Seite p111 in q1 und q2 "aus beruflicher Tätigkeit" streichen.

@SilinaKowalewski :
Hilfsvariable und Transition bei den 3**c-Seiten scheinen überall zu funktionieren 👍

**Comment by thorsteneuler** [comment]
Bitte überprüfen:

- [ ] Von Seite p304f wird bei t2wohn4weit=2 auf p320 weitergeleitet, egal welchen Wert die Hilfsvariable hv_multiwohn hat. Sollte aber nur dort landen wenn t2wohn4weit=2 & hv_multiwohn>=2. Bei t2wohn4weit=2 & hv_multiwohn<2 soll auf p401 geleitet werden.

**Comment by thorsteneuler** [comment]
Als Hinweis für die zukünftige Entwicklung der Zofar-Software: Habe auf Chrome auf meinem Handy getestet und es wäre für den Überblick schöner, wenn bei Dropdowns die Units sich etwas von den Antwortkategorien visuell unterscheiden würden. Nichts aktuell dringendes, wir haben nur zweimal überhaupt Units drin, aber vielleicht für zukünftige Befragungen noch hilfreich.

**Comment by thorsteneuler** [comment]
- [ ] Der softforce bei kleinen Bildschirmen "Diese Seite enthält Teilfragen. Mit den Pfeiltasten können Sie zwischen diesen wechseln." kann auf den Seiten p205-p208 herausgenommen werden. Wer das Batteriesystem bis dahin nicht verstanden hat wird ansonsten nur noch mehr frustriert und bricht wohlmöglich ab.

**Comment by thorsteneuler** [comment]
Hier die letzten Korrekturen:

- [ ] auf Seite p105 bei Frage 2 (t2jobbest) bei ao10 hinter "Realschullehrer(in)" noch eine schließende Klammer einfügen ")".
- [ ] bei p201 bitte zwischen in und q eine Leerzeile als Abstand einfügen.
- [ ] bei p401 in der instruction bitte "Politk" durch "Politik" ersetzen.
- [ ] bei p405 bitte zwischen in und q eine Leerzeile als Abstand einfügen.
- [ ] auf Seite end bitte zwischen hl und in eine Leerzeile als Abstand einfügen.
- [ ] auf Seite endrf  in der instruction anstatt "Wir danken Ihnen für Ihre frühere Teilnahme an den DZHW-Absolventenbefragungen und wünschen Ihnen für Ihren weiteren Lebensweg alles Gute." nun "Wir danken Ihnen für Ihre frühere Teilnahme an den DZHW-Absolventenbefragungen." schreiben.

**Comment by thorsteneuler** [comment]
Auf der Seite index kann nun (nachdem wir es mit Modellfällen getestet haben), der noch fehlende Zeitbedarf "ca. XX bis XX Minuten in Anspruch" durch "ca. 10 bis 15 Minuten in Anspruch" ersetzt werden. 

Ansonsten habe ich alle Änderungen geprüft und gebe das Instrument fürs Ausrollen zum Lasttest und zur Lieferung von Probedaten frei. Die preload-Liste kommt euch heute im Laufe des Tages zu.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Die Preloaddatei (token, pre_nojob, pre_nomobil) liegt im geschützten Bereich auf P:\koop\Euler als Datei "abs2009_3_preloads_tb2.xls". Gib Bescheid, falls ihr darauf keinen Zugriff haben solltet, dann legen wir das irgendwo anders ab.

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner @vdick: 

Könnt ihr bitte einen Lasttest bzw. Data Check durchführen?

**Comment by SilinaKowalewski** [comment]
@thorsteneuler:
Die Ergebnisse des Lasttest liegen in Form von zwei Zip-Ordnern (Hauptgefragung und Addon) im geschützten Bereich im Ordner P:\koop\Euler. 

Da sich auf der End-Seite doch noch eine Fehler eingeschlichen hatte, wurde diese Seite im Lasttest nicht angesteuert. Der Fehler ist aber nun behoben und sollte für den Data Check keine Rolle spielen.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Alles klar. Die Endseite ist ja für Filterung etc. erstmal nicht von Belang 👍 
Ich (oder Max) schauen uns die Daten an.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Leider ist unserem Datenschutzbeauftragten nach einem sehr langen inneren Monolog gestern Abend noch eingefallen, dass er eine Formulierung auf der Indexseite noch anders haben möchte.

Unter "Hinweise zum Datenschutz" soll anstelle von 
"Ihre Angaben werden ausschließlich zu wissenschaftlichen Forschungszwecken genutzt. 
Ausführliche Informationen zum DZHW, zum Datenschutz und zur Organisation der Befragung haben wir [hier] für Sie zusammengestellt."

Nun dies hier stehen:
"Ihre Angaben werden ausschließlich zu wissenschaftlichen Forschungszwecken genutzt. Forschungsergebnisse werden nur so veröffentlicht, dass Rückschlüsse auf einzelne Befragungsteilnehmer ausgeschlossen sind. 
Ausführliche Informationen zum DZHW, zum Datenschutz und zur Organisation der Befragung, sowie Ihren Rechten nach DSGVO haben wir [hier] für Sie zusammengestellt."

**Comment by SilinaKowalewski** [comment]
> Auf der Seite index kann nun (nachdem wir es mit Modellfällen getestet haben), der noch fehlende Zeitbedarf "ca. XX bis XX Minuten in Anspruch" durch "ca. 10 bis 15 Minuten in Anspruch" ersetzt werden.

Irgendwie ist diese Änderung in der aktuellen Version noch nicht umgesetzt. 

@vdick: Sollten wir nach Möglichkeit auch in der ausgerollten Version ändern.

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 
Ich hab die Änderung bereits in der Programmierung umgesetzt und neu auf dem Presentation-Server ausgerollt. Final online ausrollen werden wir die Version dann Anfang nächster Woche.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Ich habe mir die Datacheck-Dateien angesehen und keine größeren Auffälligkeiten gefunden. Dass es mit der End-Seite einen Fehler gab hattest du ja schon oben geschrieben. Dass die Dropdownmenüs nur sehr begrenzt ausgewählt werden (in der Regel bleibt alles bei 0) und die Exklusivkategorien auch andere Variablen befüllt belassen, liegt vermutlich an der Datenfüllsimulation (zumindest gehe ich hoffnungsvoll davon aus - bei Einzelfällen stand ja doch mal ein Wert jenseits von 0 in den Dropdowns).  

Gebt ihr mir bitte Bescheid, wenn die Befragung final ausgerollt und scharfgeschaltet ist? Dann checke ich diese Mittwoch nochmal mit realen Token.

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 

Die Befragung ist nun final unter dem Link http://survey02.dzhw.eu/abs2009tb2/ ausgerollt. 
Sobald ihr uns das offizielle "Go" gebt bzw. nicht mehr testet, würde Viktor die Datenbank leeren und dann kann es los gehen 👍

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Hab alles gecheckt 👍  Hier das offizielle "Go" mit der Bitte die Datenbank noch zu leeren. Dann harren wir der Dinge und hoffen auf viele Befragte, die nicht an ihren Wohnungen verzweifeln.

Ich lade euch morgen auch noch die Erinnungstexte hoch, damit die schon vorliegen.
