### ISSUE TITLE
Abs. 2009.3 TB-2: programming first draft

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#196]

**Comment by SilinaKowalewski** [comment]
## **data delivery from Torsten Euler at 15.07.2019**

**programming template:**
[Abs2009.3_PV_TB2_007.docx](https://github.com/dzhw/zofar/files/3391483/Abs2009.3_PV_TB2_007.docx)


**flow chart:**
[Pfaddiagramm_Abs20093_TB2_004.pdf](https://github.com/dzhw/zofar/files/3391487/Pfaddiagramm_Abs20093_TB2_004.pdf)


**programming template addon:**
[Abs2009.3_AddOn_PV_TB2_002.docx](https://github.com/dzhw/zofar/files/3391482/Abs2009.3_AddOn_PV_TB2_002.docx)


**screenshots template addon:**

- **browser:**

![Addon-Variante-1_Browser](https://user-images.githubusercontent.com/48087320/61204643-0d796e80-a6ee-11e9-89f4-6eaab56d293e.png)

- **responsive:**

![Addon-Variante-1_responsive](https://user-images.githubusercontent.com/48087320/61204649-110cf580-a6ee-11e9-86da-e7a16af776fa.png)

**Comment by SilinaKowalewski** [comment]
Sollen für die Fragen als Einfachauswahlmatrix (z.B.: 201) wirklich verschiedene Variablen angelegt werden, in Abhängigkeit zu der Sichtbarkeitsbedingung (z.B.: t2kdsit_a / t2kdprob_b ) , oder reicht es eine Variable (t2kdsit) anzulegen? 

Technisch wäre beides möglich.

**Comment by SilinaKowalewski** [comment]
*"Falls im responsiven Design aus den Items ein Itemkarussell wird, sofern technisch möglich bei Auswahl einer ao automatisch auf das nächste Item des Karussells weiterleiten. "*

Dies ist leider nicht möglich. Wir werden dann als Alternative einen entsprechenden Softforce programmieren, der darauf hinweist, dass weiter Teilfragen existieren.

**Comment by SilinaKowalewski** [comment]
Die Seiten Index bis 205 sind angepasst. Aber bisher nur local einsehbar.

**Comment by thorsteneuler** [comment]
> 
> 
> Sollen für die Fragen als Einfachauswahlmatrix (z.B.: 201) wirklich verschiedene Variablen angelegt werden, in Abhängigkeit zu der Sichtbarkeitsbedingung (z.B.: t2kdsit_a / t2kdprob_b ) , oder reicht es eine Variable (t2kdsit) anzulegen?
> 
> Technisch wäre beides möglich.

Es genügt eine Variable (also z.B. t2kdsit). Die a/b-Variante hatte ich aus der PV von Abs2013.2-TB3 kopiert. Dort war diese so aufgeführt gewesen. Uns geht es nur darum, dass die Befragten die passende Zeitform in der Formulierung erhalten, je nachdem ob die aktuell oder früher erwerbstätig sind. Andrea beschrieb mir eben die Variante einer Matritze, die je nach Erwerbsstatus mit der passenden Fomulierung eingeblendet wird und in die gleiche Variable schreibt. Das würden wir so nehmen.

Dazu die Bitte, uns ein PV-Muster zu schicken, wie solch eine Matritzen in die PV eingetragen werden müsste, damit ich dies unserer PV aktualisieren kann und zukünftige Projekte dann dies für eigene PVs verwenden können.

**Comment by SilinaKowalewski** [comment]
Vor die Seitennummern wurde jeweils ein "p" hinzugefügt, da diese Seitennummern nicht mit einer Zahl beginnen dürfen. 

z.B.: 
101 > p101

**Comment by SilinaKowalewski** [comment]
Fragebogen komplett programmiert und local ausgerollt um im Team zu testen. 

@thorsteneuler: Nach einem ersten internen Test werde ich die Befragung so ausrollen, dass auch du sie testen kannst.

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 

Unter folgenden Links kannst du die dir eine erste Version der Hauptbefragung sowie Addon-Befragung anschauen: 

http://vmzofarprod-app3.his.de:8080/Absolventen2009-3-tb-2/
http://vmzofarprod-app3.his.de:8080/Absolventen2009-3-tb-2-Addon

Tester-Token: tester1 - tester100


**to do:**
- [ ] units in dropdowns sind programmiert, werden aber nicht angezeigt
- [ ] Filterführung über Hilfsvariable noch nicht programmiert

**Comment by thorsteneuler** [comment]
Könntet ihr bitte die Time-Out-Grenze etwas nach oben setzen. Aktuell fliegen wir dauernd aus den Sessions raus sobald wir anfangen unsere Anmerkungen zu notieren.

**Comment by thorsteneuler** [comment]
Hier sind schon mal vorab die ersten Änderungspunkte für die erste Programmierung:

- [ ] Auf Seite p101 fehlt bei der Instruktion vor "Erwerbstätigkeit" ein "Zur". Bitte nachtragen.
- [ ] Auf Seite p102 in der Instruktion "im Betrieb/der Organisation" durch "im Betrieb/in der Organisation" ersetzen.
- [ ] Auf Seite p104 die Antwortvalidierung so anpassen, dass in allen drei Eingabefeldern nur Zahlen  (≤ dreistellig) eingegeben werden können.
- [ ] Auf Seite p105 fehlt bei ao3 von t2jobarve hinter "Referendariat" die schließende Klammer ")".
- [ ] Auf Seite p106 die Breite der Eingabefelder angleichen (t2jobplz schmaler als t2jobort/t2jobland).
- [ ] Auf Seite p109 in q1 und q2 "Ihr UnternehmenBetrieb/Ihre Organisation Dienststelle" durch "Ihr Betrieb/Ihre Dienststelle" ersetzen.
- [ ] Auf Seite p111 in q "Brutto einkommen" zusammenschreiben.
- [ ] Auf Seite p111 in is Zeilenumbruch vor "Für Erwerbstätige im Ausland" einfügen.
- [ ] Auf Seite p111 die Breite der Eingabefelder angleichen (t2brutto aktuell schmaler als t2bruttodev)
- [ ] Auf Seite p111 den Hinweis "Bitte  runden Sie auf ganze Eurobeträge auf und verzichten auf Nachkommastellen oder Trennzeichen (12345 anstatt 12.345,00)" muss von vornherein immer angezeigt werden. Derzeit kommt dieser nur bei Eingabe von Buchstaben im Nummernfeld von t2brutto (da muss dann aber als av der Verweis auf Nur Zahleneingabe auftauchen). Werden aktuell Zahlen eingegeben, kommt der Hinweis "Bitte  runden Sie..." gar nicht erst - muss aber allen Befragten angezeigt werden.
- [ ] Bei p204 ist kein Itemstamm vorgesehen. Bitte "Bei meiner Haupterwerbstätigkeit …" entfernen.
- [ ] Bei p205 ist kein Itemstamm vorgesehen. Bitte "Bei meiner Haupterwerbstätigkeit …" entfernen.
