### ISSUE TITLE
Abs. 2009.3 TB-2: screenshots

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#199]

**Comment by vdick** [comment]
[Absolventen2009-3-tb-2-Addon_screenshots.zip](https://github.com/dzhw/zofar/files/3739167/Absolventen2009-3-tb-2-Addon_screenshots.zip)

http://vmdevwiki.dzhw.local/transfer/Absolventen2009-3-tb-2_screenshots.zip

**Comment by andreaschu** [comment]
@thorsteneuler see screenshots above for download.
