### ISSUE TITLE
Attached Open

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#20]
To Do:

- [x]  Test Infrastructure
- [x]  Formulate Test Cases
- [x]  Write Unit Tests

Used Time : 1
Sprint 3 Used Time: 16

**Comment by kastirke** [comment]
Is it possible to display the attached open only when the radiobutton of the "others" category has been selected?

**Comment by kastirke** [comment]
Please display the attached open below the "others"-category if possible.
![attached open i](https://user-images.githubusercontent.com/30147532/28633649-dcef1f3e-7234-11e7-87fb-34507017e8fc.png)

**Comment by kastirke** [comment]
If possible, the phrase "Sonstige, und zwar" should be within the input field, which saves space. Font color: gray.

**Comment by dzhwmeisner** [comment]
- Sonstiges, und zwar as Placeholder is done
- Attached Open on Radio Select needs more discussion. Technical implementation not reliable enough and Convenience Method to select Radio on typing in Attached deprecated

**Comment by Miktarbad** [comment]
**further comments please to #28 **

**Comment by dzhwmeisner** [comment]
ready to test

**Comment by Miktarbad** [comment]
![screenshot_20171016-101622](https://user-images.githubusercontent.com/29864065/31602297-e172086a-b25c-11e7-9bfd-8da63565a6f3.png)

filling not fully readable

**Comment by kastirke** [comment]
Font for placeholder "und zwar" vary. Please use uniform font (please do not use bold).

**Comment by kastirke** [comment]
Please use uniform fonts for placeholder "und zwar". NOT Times New Roman. Calibri?

**Comment by andreaschu** [comment]
[C] attached open overlays answer option - text (in super small width)
(windows, desktop, firefox)

![as_firefox_desktop_page0_scvertical_supersmall_20171020](https://user-images.githubusercontent.com/30111489/31821807-9a9ebb3e-b5a6-11e7-860d-11a37e3efad4.PNG)

**Comment by andreaschu** [comment]
[D] Way too long on big screen (and if not limited by check boxes or screen size)
(Desktop, Firefox, Windows)

![as_firefox_desktop_page7_mc_20171020](https://user-images.githubusercontent.com/30111489/31824407-3617b572-b5af-11e7-91a8-433925be5638.PNG)

**Comment by kastirke** [comment]
iPhone SE, iOS 11.0.2; Safari

[E] Still don't like the position of the atteched open.

More distance to the answer option needed:

![img_5727](https://user-images.githubusercontent.com/30147532/31886243-d5406dce-b7f3-11e7-9f7a-b8d47388d015.PNG)

It should be placed next to the answer option or below the answer option. 

![img_5728](https://user-images.githubusercontent.com/30147532/31886384-5be3b76e-b7f4-11e7-95a4-a07e84e09e01.PNG)

**Comment by dzhwmeisner** [comment]
[A][B][C][D] fixed
[E] increased margin-left for apple devices. Functional Test impossible. No modern Safari available

**Comment by Miktarbad** [comment]
**[ F ]** positioning of the attached open fields is still inefficent in carousel

![screen-atopen-mmc-car-2](https://user-images.githubusercontent.com/29864065/31995045-278a4e48-b983-11e7-8455-7e016a4a64de.jpg)

**Comment by Miktarbad** [comment]
**[ H ]**  Validationmessage is displayed faulty in fullscreen mode

![screen-atop-errorm-1-fullscreen](https://user-images.githubusercontent.com/29864065/31995572-4efe6a5c-b985-11e7-91bf-fa18ca325b54.jpg)

**Comment by Miktarbad** [comment]
**[ I ]**
- positioning of the attached open on mobile still inefficient after fixing [E] (S7 - Android 7 - Chrome)
![screenshot_mobile-atopen-1](https://user-images.githubusercontent.com/29864065/31995866-79560a48-b986-11e7-8a0b-07d8a5d50c3d.jpg)

**Comment by Miktarbad** [comment]
Still to be tested:

[ E ] @kastirke: please check the changes

Tasklist DEV:

- [ ] [ F ] positioning in carousel
- [ ] [ G ] ao filling next to answerbox
- [ ] [ H ] display of validation message 
- [ ] [ I ] positioning of the attached open

**Comment by kastirke** [comment]
[E] checked with standard device 👍 
[E] checked with iPhone SE, iOS 11.0.2; Safari: 👎 -> still don't like the position of the attached open (to close to ao "Nein" in portrait and overlay ao "Nein" in landscape format)

![img_5962](https://user-images.githubusercontent.com/30147532/32286632-68d2c438-bf2e-11e7-9733-7abdd2d1d3e2.jpg)

![img_5963](https://user-images.githubusercontent.com/30147532/32286642-6d328928-bf2e-11e7-980a-948978a1e6bb.PNG)

**Comment by dzhwmeisner** [comment]
Positioning refactored. Need testing

**Comment by dzhwmeisner** [comment]
[ G ] Bootstrap Tooltip disabled, because no dynamic Positioning possible, Using default Title-Tooltip mechanism instead. Testing needed

**Comment by Miktarbad** [comment]
[ F ] positioning in carousel still inefficent
[ H ] fixed
[ I ] fixed

**Comment by Miktarbad** [comment]
[ G ] fixed (works in: Edge14, Firefox, Firefox Dev, Chrome)

**Comment by Miktarbad** [comment]
[ J ] distance between attached open and label to big

![label-and-ao](https://user-images.githubusercontent.com/29864065/32649166-5fc7e3e2-c5f9-11e7-9c9f-8ec52a52c1d7.jpg)

**Comment by Miktarbad** [comment]
resolved.
