### ISSUE TITLE
Abs. 2009.3 TB-2: export of data

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#200]

**Comment by thorsteneuler** [comment]
Da der Feldstart der dritten Teilbefragung (2.10.19) vor dem Ende der zweiten Teilbefragung liegt, benötigen wir vorher einen Zwischendatenexport der Add-On-Befragung zur Aktualisierung der Adressdaten für die Einladung TB3. Bitte sofern möglich auf den 23./24.9. terminieren, damit wir noch genug Zeit zum Einpflegen haben.

**Comment by andreaschu** [comment]
@thorsteneuler der vorläufige Export der Adressdaten wurde hierhin transferiert: C:\\daten\Absolventen\abs2009

**Comment by andreaschu** [comment]
@thorsteneuler ich habe den Export von Befragungs- und Adressdaten erstellt und den Transfer veranlasst (siehe E-Mail).
Im \Doc-Ordner findest Du die aggregierten Paradaten und Rücklaufgraphiken.
