### ISSUE TITLE
Abs. 2009.3 TB-2: Invitation

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#203]
Am **15.08.** soll die Feldphase starten und die Einladungen versendet werden.

**Comment by SilinaKowalewski** [comment]
- [ ] match token with preloads and adresses
- [ ]  prepare invitation (test-mail)

**Comment by thorsteneuler** [comment]
Hier der Text für die Invitation am 15.8. 

[1_Einladung_E-Mail_M3_TB2_005.docx](https://github.com/dzhw/zofar/files/3492232/1_Einladung_E-Mail_M3_TB2_005.docx)

**Comment by SilinaKowalewski** [comment]
Bitte gebt uns noch das Go für die Test-Mail bzw. den Mail-Versand. 

Da ich nun die neue Adressdatei habe können wir gleich mit den Einladungen starten.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Na klar, hier das "Go" für den Versand der Einladungsmails in der gestern an uns testweise versandten Form.

**Comment by SilinaKowalewski** [comment]
Der Versand der Einladung ist abgeschlossen. Es konnten alle Mails versendet werden.
