### ISSUE TITLE
progress bar for modules

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#207]
Let's test a contentual progress bar that allows to skip between modules, topics or chapters.
The progress bar should consits of following criterias:
- allow to go back 
- allow to go forward to the modules the respondent already had passed through 
- not allow to skip modules that are not fininished 
- the passed modules should be greyed out
- should be dynamically constructable subjected to the transitions
- usable and visible for small screen sizes

Let's test if it is better in header, as a drop down list or on the left side of the screen.

**Comment by dzhwmeisner** [comment]
@dzhwmeisner build example

**Comment by dzhwmeisner** [comment]
Implemented in SLC
