### ISSUE TITLE
Zofar-Showroom: responsive design

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#209]
The showroom for Zofar is for the older design - it should represent the latest version. Could it get responsive?

**Comment by SilinaKowalewski** [comment]
Building questionnaire with responsive dependencies

**Comment by vdick** [comment]
ready to test at http://vmzofar-pres.his.de:8080/showroom

**Comment by vdick** [comment]
the external link : 
http://presentation.dzhw.eu/showroom

**Comment by kastirke** [comment]
...is in progress.

**Comment by DusdalA** [comment]
![showroom_link](https://user-images.githubusercontent.com/28007144/64254144-108b2100-cf1f-11e9-8594-705aae9e6ee9.png)

Links aren't highlighted as of now. You have to hover over a link to get it highlighted.

![showroom_überschrift](https://user-images.githubusercontent.com/28007144/64254261-50520880-cf1f-11e9-866e-c553a8583d12.png)

Headlines could be more emphasized. Same problem with the links.

![showroom_blocksatz](https://user-images.githubusercontent.com/28007144/64254319-711a5e00-cf1f-11e9-91da-db0d65992f1e.png)

Textpassages would look much better if they were justified (Blocksatz).

![showroom_an-beispiel](https://user-images.githubusercontent.com/28007144/64254389-96a76780-cf1f-11e9-8cc1-1a1ee78ca462.png)

In Example 2 "Einfachauswahl" the free text field overlaps with the radio-buttons.

![showroom_an-beispiel_1](https://user-images.githubusercontent.com/28007144/64254459-bc347100-cf1f-11e9-9e94-79be6551d16a.png)

Example 3 "Einfachauswahl" is not correctly displayed.

![showroom_an-beispiel_2](https://user-images.githubusercontent.com/28007144/64254520-df5f2080-cf1f-11e9-887a-aee37976df4a.png)

The same goes for Example 4 "Einfachauswahl".

![showroom_mehrfachauswahl_bsp](https://user-images.githubusercontent.com/28007144/64254572-f4d44a80-cf1f-11e9-820f-cea26779dcc8.png)

The border of the buttons in Example 1 "Mehrfachauswahl" does not look correct.

![showroom_mehrfachauswahl_bsp1](https://user-images.githubusercontent.com/28007144/64254614-09184780-cf20-11e9-92ee-94372abcbf96.png)

Example 2 "Mehrfachauswahl" is not correctly displayed as well.

![showroom_matrix_bsp](https://user-images.githubusercontent.com/28007144/64254654-1f260800-cf20-11e9-973e-24f5f8ef5c91.png)

The item names in Example 1 "Matrix" are bigger than the question.

![showroom_matrix_bsp1](https://user-images.githubusercontent.com/28007144/64254702-3e249a00-cf20-11e9-98a5-59a288deee2a.png)

Example 2 "Matrix" is missing the titles.

![showroom_matrix_bsp2](https://user-images.githubusercontent.com/28007144/64254738-4e3c7980-cf20-11e9-86ec-f088c66aa036.png)

The free text fields in Example 3 "Matrix" should be moved somewhere else.

![showroom_matrix_bsp3](https://user-images.githubusercontent.com/28007144/64254780-5dbbc280-cf20-11e9-9982-d683b011b8ab.png)

The gap between both categories in example 4 "Matrix" seems to be too big.

![showroom_doppelmatrix_bsp](https://user-images.githubusercontent.com/28007144/64254840-79bf6400-cf20-11e9-9cba-1caf5456c72b.png)

The titles in Example "Doppelmatrix" are overlapping.

![showroom_semdif_bsp](https://user-images.githubusercontent.com/28007144/64254877-8cd23400-cf20-11e9-85f1-6bb0c92e7bfe.png)

The item names are missing in Example "semantisches Differential".

![showroom_kalendarium_bsp1](https://user-images.githubusercontent.com/28007144/64254930-a83d3f00-cf20-11e9-801f-f06d943d2915.png)

You cannot fill out the "Kalendarium" as of right now and the options to change the color scheme are not working.

![showroom_kalendarium_bsp2](https://user-images.githubusercontent.com/28007144/64255024-d02ca280-cf20-11e9-83a3-c7180a1c6ffc.png)

The buttons and the text are not alligned in the last selection choice in "Kalendarium".



Generally all links have to be highlighted on all pages with links. The current problems apply for the mobile view as well but I still have to take a closer look at the mobile view.

**Comment by kastirke** [comment]
@dzhwmeisner & @vdick : Please go for the issues Arthur listet above.

**Comment by andreaschu** [comment]
there is a new issue for the showroom (#401) so this will be closed.
