### ISSUE TITLE
Double SC Matrix

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#21]
To Do:

- [x] Test Infrastructure
- [x] Formulate Test Cases
- [x] Write Unit Tests

Used Time : 2
Sprint 3 Used Time: 6 (et: 8)

**Comment by kastirke** [comment]
using iPhone SE, iOS 10.3.3, Safari

May you expand the underlying text space if the landscape format is used? One-line label would save vertical space...
![img_3958](https://user-images.githubusercontent.com/30147532/28664458-e096242a-72c0-11e7-8566-0d4312e43fa9.PNG)

**Comment by dzhwmeisner** [comment]
suppress  breaks in Labels on small screen done

**Comment by DusdalA** [comment]
I think the answer options should mirror each other. I would switch "in hohem Maße" and "in geringem Maße" and put the Option "weiß nicht" on the left side to the far left. 

![sc-doppemmatrix png_1](https://user-images.githubusercontent.com/28007144/28921786-9a7d85d6-7857-11e7-9772-de5f1cfb1d25.png)

**Comment by kastirke** [comment]
Thanks for the suggestion, but they should not mirror each other. @dzhwmeisner: Please do not change the structure of the question.

**Comment by kastirke** [comment]
using Desktop PC

Labels are double layered when screen is reduced:

![unbenannt](https://user-images.githubusercontent.com/30147532/29413541-02ea9ffe-835d-11e7-9852-5ddbfdaf59eb.png)

**Comment by Miktarbad** [comment]
![doubescmatrix-firefox-eingeklappt_1](https://user-images.githubusercontent.com/29864065/31214091-fe8d1004-a9a9-11e7-8600-7f7cdc46c6e3.jpg)
![doubescmatrix-firefox-eingeklappt_2-ohnetitles](https://user-images.githubusercontent.com/29864065/31214092-fe8d413c-a9a9-11e7-841c-ef26ca71bec7.jpg)
![doubescmatrix-firefox-eingeklappt_2-wenigerbreite](https://user-images.githubusercontent.com/29864065/31214093-fe8d71ac-a9a9-11e7-816e-6cd33042648a.jpg)


- titles missing in a certain width range
- same problem at #19

**Comment by kastirke** [comment]
👎 
checked "suppress breaks in Labels on small screen done"
Please use whole wide of the existing column.

![image-1](https://user-images.githubusercontent.com/30147532/31765448-afdcdf7c-b4c4-11e7-93fc-4d19b259eb75.jpg)

**Comment by kastirke** [comment]
Mac, OS X 10.9.5, Safari

Strange behavior while loading page.


![mac_4](https://user-images.githubusercontent.com/30147532/31880054-a9996072-b7df-11e7-88f7-e62d40357526.gif)

**Comment by dzhwmeisner** [comment]
[Strange behavior while loading page.] fixed

**Comment by kastirke** [comment]
[Strange behavior while loading page.]  checked 👍

**Comment by dzhwmeisner** [comment]
[ A ] not reproducible. please check  again.
[Labels are double layered when screen is reduced] no solution up to now

**Comment by Miktarbad** [comment]
[Labels are double layered when screen is reduced] is within the range of 775 to 1000px (Windows, Firefox Dev)

**Comment by dzhwmeisner** [comment]
[Labels are double layered when screen is reduced] fixed. testing needed

**Comment by dzhwmeisner** [comment]
[ A ] fixed. testing needed

**Comment by Miktarbad** [comment]
[ A ] no iphone testing available, seems fixed when reducing the browser to that width.

**Comment by Miktarbad** [comment]
no real device available, tested via emulator seems fixed.

Question Type seems to be finished for now - therefore closed.

**Comment by FineCordua** [comment]
![whatsapp image 2018-05-14 at 09 08 50](https://user-images.githubusercontent.com/27995239/39985985-9b6715a0-5760-11e8-95bb-69deae95b599.jpeg)
tested with android 8.0.0, google chrome and on Laptop (problems occur on small display only)
[B] itemtext contains white stripes in text
[C] itemtext only above left scale (in earlier versions it is above both scales)

**Comment by Miktarbad** [comment]
confirmed on Galaxy S7 - Chrome - Android 7
[B] aswell, but only visible on grey background - is not over the text
[C] same on this configuration
