### ISSUE TITLE
Zofar-Showroom: content

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#210]
There is a lot of blank pages in the showroom. Let's fill it with more descriptive content.

**Comment by kastirke** [comment]
...is in progress.

**Comment by andreaschu** [comment]
Texts are written for:
- [ ] Randomisierung
- [ ] Antwortvalidierung
- [ ] Fragebogensteuerung

the should be corrected.

**Comment by kastirke** [comment]
External URL: https://presentation.dzhw.eu/showroom

**Comment by kastirke** [comment]
@DusdalA: I checked your draft. Thank you very much. Let's feed the showroom.

- [ ] Get "Zofar Showroom" from SVN Repository

- [ ] Add the following text in the menu "Randomisation" (http://vmtest.dzhw.local:8080/showroom/randomisierung_start.html): 

Randomisierung

Im klassischen Sinne bedeutet Randomisierung die „zufällige Aufteilung der Teilnehmer auf verschiedene Gruppen“ (Opp 2010). Eine Randomisierung kann mit Zofar sowohl über Fragebogenabschnitte hinweg, als auch innerhalb von Fragen (also auf Itemebene) erfolgen, um die Reihenfolge dieser zu variieren und Fragekontexteffekten (Opp 2010, Weirich 2015) zu begegnen. Zusätzlich bietet Randomisierung die Möglichkeit, die Befragung zu modularisieren und Befragungsinhalte nur jeweils einem zufällig bestimmten Teil der Zielpersonen zu präsentieren. Insbesondere bei umfangreichen Fragebögen könnte dieses Vorgehen die Beteiligungsraten erhöhen.

Die Randomisierung kann mit jedem Seitenaufruf neu oder einmalig erfolgen. Ist letzteres der Fall, wird die erste zufällige Zuteilung gespeichert und die Fragen bei jedem Betreten der Fragebogenwebsite unverändert dargestellt.


- [ ] Add this literature and the end of the questionaire (http://vmtest.dzhw.local:8080/showroom/literaturverzeichnis_start.html): 

Opp, Karl-Dieter (2010): Kausalität als Gegenstand der Sozialwissenschaften und der multivariaten Statistik. In: Wolf, Christof; Best, Henning (Hrsg): Handbuch der sozialwissenschaftlichen Datenanalyse. Wiesbaden: VS Verlag für Sozialwissenschaften, pp. 9-38.

Weirich, Sebastian (2015):Kontexteffekte in Large-Scale Assessments. Dissertation. Humboldt-Universität zu Berlin


- [ ] Try to develop an appropriate illustrative example (see http://vmtest.dzhw.local:8080/showroom/fragetypen_offene_frage.html and http://vmtest.dzhw.local:8080/showroom/fragetypen_offene_frage_beispiel.html).

- [ ] Delete the page "Zufallsfunktion in SpEL"

---

If you have any questions, please let me know.

**Comment by SilinaSchirmer** [comment]
@andreaschu: Können wir dieses Issue schließen oder sollten wir es weiternutzen?

**Comment by andreaschu** [comment]
@SilinaSchirmer könntest Du noch schnell prüfen, ob die konkreten Änderungen von Kastirke übernommen sind und dann schließen?
