### ISSUE TITLE
Die Studierendenbefragung in Deutschland: programming first draft

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#213]

**Comment by andreaschu** [comment]
done for:
- [x] https://github.com/dzhw/SiD/blob/master/Modul-B1_Geschlecht.md
- [x] https://github.com/dzhw/SiD/blob/master/Modul-D2_Studiensituation.md

**Comment by SilinaKowalewski** [comment]
wuhuuu!
