### ISSUE TITLE
Die Studierendenbefragung in Deutschland:  creating a project

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#214]

**Comment by SilinaKowalewski** [comment]
Survey created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/sid
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/sid-Addon

Jenkins:
http://vmbuild.dzhw.local:8080/job/sid/

On presentation.dzhw.eu will be available after first build:
?

**Comment by vdick** [comment]
@andreaschu  
http://vmtest.dzhw.local:8080/sid/
https://presentation.dzhw.eu/sid/
