### ISSUE TITLE
Die Studierendenbefragung in Deutschland: response statistic

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#216]

**Comment by SilinaKowalewski** [comment]
- [ ] project should get access to cockpit

@dzhwmeisner: please create public cockpit

**Comment by dzhwmeisner** [comment]
http://vmdevwiki.dzhw.local/CockpitNeu/cockpitSIDPretest.jnlp
bzw.
http://vmzofarprod-store.dzhw.local:9090/rest-server/user/cockpit.html?id=473bedf6-b27d-470c-a376-03267799aa23
