### ISSUE TITLE
Student Life Cycle (SLC): going online

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#223]
- [ ]  load test
- [ ]   roll out
- [ ]   project should get access to cockpit (#228 )

**Comment by andreaschu** [comment]
@vdick kannst Du die korrigierte Version auf den Servern ausrollen?

**Comment by vdick** [comment]
@andreaschu wird gemacht, es kann aber etwas dauern, da zur Zeit recht viel auf den Server los ist
