### ISSUE TITLE
Student Life Cycle (SLC): creating a project

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#226]

**Comment by SilinaKowalewski** [comment]
**Create a project with the name:** 



Survey created:


Jenkins:


On presentation.dzhw.eu will be available after first build:

**Comment by SilinaKowalewski** [comment]
Please create porject with name: **SCL_IntEr**

**Comment by vdick** [comment]
Project created
SVN: https://vmvcs.dzhw.local/svn/hiob/tags/surveys/SCL_IntEr
Jenkins: http://vmbuild.dzhw.local:8080/job/SCL_IntEr/
Link: https://presentation.dzhw.eu/SCL_IntEr/  (available, after first build)

Addon
SVN: https://vmvcs.dzhw.local/svn/hiob/tags/surveys/SCL_IntEr-Addon
Jenkins: http://vmbuild.dzhw.local:8080/job/SCL_IntEr-Addon/
Link: https://presentation.dzhw.eu/SCL_IntEr-Addon/  (available, after first build)
