### ISSUE TITLE
Design: Radiobutton

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#23]
When selected, the button-point is not centered inside the button.

Ref:
#21 
#19 
#18 

Concerns:
- Firefox
- Chrome

Works:
- Edge
____
![radiobutton1](https://user-images.githubusercontent.com/29864065/28263338-a63d492a-6ae6-11e7-8958-e8136a71fea4.jpg)
![radiobutton2](https://user-images.githubusercontent.com/29864065/28263339-a63e1850-6ae6-11e7-8f7c-b427893482aa.jpg)
![radiobutton3](https://user-images.githubusercontent.com/29864065/28263340-a63fc8f8-6ae6-11e7-9aef-297ff9b79703.jpg)

**Comment by kastirke** [comment]
Radiobutton looks frayed.

![unbenannt](https://user-images.githubusercontent.com/30147532/28656830-553faaac-72a4-11e7-9a30-8acb48bee88b.PNG)

**Comment by Brochterbeck** [comment]
Former Style not reliable in all Browsers and Zoom-Scales
Unreliable Style Features deactivated

**Comment by kastirke** [comment]
👍 
Checked radiobutton. Solution rocks!

**Comment by Miktarbad** [comment]
Changes approved. Very good 👍

**Comment by andreaschu** [comment]
I like 👍

**Comment by Miktarbad** [comment]
Changes generally approved - Issue closed.
