### ISSUE TITLE
SPanel 18-2: data export bugs

### ISSUE THREAD

**Issue by heikQ** [dzhw/zofar#233]
In allen Variablen der exportierten Daten der Befragung SPanel 2018.2, die eigentlich Kommas enthalten, sind diese im export file nicht vorhanden [z.B. Variable abinote, dirzuw (Einkommen) und sämtliche string Variablen wie berufvat, berufmut). Die Kommas fehlen bereits in der csv. Datei die wir bekommen haben, es müsste also ein Export-Problem sein. Ohne die Kommas sind die betroffenen Variablen und daher auch der Datensatz für uns nicht nutzbar. Wir bitten daher um einen Export mit Kommas.

**Comment by SilinaKowalewski** [comment]
@mattenko: 
Könntest du bitte den Datensatz dieses Projekts "re-archivieren"?

**Comment by heikQ** [comment]
Wann können wir denn mit einem Datensatz rechnen, der alle Zeichen enthält?

**Comment by SilinaKowalewski** [comment]
@heikQ: 

Wir haben bereits einen neuen Export gezogen. In der Datenbank sind noch Kommata sowie Punkte drin. Es scheint also eher am Exporter oder am Einlesen der CSV zu liegen. 

Wir werden das noch weiter prüfen und dir innerhalb der nächsten Tage eine Rückmeldung geben.

**Comment by heikQ** [comment]
Vielen Dank für den Export, Kommas sind jetzt drin, scheint auch so alles fein zu sein.
