### ISSUE TITLE
As a Developer i want to replace Webstart for Zofar-Tools

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#234]
Reasons for the need to replace Webstart as Distribution-System are:

1. Webstart is deprecated
2. Clients needs a installed java
3. Execution of Tools are limited by the Resources of Client-System
4. Tools have to be signed by Certificate. In some cases this leads to conflicts with 
   used Frameworks

**Comment by dzhwmeisner** [comment]
implement Baseplattform

**Comment by dzhwmeisner** [comment]
Baseplattform implemented 
(SVN: https://vmvcs.dzhw.local/svn/hiob/trunk/ZofarSuite)
and rolled out to 
http://vmzofarprod-store.dzhw.local:9090/rest-server

Need to be tested

**Comment by vdick** [comment]
test completed successfully

**Comment by vdick** [comment]
and now please test the first draft of a angular project. You'll find a zip-file in src/main/ (a zip because its too big to commit to svn).
after deployment on docker open this link: http://localhost:9090/rest-server/zofar-service/index.html

**Comment by dzhwmeisner** [comment]
Let's change default language to 'de'. Review successful. Rollout to http://vmzofarprod-store.dzhw.local without problems.
