### ISSUE TITLE
Webstart replacement: add Cockpit logic to backend

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#235]

**Comment by dzhwmeisner** [comment]
implemented and deployed to 
http://vmzofarprod-store.dzhw.local:9090/rest-server/user/cockpit.html?id=93a0b087-cadb-4d29-8972-4c909b46aff4

need to be reviewed

**Comment by vdick** [comment]
reviewed successful

**Comment by andreaschu** [comment]
@vdick how can I test it? Do I need access for the link above?

**Comment by andreaschu** [comment]
Could there be made some changes?
- [ ] rename "participated" to "unfinished"
- [ ] create a new line 'participated'= Sum['finished','unfinished']

**Comment by dzhwmeisner** [comment]
Request for Testing. 
Please compare 
http://vmzofarprod-store.dzhw.local:9090/rest-server/user/cockpit.html?id=a618a515-24e8-4690-9a4c-274e570249ba

with
vmdevwiki.dzhw.local/CockpitNeu/cockpitAbs20093tb3.jnlp

**Comment by dzhwmeisner** [comment]
Configuration for SLC for testing

Exporter
http://vmzofarprod-store.dzhw.local:9090/rest-server/user/exporter.html?id=091caf28-5fa2-4a84-ae10-92f65010f0be

http://vmdevwiki.dzhw.local/Exporter/neu/debug/exporterSLC_IntEr.jnlp

**Comment by andreaschu** [comment]
to make it more overseeable, it would be helpful to:

- [ ] change the date format to _dd.mm.yyyy, hh:mm:ss (MEZ)_
- [ ] delete the second line (_configuration : Server : vmzofar-db2.dzhw.local:5432 Database : prod_slc_inter_)
- [ ] add the project as header (e. g. _slc_inter_)
- [ ] delete the id-line (id : 091caf28-5fa2-4a84-ae10-92f65010f0be)
- [ ] delete the timestamp (only keep _timestampOfRequest_  and _exitTimestamp_ but rename it to _Timestamp_) 
- [ ] change the format to more like the screenshot below (and use the numbers also for the legend)


![grafik](https://user-images.githubusercontent.com/30111489/73347937-c6695a00-4288-11ea-92c9-26e3e781a742.png)

![grafik](https://user-images.githubusercontent.com/30111489/73348171-3677e000-4289-11ea-88dc-495c096ed589.png)
