### ISSUE TITLE
Add Exporter to Webstart-Replacement

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#236]

**Comment by dzhwmeisner** [comment]
integrated to http://vmzofarprod-store.dzhw.local:9090/rest-server/user/exporter.html?id=<CONFIGID>

retrieve test <CONFIGID> from http://vmzofarprod-store.dzhw.local:9090/rest-server/config/all

**Comment by vdick** [comment]
test completed successfully
