### ISSUE TITLE
Abs. 2009.3 TB-3: creating a project

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#237]

**Comment by thorsteneuler** [comment]
Da ich in die Card mit den Datumangaben nicht reinkomme, hier die restlichen Daten:

Geplanter Feldstart 02.10.19
1. Erinnerung (Email) 17.10.19
2. Erinnerung (Email) 30.10.19
3. Erinnerung (Email) 14.11.19

Feldende 2.12.19
