### ISSUE TITLE
Abs. 2009.3 TB-3: programming first draft

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#238]

**Comment by thorsteneuler** [comment]
Hier die Programmiervorlage für die TB3. Die Seiten 201-2017, 301-317, 401-417, 501-517, 601-617 und 701-717 sind Schleifen zur Erfassung von Kindern und im Aufbau gleich. Die Seiten 8** entstammen der dritten Teilbefragung von Abs2013.2.

[Abs2009.3_PV_TB3_010.docx](https://github.com/dzhw/zofar/files/3593942/Abs2009.3_PV_TB3_010.docx)

**Comment by thorsteneuler** [comment]
Hier noch das Zusatzmaterial, auf dass in der PV verwiesen wird.
[Fragebogen_VFB_2005_3_Auszug.pdf](https://github.com/dzhw/zofar/files/3593944/Fragebogen_VFB_2005_3_Auszug.pdf)
![Abs2013_2_tb3_p402b](https://user-images.githubusercontent.com/52777773/64588456-c1bc0c00-d3a2-11e9-9810-d7f1b61832b7.jpg)

**Comment by thorsteneuler** [comment]
Und noch das Pfaddiagramm:
[Pfaddiagramm_Abs20093_TB3_003.pdf](https://github.com/dzhw/zofar/files/3594188/Pfaddiagramm_Abs20093_TB3_003.pdf)

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: 

Leider fehlen die Variablennamen für die Frage **p216**. 
Bitte nennt uns die Namen für die Variablen der Items **it1-it8**.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Sorry, das ist uns offenbar durchgerutscht. Hier die fehlenden PV-Variablennamen. Für die Seiten p316-p716 erhöht sich die Zahl nach dem "kk" jeweils um 1 fürs nächste Kind.

**p216:**
vn: v93kk1ein (v93kk1einpart, v93kk1einverwa, v93kk1einfreun, v93kk1einkita, v93kk1einfirma, v93kk1einteilz, v93kk1einflex, v93kk1einsons, v93kk1einsosx [string])
qt: Einfachauswahlmatrix mit horizontalen ao und offener Angabe
hl: 
in: 
q: Und inwieweit haben Ihnen die folgenden Aspekte die Rückkehr in Erwerbstätigkeit erleichtert?
is: 
it1: (v93kk1einpart): Unterstützung durch die Partnerin/den Partner
it2: (v93kk1einverwa): Hilfe durch Verwandte
it3: (v93kk1einfreun): Hilfe durch Freunde
it4: (v93kk1einkita): Betreuung durch Krippen, Kindertagesstätten, Tagesmütter/-väter
it5: (v93kk1einfirma): Unterstützung durch das Unternehmen/den Betrieb
it6: (v93kk1einteilz): Ermöglichung von Teilzeitarbeit durch den Arbeitgeber
it7: (v93kk1einflex): Ermöglichung von flexiblen Arbeitszeiten durch den Arbeitgeber
it8: (v93kk1einsons): Andere Gründe: (v93kk1einsosx)[string]

**Comment by SilinaKowalewski** [comment]
@thorsteneuler: Danke! :)

**Comment by andreaschu** [comment]
> @SilinaKowalewski please asure that following paradata will be captured:

@SilinaKowalewski sorry! The code is (on index-page):

		<zofar:triggers>
			<zofar:variable variable="url" value="zofar.baseUrl()" />
			<zofar:jsCheck variable="jsCheck" xvar="width" yvar="height" />
			<zofar:variable variable="isMobile" value="zofar.isMobile()" />
			<zofar:variable variable="startPoint" value="zofar.getTimeStamp()" />
			<zofar:variable variable="uas" value="zofar.userAgent()" />
		</zofar:triggers>

**Comment by SilinaKowalewski** [comment]
Die Seiten index-p218 sind nun in einer ersten Version programmiert und können getestet werden.

**Comment by andreaschu** [comment]
@SilinaKowalewski: regarding comment in issue #240

> Im Browserheader/-titel bitte "Absolventen 2009.3 Vereinbarkeit Beruf, Freizeit und Familie" anzeigen.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Bevor die Frage kommt, hier noch die Zuordnung it zu Variablennamen bei p920, p921 und p922 ;-)

**p920:**
it1: v93sasbteiln: Ich werde viel zu oft darum gebeten, an Umfragen teilzunehmen.
it2: v93sasbpriv: Ich empfinde Umfragen als einen Eingriff in meine Privatsphäre.
it3: v93sasbanst: Ich finde es anstrengend, bei einer Befragung viele Fragen zu beantworten.

**p921:**
it1: v93sasvgesell : Ich bin der Meinung, dass Umfragen für die Gesellschaft wichtig sind.
it2: v93sasverke : Ich finde, aus Umfragen können wichtige Erkenntnisse gewonnen werden.
it3: v93sasvzeit : Meiner Meinung nach ist die Teilnahme an Umfragen Zeitverschwendung.

**p922:**
it1: v93sasesant : Es macht mir Spaß, Fragebögen zu beantworten, die per Post oder Internet zugeschickt werden.
it2: v93saseintv : Es macht mir Spaß für Umfragen interviewt zu werden.
it3: v93saseansi : Ich finde Umfragen an sich interessant.
