### ISSUE TITLE
MultipleChoice Question

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#24]
To Do:

dev:
- [x] code review
- [x] renderer implement
- [x] generate html code
- [ ] debugging

testing:
- [ ]     Test Infrastructure
- [ ]     Formulate Test Cases
- [ ]     Write Unit Tests

Sprint 3 Used Time: 3

**Comment by andreaschu** [comment]
[A] check mark is not centered in checkbox on Fairphone (Android)

it looks perfect on desktop in super small 👍

Fairphone:
![as_fp android_page7_mc_20171020](https://user-images.githubusercontent.com/30111489/31823547-bb88f94e-b5ac-11e7-804c-f7605f6e3ebb.png)
Desktop (Windows, Firefox, supersmall)
![as_firefox_desktop_page7_mc_supersmall_20171020](https://user-images.githubusercontent.com/30111489/31823579-cd2ce7b4-b5ac-11e7-88bf-56a28260b715.PNG)

**Comment by kastirke** [comment]
checked with iPhone SE, iOS 11.0.2; Safari 👍

**Comment by Miktarbad** [comment]
[ B ] mouseover works on every aopen now - fixed

**Comment by Miktarbad** [comment]
[ A ] explained by old hard-/software

tested and approved - closed.
