### ISSUE TITLE
Abs. 2009.3 TB-3: going online

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#240]

**Comment by thorsteneuler** [comment]
Für die Erhebung benötigen wir 5100 Token (zur Vermeidung von Überschneidungen mit den TB2-Token) mit folgendem Aufbau:

Präfix "B9", danach fünf Buchstaben/Ziffern, alles in Großbuchstaben z.B. B9A1B2C

Bitte die Liste als xls oder csv von 2M auf den gwinter in "daten/absolventen/abs2009/2009-3_Dritte_Teilbefragung" transferieren lassen.

**Comment by andreaschu** [comment]
@thorsteneuler wie soll der Name der Befragung für den Link lauten?

**Comment by thorsteneuler** [comment]
@andreaschu 

Für den Link (um ihn von der parallel laufenden TB2 zu unterscheiden): http://survey02.dzhw.eu/abs2009vfb/

Im Browserheader/-titel bitte  "Absolventen 2009.3 Vereinbarkeit Beruf, Freizeit und Familie" anzeigen.

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Ich habe meine Beispielfälle für die Filterführung noch einmal durchgeschaut und nach unseren gestrigen Änderungen sieht alles nun grün aus. Das Einzige, dass ich noch gefunden habe ist die Transition von p211 auf p213, vermutlich wegen der Abprüfung einer Mehrfachnennungsauswahl.

Das Ganze müsste auf p211 lauten (in der ersten tr-Zeile): 
GOTO p213 IF v93k1ezpeu=1 bzw. GOTO p213 IF v93k1ezpeu.value

**Comment by SilinaKowalewski** [comment]
@thorsteneuler 

Habe auf der p211 jeweils v93k1ezpeu==1 in v93k1ezpeu.value geändert. Sollte nun also funktionieren 👍

**Comment by thorsteneuler** [comment]
Ich gehe davon aus, dass wir die Fehlerkorrekturen bis Ende der Woche noch hinbekommen. Könnte ich dann am 30.9. einen Datacheck-Datensatz erhalten, um diesen noch final zu überprüfen?

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner: 

Könntest du am 30.09. einen Datacheck erstellen?

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Hier die noch fehlende Add-On-PV (alles wie bei TB2, nur die Variablen heißen jetzt ***_tb3_***)

[Abs2009.3_AddOn_PV_TB3_001.docx](https://github.com/dzhw/zofar/files/3669658/Abs2009.3_AddOn_PV_TB3_001.docx)

**Comment by thorsteneuler** [comment]
Da Hanna Kern nicht mehr im Projekt arbeitet, würde ich euch bitten die Rücklaufstatistiken wieder an mich zu senden.

**Comment by SilinaKowalewski** [comment]
Hier nun der "Export" des Datechecks. 

[output.zip](https://github.com/dzhw/zofar/files/3671673/output.zip)

**Comment by SilinaKowalewski** [comment]
> 
> Für den Link (um ihn von der parallel laufenden TB2 zu unterscheiden): […/abs2009vfb/](%E2%80%A6/abs2009vfb/)
> 
> Im Browserheader/-titel bitte "Absolventen 2009.3 Vereinbarkeit Beruf, Freizeit und Familie" anzeigen.

@vdick @dzhwmeisner: 

Bitte denkt beim finalen Ausrollen daran, dass der Link zur Befragung wie folgt lauten soll: 
http://survey02.dzhw.eu/abs2009vfb/...

**Comment by thorsteneuler** [comment]
> 
> 
> Hier nun der "Export" des Datechecks.
> 
> [output.zip](https://github.com/dzhw/zofar/files/3671673/output.zip)

Für die zukünftigen Weiterentwicklungen von Zofar in den nächsten Jahren würde ich die Entwicklung eines echten Datensimulator für den datacheck befürworten. Falls mal Ideen für sowas auf den Tisch kommen sollten ;-)

**Comment by dzhwmeisner** [comment]
[addon_2019_12_57_01_output.zip](https://github.com/dzhw/zofar/files/3676270/addon_2019_12_57_01_output.zip)

Datencheck der Addon

**Comment by thorsteneuler** [comment]
@SilinaKowalewski 

Danke für die Files, habe alles (QML und datacheck_addon) durchgeschaut (nichts mehr gefunden) und auch die Variablenkennungen aller Variablen überprüft. 

Von Projektseite her ist das Instrument (Befragung und Add-On-Befragung) freigegeben und kann produktiv ausgerollt werden. 
Bitte gebt uns Bescheid wenn dies geschehen ist, dann würden wir noch einmal den echten Link mit realen Befragtentoken testen und euch Bescheid geben (bis morgen spätestens 12 Uhr), die Datenbank vor dem Versand der Einladung morgen noch einmal zu leeren und die Einladungen dann rauszuschicken.

**Comment by SilinaKowalewski** [comment]
> @SilinaKowalewski
> 
> Danke für die Files, habe alles (QML und datacheck_addon) durchgeschaut (nichts mehr gefunden) und auch die Variablenkennungen aller Variablen überprüft.
> 
> Von Projektseite her ist das Instrument (Befragung und Add-On-Befragung) freigegeben und kann produktiv ausgerollt werden.
> Bitte gebt uns Bescheid wenn dies geschehen ist, dann würden wir noch einmal den echten Link mit realen Befragtentoken testen und euch Bescheid geben (bis morgen spätestens 12 Uhr), die Datenbank vor dem Versand der Einladung morgen noch einmal zu leeren und die Einladungen dann rauszuschicken.

@vdick

**Comment by SilinaKowalewski** [comment]
Die Befragung ist produktiv ausgerollt und der Mail-Versand abgeschlossen.
