### ISSUE TITLE
Abs. 2009.3 TB-3: Invitation

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#242]

**Comment by thorsteneuler** [comment]
Hier der Text für die Einladung zur Befragung. Die Excelliste für die gelb hinterlegten Serienbrieffelder wird noch transferiert.
[1_Einladung_E-Mail_M3_TB3_008.docx](https://github.com/dzhw/zofar/files/3669439/1_Einladung_E-Mail_M3_TB3_008.docx)

**Comment by SilinaKowalewski** [comment]
Der Mail-Versand ist abgeschlossen.

Es wurden 4.731 Mails verschickt. Eine Mail wurde vom Programm als "ungültig" erkannt. Welche Adresse dies konkret war, ist leider nicht erkennbar.
