### ISSUE TITLE
Abs. 2009.3 TB-3: screenshots

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#246]

**Comment by vdick** [comment]
[absolventen20093m3-addon_screenshots.zip](https://github.com/dzhw/zofar/files/3739172/absolventen20093m3-addon_screenshots.zip)

http://vmdevwiki.dzhw.local/transfer/abs20093tb3_screenshots.zip

**Comment by andreaschu** [comment]
@thorsteneuler see screenshots above for download.
