### ISSUE TITLE
Abs. 2009.3 TB-3: export of data

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#247]

**Comment by thorsteneuler** [comment]
Befragung kann heute aus dem Feld genommen werden und der Datenexport wie immer erfolgen.

**Comment by thorsteneuler** [comment]
@andreaschu 

Danke für die Daten. Denkt ihr bitte noch daran, uns den Export der Add-On (mit unseren B9****-token) auf den gwinter transferieren zu lassen?
