### ISSUE TITLE
Test Carousel with automatic forwarding

### ISSUE THREAD

**Issue by kastirke** [dzhw/zofar#249]
Carousel with automatic forwarding developed. #38 
Should be tested in a survey (if technically possible against conventional matrix, too).

**Comment by thorsteneuler** [comment]
@andreaschu 
Generally, I think it would be feasible to test it with the third partial survey of absolventen 2009-3.

I'm only hesitant to apply the test to the whole survey and would be happier if we could select a single question for it. Is your focus on its performance in general or do you plan specific tests that would require a minimum size of the sample answering the question. Provided that they use a mobile device.

**Comment by andreaschu** [comment]
@thorsteneuler the idea Nadin and I had, was to test a single page/ question only with respondents who has no children and won't be lead into the children-loops. The test then could be made with a new question that is not part of the questionnaire yet. 

It would be great if we could test a grid vs. an alternative version. The main aim is getting an idea if the _automatic forward_ works. Nevertheless it would be great if we have enough responses for more elaborated analysis.

**Comment by andreaschu** [comment]
@dzhwmeisner could you please check if we are able to deactivate the responsibility/ carousel for only one single choice matrix in this questionnaire?

**Comment by dzhwmeisner** [comment]
Implemented for SingleChoice Matrix Questions. Need to be tested at http://vmzofar-pres.his.de:8080/devhtml5/page4.html

**Comment by kastirke** [comment]
I like it, but word length may cause trouble.

![grafik](https://user-images.githubusercontent.com/30147532/65498344-03c57180-debc-11e9-8539-9d0361c7c36c.png)

For the planned test (#250) I will reformulate the items so they will contain shorter words.

**Comment by kastirke** [comment]
@dzhwmeisner Thanks. We will use this matrix design to test it against the new version with automatic forwarding.

**Comment by kastirke** [comment]
Testplan. Carousel wurde bei ATS items eingesetzt.
![grafik](https://user-images.githubusercontent.com/30147532/72727301-da2b0700-3b8a-11ea-8d7d-93c9585750f8.png)
