### ISSUE TITLE
MultipleChoice Matrix

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#25]
To Do:

dev:
- [x] code review
- [x] renderer implement
- [x] generate html code
- [ ] debugging

testing:
- [ ]     Test Infrastructure
- [ ]     Formulate Test Cases
- [ ]     Write Unit Tests

**Comment by FineCordua** [comment]
![fc_chrome_nomus10_multiplechoicematrix](https://user-images.githubusercontent.com/27995239/29962176-89a1bf54-8f02-11e7-9a57-5bb90e193359.png)

- display is a mess

**Comment by kastirke** [comment]
[A] answer option overlay instruction when browser window is collapsed

![grafik](https://user-images.githubusercontent.com/30147532/32280460-39ee0216-bf1c-11e7-9dc2-ff4da66c77ea.png)

**Comment by kastirke** [comment]
checked with iPhone SE, iOS 11.0.2; Safari 👍

**Comment by andreaschu** [comment]
checked with Windows, Firefox, Desktop 👍

**Comment by andreaschu** [comment]
[A] checked with Windows, Firefox, Desktop -> the same as reported above 👎

**Comment by vdick** [comment]
[A]please check again

**Comment by Miktarbad** [comment]
[ A ] fixed - tested on Firefox, Chrome, Edge

**Comment by Miktarbad** [comment]
all bugs fixed and approved - closed.
