### ISSUE TITLE
Webstart replacement: create frontend for Cockpit

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#254]

**Comment by dzhwmeisner** [comment]
Add legend

**Comment by SilinaKowalewski** [comment]
- ***1***  (Teilnehmende - finished + participants)
Personen, die wenigstens die erste Seite der Befragung   gesehen haben
- ***2*** (finished)
Personen, die die letzte Seite der Befragung gesehen   haben
- ***3*** (participants)
Personen, die noch nicht die letzte Seite der   Befragung gesehen haben
- ***4*** (exit pages)
Teilnehmende, die nicht gerade in die Befragung   eingeloggt sind oder waren (siehe abweichender Timestamp)

> (- ***0*** 
> Personen, die von uns eingeladen wurden, an der   Befragung teilzunehmen (Bruttostichprobe inkl. Noncontacts))

Wird diese Info überhaupt im Cockpit ausgegeben?

**Comment by andreaschu** [comment]
some little corrections to the legend (see above): 

- I added the headline 
-  I deleted the numbers. I guess the numbers are not in the response statistic, so it would be confusing to put it in the legend.
- some text changes
- I adapted the categories to the new version (see #235) 

> 
> rename "participated" to "unfinished"
> create a new line 'participated'= Sum['finished','unfinished']

-----------------------------------------------------------------
_Legende_ 
***participants***  (Teilnehmende= finished + unfinished)
Personen, die wenigstens die erste Seite der Befragung gesehen haben
***finished*** 
Personen, die die letzte Seite der Befragung gesehen haben
***unfinished*** 
Personen, die noch nicht die letzte Seite der Befragung gesehen haben
***exit pages***
vorläufige Ausstiegsseite der Teilnehmenden, die nicht gerade in die Befragung eingeloggt sind oder waren (siehe abweichender Timestamp)

**Comment by dzhwmeisner** [comment]
legend added

**Comment by andreaschu** [comment]
@vdick there is a lot of white space for the legend here that is not needed (see red line). Could the feedback part (blue line) get more space instead?

![grafik](https://user-images.githubusercontent.com/30111489/75163590-cb9eb500-571f-11ea-83fc-90af42a5985b.png)

**Comment by andreaschu** [comment]
Since the function of additional variables does not work yet, could the space and the labels for that, be excluded? 

![grafik](https://user-images.githubusercontent.com/30111489/75342223-41c52800-5896-11ea-9532-88c218d62959.png)

**Comment by vdick** [comment]
ready to test

**Comment by christian-fr** [comment]
http://vmzofarprod-store.dzhw.local:9090/rest-server/
