### ISSUE TITLE
Webstart replacement: add Exporter logic to backend

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#255]

**Comment by dzhwmeisner** [comment]
Request for testing.
Compare Content of resulting Archives of
http://vmdevwiki.dzhw.local/Exporter/neu/debug/exporterAbs20093tb3.jnlp
and
http://vmzofarprod-store.dzhw.local:9090/rest-server/user/exporter.html?id=a618a515-24e8-4690-9a4c-274e570249ba

**Comment by christian-fr** [comment]
error occured in SID
needs to be checked

**Comment by andreaschu** [comment]
Configuration for SLC for testing

Exporter
http://vmzofarprod-store.dzhw.local:9090/rest-server/user/exporter.html?id=091caf28-5fa2-4a84-ae10-92f65010f0be

http://vmdevwiki.dzhw.local/Exporter/neu/debug/exporterSLC_IntEr.jnlp

**Comment by andreaschu** [comment]
I only get codebook, Doc, instruction and navigation even when I want to get the whole package with the data.

**Comment by andreaschu** [comment]
the data codes checkboxes as true/false instead of 1/0. Could this be corrected?

**Comment by andreaschu** [comment]
data base problem seems to be resolved. 
For other remarks a new issue is opened (#382)
