### ISSUE TITLE
Webstart replacement: add Feedback logic to backend

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#260]

**Comment by dzhwmeisner** [comment]
Add custom Variables to Cockpit logic. (already in Configuration)

**Comment by dzhwmeisner** [comment]
Implemented (Example : http://vmzofarprod-store.dzhw.local:9090/rest-server/user/cockpit.html?id=3fece858-837c-4b37-a8f4-36c7b11cfd29) Request for testing
