### ISSUE TITLE
Webstart Replacement: Updating automated project creation process

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#263]
As a Developer i want to generate Configurations  for Exporter and Cockpit while automated process of project creation

**Comment by dzhwmeisner** [comment]
- [ ] optional add REST-interface in Webstart-Replacement to add configurations or add directly to
      MongoDB
- [ ] create configuration according to to new Project
- [ ] field testing

**Comment by vdick** [comment]
look at #342
