### ISSUE TITLE
Exma - Masterbefragung: creating a project

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#264]
Create a project in svn

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner oder @vdick: 

Please create a project with the name "**_ExMa_**"

**Comment by vdick** [comment]
Project created:
http://vmvcs.dzhw.local/svn/hiob/tags/surveys/ExMa-2019
http://vmbuild.dzhw.local:8080/job/ExMa-2019/
http://vmtest.dzhw.local:8080/ExMa-2019 (available after first build)
http://presentation.dzhw.eu/ExMa-2019 (available after first build)

Addon
Project created:
http://vmvcs.dzhw.local/svn/hiob/tags/surveys/ExMa-2019-Addon
http://vmbuild.dzhw.local:8080/job/ExMa-2019-Addon/
http://vmtest.dzhw.local:8080/ExMa-2019-Addon (available after first build)
http://presentation.dzhw.eu/ExMa-2019-Addon (available after first build)

**Comment by SilinaKowalewski** [comment]
@SoerenIsleib: 

Unter folgendem Link kannst du zukünftig die Befragung test. Dies gilt sowohl für die Browser-Ansicht, als auch für das responsive Design. 

http://presentation.dzhw.eu/ExMa-2019

**Comment by SoerenIsleib** [comment]
Ergänzend zur eben übermittelten neuen Version des Fragebogens: Für alle 5er und 7er Skalen sollen die Values aus den Labeln gelöscht werden (nur noch Pole benennen mit bspw. "trifft voll zu" und "trifft überhaupt nicht zu" oder Ähnlichem, aber keine Zahlen mehr an die einzelnen Skalenstufen). Das betrifft folgende pages:
1001
2103
2207
2208 (alle)
2210
2212
2303
2304
2308
2309
2310
2312
2313
2314
2315
2316
2317
2401
2402
2504
5201
5303
5305 (alle)
5307
5309
6109 (war bislang 6108)
