### ISSUE TITLE
Exma - Masterbefragung: going online

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#267]

**Comment by SilinaKowalewski** [comment]
@vdick @dzhwmeisner: 
Bitte zunächst eine Landingpage erstellen, falls einige Links schon getestet werden bevor die Befragung online ist. 

Text: **Hier startet am 07.01.2020 die Masterbefragung.**

**Comment by vdick** [comment]
@SilinaKowalewski  erledigt, bitte kurz testen
