### ISSUE TITLE
Exma - Masterbefragung: response statistic and feedback

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#268]

**Comment by andreaschu** [comment]
@vdick könntest Du die Variable _**hsma**_ in die Rücklaufstatistik integrieren? (Am besten für das neue und das alte Cockpit zum Testen)

**Comment by vdick** [comment]
@andreaschu in der "alten" Version habe ich es angepasst, in der  "neuen" Version werden die Variablen noch nicht berücksichtigt. Sofern deinerseits nichts gegen spricht, erstelle ich ein neues Issue, das die Aufgabe erfasst und fange direkt mit der Umsetzung an.

**Comment by andreaschu** [comment]
@vdick danke. Dann reicht das. Ein Issue kannst Du erstellen, aber noch nicht umsetzen. Das machen wir im Planning für den nächsten Sprint.

**Comment by SoerenIsleib** [comment]
Liebe Kolleg*innen,
könnte ich relativ akut nochmal aktuelle Rücklaufzahlen haben? Ich hatte die letzte Woche für gestern angefragt, aber noch nichts gehört, da Uli diese gleich im Jahresarbeitsgespräch berichten würde.

Dank und Gruß
Sören
