### ISSUE TITLE
SPanel 18-2: Fehlerhafte Erhebung Variablenwerte. Frage unbrauchbar

### ISSUE THREAD

**Issue by heikQ** [dzhw/zofar#276]
Im Studienberechtigenpanel 2018.2 haben wir eine Variable "wbereich" mit 6 Kategorien erhoben. Es zeigt sich nun im Datensatz, dass die Kategorie 6 überhaupt nicht besetzt ist, wogegen sie bei den schriftlich-befragten Probanden gut besetzt ist. Laut eurem Codebook-Export, dass wir erst im Februar nach der Erhebung erhalten haben, wurden die Kategorien 5 und 6 beide mit dem Wert 5 erhoben, was in Pretests für uns natürlich nicht ersichtlich war. Könnt ihr das bitte prüfen? Dann wäre diese Frage völlig unbrauchbar für uns und wir können sie eigentlich löschen, da inhatlich völlig verschiedene Kategorien mit dem gleichen Variablenwert erhoben wurden. Zukünftig wäre zu überlegen, wie sowas im Rahmen von Qualitätssicherung vermieden werden kann, denn das können die Projekte gar nicht testen und müssen sich darauf verlassen können, dass die Werte in der Datenbank stimmen. Sehr ärgerlich.

**Comment by andreaschu** [comment]
Das kann man leicht reparieren. Wir müssen dafür nur einen neuen Export machen.
Aber das wird frühestens nächste Woche etwas, mglw. noch später.

**Comment by andreaschu** [comment]
- [ ] @mattenko kannst Du die Befragung (Panel18.2) noch mal aus dem Archiv holen?
- [ ] @dzhwmeisner oder @vdick kann einer von Euch das xml korrigieren (values von wbereich) und den Export neu ziehen?

**Comment by mattenko** [comment]
Panel18.2 is restored and on db1/present

**Comment by heikQ** [comment]
So vor gut vier Wochen sollten wir den reparierten Datensatz bekommen. Passiert da noch was? Ist blöd ohne Datensatz.

**Comment by andreaschu** [comment]
die Variable "wbereich" gibt es nicht im Datensatz. Welche genau soll korrigiert werden?

**Comment by heikQ** [comment]
joa, sollte wbereich heißen gemäß unserer variablen-Liste, laut eurem codebook wurde bwbereich, draus nehmen wir also bwbereich, ist die gleiche

**Comment by heikQ** [comment]
@andreaschu ist zwar jetzt fast 2 Monate her, aber bekommen wir den Datensatz mit der korrigierten Variable noch? Wir könnten ihn ziemlich dringend brauchen

**Comment by heikQ** [comment]
hallo?

**Comment by heikQ** [comment]
![grafik](https://user-images.githubusercontent.com/52539440/71080973-85146380-218e-11ea-837f-cf06f6cfcc94.png)
