### ISSUE TITLE
Promopanel-w6: creating a project

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#278]

**Comment by vdick** [comment]
Projects created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Promopanel-w6
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Promopanel-w6-addon
Testserver (after first build):
http://vmtest.dzhw.local:8080/Promopanel-w6
http://vmtest.dzhw.local:8080/Promopanel-w6-addon
Presentation(after first build):
http://presentation.dzhw.eu/Promopanel-w6
http://presentation.dzhw.eu/Promopanel-w6-addon

**Comment by SilinaKowalewski** [comment]
Projekt wurde erstellt und ausgerollt.
