### ISSUE TITLE
Promopanel-w6: programming first draft

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#279]

**Comment by SilinaKowalewski** [comment]
Programmiervorlage vom 05.12. per Mail

[Fragebogen_W6_v8.docx](https://github.com/dzhw/zofar/files/3983205/Fragebogen_W6_v8.docx)
[Flowchart_W6_v4.pptx](https://github.com/dzhw/zofar/files/3983206/Flowchart_W6_v4.pptx)

**Comment by vdick** [comment]
Die Befragung ist ab sofort auf dem Testserver verfügbar
(http://vmtest.dzhw.local:8080/Promopanel-w6/)
Testertoken 1-500 sind angelegt. Das CSS scheint soweit in Ordnung zu sein.

**Comment by SilinaKowalewski** [comment]
FirstDraft erledigt und zum Testen auf http://vmtest.dzhw.local:8080/Promopanel-w6 ausgerollt.

**Comment by andreaschu** [comment]
Update: 
[Fragebogen_W6_v10.docx](https://github.com/dzhw/zofar/files/4086443/Fragebogen_W6_v10.docx)

**Comment by andreaschu** [comment]
@vdick please import the testtoken in database (see docs-folder)

**Comment by vdick** [comment]
erledigt

**Comment by SilinaKowalewski** [comment]
survey is updated and testtoken were insert in database.
