### ISSUE TITLE
Promopanel-w6: testing and correcting

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#280]

**Comment by andreaschu** [comment]
@vdick

**Comment by vdick** [comment]
fixed, ab nächsten Rollout verfügbar

**Comment by GescheBrandt** [comment]
Liebes Zofarteam, hier einige Änderungswünsche nach der ersten Testrunde:

- [ ] page 5a-5e: Die Spaltenbreiten im Kalendarium sollen vereinheitlicht werden
- [ ] page 5a-5e: Kann die Höhe der Kategorien im Kalendarium vereinheitlicht werden, oder hängt die Darstellung vom Bildschirm ab? (Hängt irgendwie auch vom tester ab, bei tester 3 sieht es besser aus als bei tester 2)
- [ ] page 7-16: das offene Feld für Land (Variable c6taet*land) größer machen, gleiche Größe wie für Ortsangabe. 
- [ ] page 25: Die Einblendung ist nicht korrekt wenn c6akerwerb!=2. Text bitte an die Vorlage anpassen.
- [ ] page 26: Abstand zwischen den beiden Fragen vergrößern.
- [ ] page 44: Punkte am Ende der Items löschen
- [ ] page 50: Abstand zwischen Antworten zur ersten Frage und Fragetext der zweiten Frage vergrößern
- [ ] page 57: Items und Variablenbezeichnungen bitte ändern wie folgt:
[0/1] Sommersemester 2019 [w6lehre1]  : _ _ [w6lehresose19]    
[0/1] Wintersemester 2019/2020 [w6lehre2]  : _ _ [w6lehrewise19]   
[0/1] Nein  [w6lehre]
- [ ] page 71a: Zeilenabstand vergrößern (habt ihr wahrscheinlich schon gemacht, s.o.)
- [ ] page 71c, Frage 5.5: Skalenbeschriftung der 1 muss "überhaupt nicht" heißen (das Wort "leicht" streichen)
- [ ] page 71d: Items farblich alternieren
- [ ] page 71d: Zahlenwerte über der Skala entfernen
- [ ] page 71d: Skalenpunkt 3 mit "weiß nicht" beschriften (statt "Weiß ich nicht") ja und nein bitte jeweils Kleinschreibung

**Comment by GescheBrandt** [comment]
Wir würden gerne ein kleines Methodenexperiment auf page 71b einbauen. Aktuell ist die Skalenrichtung von "1=sehr interessiert" bis "5=überhaupt nicht interessiert". Wir würden gerne die Hälfte der Befragten mit einer umgedrehten Skala, also 1="überhaupt nicht interessiert" bis 5="sehr interessiert" befragen. Wie könnte das umgesetzt werden? Verschiedene pages oder verschiedene Einblendungen? Wie würde die Zuteilung der Befragten zu den Gruppen erfolgen?

**Comment by andreaschu** [comment]
> Wir würden gerne ein kleines Methodenexperiment auf page 71b einbauen. […]

das könnte sowohl mit Einblendungen auf derselben Seite erfolgen als auch mit verschiedenen Seiten und Weiterleitungen. Unterscheidet sich im Aufwand nicht und im Ergebnis im Datensatz auch nicht. Das einzige, was dann unterschiedlich ist, ist der Screenshot.

Die Zuteilung könnte per Zufall erfolgen, z.B. durch eine Hilfsvariable mit einer Zufallszahl mit zwei Ausprägungen, die auf der Index-Seite gesetzt und später für die Weiterleitung/Einblendung verwendet wird. Es ginge aber auch über eine Preload-Variable. Dann könntet und müsstet Ihr die Zuteilung im Vorfeld übernehmen und uns wie gehabt die Preloadvariable liefern.

**Comment by SilinaKowalewski** [comment]
@GescheBrandt: 

Ich habe euch nun, genau wie für die Nacaps-Befragung, eine Variable "s_split_poli1" angelegt, welche zufällig mit den Werten 1 oder 2 gefüllt wird. Dieses zufällige Befüllen der Variable geschieht direkt auf der Index-Seite. 

Anhand der Variable "s_split_poli1" wird dann auf page71b entschieden welche Skalenausrichtung der Proband sieht. 

Zum Testen wird übergangsweise der Wert der Variable auf Page3 eingeblendet.

**Comment by GescheBrandt** [comment]
@SilinaKowalewski 
Perfekt, besten Dank!

**Comment by GescheBrandt** [comment]
Wir bitten noch um folgende Anpassungen:

- [ ] Einwahl: Es wurde versucht mit Smartphone zu testen, aber die Einwahl hat nicht funktioniert, Liegt wahrscheinlich daran, dass es ein interner Link ist, richtig?

- [ ] Index: "Sie müssen einwilligen, um an der Befragung teilnehmen zu können." --> Dieser Hinweis sollte weiter oben stehen, am besten in fett direkt über der Zeile mit der Einwilligung. Jetzt steht der Satz ganz am Ende und wenn man nicht runter scrollt, weiß man nicht, was das Problem ist.

- [ ] page 4: Softreminder fehlt. Wird hier keine Angabe gemacht, soll ein Hinweis erscheinen, dass diese Angabe wichtig ist (siehe Vorlage). Danach kann auch ohne Angabe weitergeklickt werden.

- [ ] Page 19: Hier muss der Filter noch ergänzt werden: 
GOTO page 21 if (c6bezugsnr=1 & c6taet1wiss=1) usw.
GOTO page 22 if (c6bezugsnr=1 & c6taet1wiss=2) usw.
**NEU: GOTO page 21 if c6taet2vorh!=1 & c6taet1wiss=1
NEU: GOTO page 22 if c6taet2vorh!=1 & c6taet1wiss=2**
GOTO page 20


- [ ] page 71b: Es wird jedes mal die gleiche Skala eingeblendet, egal ob auf page 3 "split 1" oder split 2" steht.

- [ ] page 71d: Fragezeichen am Ende des letzten Items ergänzen.

**Comment by SilinaKowalewski** [comment]
@GescheBrandt: 

Wir haben die Befragung nun auch auf dem Presentation-Server ausgerollt (https://presentation.dzhw.eu/Promopanel-w6). Der Link kann also jetzt auch vom Handy aus aufgerufen werden. 

Wichtig hierbei ist allerdings, dass die Befragung nicht responsiv ist und daher nicht für eine Bearbeitung auf dem Handy geeignet ist.

**Comment by GescheBrandt** [comment]
Vielen Dank für die schnelle Umsetzung unserer Anmerkungen.
Wir hatten den Lasttest für Ende Februar geplant, wäre es möglich ihn in dieser Woche zu machen?

**Comment by andreaschu** [comment]
@GescheBrandt ist denn der Fragebogen aus Eurer Sicht fertig? Vorher macht ein DataCheck keinen Sinn.

**Comment by GescheBrandt** [comment]
@andreaschu Ja, wenn alle unsere Anmerkungen umgesetzt wurden, ist der Fragebogen fertig und kann gecheckt werden.

**Comment by andreaschu** [comment]
@GescheBrandt die Änderungen wurden umgesetzt. Ich gehe davon aus, dass Ihr die auch getestet habt, wenn Ihr den Lasttest haben wollt.
Wir werden den Lasttest gemeinsam mit dem von Nacaps machen, da es ja ein Projekt ist und Promopanel, soweit ich weiß, nach Nacaps ins Feld gehen möchte.

**Comment by GescheBrandt** [comment]
Hab es gerade nochmal geprüft, stimmt soweit, nur der Filter auf page 19 funktioniert nach der Änderung nicht mehr. Der muss wie folgt aussehen:

GOTO page 21 if (c6bezugsnr=1 & c6taet1wiss=1) oder 
(c6bezugsnr=2 & c6taet2wiss=1) oder 
(c6bezugsnr=3 & c6taet3wiss=1) oder 
(c6bezugsnr=4 & c6taet4wiss=1) oder 
(c6bezugsnr=5 & c6taet5wiss=1) oder 
(c6bezugsnr=6 & c6taet6wiss=1) oder 
(c6bezugsnr=7 & c6taet7wiss=1) oder 
(c6bezugsnr=8 & c6taet8wiss=1) oder 
(c6bezugsnr=9 & c6taet9wiss=1) oder 
(c6bezugsnr=10 & c6taet10wiss=1)

GOTO page 22 if (c6bezugsnr=1 & c6taet1wiss=2) oder 
(c6bezugsnr=2 & c6taet2wiss=2) oder 
(c6bezugsnr=3 & c6taet3wiss=2) oder 
(c6bezugsnr=4 & c6taet4wiss=2) oder 
(c6bezugsnr=5 & c6taet5wiss=2) oder 
(c6bezugsnr=6 & c6taet6wiss=2) oder 
(c6bezugsnr=7 & c6taet7wiss=2) oder 
(c6bezugsnr=8 & c6taet8wiss=2) oder 
(c6bezugsnr=9 & c6taet9wiss=2) oder 
(c6bezugsnr=10 & c6taet10wiss=2)

GOTO page 21 if c6taet2vorh!=1 & c6taet1wiss=1

GOTO page 22 if c6taet2vorh!=1 & c6taet1wiss=2

GOTO page 20

**Comment by andreaschu** [comment]
@GescheBrandt ich habe hinzugefügt und an einer Stelle Code korrigiert. Der Rest sah richtig aus.
`GOTO page 22 if c6taet2vorh!=1 & c6taet1wiss=2`

Es gibt noch transitions zu page26. Mir ist unklar, ob die gelöscht werden sollen, was ich jetzt nicht gemacht habe. Bitte teste das noch mal!

Wenn es nicht stimmt, die Änderungen bitte im Änderungsmodus in der Programmiervorlage vornehmen und hier hochladen. Sonst ist es schwer nachzuvollziehen, wo die Änderungen vorgenommen wurden.

**Comment by GescheBrandt** [comment]
@andreaschu 
[PP14_Fragebogen_W6_v12_an2M.docx](https://github.com/dzhw/zofar/files/4291867/PP14_Fragebogen_W6_v12_an2M.docx)
[PP14_Fragebogen_W6_v9_an2M.docx](https://github.com/dzhw/zofar/files/4291868/PP14_Fragebogen_W6_v9_an2M.docx)

Ja, die transitions zu page26 sollten raus, das steht im Änderungsmodus in der ersten Version, die wir euch geschickt hatten (_v9). Ich hänge die nochmal ran. Prüfen kann ich das nicht, weil es die dort verwendeten Preloads nicht mehr gibt. Vorsicht, in Version 9 fehlen noch die beiden neuen Zeilen im Filter. Zusätzlich hänge ich auch die aktuelle FB-Version an, in der die letzte Änderung im page-19-Filter steht. Wenn noch was unklar ist, ruf mich gerne an.

**Comment by andreaschu** [comment]
> Ja, die transitions zu page26 sollten raus, das steht im Änderungsmodus in der ersten Version, die wir euch geschickt hatten (_v9). Ich hänge die nochmal ran. 

Habe ich entsprechend der Programmiervorlagen angepasst. Jetzt könnt Ihr das noch mal testen.

**Comment by GescheBrandt** [comment]
@andreaschu Hallo Andrea, wurde der Lasttest jetzt zusammen mit dem Nacaps-Lasttest durchgeführt?

**Comment by andreaschu** [comment]
@GescheBrandt könnt Ihr auch noch mal in die Adress-Abfrage hineinschauen?
http://vmtest.dzhw.local:8080/Promopanel-w6-addon/

**Comment by GescheBrandt** [comment]
@andreaschu sieht gut aus

**Comment by GescheBrandt** [comment]
keine Änderungen erforderlich

**Comment by GescheBrandt** [comment]
[Preloads_W6.docx](https://github.com/dzhw/zofar/files/4344469/Preloads_W6.docx)

@andreaschu Es gibt leider noch Probleme mit den Preloads. 

Im Testdatensatz befindet sich die Preload-Variable "preloadpre_c4weibstatus", in der keine Werte stehen. Diese müsste laut der Programmiervorlage "pre_weibstatus" heißen (also ohne c4) und Werte zwischen -1 und 3 enthalten. Das ist in dem Preloaddatensatz den wir zum Einlesen erstellt haben auch der Fall, das habe ich sicherheitshalber nochmal geprüft. In den Testdaten wurden jetzt die pages 33a und 34 nicht angesteuert, d.h. die Variablen auf diesen Seiten wurden für alle 2000 Fälle überfiltert. 
Bei der Fragebogentestung wurden diese pages aber angezeigt. Wäre es möglich, dass das beim Einlesen der Preloads passiert ist, weil dort z.B. noch ein alter Variablenname stand? Bitte prüft das nochmal.

Die Variablen pre_c2nperwerb, pre_c3nperwerb, pre_c4nperwerb werden im Unterschied zu den Vorwellen nicht mehr verwendet. Die stehen auch noch in den Testdaten ohne Werte zu enthalten. Das scheint für die Daten aber unproblematisch zu sein, da diese Variablen nicht angesteuert werden.

**Comment by andreaschu** [comment]
@vdick kannst du bitte noch mal die Preloads testen? Im docs-Ordner sind die richtigen Preloads.

**Comment by andreaschu** [comment]
@GescheBrandt mit den Preloads stimmt tatsächlich einiges nicht. 
Es gibt einen Fehler in der Programmierung, nämlich dass auf Seite page32 die transition auf Basis von pre_c4weibstatus geschrieben war. Das konnte beim Testen nicht auffallen, da diese Preload-Variable auch in der von Euch gelieferten Tabelle mit Tester-Preloads pre_c4weibstatus enthielt.

**Comment by GescheBrandt** [comment]
@andreaschu Okay, das ist blöd gelaufen, aber gut dass es noch aufgefallen ist. Kann ich noch irgendwas machen, um sicherzustellen, dass es morgen korrekt funktioniert?

**Comment by andreaschu** [comment]
@GescheBrandt ich habe folgende Änderungen vorgenommen:
- die Preload-Variable pre_c4weibstatus in pre_weibstatus geändert (sowohl in der transition als auch in der Datenbank)
- die transition auf der seite page4 korrigiert
- die nichtverwendeten Variablen gelöscht (pre_c2nperwerb, pre_c3nperwerb, pre_c4nperwerb, sowie c6taet1std-c6taet10std)

Kannst Du die ersten beiden Änderungen auf Richtigkeit testen?

Wenn Du das getestet hast und uns das Go gibst, versuchen wir das auszurollen, was etwas dauern kann, weil Nacaps derzeit sehr aktiv ist, und dann noch mal ein paar Tester drüberjagen. Wenn alles klappt, können wir Morgen einladen. Aufgrund dieser Fehler, sollten wir aber sorgfältig arbeiten und das testen.

**Comment by GescheBrandt** [comment]
Okay danke, ich teste das sofort.
Ich habe die Testdaten nun komplett durchgetestet und bis auf die angesprochene Preloadproblematik und die nicht erreichbare Kalendariumsseite page5d, ist mir nur noch eine Kleinigkeit aufgefallen:

- [ ] Auf page 52 sollen in allen Variablen w6pubpanz-w6pubbnd 3-stellige Zahlenwerte eingegeben werden können. in den Testdaten gab es hier nur Werte von 0-10. Bitte stellt sicher, dass auch wirklich dreistellige Werte eingegeben werden könnten und hier keine Wertebereichsbeschränkung bis 10 oder so vorliegt.

- [ ] Und nach der Variable x6anmerkungen kommen noch ca. 50 Variablen (c6taet1std-flag81e), die leer sind und noch aus der Vorwelle stammen, aber nicht mehr abgefragt werden. Die sind erstmal unproblematisch, aber werden nicht mehr benötigt.

- [ ] Da die Drop-Downs nicht funktionieren (nur Wert -1) und Exklusivantworten auch nicht, konnte ich ein paar Dinge nicht testen. Das ist aber normal, oder?

Darüber hinaus sieht alles gut aus. Vielen Dank!

**Comment by GescheBrandt** [comment]
Habe die Änderungen im Fragebogen getestet, sieht alles korrekt aus. Danke!

@vdick Der zweite Testlauf kann gestartet werden. GO

**Comment by GescheBrandt** [comment]
Guten Morgen! Könnt ihr schon absehen, wann ich anfangen kann, die neuen Daten zu testen?

**Comment by vdick** [comment]
Guten Morgen!  Ich habe die neue Version der Befragung gerade ausgerollt und starte gleich mit dem Test. Sofern alles gut läuft, bekommst du die Daten in 1 bis  2 Stunden

**Comment by GescheBrandt** [comment]
Okay, prima!

**Comment by GescheBrandt** [comment]
@andreaschu @vdick Ich habe die Preloads und das Kalendarium geprüft, sieht alles gut aus. Was mich allerdings irritiert hat ist, dass im ersten Datensatz alle Fälle entweder auf der Indexseite rausgefallen sind oder bis zur Endseite gelangt sind. Entsprechend hat die lastpage-Variable nur zwei Ausprägungen.
Bei den neuen Daten gehen unterwegs immer mal Fälle verloren, die haben dann auf den Folgevariablen meistens den Wert -9992 und in der lastpage-Variable gibt es verschiedene Werte. 
Wie kommt das Zustande?

**Comment by vdick** [comment]
@GescheBrandt @andreaschu Ich habe gerade die Logs der Server geprüft und keine Fehler gefunden. Von 1000 Teilnehmer sind:
898 bis zur Endseite durchgekommen;
67 auf der Index-Seite "stecken" geblieben;
36 verteilt auf die gesamte Befragung, von verschiedenen Seiten nicht weitergekommen. (Ist auf unseren Simulator zurückzuführen, wegen timeout etc.)

**Comment by GescheBrandt** [comment]
Okay prima, wenn das an der Simulation liegt, sollte das ja völlig unproblematisch sein. Hatte mich nur gewundert, weil das in den ersten Daten nicht der Fall war, da kamen alle bis zur Endseite (außer die Indexsteckenbleiber)

**Comment by vdick** [comment]
Den letzten Test habe ich von zuhause aus durchgeführt, somit sind die Ausgangsvoraussetzungen nicht die gleichen. Die Internetleitung hat zwischendurch leichte aussetzer wodurch es zu Timeouts kommen kann

**Comment by andreaschu** [comment]
@GescheBrandt nach Rücksprache mit Viktor und erneutem Blick auf die betroffenen Seiten, sind wir uns sicher, dass es nicht durch Weiterleitungen zustande gekommen ist und halten das für die Befragung für unproblematisch. 
Wenn Du uns das GO gibst, sind wir startklar. :o)

**Comment by GescheBrandt** [comment]
> 
> 
> @GescheBrandt:
> 
> Ich habe euch nun, genau wie für die Nacaps-Befragung, eine Variable "s_split_poli1" angelegt, welche zufällig mit den Werten 1 oder 2 gefüllt wird. Dieses zufällige Befüllen der Variable geschieht direkt auf der Index-Seite.
> 
> Anhand der Variable "s_split_poli1" wird dann auf page71b entschieden welche Skalenausrichtung der Proband sieht.
> 
> Zum Testen wird übergangsweise der Wert der Variable auf Page3 eingeblendet.

@SilinaKowalewski Kannst du mir sagen, welche Skala die Befragten gesehen haben, je nach Wert von s_split_poli1? Bin gerade dabei die Labels zu erstellen und wir haben das leider nicht dokumentiert.

**Comment by andreaschu** [comment]
**Seite:** page71b
**Variable:** k6polinter

\
`s_split_poli1==1`
### Wie sehr interessieren Sie sich für Politik? 
**Sind Sie…**
_sehr interessiert  -  -  -  überhaupt nicht interessiert_
____
`s_split_poli1==2`
### Wie sehr interessieren Sie sich für Politik?
**Sind Sie…**
_überhaupt nicht interessiert -  -  -   sehr interessiert_
