### ISSUE TITLE
Promopanel-w6: going online

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#281]
Checklist for Going Online:
- [x] data protection document
- [x] E-Mail-Adress -> access for Zofar
- [x] token mit Preloads
- [x] How does the link should be named?
- [x] text for invitation E-Mail

**Comment by andreaschu** [comment]
@GescheBrandt für den Lasttest benötigen wir noch die Token mit Preloads und den Namen der Befragung für den Link.

**Comment by andreaschu** [comment]
@vdick die Token mit Preloads sind im docs-Ordner (Preloadvar_Onlinebefragung_W6.xls mit 4.794 Fällen)

**Comment by andreaschu** [comment]
@vdick ich habe Panel-Token angespielt.

**Comment by andreaschu** [comment]
@geschebrandt sollen wir die Befragung entsprechend der vorherigen Wellen "/promovierendenpanel-w6" nennen?

**Comment by GescheBrandt** [comment]
@andreaschu Ja, bitte so wie in den Wellen zuvor. Aber bitte promoviertenpanel-w6 (nicht promovierendenpanel). Danke.

**Comment by andreaschu** [comment]
@vdick bitte sicherstellen, dass die Befragung **promoviertenpanel-w6** und nicht 
_promovierendenpanel_ heißt.

**Comment by vdick** [comment]
@andreaschu ist nun entsprechend angepasst

**Comment by andreaschu** [comment]
@vdick könntest Du noch mal ein paar Token drüberjagen? Vielleicht 200 oder so, damit wir einen neuen Export machen und das testen können.

**Comment by GescheBrandt** [comment]
Wartet am besten noch kurz, es gibt noch einen Filterfehler beim Kalendarium, dann kann man den gleich mittesten. Ich prüfe gerade, woran es liegen könnte.

**Comment by GescheBrandt** [comment]
Folgendes: Auf page 4 gibt es den Filter, der zu den verschiedenen Kalendariumsseiten führt. Die sind alle vorhanden, aber die 4. Bedingung "GOTO page 5d if pre_x4teilnahme==1 & pre_x5teilnahme==0" scheint nicht zu greifen. Es sieht aus, als würden diese Fälle zu page 5e geleitet werden, da sie nur in den MO-Variablen 73-96 Angaben stehen haben (also die Jahre 2019+2020).

**Comment by CaroTeich** [comment]
Hallo zusammen,

hier der Speicherort für die Adressdatei (Excelliste mit 4.578 Mails, Anrede, Token, die URL bitte prüfen und ggf. ändern, dies ist noch aus dem Vorjahr und ALT). oder soll ich die ALTE URL lieber löschen? 

gWinter: _daten/promovierte/2M/PP14_W6_Einladung_Versandliste_ (Excel-Liste, keine Dateiendung im Dateinamen)

Nocheinmal: die URL bitte prüfen.

**Comment by CaroTeich** [comment]
Es gibt auch eine Testliste für die Testmails:
gWinter: _daten/promovierte/2M/PP14_W6_testliste (Excel-Liste, keine Dateiendung im Dateinamen)

**Comment by andreaschu** [comment]
@GescheBrandt ich habe die Daten wieder in den Austausch-Ordner im geschützten Bereich gelegt.

**Comment by GescheBrandt** [comment]
Falls das mit den Drop-Outs (siehe mein Kommentar in "testing and correcting") unproblematisch ist, weil Teil der Simulation oder ähnliches, würden wir gerne mit der Feldphase starten. Wärt ihr ansonsten startklar?

**Comment by andreaschu** [comment]
regarding https://github.com/dzhw/zofar/issues/280#issuecomment-601151100
@GescheBrandt Wenn Du uns das GO gibst, sind wir startklar. :o)

**Comment by GescheBrandt** [comment]
@andreaschu @vdick Okay, dann legt mal los. GO! :-)
