### ISSUE TITLE
Promopanel-w6: export of data

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#288]

**Comment by andreaschu** [comment]
@GescheBrandt könnten wir für den richtigen Export hier alle Variablen sammeln, die als string-Variablen eingelesen werden sollen, wie Postleitzahlen (wegen voranstehender Null) und Einkommensvariablen (wegen Trennzeichen)?

**Comment by andreaschu** [comment]
Ich fang mal an:
c6taet1plz
c6taet1plz
c6taet1plz
c6taet1plz
c6taet1plz
c6taet1plz
c6taet1plz
c6taet1plz

**Comment by GescheBrandt** [comment]
Hallo Andrea, vielen Dank. Die k6hws*plz-Variablen wurde in dieser Welle nicht abgefragt, die kannst du streichen. Ergänzen möchte ich noch:
c6jzujahr

**Comment by GescheBrandt** [comment]
Bitte achtet beim Export der anderen Stringvariablen auch noch auf folgendes
-              die Stringvariablen nicht abschneiden,
-              eine korrekte Darstellung von Umlauten,

**Comment by andreaschu** [comment]
@GescheBrandt ich habe den Transfer veranlasst.
- Im csv-Ordner liegt auch die erstellte maxpage als eigene Datei.
Im Doc-Ordner liegen:
- log-Datei über die Erstellung der maxpage (falls ich Fehler gemacht habe).
- Rücklauf-Graph
- Datenschutzblatt
