### ISSUE TITLE
Studienzweifler: create project 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#299]

**Comment by SilinaKowalewski** [comment]
Projects created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Studienzweifler
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/Studienzweifler-Addon
Testserver (after first build):
http://vmtest.dzhw.local:8080/Studienzweifler
http://vmtest.dzhw.local:8080/Studienzweifler-Addon
Presentation(after first build):
http://presentation.dzhw.eu/Studienzweifler
http://presentation.dzhw.eu/Studienzweifler-Addon
