### ISSUE TITLE
Cockpit enhancement

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#3]
**Participants:**
- not relevant

**User:** 
- as a User i want to directly request live feedback from a survey
- possibly through an interface

**Service:**
- automated feedback system for the users, without much involvement

**Dev:**
- automated feedback system for the users, without much involvement

**Comment by andreaschu** [comment]
included in project [Zofar: webstart replacement ](https://github.com/dzhw/zofar/projects/10)
