### ISSUE TITLE
Studienzweifler: programming first draft

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/zofar#300]

**Comment by SilinaKowalewski** [comment]
Lieferung der Programmiervorlage per Mail vom 15.01.2020

[Fragebogen v150120.docx](https://github.com/dzhw/zofar/files/4071645/Fragebogen.v150120.docx)

**Comment by SilinaKowalewski** [comment]
_**pn1002**_ 

**Hinweis:**
- Darstellung des semantischen Differentials responsiv nach wie vor problematisch
- nur die Skalenpunkte 2-4 können belabelt werden

______

_**_Probleme:_**_ 
Sind die Variablen hier richtig benannt? Wenn alle Variablennamen verwendet werden unterscheiden sich die Namen zur vorherigen Befragung: 

Studienzweifler: 
It1 - merkls
It2 - merklsor
It3 - merklsun
It4 - merklsgf
It5 - merklspt
It6 - merklssv

Masterbefragung: 
Studienzweifler: 
It1 - merklsor
It2 - merklsun
It3 - merklsgf
It4 - merklspt
It5 - merklssv

______

` fo: Itemklassen, mv absetzen` 
- Welche Item sollen hier zu Klassen zusammengefügt werden? 
- Welcher soll der mv-Wert sein?

**Comment by SilinaKowalewski** [comment]
**_pn3001_**

`Für den weiteren Verlauf der Befragung ist es unerlässlich, dass Sie diese Frage beantworten. Anderenfalls kann die Befragung nicht fortgesetzt werden. : Ich möchte die Befragung nicht fortsetzen.`

Für welchen Fall soll dieser Softforce angezeigt werden? Sobald eines der Items nicht beantwortet wurde oder reicht es, wenn einer der Items beantwortet wurde?

**Comment by SilinaKowalewski** [comment]
**_pn4001_**

```
GOTO pn4101 IF absang = 1 OR absang = 2 OR absang = 5 AND bakabserw = 1 OR baabserwf = 1 AND baabserwss = 0 AND baabserwws = 0 
GOTO pn4102 IF absang = 3 OR absang = 4 AND makabserw = 1
```
Hier fehlen noch Klammern damit klar wird welche Bedingungen zusammen gehören.

**Comment by SilinaKowalewski** [comment]
**_pn4005_**

`Welche Rolle spielten die folgenden Gründe dafür, dass Sie ernsthafte Zweifel an Ihrem letzten Bachelorstudium hatten?`

Macht die Frage bei einer Doppelmatrix mit den Ausprägungen ka1: Bachelorstudium/ka2: Masterstudium Sinn?

**Comment by SilinaKowalewski** [comment]
**_pn5001_**

Wo soll die ka: universitäre Beratung angezeigt werden bzw. für welche Items gilt dies? 

____

`fv: sf_ber: Für den weiteren Verlauf der Befragung ist es unerlässlich, dass Sie diese Frage beantworten. Anderenfalls kann die Befragung nicht fortgesetzt werden. : Ich möchte die Befragung nicht fortsetzen.`

Wann soll dieser Softforce angezeigt werden?

**Comment by SilinaKowalewski** [comment]
**_pn5001_**

Sollen die drei Matrix-Fragen wirklich einzeln auf der Seite dargestellt werden - inkl. drei Fragetexten - oder soll die Seite final in etwa so aussehen (Screenshot der Masterbefragung) 

![Screenshot_pn2304](https://user-images.githubusercontent.com/48087320/72810219-6a398100-3c5d-11ea-9a50-9890b0534fd0.png)

**Comment by SilinaKowalewski** [comment]
**_pn5012_** 

`tr: GOTO pn6001 IF absang = 1 OR absang = 2 OR IF absang = 5`

Diese Transition ist aus meiner Sicht unvollständig. Sollte sowieso nur Befragte, die "absang = 1 OR absang = 2 OR IF absang = 5" erfüllen auf diese Seite gelangen, ist die Transition bzw. deren Bedingungen überflüssig

**Comment by SilinaKowalewski** [comment]
**_pn5013_**

`tr: GOTO pn6007 IF absang = 3 OR absang = 4`

Diese Transition ist aus meiner Sicht unvollständig. Sollte sowieso nur Befragte, die "tr: GOTO pn6007 IF absang = 3 OR absang = 4" erfüllen auf diese Seite gelangen, ist die Transition bzw. deren Bedingungen überflüssig

**Comment by ChristophEn-git** [comment]
> _**pn1002**_
> 
> **Hinweis:**
> 
> * Darstellung des semantischen Differentials responsiv nach wie vor problematisch
> * nur die Skalenpunkte 2-4 können belabelt werden
> 
** Die Labels für Skalenpunkte 2-4 sind auch nicht wichtig, dass war überwiegend durch copy-paste aus der Masterbefragung**
>
>
> _**_Probleme:_**_
> Sind die Variablen hier richtig benannt? Wenn alle Variablennamen verwendet werden unterscheiden sich die Namen zur vorherigen Befragung:
> 
> Studienzweifler:
> It1 - merkls
> It2 - merklsor
> It3 - merklsun
> It4 - merklsgf
> It5 - merklspt
> It6 - merklssv
> 
> Masterbefragung:
> It1 - merklsor
> It2 - merklsun
> It3 - merklsgf
> It4 - merklspt
> It5 - merklssv
> 
>
**Da ist mir ein Fehler passiert. In der Studienzweifler Befragung gibt es ein Item mehr, im Vergleich zur Masterbefragung. 

Änderung bitte wie folgt: vn: merkls(merklsor/merklsun/merklsse/merklswf/merklsi/merklslk)

Bzw: 
it1 - merklsor
it2 - merklsun
it3 - merklsse
it4 - merklswf
it5 - merklsi
it6 - merklslk

die unterschiedlichen Namen zur Masterbefragung ausgenommen bei den ersten zwei items sind erwünscht, da die anderen Items sich von der Masterbefragung unterscheiden**

> ` fo: Itemklassen, mv absetzen`
> 
> * Welche Item sollen hier zu Klassen zusammengefügt werden?
>
>
** Unter Itemklassen habe ich ein Zebramuster zw. den Items verstanden, das diese also abwechselnd grau und weiß unterlegt sind. Das soll eigentlich bei jedem semantischen Differenzial, jeder Doppelmatrix, jeder Ein- und Mehrfachauswahlmatrix passieren. **

> * Welcher soll der mv-Wert sein?
** Das ist ein copy paste Fehler aus dem anderen Fragebogen. Da wir keine "weiß nicht" Kategorie benutzen, kann die Anweisung mv-absetzen ignoriert werden, meist sind das noch Rückstände von unsauberem copy-paste. Ich bitte dafür um Entschuldigung**

**Comment by ChristophEn-git** [comment]
> **_pn3001_**/**_pn3002_**
> 
> `Für den weiteren Verlauf der Befragung ist es unerlässlich, dass Sie diese Frage beantworten. Anderenfalls kann die Befragung nicht fortgesetzt werden. : Ich möchte die Befragung nicht fortsetzen.`
> 
> Für welchen Fall soll dieser Softforce angezeigt werden? Sobald eines der Items nicht beantwortet wurde oder reicht es, wenn einer der Items beantwortet wurde?
 
Der Softforce bitte immer nur dann, wenn gar keine Antwort gegeben wurde. Sobald mindestens eine Antwort ausgewählt wurde, soll der Softforce nicht erscheinen.



> ```
> GOTO pn4201 IF bazweiffa = 4 OR bazweiffa = 5 AND bazweifhf = 4 OR bazweifhf = 5 AND bazweifauf = 4 OR bazweifauf = 5
> AND bakabserw = 1 OR baabserwf = 1 AND baabserwss = 0 AND baabserwws = 0 
> 
> GOTO pn5001 IF bazweiffa = 4 OR bazweiffa = 5 AND bazweifhf = 4 OR bazweifhf = 5 AND bazweifauf = 4 OR bazweifauf = 5
> AND baabserwws = 1 OR baabserwss = 1 OR baabserwf= 1 AND baabserwss = 1 OR baabserwf= 1 AND baabserwws = 1
> ```
> 
> Hier fehlen noch Klammern damit klar wird welche Bedingungen zusammen gehören.

Nochmal mit Klammern:

GOTO pn4201 IF (bazweiffa = 4 OR bazweiffa = 5) AND (bazweifhf = 4 OR bazweifhf = 5) AND (bazweifauf = 4 OR bazweifauf = 5)
AND bakabserw = 1 OR (baabserwf = 1 AND baabserwss = 0 AND baabserwws = 0) 

GOTO pn5001 IF (bazweiffa = 4 OR bazweiffa = 5) AND (bazweifhf = 4 OR bazweifhf = 5) AND (bazweifauf = 4 OR bazweifauf = 5)
AND baabserwws = 1 OR baabserwss = 1 OR (baabserwf= 1 AND baabserwss = 1) OR (baabserwf= 1 AND baabserwws = 1)

GOTO pn99999 IF sf_bazweif = 1

**Comment by ChristophEn-git** [comment]
> **_pn4005_**
> 
> `Welche Rolle spielten die folgenden Gründe dafür, dass Sie ernsthafte Zweifel an Ihrem letzten Bachelorstudium hatten?`
> 
> Macht die Frage bei einer Doppelmatrix mit den Ausprägungen ka1: Bachelorstudium/ka2: Masterstudium Sinn?
 
Nein, das ist ein Fehler, richtig lauten muss die Frage:

Welche Rolle spielten die folgenden Gründe dafür, dass Sie ernsthafte Zweifel an Ihrem letzten Bachelorstudium bzw. letzten Masterstudium hatten?


> `GOTO 5004 IF maabserwws = 1 OR maabserwss=1 OR maabserwf = 1`
> 
> Diese Transition ist aus meiner Sicht unvollständig. Sollten sowieso nur Befragte, die "maabserwws = 1 OR maabserwss=1 OR maabserwf = 1" erfüllen auf diese Seite gelangen, ist die Transition bzw. deren Bedingungen überflüssig

Du hast recht, die Transition ist unvollständig. Vollständig müsste es heißen:

GOTO pn4102 IF makabserw = 1
GOTO 5004 IF maabserwws = 1 OR maabserwss=1 OR maabserwf = 1

**Comment by ChristophEn-git** [comment]
> **_pn5001_**
> 
> Wo soll die ka: universitäre Beratung angezeigt werden bzw. für welche Items gilt dies?
 
Es gilt für die ersten 10 Items, also für:
it1: Zentrale Studienberatung/Allgemeine Studienberatung
it2: Fachstudienberatung des Fachbereiches
it3: studentische Beratungsangebote (z. B. Angebote vom AStA)
it4: Beratung durch Dozent*innen (im Rahmen von Lehrveranstaltungen, Sprechstunden)
it5: Sozialberatung/Finanzierungsberatung
it6: Psychologische/ psychosoziale Beratung 
it7: Beratung durch Mentor*innen/ Studienverlaufsberater*innen
it8: Career Service der Hochschule
it9: Veranstaltungen zu Studienzweifeln
it10: andere Beratung, und zwar: [berandoffen]

Zur Anzeige schreibe der Kategorien schreibe ich etwas im Nächsten Post, zu deinem Screenshot.


> `fv: sf_ber: Für den weiteren Verlauf der Befragung ist es unerlässlich, dass Sie diese Frage beantworten. Anderenfalls kann die Befragung nicht fortgesetzt werden. : Ich möchte die Befragung nicht fortsetzen.`
> 
> Wann soll dieser Softforce angezeigt werden?

Der Softforce wie auch zuvor, bitte nur, wenn jemand gar keine Antwort gibt. Wer mindestens eine Auswahl trifft, dem soll der Softforce nicht angezeigt werden.

**Comment by ChristophEn-git** [comment]
> **_pn5001_**/**_pn5004_**
> 
> Sollen die drei Matrix-Fragen wirklich einzeln auf der Seite dargestellt werden - inkl. drei Fragetexten - oder soll die Seite final in etwa so aussehen (Screenshot der Masterbefragung)
> 
> ![Screenshot_pn2304](https://user-images.githubusercontent.com/48087320/72810219-6a398100-3c5d-11ea-9a50-9890b0534fd0.png) 

Genau diese Seite hatte ich so im Sinn für diese Fragen, nur dass statt Studienbedingungen eben da die erste Kategorie steht, also: universitäre Beratung
statt Studienanforderungen dann außeruniversitäre Beratung und dazu analog auch soziale Kontakte als Kategorie einfach links übergeordnet über den Items die dazu gehören. Also wollen wir genau das Design für Frage pn5001 und pn5004 so übernehmen wie im Screenshot. Ich liste nochmal die Kategorien auf und die zugehörigen Items:

universitäre Beratung

- it1: Zentrale Studienberatung/Allgemeine Studienberatung
- it2: Fachstudienberatung des Fachbereiches
- it3: studentische Beratungsangebote (z. B. Angebote vom AStA)
- it4: Beratung durch Dozent*innen (im Rahmen von Lehrveranstaltungen, Sprechstunden)
- it5: Sozialberatung/Finanzierungsberatung
- it6: Psychologische/ psychosoziale Beratung 
- it7: Beratung durch Mentor*innen/ Studienverlaufsberater*innen
- it8: Career Service der Hochschule
- it9: Veranstaltungen zu Studienzweifeln
- it10: andere Beratung, und zwar: [berandoffen]

außeruniversitäre Beratung

- it11: Beratungsangebote der Agentur für Arbeit
- it12: Beratungsangebote der Industrie- und Handelskammern
- it13: Beratungsangebote der Handwerkskammern
- it14: Spezielle Beratungsangebote für Studienabbrecher*innen (z.B. Jobstarter plus-Projekte)


soziale Kontakte

- it15: Freunde/Bekannte/Kommiliton*innen
- it16: Eltern/Verwandte/Partner*in
- it17: Online-Communities

**Dazu hier noch eine Anmerkung: sowohl bei pn5001 als auch pn5004 ist die Skala im Fragebogen die falsche bezüglich der letzten Batterie zu den sozialen Kontakten. Für it15/it16/it17 sollen die Antwortoptionen für beide Fragen wie folgt aussehen:**

ao1: 1 : 1 : nie 
ao2: 2 : 2 : selten
ao3: 3 : 3 : gelegentlich
ao4: 4 : 4 : häufig

aber **nur für die sozialen Kontakte**


> Auch hier ist nicht klar, wann der Softforce angezeigt werden soll.

Auch hier wieder bitte nur dann, wenn jemand gar keine Auswahl trifft den Softforce einblenden, sobald jemand mindestens eine Antwort gewählt hat, soll er den Softforce bitte nicht bekommen. 

> Hier fehlen noch Klammern damit klar wird welche Bedingungen zusammen gehören.

**pn5001** mit Klammern:


GOTO pn5007 IF (absang = 1 OR absang = 2 OR IF absang = 5) AND (bazweiffa = 1 OR bazweiffa = 2 OR bazweiffa = 3 OR bazweifhf = 1 OR bazweifhf = 2 OR bazweifhf = 3 
OR bazweifauf = 1 OR bazweifauf = 2 OR bazweifauf = 3) AND (berzs = 3 OR berzs = 4 OR berfach = 3 OR berfach = 4 OR berstu = 3 OR berstu = 4 OR berdoz = 3 OR berdoz = 4
OR bersfb = 3 OR bersfb = 4 OR berpsy=3 OR berpsy=4 OR bermen = 3 OR bermen = 4 OR bercar = 3 OR bercar = 4 OR berver=3 OR berver=4 OR berand =3 OR berand = 4)

GOTO pn5012 IF (absang = 1 OR absang = 2 OR IF absang = 5) AND (bazweiffa = 1 OR bazweiffa = 2 OR bazweiffa = 3 OR bazweifhf = 1 OR bazweifhf = 2 OR bazweifhf = 3 
OR bazweifauf = 1 OR bazweifauf = 2 OR bazweifauf = 3) AND ((berzs = 1 OR berzs = 2) AND (berfach = 1 OR berfach = 2) AND (berstu = 1 OR berstu = 2) AND (berdoz = 1 OR berdoz = 2)
AND (bersfb = 1 OR bersfb = 2) AND (berpsy=1 OR berpsy=2) AND (bermen = 1 OR bermen = 2) AND (bercar = 1 OR bercar = 2)
AND (berver=1 OR berver=2) AND (berand =1 OR berand = 2) AND (beraa = 1 OR beraa = 2) AND (berih = 1 OR berih = 2)
AND (berhand = 1 OR berhand = 2) AND (berspez = 1 OR berspez = 2))

GOTO pn5011 IF ((bazweiffa = 4 OR bazweiffa = 5) AND (bazweifhf = 4 OR bazweifhf = 5) AND (bazweifauf = 4 OR bazweifauf = 5) AND ((berzs = 3 OR berzs = 4) OR (berfach = 3 OR berfach = 4) OR (berstu = 3 OR berstu = 4) OR (berdoz = 3 OR berdoz = 4)
OR (bersfb = 3 OR bersfb = 4) OR (berpsy=3 OR berpsy=4) OR (bermen = 3 OR bermen = 4) OR (bercar = 3 OR bercar = 4) OR (berver=3 OR berver=4) OR (berand =3 OR berand = 4))

GOTO pn6001 IF (absang = 1 OR absang = 2 OR IF absang = 5) AND ((bazweiffa = 4 OR bazweiffa = 5) AND (bazweifhf = 4 OR bazweifhf = 5) AND (bazweifauf = 4 OR bazweifauf = 5))

GOTO pn99999 IF sf_ber = 1


**pn5004** mit Klammern:

tr: GOTO pn5008 IF (bamazweiffa = 1 OR bamazweiffa = 2 OR bamazweiffa = 3 OR bamazweifhf = 1 OR bamazweifhf = 2 OR bamazweifhf = 3
OR bamazweifauf = 1 OR bamazweifauf = 2 OR bamazweifauf = 3) AND ((mazweiffa = 4 OR mazweiffa = 5 )
AND (mazweifhf = 4 OR mazweifhf = 5) AND (mazweifauf =4 OR mazweifauf = 5)) AND ((bberzs = 3 OR bberzs = 4) OR (bberfach = 3 OR bberfach = 4) OR (bberstu = 3 OR bberstu = 4) OR (bberdoz = 3 OR bberdoz = 4 )
OR (bbersfb = 3 OR bbersfb = 4) OR( bberpsy =3 OR bberpsy = 4) OR (bbermen = 3 OR bbermen = 4 )
OR (bbercar = 3 OR bbercar = 4) OR (bberver = 3 OR bberver = 4) OR (bberand = 3 OR bberand = 4))

GOTO pn5009 IF (mazweiffa = 1 OR mazweiffa = 2 OR mazweiffa = 3 OR mazweifhf = 1 OR mazweifhf = 2 OR mazweifhf = 3
OR mazweifauf = 1 OR mazweifauf = 2 OR mazweifauf = 3) AND ((bamazweiffa = 4 OR bamazweiffa = 5) AND (bamazweifhf = 4 
OR bamazweifhf = 5) AND (bamazweifauf =4 OR bamazweifauf = 5)) AND ((mberzs = 3 OR mberzs = 4) OR (mberfach = 3 OR mberfach = 4) OR (mberstu = 3 OR mberstu = 4) OR (mberdoz = 3 OR mberdoz = 4)
OR (mbersfb = 3 OR mbersfb = 4) OR (mberpsy = 3 OR mberpsy = 4) OR (mbermen = 3 OR mbermen = 4) OR (mbercar = 3 OR mbercar = 4)
OR (mberver = 3 OR mberver = 4) OR (mberand = 3 OR mberand = 4)

GOTO pn5008 IF (bamazweiffa = 1 OR bamazweiffa = 2 OR bamazweiffa = 3 OR bamazweifhf = 1 OR bamazweifhf = 2 OR bamazweifhf = 3
OR bamazweifauf = 1 OR bamazweifauf = 2 OR bamazweifauf = 3) AND (mazweiffa = 1 OR mazweiffa = 2 OR mazweiffa = 3 
OR mazweifhf = 1 OR mazweifhf = 2 OR mazweifhf = 3 OR mazweifauf = 1 OR mazweifauf = 2 OR mazweifauf = 3) AND (bberzs = 3 OR bberzs = 4 OR bberfach = 3 OR bberfach = 4 OR bberstu = 3 OR bberstu = 4 OR bberdoz = 3 OR bberdoz = 4 
OR bberdoz = 3 OR bberdoz = 4 OR bbersfb = 3 OR bbersfb = 4 OR bberpsy =3 OR bberpsy = 4 OR bbermen = 3 OR bbermen = 4 
OR bbercar = 3 OR bbercar = 4 OR bberver = 3 OR bberver = 4 OR bberand = 3 OR bberand = 4 ) AND (mberzs = 3 OR mberzs = 4 OR mberfach = 3 OR mberfach = 4 OR mberstu = 3 OR mberstu = 4 OR mberdoz = 3 OR mberdoz = 4
OR mbersfb = 3 OR mbersfb = 4 OR mberpsy = 3 OR mberpsy = 4 OR mbermen = 3 OR mbermen = 4 OR mbercar = 3 OR mbercar = 4
OR mberver = 3 OR mberver = 4 OR mberand = 3 OR mberand = 4)

GOTO pn6007 IF ((bamazweiffa = 4 OR bamazweiffa = 5) AND (bamazweifhf = 4 OR bamazweifhf = 5) AND (bamazweifauf = 4 OR bamazweifauf = 5)) AND ((mazweiffa = 4 OR mazweiffa = 5) AND (mazweifhf = 4 OR mazweifhf = 5) AND (mazweifauf = 4 OR mazweifauf = 5)) AND ((bberzs = 1 OR bberzs = 2) AND (bberfach= 1 OR bberfach= 2) AND (bberstu = 1 OR bberstu = 2) AND (bberdoz = 1 OR bberdoz = 2) AND (bbersfb = 1 OR bbersfb = 2) AND (bberpsy = 1 OR bberpsy=2) AND (bbermen = 1 OR bbermen=2) AND (bbercar= 1 OR bbercar=2) AND (bberver= 1 OR bberver=2) AND (bberand =1 OR bberand =2)) AND ((mberzs = 1 OR mberzs = 2) AND (mberfach = 1 OR mberfach = 2) AND (mberstu = 1 OR mberstu = 2) AND (mberdoz = 1 OR mberdoz =2) AND (mbersfb= 1 OR mbersfb = 2) AND (mberpsy =1 OR mberpsy = 2) AND (mbermen=1 OR mbermen=2) AND (mbercar=1 OR mbercar=2) AND (mberver = 1 OR mberver=2) AND (mberand = 1 OR mberand = 2) AND (bberaa =1 OR bberaa =2) AND (bberih=1 OR bberih =2) AND (bberhand=1 OR bberhand=2) AND (bberspez = 1 OR bberspez = 2) AND (mberaa =1 OR mberaa =2) AND (mberih =1 OR mberih=2) AND (mberhand=1 OR mberhand=2)) 

GOTO pn5011 IF ((bamazweiffa = 4 OR bamazweiffa = 5) AND (bamazweifhf = 4 OR bamazweifhf = 5 ) AND (bamazweifauf = 4 OR bamazweifauf = 5)) AND ((mazweiffa = 4 OR mazweiffa = 5) AND (mazweifhf = 4 OR mazweifhf = 5) AND (mazweifauf = 4 OR mazweifauf = 5)) AND (bberzs = 3 OR bberzs = 4  OR bberfach = 3 OR bberfach = 4 OR bberstu = 3 OR bberstu = 4 OR bberdoz = 3 OR bberdoz = 4 OR bberdoz = 3 OR bberdoz = 4 OR bbersfb = 3 OR bbersfb = 4 OR bberpsy =3 OR bberpsy = 4 OR bbermen = 3 OR bbermen = 4 OR bbercar = 3 OR bbercar = 4 OR bberver = 3 OR bberver = 4 OR bberand = 3 OR bberand = 4 OR mberzs = 3 OR mberzs = 4 OR mberfach = 3 OR mberfach = 4 OR mberstu = 3 OR mberstu = 4 OR mberdoz = 3 OR mberdoz = 4 OR mbersfb = 3 OR mbersfb = 4 OR mberpsy = 3 OR mberpsy = 4 OR mbermen = 3 OR mbermen = 4 OR mbercar = 3 OR mbercar = 4 OR mberver = 3 OR mberver = 4 OR mberand = 3 OR mberand = 4)

GOTO pn5013 IF (bamazweiffa = 1 OR bamazweiffa = 2 OR bamazweiffa = 3 OR bamazweifhf = 1 OR bamazweifhf = 2 OR bamazweifhf = 3 OR bamazweifauf = 1 OR bamazweifauf = 2 OR bamazweifauf = 3) AND ((mazweiffa = 4 OR mazweiffa = 5) 
AND (mazweifhf = 4 OR mazweifhf = 5) AND (mazweifauf =4 OR mazweifauf = 5)) AND ((bberzs = 1 OR bberzs = 2) AND (bberfach= 1 OR bberfach= 2) AND (bberstu = 1 OR bberstu = 2) AND (bberdoz = 1 OR bberdoz = 2) AND (bbersfb = 1 OR bbersfb = 2) AND (bberpsy = 1 OR bberpsy=2) AND (bbermen = 1 OR bbermen=2) AND (bbercar= 1 OR bbercar=2) AND (bberver= 1 OR bberver=2) AND (bberand =1 OR bberand =2) AND (bberaa =1 OR bberaa =2) AND (bberih=1 OR bberih =2) AND (bberhand=1 OR bberhand=2) AND (bberspez = 1 OR bberspez = 2))

GOTO pn5014 IF (mazweiffa = 1 OR mazweiffa = 2 OR mazweiffa = 3 OR mazweifhf = 1 OR mazweifhf = 2 OR mazweifhf = 3
OR mazweifauf = 1 OR mazweifauf = 2 OR mazweifauf = 3) AND ((bamazweiffa = 4 OR bamazweiffa = 5) AND (bamazweifhf = 4 
OR bamazweifhf = 5) AND (bamazweifauf =4 OR bamazweifauf = 5)) AND ((mberzs = 1 OR mberzs = 2) AND (mberfach = 1 OR mberfach = 2) AND (mberstu = 1 OR mberstu = 2) AND (mberdoz = 1 OR mberdoz =2) AND (mbersfb= 1 OR mbersfb = 2) AND (mberpsy =1 OR mberpsy = 2) AND (mbermen=1 OR mbermen=2) AND (mbercar=1 OR mbercar=2) AND (mberver = 1 OR mberver=2) AND (mberand = 1 OR mberand = 2) AND (mberaa =1 OR mberaa =2) AND (mberih=1 OR mberih=2) AND (mberhand=1 OR mberhand=2) AND (mberspez = 1 OR mberspez =2))

GOTO pn5015 IF (bamazweiffa = 1 OR bamazweiffa = 2 OR bamazweiffa = 3 OR bamazweifhf = 1 OR bamazweifhf = 2 OR bamazweifhf = 3 OR bamazweifauf = 1 OR bamazweifauf = 2 OR bamazweifauf = 3) AND (mazweiffa = 1 OR mazweiffa = 2 OR mazweiffa = 3 OR mazweifhf = 1 OR mazweifhf = 2 OR mazweifhf = 3 OR mazweifauf = 1 OR mazweifauf = 2 OR mazweifauf = 3) AND ((bberzs = 1 OR bberzs = 2) AND (bberfach= 1 OR bberfach= 2) AND (bberstu = 1 OR bberstu = 2) AND (bberdoz = 1 OR bberdoz = 2) AND (bbersfb = 1 OR bbersfb = 2) AND (bberpsy = 1 OR bberpsy=2) AND (bbermen = 1 OR bbermen=2) AND (bbercar= 1 OR bbercar=2) AND (bberver= 1 OR bberver=2) AND (bberand =1 OR bberand =2)) AND ((mberzs = 1 OR mberzs = 2) AND (mberfach = 1 OR mberfach = 2) AND (mberstu = 1 OR mberstu = 2) AND (mberdoz = 1 OR mberdoz =2) AND (mbersfb= 1 OR mbersfb = 2) AND (mberpsy =1 OR mberpsy = 2) AND (mbermen=1 OR mbermen=2) AND (mbercar=1 OR mbercar=2) AND (mberver = 1 OR mberver=2) AND (mberand = 1 OR mberand = 2)) AND ((bberaa =1 OR bberaa =2) AND (bberih=1 OR bberih =2) AND (bberhand=1 OR bberhand=2) AND (bberspez = 1 OR bberspez = 2)) AND ((mberaa =1 OR mberaa =2) AND (mberih=1 OR mberih=2) AND (mberhand=1 OR mberhand=2) AND (mberspez = 1 OR mberspez =2))

GOTO pn99999 IF sf_bber = 1 OR sf_mber = 1

**Comment by ChristophEn-git** [comment]
> **_pn5012_**
> 
> `tr: GOTO pn6001 IF absang = 1 OR absang = 2 OR IF absang = 5`
> 
> Diese Transition ist aus meiner Sicht unvollständig. Sollten sowieso nur Befragte, die "absang = 1 OR absang = 2 OR IF absang = 5" erfüllen auf diese Seite gelangen, ist die Transition bzw. deren Bedingungen überflüssig

Ist überflüssig und kann entfernt werden.

**Comment by ChristophEn-git** [comment]
> **_pn5013_**
> 
> `tr: GOTO pn6007 IF absang = 3 OR absang = 4`
> 
> Diese Transition ist aus meiner Sicht unvollständig. Sollten sowieso nur Befragte, die "tr: GOTO pn6007 IF absang = 3 OR absang = 4" erfüllen auf diese Seite gelangen, ist die Transition bzw. deren Bedingungen überflüssig

Ist überflüssig und kann entfernt werden.

**Comment by ChristophEn-git** [comment]
Ich hätte nochmal eine Frage bezüglich der Transition, vor allem in Verbindung mit SYSMISS.

Angenommen wir haben die folgende Frage (nur als Beispiel, die Umsetzung im Fragebogen ist anders, aber mir geht es um das Verständnis des Pinzips):

pn: pnXXXX
vn: z( z1/ z2/ z3)
qt: Einfachmatrixauswahl mit horizontalen ao
hl: 
in: Viele Studierende haben während Ihres Studiums ernsthafte Studienzweifel. Sie denken darüber nach, ob sie ihr Studienfach wechseln oder das Studium ganz abbrechen und treffen entsprechende Entscheidungen. 
q: Wenn Sie an Ihre Studienzeit denken: In welchem Maße haben Sie während Ihres letzten Studiums darüber nachgedacht, …
is: 

it1: … Ihr Studienfach an der Hochschule zu wechseln?
it2: … Ihr Studienfach und die Hochschule zu wechseln?
it3: … das Studium endgültig aufzugeben? 
st:
ao1: 1 : 1 : in hohem Maße
ao2: 2 : 2 :
ao3: 3 : 3 :
ao4: 4 : 4 :
ao5: 5 : 5 : überhaupt nicht 
...

Als Studienzweifler gelten alle, die zumindest einmal irgendwo eine 1 oder 2 angegeben haben.
Wenn ich jetzt explizit nur Befragte, die KEINE Studienzweifler sind weiterleiten möchte und ich setze den Filter wie folgt:

GOTO XY IF (z1= 3 OR z1 = 4 OR z1=5) AND (z2 = 3 OR z2 = 4 OR z2 =5)  AND (z3 = 3 OR z=4 OR z3 =5)

wird dann jemand der z1= 4, z2=SYSMISS, z3=5 hat zu XY weitergeleitet, oder muss ich noch explizit das SYSMISS in die Transition dafür einbauen? 

Je nach dem muss ich die Transitionen nochmal überarbeiten...


Ich bedanke mich für alle Anmerkungen und die Hilfe hier und versuche weiterhin nach bestem Wissen und Gewissen und nach Absprache mit Herr Hutzsch zu antworten.

**Comment by SilinaKowalewski** [comment]
@ChristophEn-git:

Lieber Christoph, 

vielen Dank für deine Rückmeldungen. Ich werde mich schnellstmöglich daran machen diese umzusetzen. Wichtig wäre allerdings für uns, dass du diese Änderungen auch in der Programmiervorlage anpasst und uns eine neue Version zuschickst. 

Zudem sind leider noch einige weitere Fragen von dem "Klammer-Problem" in den Transitions betroffen. Am besten du änderst diese direkt in der neuen Version der Programmiervorlage mit. 

Bezüglich deiner Frage zu den Transitions würde ich vorschlagen, dass wir einfach einmal kurz telefonieren. Du erreichst mich unter 0511-450670145. 

Liebe Grüße
Silina

**Comment by andreaschu** [comment]
@vdick, bei [pn1002](http://vmtest.dzhw.local:8080/Studienzweifler/pn1002.html) funktioniert das semant. Differential nicht.

**Comment by vdick** [comment]
fixed, ab nächsten Rollout verfügbar
