### ISSUE TITLE
WeGe: creating a project

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#306]
please clone the project of the last time.

**Comment by vdick** [comment]
Projects created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/WeGe-2020
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/WeGe-2020-Addon
Testserver (after first build):
http://vmtest.dzhw.local:8080/WeGe-2020
http://vmtest.dzhw.local:8080/WeGe-2020-addon
Presentation (after first build):
http://presentation.dzhw.eu/WeGe-2020
http://presentation.dzhw.eu/WeGe-2020-addon
