### ISSUE TITLE
WeGe: programming first draft

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#307]
[PV_WeGe_Welle_3_V-1-0-2.docx](https://github.com/dzhw/zofar/files/4159080/PV_WeGe_Welle_3_V-1-0-2.docx)

**Comment by SilinaKowalewski** [comment]
aktuelle Programmiervorlage per Mail am 05.02.: 

[PV_WeGe_Welle_3_V-1-0-2.docx](https://github.com/dzhw/zofar/files/4159312/PV_WeGe_Welle_3_V-1-0-2.docx)

**Comment by SilinaKowalewski** [comment]
@gruettner @CarOtto 

Hallo ihr Lieben, 

ich habe mich gestern mal direkt durch eure Programmiervorlage geklickt. Dabei sind mir einige Probleme aufgefallen: 

**Preload Token**

In einem Kommentar im "Info-Bereich" steht, dass ihr die Preload-Variable Token nicht mehr verwenden wollte. Später wird diese Variable aber für Weiterleitungsbedingungen genutzt. Sollen wir diesen Preload also weiterführen oder nicht? 

Achtet an dieser Stelle auch darauf, nicht Projekt-Intern in der PV zu kommunizieren. Das verwirrt mich nur ;) 

**Fragetypen**

Bei einigen Fragen (z. B.: stu11, stu12 ... ) scheinen mir die angegebenen Fragetypen "falsch" bzw. unpassend zu sein. Angegeben ist hier eine Mehrfachauswahlmatrix, allerdings sind keine Item vorgesehen. Zudem handelt es sich bei diesen Fragen um skalierte Abfragen, sodass ich davon ausgehe, dass ihr eine einfache SingleChoice-Frage meint, oder?

___

**doppelte Variablen**
Die Variablen s22001, s22002 und s80029 wurden doppelt vergeben.

___

**doppelte Seitennamen**
Die pn all25 wurde doppelt vergeben.

___ 

**fehlende Seiten**
Laut PV sollen die Seiten sta02 und sve03 nicht mehr in der Befragung angezeigt werden. In einigen Weiterleitungsbedingungen wird aber dennoch auf diese beiden Seiten weitergeleitet. 

__

**stu15**

Leider ist es nicht möglich, eine Skala mit Bildern zu belabeln. Das ist technisch nicht umsetzbar und wäre auch in Hinblick auf die Responsivität der Befragung sehr kritisch.

**Comment by gruettner** [comment]
preload token: Es wird in der aktuellen Befragung nur Personen mit preload token == 1 geben. Daher ist der (interne) Kommentar irreführend gewesen. 
In diesem Zusammenhang: Screens, die nach aktueller Filterführung niemand mehr zu Gesicht bekommt und die daher entweder auskommentiert oder bei der Überarbeitung einfach ignoriert werden könnten, habe ich ausgegraut.

P.S.: Es sind jetzt nur noch Kommentare drin, die sich an dich/euch richten.

Fragetypen:

Danke. Das ist beim copy-past und anpassen passiert und hinterher niemandem mehr aufgefallen. Entsprechende Unstimmigkeiten haben wir korrigiert.

doppelte Variablennamen:

Ein Übertragungsfehler aus unserem Konstruktbaum: richtig waren s21100-s21102, s80039 und das haben wir jetzt korrigiert.

doppelter Seitenname:

jetzt all26. Wird jetzt auch in der transition all25 -> all26 entsprechend genannt.

fehlende Seiten:

sta02 wird nur bei preload_token == 0 angesteuert. Das ist also unproblematisch.
sve03 wurde in der transition durch sta06 ersetzt.

stu15:

wie müssen wir euch das Objekt (Grafik) zuliefern, damit es in die Skalenbelabelung eingebunden werden kann?

Schon einmal vielen Dank an dich, Silina!
[PV_WeGe_Welle_3_V-1-0-3.docx](https://github.com/dzhw/zofar/files/4171362/PV_WeGe_Welle_3_V-1-0-3.docx)

**Comment by SilinaKowalewski** [comment]
@vdick: Könntest du bitte das Projekt so "ändern" dass nur noch die Eingabe eines Token als Login-Methode möglich ist? Einen Generic-Link soll es nicht mehr geben.

**Comment by gruettner** [comment]
Hi, ich denke, dass es schon so programmiert sein sollte. Das hatte Victor m.W. bei der letzten Welle dann schon angepasst. Aber gerne noch einmal checken.

**Comment by gruettner** [comment]
Danke für den first draft!
http://vmtest.dzhw.local:8080/WeGe-2020/ 

Leider geht es bisher nur bis zum Ende des screen all01. Danach geht es in den "DEBUG!".

Allerdings habe ich auch noch keine Testtoken und der Link oben lässt bisher auch keine Eingabe von Testtoken zu, und das wird der Fehler sein.

Könnt ihr uns bitte eine Liste mit 99 Testtoken bereitstellen? : 
99 mit preload-token == 1, davon 33 mit preload-pre_w02 == 1, 33 mit preload-pre_w02 == 2 und 33 mit preload-pre_w02 == 3. Damit sollten wir dann auch testen können. 

Danke!

**Comment by andreaschu** [comment]
@vdick könntest Du die Tester-Token hinzufügen (siehe docs-Ordner)

**Comment by vdick** [comment]
@erledigt

**Comment by andreaschu** [comment]
@vdick lässt sich nicht bauen. :disappointed: 

![grafik](https://user-images.githubusercontent.com/30111489/74243911-dd746700-4ce0-11ea-9187-06f6463f288b.png)

**Comment by andreaschu** [comment]
@gruettner tester sind enthalten und die Befragung ist verfügbar.

**Comment by CarOtto** [comment]
Hallo zusammen,

nachfolgend habe ich noch einige Änderungswünsche zum Online-Fragebogen:

**Index:** 
- Text unvollständig im 2. Absatz:
"Mit Ihrer Teilnahme an der Befragung unterstützen Sie die Forschung zur Situation von Menschen, die nach Deutschland gekommen sind und hier studieren möchten.  Egal, ob Sie zurzeit studieren oder etwas anderes machen:  Bitte nehmen Sie sich 20 Minuten Zeit um den Fragebogen zu beantworten. Sie können die Befragung jederzeit unterbrechen und später fortsetzen. Vielen Dank!" 

**Sta06**
- Punkt am Ende des 1. Items fehlt:
ao1: 1: Ich studiere in einem Studiengang an einer Hochschule oder Universität.

**Stu07**
- Klammer am Ende des letzten Items fehlt:
It5: Lernaktivitäten zeitlich sinnvoll zu strukturieren (z.B. Zeitpunkt und Dauer des Lernens) 

**Stu09**
- Item 3 Rechtschreibung korrigieren (zusammenzuarbeiten und Bindestrich bei „vorbereiten“ entfernen:
It3: im Team zusammenzuarbeiten (z.B. gemeinsam Aufgaben bearbeiten, Referate vorbereiten)

**Stu10**
- Item 3 „Mich“ groß schreiben:
It3: Mich aktiv in Seminaren, Übungen und Tutorien zu beteiligen (z.B. mitdiskutieren oder Fragen stellen)

**Stu12 und stu13**
AO1 und AO7 nicht komplett lesbar

**Stu14**
- Bei Item 2 fehlt die Unterstreichung bei „nicht“
It2: …zählt meine Leistung und nicht meine Herkunft.

**All12**
- Rechtschreibung bei q1 ändern: „Ihres“:
q1: Haben Sie vor Beginn Ihres Studiums an einem der genannten Angebote teilgenommen?

**All13**
- Rechtschreibung „Mal“
ao: Präfix [ao] Suffix: Ich habe mich [number] Mal beworben.

**All18**
-Filter funktioniert nicht
GOTO all19 IF s60000 == 5

**All20** 
-Punkt am Ende von ao1 löschen
ao1: 1: Finanzielle Unterstützung durch Familie

**all21**: 
-Skala ist Online falsch dargestellt bzw. falsch grau unterlegt (ao1 bis ao5 miteinander verbinden und mv absondern)

**all25**
- mv „gar nicht“ von den anderen aos absondern

**all26**
- Darstellung der Monate vereinheitlichen
- Zwar funktioniert die Auswahl einer Aktivität, aber danach ist keine Eintragung im Kalender möglich 
-bei der Auswahl der Aktivitäten steht ao5 unter dem Auswahlfeld und nicht daneben

**End02**
- Rechtschreibung:
in1: …dass Sie an unserer Befragung teilgenommen haben! Ihre Daten sind sicher auf unserem Server gespeichert. Mit Ihrer Teilnahme haben Sie einen wichtigen Beitrag zur Forschung geleistet. Sie haben nun die Möglichkeit Ihre Kontaktdaten zu aktualisieren und an einer Verlosung teilzunehmen.
In2: …dass Sie an unserer Befragung teilgenommen haben! Ihre Daten sind sicher auf unserem Server gespeichert. Mit Ihrer Teilnahme haben Sie einen wichtigen Beitrag zur Forschung geleistet. Damit wir wissenschaftliche Erkenntnisse über die Herausforderungen auf dem Weg ins Studium in Deutschland erarbeiten können, ist es wichtig, dass Sie im Jahr 2020 an einer weiteren Befragung teilnehmen. Bitte geben Sie uns nun die Möglichkeit, Sie für weitere Befragungen oder die Verlosung zu kontaktieren. 

-Weiterleitung auf end03, egal, was man auf end02 angibt


Vielen Dank und viele Grüße

Carolin

**Comment by andreaschu** [comment]
@CarOtto wir sind im neuen Issue unterwegs #308. Ich habe deine Anmerkungen dorthin kopiert.
