### ISSUE TITLE
WeGe: going online

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#309]

**Comment by SilinaKowalewski** [comment]
@gruettner @CarOtto

Um einen reibungslosen Feldstart zu ermöglichen würden wir gerne bereits jetzt alle erforderlichen Konfigurationen des Servers vornehmen. Hierfür benötigen wir allerdings noch den Namen den die Befragung bekommen soll. 

Es wäre also schön, wenn ihr uns zeitnah einen Namen nennen könntet.

**Comment by gruettner** [comment]
Wie wäre es mit "stups2020"?

**Comment by SilinaKowalewski** [comment]
@gruettner 
Für uns ist der Name ja recht egal ;) 
Werden wir dann so umsetzten.

**Comment by andreaschu** [comment]
@vdick der Lasttest könnte starten. Die Token hat Silina.
