### ISSUE TITLE
Navigation button

### ISSUE THREAD

**Issue by kastirke** [dzhw/zofar#31]
using FIREFOX

Please remove the navigation button "Befragung abschließen".

![unbenannt](https://user-images.githubusercontent.com/30147532/28659181-c2a12eea-72ae-11e7-82ff-e18691d452da.PNG)

**Comment by dzhwmeisner** [comment]
done

**Comment by Miktarbad** [comment]
fixed - removed mobile (Android) and on desktop (Win10).
