### ISSUE TITLE
WeGe: invitation

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#310]

**Comment by SilinaKowalewski** [comment]
Einladungstext pro Mail am 05.03.

[Einladungstext_WeGe_Welle3_fin.docx](https://github.com/dzhw/zofar/files/4305298/Einladungstext_WeGe_Welle3_fin.docx)

**Comment by SilinaKowalewski** [comment]
@CarOtto @SteffiSchroe: 

Um die Einladungstexte bzw. den Versand vorzubereiten benötige ich noch eine Info darüber, über welche Mail-Adresse die Einladungen verschickt werden sollen. Gebt mir doch bitte die Mail-Adresse sowieso die Zugangsdaten zu dem Account, dann kann ich auch direkt eine Text-Mail zukommen lassen.

**Comment by SteffiSchroe** [comment]
@SilinaKowalewski Hi, wir wollten gern von Michael's Adresse aus einladen. Die Zugangsdaten und das Passwort habe ich im Büro, bin aber heute im Homeoffice in Münster und kann Dir beides also erst morgen geben. Ist das in Ordnung?

**Comment by SilinaKowalewski** [comment]
@SteffiSchroe: Ja, das wäre schon in Ordnung. Brauche dann morgen nur relativ bald eine Rückmeldung auf die Test-Mail, zumindest für den Fall, dass ihr morgen einladen wollt.

**Comment by SteffiSchroe** [comment]
@SilinaKowalewski Mein Zug kommt (hoffentlich pünktlich) um halb zehn in Hannover Hbf. an. Ich sollte also mit der Nutzerkennung und dem Passwort gegen 10.00 Uhr zu Dir kommen können. Passt das zeitlich mit einer Rückmeldung zur Testmail und dem Plan, gegen 14.00 Uhr einzuladen?

**Comment by SilinaKowalewski** [comment]
@SteffiSchroe: Das sollte passen :)

**Comment by SteffiSchroe** [comment]
@andreaschu: Wie geht es Euch im Zofar-Team? Wird es Euch möglich sein, morgen die erste Erinnerung zu verschicken?

**Comment by andreaschu** [comment]
@SteffiSchroe uns geht es gut. Ja, wir können Morgen die Erinnerung verschicken. :o)

**Comment by SteffiSchroe** [comment]
OK, das ist natürlich fein. Es ist auch für uns schwierig, alles ein bisschen umzuorganisieren. Umso mehr Dankeschön an Euch, dass Ihr uns damit den Rücken freihaltet! Ihr seid super!

**Comment by SteffiSchroe** [comment]
@andreaschu Können wir heute noch einmal wegen der für nächsten geplanten Erinnerungsmail miteinander telefonieren?
