### ISSUE TITLE
WeGe: export data

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#313]

**Comment by gruettner** [comment]
Hallo,

Ist die Befragung geschlossen? Wann können wir mit dem finalen Datenexport rechnen?

Liebe Grüße

**Comment by gruettner** [comment]
Sehe gerade, die Befragung ist natürlich geschlossen. Aber der Datenexport in den geschützten Bereich fehlt bisher.

**Comment by andreaschu** [comment]
> Sehe gerade, die Befragung ist natürlich geschlossen. Aber der Datenexport in den geschützten Bereich fehlt bisher.

Ja, der ist noch nicht erstellt. Aber ihr habt ja bereits einen vorläufigen. 
Den endgültigen erstellen wir in den nächsten Tagen.

**Comment by andreaschu** [comment]
Ich habe den Transfer vom Export der Befragungsdaten und der Adressdaten veranlasst.
Im Doc-Ordner liegen zudem:
- FlowChart
- Rücklaufgraph
- Metadaten zur Bildschirmgröße, mobiler Gerätetyp (ismobile) und die (De-)Aktivierung von JavaSkript
- Datenschutzblatt
- Dokumentation der Kalendariumsvariablen
