### ISSUE TITLE
WeGe: screenshot

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#314]

**Comment by gruettner** [comment]
Hallo, das Issue ist noch offen. Hattet ihr uns die Screens schon zur Verfügung gestellt?

**Comment by andreaschu** [comment]
Hier der Screenshot aus dem MDM-Export. Einen anderen finde ich nicht.
[WeGe_Screenshot.pdf](https://github.com/dzhw/zofar/files/6575164/WeGe_Screenshot.pdf)
