### ISSUE TITLE
verifier: add syntactical check for zofar functions

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#329]

**Comment by dzhwmeisner** [comment]
- [ ] update Fake Zofar Functions (compare by Reflection)
- [ ] replicate logic of real Zofar Functions to fit the needs of Exporter Visibility Check

**Comment by dzhwmeisner** [comment]
outsource Fake Zofar Functions to aseparate Maven Project.
Check state of Fake and Real Version by Java Reflection

**Comment by dzhwmeisner** [comment]
add Zofar-Function-Dummies (incl. Fake-Logic) to Fake-Version and outsource to Maven-Project
