### ISSUE TITLE
calendar: FrontEnd

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#332]

**Comment by andreaschu** [comment]
- [ ] create a requirement list (#348)
- [ ] estimate expected effort
- [ ] clearify financial options
- [ ] prepare an announcement

**Comment by vdick** [comment]
https://presentation.dzhw.eu/calendar_new/calendar.html

**Comment by andreaschu** [comment]
Some more specific issues are openend, so this issue can be closed.
(#439, #440, #441, #442)
