### ISSUE TITLE
NACAPS 2019: export of metadata

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#333]
the FDZ needs an export of the metadata of NACAPS (first wave) to import it to the MDM.

**Comment by dzhwmeisner** [comment]
- [ ] Export in MDM Mode
- [ ] optional technical modifications
- [ ] Validate Output in MDM

**Comment by andreaschu** [comment]
FDZ needs also an export of the meta data for Promoviertenpanels 2014 (wave 3 - 5), see issue #349

**Comment by dzhwmeisner** [comment]
For MDM Export some Information needed:

DATAACQUESTIONPROJECT
SURVEYID
INSTRUMENTID
DATASETID

**Comment by UteH** [comment]
@dzhwmeisner thank you for the quick reply! (fyi @anneweber)

attribute | content
-- | --
dataAcquisitionProjectId | nac2018
studyId | stu-nac2018
instrumentId | ins1 (ins-gra2005-ins1)
DATASET   ID | ds1 (dat-gra2005-ds1)

**Comment by dzhwmeisner** [comment]
Exports ready for validation at faust/Abt4/Austausch/MDM

**Comment by anneweber** [comment]
Vielen Dank @dzhwmeisner !

**Comment by anneweber** [comment]
Hallo @dzhwmeisner , hallo @vdick ,
kleine Frage zu den Question-Metadaten, damit es kein Missverständnis gibt: Haben wir es richtig verstanden, dass diese jetzt bei Viktor zum Review liegen oder sind sie bereits an uns übergeben? Falls Review: Könntet Ihr uns kurz Bescheid geben, wann wir mit den finalen Dateien rechnen können? Lieben Dank!

**Comment by vdick** [comment]
@anneweber Daten sehen gut aus, können ins FDZ importiert werden

**Comment by anneweber** [comment]
@vdick Ok, danke für die schnelle Rückmeldung, dann versuchen wir es mal.

**Comment by UteH** [comment]
@dzhwmeisner @vdick thank you! we had a look at the files and have some question/remarks:
[Feedback_Zofar_Lieferung.pdf](https://github.com/dzhw/zofar/files/4413754/Feedback_Zofar_Lieferung.pdf)

**Comment by UteH** [comment]
@dzhwmeisner 
i was also wondering: when working on Modul H we planned to flag the "FDZ question" in QML (s. https://github.com/dzhw/zofar/issues/87#issuecomment-441259725). We wanted to use nacaps as a pilot project for that. Then, we could use `questions` instead of `pages`. 

Were u able to implement it? If not, we will use `pages` as usual

**Comment by UteH** [comment]
@dzhwmeisner 
about `Relatedquesionstrings`. In general, could you use line breaks instead of commas to separate the parts (reason: they are exported to a pdf and would look better with line breaks 🤓 ) 
(that's a new request, just taking the opportunity here to ask you, maybe that's easy to fix in the scripts 😇 )

**Comment by UteH** [comment]
@dzhwmeisner  @andreaschu wie ist die Lage?

**Comment by vdick** [comment]
@UteH Guten Morgen Ute, ich bin noch dran, sollte aber heute oder spätestens morgen ein Update geben

**Comment by vdick** [comment]
@UteH  Hallo Ute, sorry, aber ich bin gestern wohl etwas zu optimistisch gewesen..
Mein letzter Lösungsansatz hat nicht funktioniert und das Fixen der Bugs geht weiter. Ich gehe davon aus, dass es noch ein paar Tage dauern wird.  Versuche aber schnellstmöglich eine Lösung zu finden.

**Comment by UteH** [comment]
@vdick gibts ein Upsate :)?

**Comment by anneweber** [comment]
Lieber @vdick , kannst Du uns bitte noch ein Update geben? Wir benötigen die neuen Metadaten jetzt zeitnah, um weiterarbeiten zu können. Danke und viele Grüße! Anne

**Comment by anneweber** [comment]
@vdick und ich haben gerade telefoniert (lieben Dank für den Anruf!). Das Problem ist bislang leider noch nicht gelöst. Es wird aber permanent daran gearbeitet, Christian wird demnächst auch noch unterstützen. Es wird gehofft, dass in den nächsten Tagen eine Lösung gefunden wird.

**Comment by UteH** [comment]
Hi @dzhwmeisner @vdick wie ist denn die Lage?

**Comment by vdick** [comment]
Hallo @UteH wir sind noch dran, einige Bugs konnten gefixt werden, ein paar sind noch offen.

**Comment by anneweber** [comment]
Hallo @vdick , danke für die Rückmeldung. Kannst Du denn sagen, wie lange es in etwa noch dauern wird?

**Comment by anneweber** [comment]
@vdick Könntest Du mir noch eine kurze Rückmeldung geben, bis wann die restlichen Bugs voraussichtlich und nach aktueller Einschätzung gefixt werden können? Lieben Dank!

**Comment by vdick** [comment]
Hallo @UteH  und @anneweber , das Gröbste ist behoben, wollte euch heute morgen einen Export liefern, aber mir sind noch ein paar Problemfälle aufgefallen, wo die Änderungen nicht funktioniert haben. Ich hoffe diese bis morgen gelöst zu haben.  Sofern alles gut geht, bekommt ihr morgen gegen Nachmittag einen Export. Sorry für die Verzögerung..

**Comment by anneweber** [comment]
@vdick Alles klar, dankeschön für das Update! Wir drücken die Daumen.

**Comment by vdick** [comment]
Hallo @UteH und @anneweber , es dauert leider noch an ((
Die letzten 2 Exporte sind noch nicht sauber gewesen..

**Comment by anneweber** [comment]
Hallo @vdick , könntest Du uns noch mal ein kurzes Update zum Stand der Dinge geben? Lieben Dank!

**Comment by anneweber** [comment]
@vdick Könntest Du hier noch mal kurz schreiben, wie es aussieht? Vielen Dank!

**Comment by anneweber** [comment]
Hi @vdick , ich wollte nur noch mal fragen, wie die Lage ist? Liebe Grüße!

**Comment by vdick** [comment]
Hallo @anneweber, es ist nur noch ein Bug da, hoffentlich bekomme ich diesen heute gefixt und im Anschluß gibt's den Export.  Es gab in den letzten Arbeitstagen ein paar Aufgaben, die dringender waren, daher hat sich alles etwas verzögert

**Comment by anneweber** [comment]
@vdick Super, dankeschön für die Info!

**Comment by vdick** [comment]
Hallo @anneweber, leider ist auch der letzte Export  fehlerhaft und die Suche geht weiter.. 
Wegen der in Kürze anstehenden Befragung (sid) muss ich die Arbeiten am MDM-Export auf Ende nächster Woche verlegen, ab da wird sich auch Christian wieder mit den Problemen beschäftigen.
LG

**Comment by anneweber** [comment]
@vdick Ok, danke Dir für die Info (Du hattest auch vorhin angerufen, oder? Sorry, ich war da gerade in der Pause und hab es nicht gehört) und viel Erfolg Euch beim SiD-Start.
Eine kurze Frage noch: Betrifft der bestehende Bug nur einen Teil des Exports oder Alles? Wenn z.B. die Datei für die variables oder das Dokument mit allen Screenshots schon fertig wären, nehmen wir auch gerne schon eine Teillieferung :).

**Comment by vdick** [comment]
Guten Morgen @anneweber, wie abgesprochen, findest du die Variables.csv auf dem faust-server unter faust/Abt4/Austausch/MDM

**Comment by anneweber** [comment]
Cool @vdick , vielen lieben Dank dafür!

**Comment by anneweber** [comment]
Guten Morgen @vdick ,

wir haben uns den Export jetzt angeschaut und die Übersetzungen scheinen alle drin zu sein. 👍 

Die anderen beiden Probleme, die @UteH in dem Dokument oben (https://github.com/dzhw/zofar/issues/333#issuecomment-607104541) gemeldet hatte bestehen allerdings weiterhin.

- Teilweise Fragenummern falsch, z.B.:
![image](https://user-images.githubusercontent.com/17066262/84113595-2a681000-aa2b-11ea-9a71-5b08e7186d3a.png)

- Frage A14 scheint jetzt ganz zu fehlen. (Ob das evtl. noch weitere Fragen betrifft, habe ich nicht geprüft. Ich habe nur gezielt nach A14 geschaut, weil hier im Dokument oben ein Problem aufgefallen war.)

- Zudem ist die Instrument ID jetzt 3, müsste aber 1 sein, oder?

- Außerdem scheinen teilweise Texte zu fehlen, z.B.:
![image](https://user-images.githubusercontent.com/17066262/84113864-a4989480-aa2b-11ea-8474-7dae9da6718e.png)


Könntet Ihr Euch das bitte auch noch mal anschauen, wenn Ihr daran weiterarbeiten könnt?

Lieben Dank!

**Comment by rbirkelbach** [comment]
Hi, @vdick bist du bereits dazu gekommen die von @anneweber angesprochenen Punkte anzugehen und ich habe es nur übersehen? Falls nicht: wann denkst du, dass du dazu kommst? Danke schonmal!

**Comment by andreaschu** [comment]
@anneweber und @rbirkelbach bezüglich der 'falschen' Variablennamen haben wir ja schon rausgefunden, dass das doppelt verwendete Variablen mit verschiedenen Texten sind, die jeweils mit der Raute getrennt sind. Ich war bei der Entwicklung nicht wirklich involviert, aber für mich sieht das aus, als sollte das so. Wenn nicht, müsstet ihr überlegen, wie das exportiert werden soll. Ein Vorschlag wäre, es ganz zu trennen, also von vorher so:

![image (1)](https://user-images.githubusercontent.com/30111489/85123038-cf52cc00-b227-11ea-827c-7fe74a3a5a18.png)

zu so:

![grafik](https://user-images.githubusercontent.com/30111489/85123152-045f1e80-b228-11ea-8e8b-c65e537a4d3b.png)

**Comment by rbirkelbach** [comment]
Beim letzten Export waren auch immer noch an ein paar Stellen die questionText.de/en Felder leer.

**Comment by UteH** [comment]
### Review besprochen mit @andreaschu @dzhwmeisner 
variables: https://github.com/dzhw/nac2018.1/issues/108
questions: https://github.com/dzhw/nac2018.1/issues/120
instrument: https://github.com/dzhw/nac2018.1/issues/112
