### ISSUE TITLE
SiD: creating a project 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#334]

**Comment by dzhwmeisner** [comment]
- [ ] test the brand new Project Creator
- [ ] create addon

**Comment by vdick** [comment]
Projects created:
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/sid-2020
https://vmvcs.dzhw.local/svn/hiob/tags/surveys/sid-2020-Addon
Testserver (after first build):
http://vmtest.dzhw.local:8080/sid-2020
http://vmtest.dzhw.local:8080/sid-2020-Addon
Presentation-Server (after first build):
http://presentation.dzhw.eu/sid-2020
http://presentation.dzhw.eu/sid-2020-Addon
