### ISSUE TITLE
make calendar creator usable

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#341]
as a zofar user I want to create the qml for a calendar by my own.

**Comment by dzhwmeisner** [comment]
- [ ] configuration as properties File
- [ ]  create JAR with dependencies to use in CLI
- [ ]  field testing

**Comment by vdick** [comment]
Request for testing
http://vmdevwiki.dzhw.local/intern/Generator.zip

**Comment by christian-fr** [comment]
Just a hint: in Windows paths work if I double-escape them:

```
C:\\tmp\\Generator\\
```

**Comment by dzhwmeisner** [comment]
@andreaschu comment and correct read me-file
