### ISSUE TITLE
make it possible to create a project

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#342]
as a zofar user I want to create a new project by my own.

**Comment by dzhwmeisner** [comment]
- [ ] add Verifier execution for SpelCheck
- [ ] update Configuration modifications.
- [ ] create Addon-DB for testing
- [ ] create Cockpit/Exporter Configurations (for Webstart Replacement)
- [ ] create JAR with dependencies to use in CLI

**Comment by dzhwmeisner** [comment]
Request for testing
http://vmdevwiki.dzhw.local/intern/Automation.zip

**Comment by vdick** [comment]
@dzhwmeisner  works very well :) 
checked: svn, jenkins, rest-server, db server

**Comment by christian-fr** [comment]
good job!
I just created my first project :)
checked: svn, jenkins, db-server
http://vmbuild.dzhw.local:8080/job/TestSurvey123xyz

the jenkins build also worked well, but it could not be deployed:
>![grafik](https://user-images.githubusercontent.com/42959832/74920980-55234f80-53cd-11ea-9fa3-bf05f00f52b4.png)

**Comment by dzhwmeisner** [comment]
The Jenkins Problem was temporary. everything running again.

**Comment by andreaschu** [comment]
@vdick after opening the jar-file I just don't know what to do. The readme.txt does not help me much. :o(
