### ISSUE TITLE
calendar: dynamic visibility in calendar dialogue

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#343]
As a zofar user I want the visibility of event properties to be dynamic depending on the selection of event type (drop down) masking in calendar dialogue to restrict the possible answer options for each element type.

**Comment by dzhwmeisner** [comment]
implemented. Have a look at http://vmtest.dzhw.local:8080/Test_Modul.
In Dialog Name Field become invisible by selection of type "Studium"

**Comment by andreaschu** [comment]
seems to work also in the latest version: https://presentation.dzhw.eu/calendar_new/calendar.html
