### ISSUE TITLE
calendar: display additional event properties in calendar

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#344]
To enhance the correction mode for respondents, informations of events that are not surveyed in the initial calendar, should be possible to be displayed in the (correction) calendar, preferable via mouse over.

**Comment by dzhwmeisner** [comment]
- [ ] add zofar function to splfit episodes

**Comment by dzhwmeisner** [comment]
lets do in two steps:
1. show all episode properties
2. filter displayed properties

Create API for displaying episode properties overview in calendar (for external contractor).
