### ISSUE TITLE
Calendar: SLC Beispielmodul

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#347]
Let's test the functionalities in a small project that includes a large amount of the function range.

**Comment by andreaschu** [comment]
@jocarstensen and @se-lang could you provide us a small project?

**Comment by jocarstensen** [comment]
Is this sufficient?


[Testszenario Ausbildung.pdf](https://github.com/dzhw/zofar/files/4198644/Testszenario.Ausbildung.pdf)

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner: 

Ich habe das Test-Modul angelegt und nach bestem Wissen und Gewissen mit den Fragen und Weiterleitungen des Flow-Charts gefüllt. 

Das Projekt heißt "Test_Modul" und liegt auf dem SVN unter [tag/surveys/Test_Modul]. 

Hier fehlt aber noch der Counter und die Informationen aus dem Kalendarium (AB-Episoden vorhanden/Kalendarium unvollständig). Könntest du bitte diese Bedingungen einbauen oder mir erklären wie das geht? :)

**Comment by dzhwmeisner** [comment]
QML for it is created,
functionality for checking if calendar is filled completely. (#357)
functionality for checking existance of specific episode (#358). 
implement loops (#359)
functionality for splitting and creating new episodes (#360)

**Comment by andreaschu** [comment]
We need testcases.

**Comment by christian-fr** [comment]
definition of done: syntax is correct

**Comment by dzhwmeisner** [comment]
review Episode-related parts of QML

**Comment by andreaschu** [comment]
@jocarstensen könntest Du uns das FlowChart noch mal als .graphml-Datei zukommen lassen, damit wir den aktuellen Stand daran dokumentieren können.

**Comment by jocarstensen** [comment]
Kommt per Mail da hier nicht unterstützt.

**Comment by christian-fr** [comment]
## PDF
[2021-07-28_questionnaire_Test_Modul_Episode_Calendar_LOOP1_001.pdf](https://github.com/dzhw/zofar/files/6892835/2021-07-28_questionnaire_Test_Modul_Episode_Calendar_LOOP1_001.pdf)

## SVG & graphml
[2021-07-28_questionnaire_Test_Modul_Episode_Calendar_LOOP1_001.zip](https://github.com/dzhw/zofar/files/6892836/2021-07-28_questionnaire_Test_Modul_Episode_Calendar_LOOP1_001.zip)

**Comment by andreaschu** [comment]
[Testmodul_Ausbildung.pdf](https://github.com/dzhw/zofar/files/6893006/Testmodul_Ausbildung.pdf)

**Comment by andreaschu** [comment]
@christian-fr or @dzhwmeisner we still need the auxiliary variables or whatever for STARTDATUM and ENDDATUM to complete the questions like _"Sie haben angegeben von [Startdatum] bis [Enddatum] eine Ausbildung gemacht zu haben."_

How do we implement that into the qml-code?

**Comment by andreaschu** [comment]
The programmed status is: 
[Testmodul_Ausbildung_20210804.pdf](https://github.com/dzhw/zofar/files/6931971/Testmodul_Ausbildung_20210804.pdf)
[Testszenario Ausbildung.zip](https://github.com/dzhw/zofar/files/6931972/Testszenario.Ausbildung.zip)

I guess this is already programmed but I am not sure what the trigger and condition is so it's not described in the flow chart: the case when one episode loop is finished but there is another episode reported in the calendar (or it was the last reported episode).

We may still need  auxiliary variables for Start- and Enddatum instead of vaa01 to vaa04. But this can be decided later. For testing it should work that way.

**Comment by christian-fr** [comment]
this issue can be closed

**Comment by andreaschu** [comment]
https://presentation.dzhw.eu/EpisodeCalendar
