### ISSUE TITLE
Calendar: Requirement List for FrontEnd

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#348]

**Comment by andreaschu** [comment]
- parallel events of the same event type: as there can be parallel events of the same type in life, the calendar have to support parallel events of the same type
- the respondent should be able to define and describe an event freely with a name as well as with some further details (e.g. event type, full-time/part-time for an employment event) 
- the amount of events shouldn't be limited
- the events are on basis of months and should be presented in this way 
- events have to be editable: when reported an event once, it should be editable afterwards for the respondent
- the calendar have to be usable for touchscreens as well as for desktop
- the calendar have to be readable for small screens as well as for big screens
- as the respondents don't have feedback while answering the questions filling out the event calendar should be as intiutive as it can be
- it should be possible to limit the time frame to only some months of a year (e. g. by greying out the other ones)

**Comment by dzhwmeisner** [comment]
- The communication to Backend is by JSon-Array, which are communicated via invisible Input-Field

`[{"id":0,"name":"episode1","type":"Slot3","startDate":"2018-02-01T01:00:00.000Z","endDate":"2019-05-31T01:00:00.000Z","color":"#2C8FC9"},{"id":1,"name":"episode2","type":"Slot4","startDate":"2018-02-01T01:00:00.000Z","endDate":"2021-04-30T01:00:00.000Z","color":"#9CB703"},{"id":2,"name":"jklhjklj","type":"Slot2","startDate":"2018-04-01T01:00:00.000Z","endDate":"2022-05-31T01:00:00.000Z"}]`

- Communication with Backend:
  - Getting Data from Backend while entering Page
  - Send Data to Backend while leaving Page

- Products, we need for Survey System Integration:
  - HTML-Code (will be implemented in Renderers)
  - JavaScript (will be included in resources/html5/js/master.js)
  - CSS (will be included in  resources/html5/css/master.css)
