### ISSUE TITLE
Promopanel: export of metadata

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#349]
For the waves 3, 4 and 5 of Promoviertenpanel 2014, do:
- [x] Export in MDM Mode
- [ ] optional technical modifications
- [ ] Validate Output in MDM

**Comment by dzhwmeisner** [comment]
For MDM Export some Information needed:

DATAACQUESTIONPROJECT
SURVEYID
INSTRUMENTID
DATASETID

**Comment by svietgen** [comment]
Hello @dzhwmeisner ,

- the dataAcquisitionProjectId is **phd2014**,  
- surveyId: sur-phd2014-**sy3**, sur-phd2014-**sy4** and sur-phd2014-**sy5** (Welle 3-5)
- instrumentId: ins-phd2014-**ins3**, ins-phd2014-**ins4** and ins-phd2014-**ins5** (Welle 3-5)
- datasetId: dat-phd2014-**ds1**

**Comment by dzhwmeisner** [comment]
Exports ready for validation at faust/Abt4/Austausch/MDM

**Comment by McWallis** [comment]
Hello @vdick, can you please assign me as soon as the data is ready for the FDZ. Thank you and best regards Marten

**Comment by vdick** [comment]
the data is ready for validation as dzhwmeisner committed 11 days ago

**Comment by McWallis** [comment]
Thank you.

**Comment by vdick** [comment]
you're welcome :)
