### ISSUE TITLE
Carousell

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#35]
To Do:

- [x] code review
- [x] debugging
- [x] testing

**Comment by dzhwmeisner** [comment]
ready to test

**Comment by Miktarbad** [comment]
![cours-560-700px-labels](https://user-images.githubusercontent.com/29864065/31601577-9e9f786c-b25a-11e7-816b-55b56609a447.jpg)
![cours-560-750px-labels-doublescm](https://user-images.githubusercontent.com/29864065/31601578-9eb92f5a-b25a-11e7-9209-253bfa46efb9.jpg)

Range around 550-750 px width has still missing labels on SCM, SCDM and MCM.

- [ ] Mobile Device (Samsung Galaxy S7 - Android 7.0 - Chrome) works flawless.

**Comment by kastirke** [comment]
Can you add an indicator for the item number (see clickable counter in the lower picture)?

![grafik](https://user-images.githubusercontent.com/30147532/31723884-64244d30-b420-11e7-8b71-535bcfbb8944.png)

**Comment by kastirke** [comment]
Is it possible that the next item is automatically displayed when the last item is answered?

**Comment by dzhwmeisner** [comment]
Visibility Bug in Matrix Carousel fixed.
Number Indicators and automatically next click on Answer should be separated Issues

**Comment by kastirke** [comment]
👍 
checked "Visibility Bug in Matrix Carousel fixed."

**Comment by Miktarbad** [comment]
Changes are functional, tested by two testers - therefore closed.
