### ISSUE TITLE
Webstart Replacement: additional variables in Cockpit

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#350]
As a user I want the labels only to be visible in the cockpit, if there are additional variables to be reported.

![grafik](https://user-images.githubusercontent.com/30111489/75342640-14c54500-5897-11ea-81fc-55366f6e43c7.png)

**Comment by dzhwmeisner** [comment]
fixed

**Comment by andreaschu** [comment]
Funzt. Ich mach zu.
