### ISSUE TITLE
calendar: functionality for checking if calendar is filled completely

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#357]

**Comment by dzhwmeisner** [comment]
implemented. Have a look at http://vmtest.dzhw.local:8080/Test_Modul

**Comment by dzhwmeisner** [comment]
Zofar-Function isEpisodesComplete exists.
Checks if there are no days without Episode between start of first Episode and End of last Episode

**Comment by christian-fr** [comment]
there was a bug - vdick created a new version of the function, we should test / evaluate it and then possibly close the issue

**Comment by vdick** [comment]
the bug was fixed, Zofar-Function isEpisodesComplete is working now
