### ISSUE TITLE
calendar: functionality for splitting and creating new episodes

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#360]
implementation of splitting and creating with input one episode and breakpoint return two episodes.

**Comment by andreaschu** [comment]
@jocarstensen wir haben doch noch Nachfragen zu dem Slitten von Episoden: 
1. Wenn durch die Nachfragen eine neue Episode entsteht, sollen dann die Monate der beiden Episoden aneinander grenzen (also wie in der Darstellung: Ep.1 bis Aug. 2018 und Ep.2 ab Sept 2018) oder soll es hier eine Überschneidung geben (also: Ep.1 bis Sep. 2018 und Ep.2 ab Sept 2018)?
2. wenn durch die Nachfragen eine Episode zwischen zwei vorhandenen geschoben wird (zweite Abbildung), soll sie dann tatsächlich dazwischen sein, oder am Ende (lt. Beispiel dann Episode 4 werden)?

Ich hoffe die Fragen waren verständlich. Ansonsten können wir gern telefonieren/slacken.

**Comment by jocarstensen** [comment]
@andreaschu Kannst Du bitte Sebatian auch assignen?

**Comment by jocarstensen** [comment]
Zu 2: In der Grafik soll Episode 3 vor dem Split identisch sein mit Episode 4 nach dem Split oder? Es geht hier nur um Episode 2 (vorher) bzw. Episoden 2 und 3, richtig? Episode 3 (vorher) bzw. 4 (nachher) hat nämlich unterschiedliche Startdaten.

**Comment by andreaschu** [comment]
Assignen kann ich ihn nicht. Deswegen so: @se-lang kannst Du was zu den Fragen aus dem Kommentar (https://github.com/dzhw/zofar/issues/360#issuecomment-920724015) sagen?

**Comment by andreaschu** [comment]
> 
> 
> Zu 2: In der Grafik soll Episode 3 vor dem Split identisch sein mit Episode 4 nach dem Split oder? Es geht hier nur um Episode 2 (vorher) bzw. Episoden 2 und 3, richtig? Episode 3 (vorher) bzw. 4 (nachher) hat nämlich unterschiedliche Startdaten.

Oh, ist mir gar nicht aufgefallen. Ja, es geht nur um die Definition und Position der neuen Episoder 3 (aktive Episode) bzw. der Änderung von Episode 2 zu Episoden 2 und 3. 
Episode 3 (vorher) und Episode 4 (nachher) sollen identisch sein.

**Comment by andreaschu** [comment]
Es hat darstellerische Auswirkungen und Auswirkungen darauf in welcher Reihenfolge sie ggf. noch mal aufgerufen werden (auch wenn das nicht passiert oder intendiert ist).

Und die andere Frage (Frage 1) ist die, ob die Episoden aneinander grenzen sollen oder überlappen. Wenn also die Frage lautet _"Wann hat sich Ihr Ausbildungsberuf geändert?"_ und dann **Sept. 2018** angegeben wird, soll die erste Episode bis August 2018 (wie im Beispiel) gehen oder bis September?

**Comment by jocarstensen** [comment]
Zu Frage 1: Bitte ohne Überlappungen und im Fall des Beispiels dann August, also Erster Split bis Monat vor Änderungsdatum, zweiter Split ab Änderungsdatum

Zu Frage 2: Sie sollte tatsächlich dazwischen sein. Also von 1 - 2 - 3 auf 1 - 2a - 2b - 3

**Comment by andreaschu** [comment]
Die Aufteilung von Episoden klappt gut in den Json-Objekten: die Eigenschaften werden kopiert und die Anfang- und Enddaten angepasst. 
Die neu entstandene Episode (die zweite) wird aber nicht ins Kalendarium übertragen und deshalb kommt man auch nicht mehr in die ntsprechende Schleife dazu.

**Comment by andreaschu** [comment]
@dzhwmeisner ich glaube, ich habe den Fehler gefunden. 
Offenbar wird in der kopierten Episode auch das Enddatum verändert, so dass das Enddatum in der neu erstellten Episoder vor dessen Startdatum ist.

![InkedScreenshot 2021-12-10 at 16-22-50 Zofar Demo_LI](https://user-images.githubusercontent.com/30111489/145598288-3c7fd914-2599-44d9-b072-dea945bf1460.jpg)

**Comment by dzhwmeisner** [comment]
fixed

**Comment by andreaschu** [comment]
The functions are working. It should be testet substantially by project team.
