### ISSUE TITLE
MDM-Export (variables/questions): Korrekturen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#362]
## variables
<br>

- [x] `pageNumber` als eigene Spalte hinzufügen 
- [x] `pageNumber` ohne ".1"-Zusatz

**relatedQuestionStrings.de/en**
- [ ] Teilweise sind die `relatedQuesionStrings.de/en` gar nicht gefüllt. Ich vermute, dass dies auch ein systematischer Fehler ist und mit der Art und Weise, wie programmiert wurde, zusammenhängt. Der genauen Systematik sollte mal vom Zofar-Team auf den Grund gegangen werden (oder Ute? ich schaffe es gerade leider nicht genauer nachzuforschen). **-> Christian meint, die Lösung zu haben: offene Antwortformate, bei denen der Fragetext nicht mitgenommen wurden; Ute letzten Export prüfen**
   - [ ] ~leer:~ Text auch im neuen Export nicht vollständig adsv05ba, adsv05ca, adsv07b, adsv07c, adsv08ba, adsv08ca, apar01b (s auch [dieses Issue](https://github.com/dzhw/nac2018.1/issues/108#issuecomment-656081269))
- [ ] Dadurch sind in allen Fällen, bei denen es mehrere questions pro page gab, auch die `relatedQuesionStrings.de/en` nicht korrekt (sie enthalten jeweils nur Einzelelemente der Texte, aber nicht den Gesamttext zur Page). **-> Christian schaut es sich an, ob das so möglich ist; ist wahrscheinlich nicht immer automatisiert möglich** ❗ 

**Rauten-Trenner** bei mehreren Texten pro Variable
- [x] statt Raute Zeilenumbruch (\n) als Trennzeichen zwischen den verschiedenen eingeblendeten Texten verwenden
- [x] wenn nur eine question pro page: gleiche Information mehrfach enthalten, getrennt mit Raute, z. B. "B21.1 # B21.1" --> muss zu "B21.1" werden ([Beispiele](https://github.com/dzhw/nac2018.1/issues/108)) in den Spalten
  - `name` (aka varliablen_id)
  - `intrumentNumber` (aka instrumentId)
  - `questionNumber` (aka question_number)

**Umbenennungen**
- [x] CSV `variables` --> `relatedQuestions` 
- [x] Spalte `varliablen_id` --> `name`  
- [x] Spalte `instrumentId` --> `instrumentNumber`  
- [x] Spalte `question_number` --> `zofarQuestionNumber`  (von Ute: Achtung, Änderung ❕ )

**Dynamik**
- [ ] Platzhalter in Frage- und Itemtexten ersetzen durch besser lesbare Formulierung (z. B: statt `#{zofar.valueOf(adcd08o)}` 
  - [ ] de: -> `Wert von adcd08o` 
  - [ ] en: -> `value of adcd08o`

---
## questions
<br>

- [x] Screenshots von Items in Carousels in 'richtige' Reihenfolge screenshooten  **-> Christian schaut sich an** ❗ 
- [ ] überlappende Texte bei einzelnen Screenshots (z.B. B21.1, ebenso d24.1 ebenso e17.1)  **-> Christian schaut sich an, ob das so war** ❗ 
- [x] Wenn es verschiedene Frageformulierungen gibt bitte mit Zeilenumnruch statt "," trennen. 
- [ ] Screenshots der Carousel-Items (bei Units) mit Einblendbedingungen screenshooten

>  In der Gegenwartsvariante der Itembatterie steht immer noch mal der Satzanfang für die Vergangenheitsvariante der Itembatterie „In meinem wissenschaftlichen Umfeld gab es immer jemanden der“
   ![grafik](https://user-images.githubusercontent.com/18573122/86352865-c241ce00-bc66-11ea-8d78-0d22617c7e1f.png)

**Comment by UteH** [comment]
habe issue gereviewt und deassigne mich daher :)

**Comment by rbirkelbach** [comment]
Hallo, ich wollte fragen, wann ihr in etwa zu dem Issue kommen werdet?

**Comment by andreaschu** [comment]
Das Issue ist etwas unübersichtlich geworden. Mir ist nicht klar, was hier noch offen ist, außer das mit den Platzhaltern (Platzhalter in Frage- und Itemtexten) wofür es ein eigenes Issue gibt (#373).
Ich schließe mal.
