### ISSUE TITLE
MDM-Export instruments: Korrekturen

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#363]
eigentlich brauchen wir diese images (pages)
`"\\faust\Abt4\Austausch\MDM\instrument_template"`
- [x] getrennte Dokumente für
  - [x] de
  - [x] en
- [x] nur Desktopauflösung
- [x] Inhaltverzeichnis: Seitenzahlen nicht überlappen
- [x] mit page-Überschriften (z. B. "A05")
- [x] kein ODT mehr, solange es keinen besseren Screenshotter gibt

**Comment by dzhwmeisner** [comment]
\\faust\Abt4\Austausch\MDM\instrument_template war leider nicht mehr verfügbar. Änderungen werden im nächsten Export realisiert sein

**Comment by andreaschu** [comment]
Ich habe es an WeGe getestet. Sieht gut aus, deswegen mache ich hier zu.
