### ISSUE TITLE
exporter: wrong missing code -9995 instead of -9990 for items with visible condition

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#365]
### corona-sid/studium-corona
The exporter seems to wrongly set the code `-9995` for a couple of cases where the approriate code should be `-9990`.

We found evidence of that in the dataset of **corona-sid/studium-corona**:

Variable _zufrvstbe_ (page **D3_22**) shows the value `-9995`, although _h_gartcount_ exhibits a value greater than or equal to `1`.

The visible conditon for the corresponding item (**i5**) on page **D3_22**:
 ```
<zofar:item uid="i5" visible="zofar.asNumber(h_gartcount) ge 1 or gartka.value">
``` 

It is safe to conclude that the item has been shown to the respondent, although in the export-dataset the variable has been assigned the value `-9995`.

The problem onyl arises in cases where the _gartka.value_ evaluates to `false` (or `0` in the dataset).

We identified the tokens which exhibit this error, they can be found here:
`\\faust.dzhw.local\Abt4\Service\Servicebereich_Onlineforschung\02_Service\Befragungen\Sozialerhebung (SE)\corona-sonderbefragung\2020-07-23_exporter_bug\2020-07-23_tokenliste_gartcount.xlsx`

### Nacaps-Pre-2018
We also found some older evidence of this bug, in the dataset of **Nacaps-Pre-2018**:
> ![grafik](https://user-images.githubusercontent.com/42959832/88285240-06b50c80-ccef-11ea-9085-7253cb5fe247.png)
> ![grafik](https://user-images.githubusercontent.com/42959832/88285269-1896af80-ccef-11ea-808e-8b9deb193439.png)

**Comment by andreaschu** [comment]
presumebly the problem is caused by the decision client.

**Comment by christian-fr** [comment]
@dzhwmeisner fixing faked zofar functions in webstart replacement and standalone exporter

**Comment by dzhwmeisner** [comment]
starting debugging....

**Comment by dzhwmeisner** [comment]
fixed and rolled out to webstart_replacement. Request for testing

**Comment by andreaschu** [comment]
@dzhwmeisner couldn't test it for I am not getting any export out of the exporter. Could you have a look?

**Comment by christian-fr** [comment]
successfully tested the modified exporter. looks good! issue can be closed
