### ISSUE TITLE
CSS modifications: what we learned from SLC

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#366]
(häufige CSS-Fehler im responsiven Design evtl. an zentraler Stelle lösen)

**Comment by andreaschu** [comment]
correct or optimize the [breakpoints](https://getbootstrap.com/docs/5.0/layout/breakpoints/)

**Comment by SilinaSchirmer** [comment]
Häufiger CSS-"Fehler" oder Änderungswünsche aus SLC und SiD:

- [ ] Infield-Texte ein/ausblenden

- [ ] Unit ausblenden
- [ ] Unit-Textfeld zu klein

- [ ] **Items linksbündig stellen (global lösbar?)**

- [ ] Exklusiv-Kategorie absetzen
- [ ] Verbindungslinien entfernen

- [ ] Radiobutton ausblenden (bei eigentlich offener Frage)

- [ ] **Prefix vor offenem Textfeld im Karussells nicht lesbar (global lösbar?)**
- [ ] **Counter im Karussells fehlt (global lösbar?)**
- [ ] **Counter im Karussells fängt bei 0 an (global lösbar?)**


- [ ] Dropdowns hintereinander
- [ ] **Pfeile im Akkordeon (global lösbar?)**

- [ ] Skalenbeschriftungen überlappen sich oder werden an den Rändern abgeschnitten
- [ ] **Spaltenbeschriftung zentrieren (global lösbar?)**
- [ ] Skalenbeschriftung näher/weiter zur Skala
- [ ] Skalenbeschriftung näher/weiter zum Fragetext
- [ ] Skalenbeschriftung nicht über Fragetext

**Comment by andreaschu** [comment]
**Spaltenbeschriftung zentrieren** should be testet

**Comment by andreaschu** [comment]
can be closed if the last point (Spaltenüberschriften … ) is testet.

**Comment by SilinaSchirmer** [comment]
> **Itemtexte horizontal zentrieren** should be tested

Die Itemtexte sehen gut aus!
