### ISSUE TITLE
MDM-Export: Metadaten für die Studien StuMa und WeGe

### ISSUE THREAD

**Issue by anneweber** [dzhw/zofar#367]
Hallo liebes Zofar-Team, (@AndyDaniel1 zur Info)

wir benötigen einen Export für das MDM für die Studien "Ursachen der Studienaufgabe im Masterstudium (StuMa)" und "Wege von Geflüchteten an deutsche Hochschulen (WeGe)". Ich hoffe, ich hab richtig nachgesehen, dass beide Studien mit Zofar durchgeführt wurden?

Prio 1 sollte StuMa haben, Prio 2 WeGe.

Es ist nicht superdringend, aber für StuMa wäre es gut, wenn uns der Export im Laufe des Aprils vorliegen würde.

Könntet Ihr kurz Bescheid geben, wie bei Euch die zeitlichen Ressourcen aussehen bzw. wann Ihr dies in Eure Sprints aufnehmen könntet? @andreaschu 

Lieben Dank, viele Grüße und einen guten Wochenstart
Anne

**Comment by andreaschu** [comment]
> wir benötigen einen Export für das MDM für die Studien "Ursachen der Studienaufgabe im Masterstudium (StuMa)" und "Wege von Geflüchteten an deutsche Hochschulen (WeGe)". Ich hoffe, ich hab richtig nachgesehen, dass beide Studien mit Zofar durchgeführt wurden?

@anneweber ja, die wurden beide mit Zofar durchgeführt.

> Es ist nicht superdringend, aber für StuMa wäre es gut, wenn uns der Export im Laufe des Aprils vorliegen würde.

@anneweber wir würden uns gern erst Anfang März damit beschäftigen.

**Comment by anneweber** [comment]
@andreaschu Super, lieben Dank für die Rückmeldung und für's Kümmern!

**Comment by andreaschu** [comment]
@anneweber bei WeGe gibt es ja zwei Wellen. Sollen beide exportiert werden?

**Comment by anneweber** [comment]
@andreaschu Ja genau, bitte beide Wellen. Vielen lieben Dank!

**Comment by anneweber** [comment]
@andreaschu Könntest Du uns für unsere Planung kurz Bescheid geben, wann wir mit dem Export für StuMa rechnen können? Lieben Dank :)

**Comment by andreaschu** [comment]
@anneweber @vdick sitzt gerade an den Exporten für Absolventen (#370), StuMa und WeGe.

**Comment by anneweber** [comment]
Perfekt, vielen lieben Dank - für Rückmeldung und Export @andreaschu und @vdick

**Comment by vdick** [comment]
Hallo @anneweber, habe soeben 
faust.dzhw.local/abt4/Austausch/MDM/**MDM_absolventen2013-2**_06042021.zip
und
faust.dzhw.local/abt4/Austausch/MDM/**MDM-Masterbefragung**_06042021.zip
hochgeladen, magst du schauen, ob alles vollständig ist

**Comment by anneweber** [comment]
@vdick Super, vielen lieben Dank Dir! :)
Ich habe diese Woche Urlaub, aber leite es hiermit an Henrike (Schmidtchen) für StuMa bzw. Sandra (Vietgen) und Johanna (Niebuhr) für das Absolventenpanel 2013 weiter, die ich leider nur so @dzhw/fdz-sowis verlinken kann (sorry an die anderen ;) )

**Comment by henrikeschmidtchen** [comment]
herzlichen Dank @vdick! :) für StuMa ist alles vollständig!

**Comment by svietgen** [comment]
Beim Absolventenpanel 2013 ist auch alles vollständig, s. #370 Danke!

**Comment by andreaschu** [comment]
@dzhwmeisner und @vdick die Exporte für die WeGe-Befragungen fehlen noch.

**Comment by vdick** [comment]
Hallo @anneweber, habe soeben
faust.dzhw.local/abt4/Austausch/MDM/MDM_WeGe_01062021.zip
und
faust.dzhw.local/abt4/Austausch/MDM/MDM_WeGe2020_01062021.zip
hochgeladen, magst du schauen, ob alles vollständig ist

**Comment by andreaschu** [comment]
Für WeGe habe ich in den Austausch-Ordner die xml-Dateien und FlowCharts gelegt, und zwar unter: \Austausch\MDM\WeGe_sonstiges

**Comment by anneweber** [comment]
Hi Ihr Beiden @vdick @andreaschu 
und vielen lieben Dank Euch 👍 
Ich hab die Dateien bei uns in den Ordner kopiert.
Außerdem habe ich einmal grob über den Export drüber geschaut, das sah soweit gut aus! :) Das Einzige, was mir aufgefallen ist, war, dass beide Instrumente ins2 genannt wurden, was aber vermutlich daran liegt, dass ich bei der Export-Anforderung gar nicht die eigentlich von Euch gewünschten Eckdaten mitgeliefert hatte. Wir werden das selbst anpassen, ebenso falls wir bei der genaueren Bearbeitung noch etwas finden werden. Nur falls wir dahinter eine Systematik erkennen sollten, würden wir Euch das noch mal melden für zukünftige Exports.
Lieben Dank, das passt bei uns zeitlich gerade sehr gut rein, dass wir den Export jetzt von Euch bekommen haben 👍

**Comment by andreaschu** [comment]
@anneweber das mit dem ins2 ist nicht automatisch eingebaut, wir haben noch mal nachgeschaut. Beim nächsten Export sollte das also nicht mehr drin sein. Aber wenn das jetzt in Ordnung ist, das anzupassen, dann machen wir für WeGe keinen neuen Export.
Da alles bearbeitet ist, schließe ich das Issue jetzt.
