### ISSUE TITLE
MDM-Export: Metadaten für Absolventenpanel 2013 Welle 2 

### ISSUE THREAD

**Issue by svietgen** [dzhw/zofar#370]
Liebes Zofar-Team,

wir benötigen einen Export vom Absolventenpanel 2013, Welle 2 für das MDM. Es gab in dieser Welle drei Befragungen - wir benötigen die Hauptbefragung, bei euch hieß sie eventuell Basisbefragung oder auch Teilbefragung 1.

Das Absolventenpanel 2013 hat eine höhere Prio als das WeGe-Projekt, das wir erst etwas später aufbereiten.

Es wäre super, wenn ihr mich hier benachrichtigen könntet, wenn ihr das Projekt in euren Sprint aufnehmt.

Vielen Dank und liebe Grüße
Sandra

**Comment by vdick** [comment]
Hallo @svietgen , habe soeben 
faust.dzhw.local/abt4/Austausch/MDM/**MDM_absolventen2013-2**_06042021.zip
und
faust.dzhw.local/abt4/Austausch/MDM/**MDM-Masterbefragung**_06042021.zip
hochgeladen, magst du schauen, ob alles vollständig ist

**Comment by svietgen** [comment]
Hallo @vdick ,
vielen Dank für den Export. Es sieht alles vollständig aus, danke!

**Comment by andreaschu** [comment]
@svietgen kann das Issue dann geschlossen werden?

**Comment by svietgen** [comment]
@andreaschu Von unserer Seite aus kann das Issue geschlossen werden, danke!
