### ISSUE TITLE
MDM-Export: Reihenfolge Item-Screenshots

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#371]
Reihenfolge der Carousel-Shots der Items (in `questions` und `pages`-Export) entspricht nicht der richtigen Reihenfolge. 
(ScreenshotGenerator findElements liefert unsortierte Liste z.B. Zeile 530 - 535)
siehe: https://github.com/dzhw/nac2018/issues/3

**Comment by dzhwmeisner** [comment]
im nächsten Export gefixed

**Comment by SilinaSchirmer** [comment]
getestet für MDM_**WeGe2020**_01062021: 

Hier gibt es leider nur Screenshots in der Desktop-Ansicht und daher keine Bilder des Karussells.

**Comment by SilinaSchirmer** [comment]
getestet für MDM_**Nacaps**_24062020: 

Hier funktioniert es leider nicht. Die Items werden nicht in der richtigen Reihenfolge dargestellt, es ist aber auch keine Systematik zu erkennen. Zudem sind englische und deutsche Items durcheinander.

**Comment by SilinaSchirmer** [comment]
getestet für MDM-**Masterbefragung**_06042021: 

Hier gibt es leider nur Screenshots in der Desktop-Ansicht und daher keine Bilder des Karussells. (Beispiel: pn1001)
