### ISSUE TITLE
MDM-Export: page_number vs. question_number

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#372]
im json-Export question_number und page_number differentieren (page_number hinzufügen):
1. Spalte für page_number (Beispiel: A08 --> ohne .1)
2. Spalte für question_number (Beispiel: 1 / 2)

**Comment by dzhwmeisner** [comment]
Im nächsten Export implementiert

**Comment by andreaschu** [comment]
Soweit ich das sehe, kann dieses Issue geschlossen werden, was ich auch tun werde.
