### ISSUE TITLE
QML-Datei pauschal in Lieferung ans FDZ aufnehmen?

### ISSUE THREAD

**Issue by anneweber** [dzhw/zofar#378]
Liebe @andreaschu ,

ich wollte fragen, ob Du mir noch die QML-Datei zur StuMa-Befragung zuschicken könntest und ob wir die QML-Datei pauschal in Eure Lieferung an uns mit aufnehmen könnten? In dem von Euch gemachten Export sind diese Infos zwar grundsätzlich auch alle bereits enthalten, mir ist aber aufgefallen, dass es beim Nachschauen von bestimmten Punkten (z. B. Nachvollziehen der Filterführung) einfacher ist, schnell mal in die Gesamt-QML-Datei zu schauen. Außerdem könnten wir diese dann auch archivieren.

Ich bin mir nicht ganz sicher, inwiefern das für Euch Zusatzaufwand bedeutet. Ich stelle es mir so vor, dass die QML-Datei sowieso fertig irgendwo liegt und dann nur herausgesucht und übergeben werden muss. Vielleicht bin ich da aber auch zu naiv, dann gerne melden :).

Lieben Dank schon mal und liebe Grüße
Anne

**Comment by andreaschu** [comment]
@anneweber entschuldige, dass ich erst jetzt antworte. Ich kann Dir die QML-Dateien zukommen lassen für StuMa und ggf. für die anderen Befragungen, bei denen wir Euch gerade einen Export gezogen hatten. Ob oder wie wir das standardmäßig einbauen, müssen wir mal überlegen.
Ich habe das XML und FlowCharts für StuMa in den Austausch-Ordner gelegt (\Abt4\Austausch\FDZ-zofar\StuMa).

**Comment by anneweber** [comment]
@andreaschu Super, vielen lieben Dank Dir ❤️ ! Nur dass es kein Missverständnis gibt: Von meiner Seite aus müsste jetzt auch nichts neues Automatisiertes in den Export eingebaut werden, wir können auch einfach immer die QML-Datei so wie jetzt gesondert mit anfordern und sie wird manuell übergeben. Ich finde es auf jeden Fall oft praktisch, dort mal einen Blick reinwerfen zu können. Daher prima, dass wir die Unterlagen jetzt für StuMa haben und auch das FlowChart wird superhilfreich sein 👍

**Comment by andreaschu** [comment]
Prima. Kannst Du einen kurzen Blick reinwerfen und wenn es das richtige ist, das Issue schließen? Wir haben leider etwas Namensverwirrung. Deswegen gibt es ein Restrisiko, dass es das XML (und die FlowCharts) der falschen Befragung ist.

**Comment by anneweber** [comment]
@andreaschu Auch hier sorry für die verspätete Rückmeldung. Ich hab' es mir noch mal angeschaut und das sah alles gut für mich aus :).

**Comment by andreaschu** [comment]
@anneweber um das Issue zu schließen, würde ich Dich bitten, die XML und andere Dokumente gesondert anzufordern. Vielleicht kannst Du das auch in die Anleitung schreiben.
Für WeGe habe ich in den Austausch-Ordner die xml-Dateien und FlowCharts gelegt, und zwar unter: \Austausch\MDM\WeGe_sonstiges

**Comment by anneweber** [comment]
@andreaschu Jap, habe es in die Anleitung aufgenommen. Danke Dir! :)
