### ISSUE TITLE
Carousell - automatically skip answered items

### ISSUE THREAD

**Issue by kastirke** [dzhw/zofar#38]
Shall we automatically skip answered items?  

![grafik](https://user-images.githubusercontent.com/30147532/31727436-d63e7d92-b429-11e7-99ab-2bb216495372.png)
Roberts et al. 2013
https://dspace.library.uu.nl/bitstream/handle/1874/291084/MOAjaarboek2013HoxLeeuw.pdf?sequence=1

**Comment by andreaschu** [comment]
The auto forward should be stopped at the last item and the usability should be tested when implemented. 
It has to be clear to the respondents even if the scale overlaps the screen so that the changed item text is maybe not visible anymore. So it should be tested with long scales as well.

**Comment by dzhwmeisner** [comment]
Implemented for SingeChoice Matrix Questions. Need to be tested at http://vmzofar-pres.his.de:8080/devhtml5

**Comment by andreaschu** [comment]
In double matrix questions it should only be automatically forwarded when both answers are given. Otherwise the respondents has to go back at each item.

**Comment by kastirke** [comment]
Looks great (apart from Andrea's comment). 👍

**Comment by vdick** [comment]
it's in discussion. so for now it's implemented as individual function for singlechoice-matrix questions and have to be enabled manually for each of them.

`// Autoforwarding
$('.carousel').each(
		function() {
			var ignore = false;

			if ($(this).parents('.calendar').length > 0)
				ignore = true;
			if ($(this).parents('.display-calendar').length > 0)
				ignore = true;
			if ($(this).parents('.comparison').length > 0)
				ignore = true;

			if (!ignore) {
				var carouselSelector = $(this);
				
				function autoforward() {
					var currentSlide = $(carouselSelector).find('.active');
					var nextSlide = currentSlide.next();
					var answerOptionSelector = $('.custom-radio', currentSlide);
					
					$(answerOptionSelector).on('mouseup keyup',function() {
						if(nextSlide.length > 0 ){
							if (window.matchMedia('(max-width: 767px)').matches)$(carouselSelector).carousel('next');
						}
					});
				}
				
				$(carouselSelector).ready(autoforward);
				$(carouselSelector).on('slid.bs.carousel', autoforward);
			}
		}
    );`
