### ISSUE TITLE
MDM-Export: relatedQuestions

### ISSUE THREAD

**Issue by anneweber** [dzhw/zofar#380]
@vdick 
Uns sind beim Zofar-Export für das MDM im Hinblick auf die Datei `relatedQuestions.csv` noch zwei Punkte aufgefallen:
- In der Spalte `relatedQuestionStrings.de` bestehen beim Öffnen in Excel Encoding-Probleme. Beim Versuch, das beim Import in Excel zu lösen, sind wir leider gescheitert - dabei wurde immer alles zerschossen. Könntet Ihr Euch das noch einmal anschauen?
- Könnte man die Spalte `ZofarQuestionNumber` umbenennen zu `questionNumber` und die Spalte `page_Number` weglassen?

Danke und liebe Grüße!

**Comment by anneweber** [comment]
Noch eine kleine Ergänzung, die heute noch aufgefallen war: In der Spalte `relatedQuestionStrings.de` (vermutlich auch `.en`, sie war aber in unserem Fall nicht gefüllt) steht bei StuMa auch z. B. "Aufnahme des Masterstudiums" bei verschiedenen Fragen als Überschrift. Es scheint, als sei hier der Text aus einem "falschen" Feld mit reingerutscht, da die Überschriften für dieses Feld eigentlich nicht vorgesehen sind. **Für StuMa muss das nicht bereinigt werden, das lassen wir eine SHK machen.** Aber es wäre prima, wenn Ihr für zukünftige Exports einen Blick darauf werfen könntet. Lieben Dank :)

**Comment by andreaschu** [comment]
@anneweber: @vdick und ich haben zwar nicht herausgefunden woran es liegt, dafür aber einen workaround. Es liegt an den line breaks `\l`. Die werden von Excel offenbar als neue Zeile erkannt. LibreOffice kann damit besser umgehen. 
Bei mir hat es geklappt, als ich es mit LibreOffice geöffnet und dann als xlsx-Datei gespeichert habe. Dann wird alles richtig umgesetzt und kodiert.

**Comment by anneweber** [comment]
@andreaschu @vdick 
So, sorry, etwas verspätet, weil ich frei hatte: Die LibreOffice-Lösung klappt, super, vielen lieben Dank! 👍 Ich habe das so in unsere Anleitung aufgenommen.

**Comment by andreaschu** [comment]
@anneweber für mich sieht es jetzt korrekt aus. Die Spalte page_Number ist noch drin, weil wir mit Ute besprochen hatten, dass sie drin bleiben kann, da sie nicht stört. 
Kannst du das Issue schließen, wenn du es Dir angeschaut hast (und auch für richtig umgesetzt hältst)?

**Comment by anneweber** [comment]
@andreaschu Jap, passt! Super, lieben Dank für die Korrektur!
