### ISSUE TITLE
Informationen Studienberechtigtenpanel 2012 3. Welle

### ISSUE THREAD

**Issue by McWallis** [dzhw/zofar#383]
Liebes Zofar-Team,

ich bin vom FDZ und zuständig für die Aufbereitung der 3. Welle vom Studienberechtigtenpanel 2012. 
Könntet Ihr mir Daten zu dem Studienberechtigtenpanel 2012 3. Welle zur Verfügung stellen?

- Screenshots/Fragebogen
- Filterdiagramm
- Zuordnung Variable -> Screenshot?
- Welche Informationen gibt es noch?

Danke und viele Grüße
Marten

**Comment by andreaschu** [comment]
@McWallis benötigst Du den MDM-Export?

**Comment by andreaschu** [comment]
@McWallis ich habe einen Ordner für die Dokumente erstellt, und zwar: _…\Austausch\MDM\Studpanel12-3_ 

Hier ist schon mal das Flow Chart als Bilddateien. Abgelegt habe ich diese Dateien und die gml-Exporte, die z.B. mit yEd editierbar sind.

FlowChart mit Variablen, die auf den Seiten erhoben werden: [2021-06-16_16-40_Studpanel12-3_FlowChart_inclVars](https://user-images.githubusercontent.com/30111489/122240184-dc011300-cec1-11eb-8fde-255fcdcd24bd.png)
FlowChart ohne Variablen: [2021-06-16_16-42_Studpanel12-3_FlowChart](https://user-images.githubusercontent.com/30111489/122240187-dd324000-cec1-11eb-83e8-b103b0199c66.png)

**Comment by McWallis** [comment]
@andreaschu entschuldige die späte Antwort. Danke für die schnelle Bearbeitung. 

> @McWallis neben dem Screenshot und dem Flow Chart gibt es noch einen MDM-Export, mit allen Texten etc. für den Import ins MDM. Benötigst Du den?
Ich nehme, wenn es keine zu großen Umstände macht, erst einmal alles was ich bekommen kann.

> Hier ist schon mal das Flow Chart als Bilddateien. Abgelegt habe ich diese Dateien und die gml-Exporte, die z.B. mit yEd editierbar sind.
Tausend Dank

**Comment by andreaschu** [comment]
@vdick oder @dzhwmeisner könnte einer von Euch einen MDM-Export erstellen?

**Comment by vdick** [comment]
Hallo @McWallis , soeben habe ich einen MDM-Export nach …\Austausch\MDM\Studpanel12-3 hochgeladen.
Magst du bitte schauen, ob alles vollständig ist?

**Comment by McWallis** [comment]
Hallo @vdick, Dank Dir. ich schaue es mir an. Habe ab Freitag erst einmal Urlaub also nicht wundern, falls ich mich erst einmal nicht melde.

**Comment by andreaschu** [comment]
@vdick kleine Rückmeldung: die Konfiguration ist wieder / immer noch so eingestellt, dass die question\pages mit ins2 beginnen. Ist ja nicht schlimm, aber irritierend.

**Comment by andreaschu** [comment]
@McWallis da die Befragung noch für das alte Design erstellt wurde, könnte es sein, dass die Bilder nicht 1:1 wieder hergestellt wurden. Deshalb habe ich noch mal den Screenshot der Befragung in den Ordner gelegt, den wir damals gemacht haben. 
Zudem habe ich noch mal den Fragebogen in der XMl-Version in den Ordner geschoben.

**Comment by andreaschu** [comment]
@McWallis kann dieses Issue geschlossen werden?

**Comment by McWallis** [comment]
@andreaschu Ja, kann geschlossen werden. Entschuldige die späte Antwort (langer Urlaub) und Danke für Eure schnelle Bearbeitung.
