### ISSUE TITLE
Accordion: please remove bug with V from testsurvey (devhtml5)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#384]
in our testsurvey (https://presentation.dzhw.eu/devhtml5) the arrow-bug arises on pages with matrix question single choices. Please apply solution from Nacaps20.1.

![grafik](https://user-images.githubusercontent.com/30111489/122229174-d18e4b80-ceb8-11eb-8bf5-0f43b724e2cd.png)

**Comment by vdick** [comment]
fixed in devhtml5; Archetype ist bereits aktualisiert und neu gebildet

**Comment by andreaschu** [comment]
looks good in devhtml5.
