### ISSUE TITLE
qml attribute for infield-texts

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#385]
For infield labels there should be an attribute.
(should also be testet in MDM-Export)

**Comment by andreaschu** [comment]
- [ ] qml attribute
- [ ] adapt renderer
- [ ] css

**Comment by dzhwmeisner** [comment]
modifiing QML-Scheme

**Comment by dzhwmeisner** [comment]
Scheme and Plugin done. Working on Renderer

**Comment by dzhwmeisner** [comment]
renderer adapted. no need for css changes.
For testing add the Attribute infield to the Open Question.
Shoud work for all kind of open Questions in the responsive Version.

Needed dependency:
			<groupId>de.his.zofar</groupId>
			<artifactId>zofar.presentation.surveyEngine.ui-html5</artifactId>
			<version>0.0.1-SNAPSHOT</version>

and needed Plugin:
				<groupId>de.his.zofar</groupId>
				<artifactId>zofar.survey.generator.maven.plugin-html5</artifactId>
				<version>0.0.2</version>
the needed Dependency and the Plugin shoult be declared in the pom.xml of your Test-Project

Example :  
<zofar:questionOpen variable="frage81_1_open" type="text" size="20" infield="frage81_1" uid="qo"></zofar:questionOpen>

**Comment by SilinaSchirmer** [comment]
Läuft!

In der jeweiligen Pom muss lediglich die Version des Plugins wie folgt angepasst werden (bei mir Zeile 135-137): 
        <groupId>de.his.zofar</groupId>
        <artifactId>zofar.survey.generator.maven.plugin-html5</artifactId>
        <version>0.0.2</version>
