### ISSUE TITLE
snippet in template for the size of frame for unit-titles

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#386]
As zofar programmer we need a snipped for adapting the frame size for unit titles in additional css.

**Comment by vdick** [comment]
for SingleChoice&MultipleChoice questions :
```
/*
	CUSTOMIZING OF UNIT-TITLE		
*/
.custom-PAGEUID .survey-outer .question-main .question-text {
    margin-bottom: 4rem !important;
}
.custom-PAGEUID legend {
	/*
		it possible to change font-size or weight
	*/
    font-size: 1.2rem;
    font-weight: 600;
	/*
		a better way is to change the distance upwards
	*/		    
    top: -1.5rem;
}
```
!!! if the're more than one unit in question,   replace LEGEND by legendUID

**Comment by vdick** [comment]
for SingleChoiceMatrix

```
/*
	CUSTOMIZING OF UNIT-TITLE for SingleChoiceMatrix
*/
.custom-PAGEUID legend {
	/*
		it possible to change font-size or weight
	*/
    font-size: 1.2rem;
    font-weight: 600;
	/*
		a better way is to change the distance upwards
	*/		    
    top: -5.5rem;
}
.custom-PAGEUID fieldset {
    margin-top: 7.5rem !important;
}
```
!!! if the're more than one unit in question, replace LEGEND&FIELDSET by UID

**Comment by SilinaSchirmer** [comment]
> !!! if the're more than one unit in question, replace LEGEND&FIELDSET by UID

Das verstehe ich leider nicht. 😕

**Comment by christian-fr** [comment]
@vdick Habe ich das richtig verstanden? Man kann entweder 
1. den obenstehenden Code benutzen und nur die `PAGEUID` einsetzen.

oder man setzt zusätzlich

2. statt `legend` und `fieldset`den CSS-Selektor der Unit ein (bspw. `#form\:p5\:msc\:rd\:u1`)?

**Comment by SilinaSchirmer** [comment]
Aus meiner Sicht, fehlt aber vor allem noch eine Zeile um die Breite des Feldes zu vergrößern. 

Die meisten Fälle, die ich so im Kopf habe, sind einzeilige Titel die trotzdem zu lang für das Standardfeld sind. 
Reicht dann folgender Schnipsel? 

```
.custom-PAGEUID fieldset {
    witdh: 7rem [+x] ; !important;
```

**Comment by SilinaSchirmer** [comment]
Ich ziehe alle meine Aussagen zurück! :P 

Das Snippet hat bei meinen Test super funktioniert und kann ins Archetype aufgenommen werden.

**Comment by vdick** [comment]
@christian-fr is in archetype implemented, please build a new survey to test it

**Comment by christian-fr** [comment]
@vdick I cannot find the snippet in main/webapp/resources/html5/css/additional.css

**Comment by vdick** [comment]
@christian-fr  is fixed, please test again

**Comment by SilinaSchirmer** [comment]
@vdick: Now the snippets are added to the archetype but are activated by default. Maybe we should comment them out.
