### ISSUE TITLE
item label left-aligned

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#387]
As zofar-user I want to decide wether item label are left- or right-aligned.
As zofar-programmer I need a snippet in template to change the alignement.

**Comment by andreaschu** [comment]
for a global solution (for item grids):
- [ ] item class in css
- [ ] master css

**Comment by vdick** [comment]
the solution is very simple, you've to put in this snippet:
.singlechoicematrix .form-inner .text-sub
{
	justify-content: flex-start !important;
    text-align: left !important;
}
.multiplechoicematrix .form-inner .text-sub
{
	justify-content: flex-start !important;
    text-align: left !important;
}

**Comment by andreaschu** [comment]
@vdick the code only includes singleChoice- and multipleChoice- grids. What about openQuestion-grids? Are these already left aligned?

**Comment by vdick** [comment]
@andreaschu  ups.. is in progress

**Comment by vdick** [comment]
@andreaschu @SilinaSchirmer the snippet for OpenMatrix
```

.openmatrix .form-inner .text-sub {
    display: flex !important;
    justify-content: flex-start !important;
    text-align: left !important;
}
```

**Comment by christian-fr** [comment]
@vdick
Snippet has been tested and is working for matrixQuestionOpen, matrixQuestionSingleChoice and matrixMultipleChoice.
Can be added to Archetype.

**Comment by vdick** [comment]
@christian-fr  is in archetype implemented, please build a new survey to test it

**Comment by christian-fr** [comment]
CSS-snippet has been added to archetype. Issue closed.
