### ISSUE TITLE
bug: carousel counter is missing

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#395]
Seems to arise when items are randomized.
There is a snippet in the template but the bug should be corrected.

**Comment by dzhwmeisner** [comment]
...searching for bug

**Comment by dzhwmeisner** [comment]
bug found. searching for fix

**Comment by dzhwmeisner** [comment]
Bug fixed (! Caution! Affect current productive Code of SID-2021. Remove Bugfix, before deploying productive while test phase) Need to be tested at 
https://presentation.dzhw.eu/sid-2021/

**Comment by andreaschu** [comment]
for testing look at the pages that has been adapted (look e. g. at issue: https://github.com/dzhw/SiD/issues/507)

**Comment by christian-fr** [comment]
> 
> 
> for testing look at the pages that has been adapted (look e. g. at issue: [dzhw/SiD#507](https://github.com/dzhw/SiD/issues/507)) and look if the counter are still visible.

successfully tested - the counters **_are visible_** on pages: **D1_7, C2_8_r, C2_9_r, F1_2_r1, F1_2_r2**

**Comment by andreaschu** [comment]
@dzhwmeisner is this bug fix added to the archetype? Can this issue be closed?

**Comment by dzhwmeisner** [comment]
the changes are made in zofar.presentation.surveyEngine.ui-html5 (Version 0.0.1-SNAPSHOT) which is used by the archetype.
So it will take effect in future Projects and there will be no need to fix the issue by individual CSS and JS. 
In my optinion it can be closed.

**Comment by andreaschu** [comment]
@dzhwmeisner can we check before closing? How?

**Comment by dzhwmeisner** [comment]
yes. By Creating a new Project

**Comment by dzhwmeisner** [comment]
creating a new Test-Project out of Archetype (zofar.survey.archetype.surveytemplate_responsive:0.0.3-SNAPSHOT)

**Comment by christian-fr** [comment]
> 
> 
> creating a new Test-Project out of Archetype (zofar.survey.archetype.surveytemplate_responsive:0.0.3-SNAPSHOT)

I just created a new project. 

Do I have to modify anything within the `pom.xml` to use this archetype?

**Comment by vdick** [comment]
@christian-fr I think no, the version "0.0.3-SNAPSHOT" is implemented

**Comment by christian-fr** [comment]
The visibility issue seems to have been successfully resolved. This issue will be closed.

It seems that another bug has been found while testing this issue, a new issue will be created (#430).
