### ISSUE TITLE
two dropdowns in a row

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#396]
as zofar programmer i need a snippet to position two drop downs in a row.

**Comment by SilinaSchirmer** [comment]
bereits für Nacaps erstellt. Muss nur rausgesucht und ins Architype übernommen werden.

**Comment by christian-fr** [comment]
bspw. Nacaps2018-3 auf page **B08**

Ausschnitt aus der additional.css (unklar, ob alles relevant ist):

```
.custom-B08 #form\:B08\:qsc2,
.custom-B08 #form\:B08\:qsc4 {
    margin-top: -8.65rem;
    margin-left: 12rem;
}

@media (max-width: 766px) {
	.custom-B08 #form\:B08\:qsc2,
	.custom-B08 #form\:B08\:qsc4 {
		margin-top: -7.8rem;
		margin-left: 12rem;
	}	
	/* BugFix for SingleChoice horizontal smartphone  */
	.form-horizontal .custom-form.custom-form-radio .custom-control label {
	    padding: 1rem;
	    max-width: 5px;
	}
	.form-horizontal .custom-form.custom-form.custom-form-radio .custom-control-description {
	    margin-left: -5rem !important;
	}
	
	.form-horizontal .form-inner, .custom-C29 .form-horizontal .form-inner {
	    max-width: 70%;
	}
	
	
}
```

**Comment by vdick** [comment]
/*
	TWO DROPDOWNS IN A ROW
*/
.custom-PAGEUID #form\:PAGEUID\:QESUTIONUID {
    margin-top: -8.65rem;
    margin-left: 12rem;
}
@media (max-width: 767px) {
	.custom-PAGEUID #form\:PAGEUID\:QESUTIONUID {
		margin-top: -7.8rem;
		margin-left: 12rem;
	}	
}

**Comment by christian-fr** [comment]
the css code snippet works! (measures have to be individually adjusted).

still needs to be implemented into additional css

**Comment by vdick** [comment]
@christian-fr  is in archetype implemented, please build a new survey to test it

**Comment by christian-fr** [comment]
Successfully added to archetype.

@SilinaSchirmer has questions about the code; the issue stays therefore open.

**Comment by SilinaSchirmer** [comment]
Bei mir sieht eine Frage inkl. des Snippets so aus: 

![image](https://user-images.githubusercontent.com/48087320/124243539-48b11a00-db1e-11eb-85e5-65ef07abdf31.png)


Ich vermute, dass ich irgendwas nicht verstehe oder falsch nutze 😄

**Comment by vdick** [comment]
@SilinaSchirmer in der Befragung scheint grundsätzlich etwas nicht zu stimmen, da hat das Snippet nichts mit zu tun

**Comment by SilinaSchirmer** [comment]
@vdick: Das beruhigt mich etwas. Werde es dann nochmal an einer anderen Befragung testen.

**Comment by SilinaSchirmer** [comment]
Bei einer anderen Befragung passiert das gleiche. 

![image](https://user-images.githubusercontent.com/48087320/124427000-1b0ce080-dd6b-11eb-818b-4d353ea1ec35.png)

**Comment by vdick** [comment]
@SilinaSchirmer das Snippet tut, nur hast du im CSS anstatt QSC2 die QSC1 genommen (es soll ja nur die zweite DropDown angepasst werden)

**Comment by SilinaSchirmer** [comment]
Endlich bin auch ich in der Lage das Snippet richtig zu nutzen 🤦 Sorry für die Verwirrung. 

Snippet funktioniert wunderbar und ist im Archetyp eingebaut.

Das Issue kann aus meiner Sicht geschlossen werden!

**Comment by andreaschu** [comment]
> Das Issue kann aus meiner Sicht geschlossen werden!


@SilinaSchirmer dann mach doch.
