### ISSUE TITLE
showroom overhaul

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#401]
https://presentation.dzhw.eu/showroom

- restructure the showroom
- add content to the showroom

**Comment by andreaschu** [comment]
how nice would be a kollaborative workspace.
Here is the current status including new texts and ideas (to be changed in [here]([faust]Servicebereich_Onlineforschung\02_Service\Vorlagen\_Informationen\/Showroom_Konzept.docx)).
[Showroom_Konzept.docx](https://github.com/dzhw/zofar/files/6715734/Showroom_Konzept.docx)

**Comment by SilinaSchirmer** [comment]
http://vmtest.dzhw.local:8080/Showroom_new/

**Comment by SilinaSchirmer** [comment]
Das Konzept zur inhaltlichen Gestaltung des Showrooms habe ich gestern angefangen zu bearbeiten. 

Gerade zur technischen Umsetzung von **Barrierefreiheit** sowie zu **Login-Methoden** könnte ich aber auf jeden Fall noch Input vertragen.

**Comment by andreaschu** [comment]
Let us refine this issue and split it into smaller ones.

**Comment by andreaschu** [comment]
#413 
#414 
#415
#417
