### ISSUE TITLE
snippet for single choice to visually demarcate missing category

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#406]
can be implemented as soon as #389 is resolved

**Comment by andreaschu** [comment]
@vdick or @dzhwmeisner is someone working on this?

**Comment by SilinaSchirmer** [comment]
> can be implemented as soon as #389 is resolved

#389 ist gelöst.

**Comment by vdick** [comment]
@SilinaSchirmer please test this snippet

```
/*
	single choice visually demarcate missing category
*/
.custom-pageUID .singlechoice-ismissing {
    height: 30px !important;
}
```

**Comment by SilinaSchirmer** [comment]
@vdick: Das snippet funktioniert super und kann ins Archetyp übernommen worden. 

Könnten wir ein ähnliches snippet auch für multiplechoice fragen erstellen?

**Comment by SilinaSchirmer** [comment]
habe selber eine Lösung gefunden: 

/*
	single choice visually demarcate missing category
*/
.custom-pageUID .checkbox-ismissing {
    height: 30px !important;
}

**Comment by vdick** [comment]
@SilinaSchirmer habe ich bereits ins Archetype implementiert. Für MultipleChoice gibt es berreits eine Lösung.
@christian-fr magst du eine neue Befragung builden, um zu prüfen?

**Comment by SilinaSchirmer** [comment]
@vdick: Ah stimmt. 

Habe es in einer neuen Befragung getestet. Das snippet ist im Archetyp!
