### ISSUE TITLE
optimize position of attachedOpen for singlechoice/multiplechoice on smartphone 

### ISSUE THREAD

**Issue by vdick** [dzhw/zofar#407]

**Comment by SilinaSchirmer** [comment]
@vdick: 

Aus meiner Sicht würde es reichen, dieses snippet in der master.css anzupassen. 

```
.custom-control-description .attached {
    margin-left: 0px;
    margin-top: 5px;
}
```

Es funktioniert super, sobald das snippet so aussieht

```
.custom-control-description .attached {
    margin-left: 5px;
    margin-top: 0px;
}
```

**Comment by vdick** [comment]
@SilinaSchirmer sieht super aus! Habe es ins Archetype übernommen. 
@christian-fr bitte eine neue Befragung anlegen, um zu testen

**Comment by christian-fr** [comment]
In der `master.css` sehe ich keine Veränderung.

In der `additional.css` gibt es folgenden neuen Eintrag (Zeilen 386. 468-471):
```
@media ( min-width : 768px) {

[...]

	.custom-control-description .attached {
		margin-left: 5px;
		margin-top: 0px;
	}
```

@SilinaSchirmer  @vdick Wenn das so gewünscht war, kann das issue geschlossen werden.

**Comment by SilinaSchirmer** [comment]
Jap, so soll es aussehen :)
