### ISSUE TITLE
plugin: automatically commit questionnaire_generated.xml with each new jenkins build

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#412]

**Comment by dzhwmeisner** [comment]
Request to test.

*Add to POM:

> to Properties-Area:
> `<automation.recommit_qml>${recommit_qml}</automation.recommit_qml>`

> 
> to the ZofarPlugin (zofar.survey.generator.maven.plugin-html5,Version 0.0.2) in build area:

> to executions area:
> `          <execution>
>             <id>recommit-qml</id>
>             <phase>install</phase>
>             <goals>
>               <goal>recommit-qml</goal>
>             </goals>
>           </execution>` 

> 
> ***to configuration area of the plugin:
> `<recommit_qml>${automation.recommit_qml}</recommit_qml>` 
> 

*Jenkins-Job:
Add Attribute `-Drecommit_qml=true` to "Goals und Optionen"

**Comment by JensSoares** [comment]
Das Bauen von einem Projekt funktioniert nicht. Es scheint mit dem re-commit zusammenzuhängen. (Siehe Fehlermeldung)

[Fehlermeldung - Build 17.09.2021.txt](https://github.com/dzhw/zofar/files/7186043/Fehlermeldung.-.Build.17.09.2021.txt)

**Comment by dzhwmeisner** [comment]
> Das Bauen von einem Projekt funktioniert nicht. Es scheint mit dem re-commit zusammenzuhängen. (Siehe Fehlermeldung)
> 
> [Fehlermeldung - Build 17.09.2021.txt](https://github.com/dzhw/zofar/files/7186043/Fehlermeldung.-.Build.17.09.2021.txt)

Bitte ein Update (Team-> Update to HEAD) der pom.xm durchführen und nochmal versuchen.l
