### ISSUE TITLE
showroom: structure

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#417]
Within this issue the structure of the showroom shall be finalized.

**Comment by SilinaSchirmer** [comment]
Durch den Commit https://github.com/dzhw/zofar/commit/380f50457598ffa763eb0d119c82cb1d83a69d62 ist das Dokument für das Showroom-Konzept nun auf dem aktuellsten Stand.

**Comment by SilinaSchirmer** [comment]
Die aktuelle Struktur steht nun am Anfang des Showroom-Konzepts. (https://github.com/dzhw/zofar/commit/01512529ccccad7d340f91af63b5a0567f65f245)

@andreaschu: Du kannst sie dort gerne umstellen und ich passe danach die Reihenfolge des restlichen Dokuments an.

**Comment by andreaschu** [comment]
I changed it within a branch. You can merge this branch when you have reviewed it.
I wasn't sure yet with the processes. It may not be exhaustive.

**Comment by SilinaSchirmer** [comment]
Ich habe die Struktur für das gesamte Dokument übernommen und auch in ein branch eingefügt.

**Comment by andreaschu** [comment]
I close this issue, because it's done for the moment.
