### ISSUE TITLE
Calendar bug vaa01: buggy behaviour of vaa01 (creation of new episodes / deletion if backwards jump; handling of missing values)

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#429]
The first loop of the Calendar Test Module can be accessed from the page **calendar** via **vaa01** or **vaa05**.

We should make sure that the initial conditions are correct and also the same for both of those transitions.

We should also make sure that those initial conditions are consistent with a backwards jump from **vaa01** or **vaa05** to **calendar** and then back to **vaa01** or **vaa05**.

**Comment by christian-fr** [comment]
Flowchart of first loop:
[2021-07-20_questionnaire_Test_Modul_Episode_Calendar_LOOP1_003 jpg](https://user-images.githubusercontent.com/42959832/126661569-0bd61ae0-d746-42e8-9274-bbe18d563b85.jpg)

**Comment by christian-fr** [comment]
it seems to be problematic that we use both _episode_index_ and _type1str_-_type4str_ for the transition conditions on page **calendar**.
we should only use _episode_index_ and fetch _typeStr_ from the JSON object according to _episode_index_

**Comment by andreaschu** [comment]
This is fixed, I would say.
But we may have a logic problem: If the respondent fills in implausible dates (like end-date before start-date, dates out of range or missings) the creation of a new episode will not be completed and the page will be re-entered. While entering this page, the variables will be deleted what causes that the conditions for the error-message are not fullfilled.
I open a new issue for this logic-problem: #470
