### ISSUE TITLE
'forward' Button 

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#43]
[ A ]

- in Microsoft Edge 14 the 'forward' Button is displayed correctly at the bottom, but aswell within the contentarea.

![forwardbutton-iedge](https://user-images.githubusercontent.com/29864065/32598222-774c10e4-c539-11e7-8c69-67e59b01a5fc.jpg)

**Comment by vdick** [comment]
fixed

**Comment by Miktarbad** [comment]
- not fixed in Edge 14 / Firefox Dev
- works in Chrome & Firefox / aswell as Mobile (S7 - Android 7 - Chrome)

![forwardbutton-iedge-2](https://user-images.githubusercontent.com/29864065/32610032-d55de93c-c561-11e7-8f30-e1d0beb59150.jpg)

**Comment by Miktarbad** [comment]
issue resolved.
