### ISSUE TITLE
bug: calendar grid/table disappears on Safari Browsers

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#433]
### Tested on Saucelabs with Mac11 / Safari 14 1920x1440

The grid/table disappears while Safari is executing `master.js`. (This also happens with old "Calendar Test Module").

> ![grafik](https://user-images.githubusercontent.com/42959832/130475039-98f26e03-d39d-4fb0-bf14-7ce1e71558e2.png)

This is the line 3555 in `master.js` after which the grid / table disappears:

> ![grafik](https://user-images.githubusercontent.com/42959832/130474972-bdf718bf-804e-4f0d-b9a3-b5e850fa1260.png)

**Comment by vdick** [comment]
should be fixed.. please check again:
https://presentation.dzhw.eu/calendar_new/calendar.html

**Comment by andreaschu** [comment]
seems to be solved.
