### ISSUE TITLE
change color of "WARNING_START"

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/zofar#438]
Please change the color of "WARNING_START" in Layout.properties to **#ff0000**

**Comment by vdick** [comment]
@SilinaSchirmer please create a new project via archetype to test

**Comment by christian-fr** [comment]
Tested it with a new project, colors seem to be matching:

![grafik](https://user-images.githubusercontent.com/42959832/132505017-0248c505-5b71-436f-b4d2-b2e8751bc930.png)

![grafik](https://user-images.githubusercontent.com/42959832/132505105-c120194c-b57b-4344-ac05-a21b810bc8ba.png)

Issue will be closed.
