### ISSUE TITLE
calendar: events are shown incompletely on samsung

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#440]
Events are shown incompletely compared to the entered data (some months are missing). E.g., when you select a period from 2019-2022, some months in 2020 will not be highlighted.

**Comment by jocarstensen** [comment]
Samsung S10e, Android 11, Chrome and Firefox Klar

**Comment by andreaschu** [comment]
This is maybe outdated. Can be reopened when the bug recurse.
