### ISSUE TITLE
calendar: the screen size from 768 till 1023 is not optimized 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#441]
The months-labels are not in place (see screenshot below).

 ![Screenshot 2022-01-12 at 15-16-24 Zofar Demo](https://user-images.githubusercontent.com/30111489/149157088-e8c0b8c3-4c8e-4f03-8523-75479f2534ee.png)

![grafik](https://user-images.githubusercontent.com/30111489/155345240-0ae59dfd-3a35-427a-87c6-b9c6f44e46ed.png)

**Comment by vdick** [comment]
should be fixed, please test after next deploy of test_modul
