### ISSUE TITLE
calendar: dialog is not scrollable on mobile devices

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#442]
The input dialog is too large for small screen and it is not scrollable. Consequently the 'save'-button is not accessible.

**Comment by andreaschu** [comment]
scrollable container dialog is needed

**Comment by vdick** [comment]
The product is not really responsive, because here is partly worked with static widths. The first thing to change is this and then the vertical scrolling

**Comment by dzhwmeisner** [comment]
fixed in new Rollout by adding css to style and position dialog

**Comment by dzhwmeisner** [comment]
request for testing

**Comment by andreaschu** [comment]
the new dialog fits in the screen and doesn't need to be scrolled. Works on every device I tested.
Maybe some finishing is needed like the position and size of the buttons. I will open a new issue for finishing and close this one.
