### ISSUE TITLE
calendar: enter events for touchscreens

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#443]
As a respondent I want to enter a new event on JS-calendar via the touchscreen of my mobile device.

**Comment by dzhwmeisner** [comment]
add "New Episode" to context menu (right click at month tile in desktop) to open create dialog. 
if there are no episodes at this month a touch event at month tile could open create dialog instantly.

**Comment by dzhwmeisner** [comment]
implemented in current Rollout  by holding touch while moving from start month to end month.

Request for testing

**Comment by andreaschu** [comment]
Creating a new event works on every device I tested it. 
Only sometimes it starts with 01.01.1970 (when I start swiping before the first month).

**Comment by dzhwmeisner** [comment]
Range selections with incomplete start and end dates (1.1.1970) are now be ignored.

**Comment by andreaschu** [comment]
Die trigger funktionieren zwar, aber für 'edit' ist der Trigger falsch. Es müsste zur Seite **vaa05** gehen.
![https://media.giphy.com/media/Mn4kr2DjIBUIZdNGBd/giphy.gif](https://media.giphy.com/media/Mn4kr2DjIBUIZdNGBd/giphy.gif)
