### ISSUE TITLE
Eurostudent Steering Board [ESB]

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/zofar#446]

**Comment by JensSoares** [comment]
- [x] Projekt planen.
- [ ] First Draft - Fragebogen.
- [ ] Fragebogen (xml) erstellen und layouten.
- [ ] Logo einbinden.
- [ ] Datenschutz in der Index einbauen.
- [ ] Fragebogen testen.
- [ ] Abstimmung des Fragebogens mit Projektleiter.
- [ ] Projekt scharf schalten.
- [ ] Token erstellen.
- [ ] Zugangslinks mit den Adressdaten verknüpfen.
- [ ] Einladungen versenden.
- [ ] Datenauswertung.
- [ ] Grafik erstellen.
- [ ] Ergebnisse liefern (Bericht, Grafik, Ergebnis)

**Comment by JensSoares** [comment]
Duplikat.
