### ISSUE TITLE
EUROSTUDENT Steering Board (ESB)

### ISSUE THREAD

**Issue by JensSoares** [dzhw/zofar#447]
- [x] Projekt planen.
- [x] First Draft - Fragebogen:
- [x] Fragebogen (xml) erstellen und layouten.
- [x] Logo einbinden.
- [x] Datenschutz in der Index einbauen.
- [x] Fragebogen testen.
- [x] Abstimmung des Fragebogens mit Projektleiter.
- [x] Projekt scharf schalten.
- [x] Token erstellen.
- [x] Zugangslinks mit den Adressdaten verknüpfen.
- [x] Einladungen versenden.
- [x] Datenauswertung.
- [x] Grafik erstellen.
- [x] Ergebnisse liefern (Bericht, Grafik, Ergebnis)

**Comment by JensSoares** [comment]
Mit folgendem Link kommt man zur Befragung (Mit Jenkins)
http://vmtest.dzhw.local:8080/eurostudent_steering_board/page1.html

**Comment by JensSoares** [comment]
[EUROSTUDENT-SteeringBoard_ESB_PV.docx](https://github.com/dzhw/zofar/files/7224046/EUROSTUDENT-SteeringBoard_ESB_PV.docx)

**Comment by SilinaSchirmer** [comment]
@andreaschu: Die Befragung ist nun vollständig als englisches Projekt eingerichtet 🥳

**Comment by dzhwmeisner** [comment]
I'm working on it...

**Comment by dzhwmeisner** [comment]
shall the previous Botton to be removed at the end-Page?
