### ISSUE TITLE
glitter for showroom 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#448]
Let's make the showroom - as much as it exists of up to date - shiny.

----------
**To Do's zum finishing:**

- Beispielfragen:
	- [x] horizontale Einfachauswahl (mit verschiedenen Skalenlängen (5er und 11er-Skala), mehr und weniger lange Label)
	- [x] Einfachauswahl mit DropDown (mit und ohne missing-Kategorie, mit und ohne Units)
	- [x] Kalendarium
	- [ ] semantisches Differenzial
	- [x] Abgleich mit altem Showroom (z. B. Einfachauswahlfragen)
- Texte vereinheitlichen (dazu screenshot der Befragung)
	- [x] Anrede - Dutzen!
	- [x] gendern - mit * (Bspw. Lehrer*innen)
	- [ ] Textform und -stil
- Text-Arbeit (Ästhetik, Verständlichkeit, Einheitlichkeit, Vollständigkeit)
- Check aller Verlinkungen:
	- [ ] SideBar-Verlinkungen
	- [ ] Verlinkungen auf den Seiten
	- [ ] Befragungsflow checken
- Layout checken und vereinheitlichen
	- [x] Abstände checken und vereinheitlichen zwischen Überschrift und Text
	- [ ] Abstände zwischen mehreren Fragen
- [x] Content für Mehrsprachigkeit (see #451)
- [ ] Content für Zugang zur Befragung

- Screenshots und Bilder einfügen
	- [ ] 'inhaltlicher Fortschrittsbalken' (z. B. Nacaps oder Studpanel --> Einverständnis einholen)
	- [x] Einverständniserklärung

**Comment by JensSoares** [comment]
Die folgenden Einträge im Literaturverzeichnis haben einen "kaputten" Link.

- Informationszentrum Sozialwissenschaften (Hg.) (2003): Online-Erhebungen. 5. Wissenschaftliche Tagung. Bonn. Link online verfügbar, zuletzt geprüft am 08.11.2016.
- Krosnick, J. A. (1999): Survey Research. In: Annual Review of Psychology 50, S. 537–567. Link online verfügbar, zuletzt geprüft am 08.11.2016.
- Menold, N.; Kaczmirek, L.; Lenzner, T.; Neusar, A. (2014): How Do Respondents Attend to Verbal Labels in Rating Scales? In: Field Methods 26 (1), S. 21–39. Link online verfügbar, zuletzt geprüft am 08.11.2016.
- Moors, G.; Kieruj, N. D.; Vermunt, J. K. (2014): The Effect of Labeling and Numbering of Response Scales on the Likelihood of Response Bias. In: Sociological Methodology 44 (1), S. 369–399. Link online verfügbar, zuletzt geprüft am 08.11.2016.
- Nielsen, J. (2004): Checkboxes vs. Radio Buttons. Link online verfügbar, zuletzt geprüft am 08.11.2016.
- Pannewitz, J. (2002): World Wide Web-gestützte Befragungen in der empirischen Sozialforschung: Ein Erfahrungsbericht (WZB Discussion Paper, No. FSI 02-105). Link online verfügbar, zuletzt geprüft am 08.11.2016.
- Smyth, J. D.; Dillman, D. A.; Christian, L. M.; Stern, M. J. (2004): How Visual Grouping Influences Answers to Internet Surveys. American Association for Public Opinion Research. Link online verfügbar, zuletzt geprüft am 08.11.2016.

**Comment by JensSoares** [comment]
Die Links auf der Seite "Doppelmatrix" funktionieren nicht.
![Doppelmatrix - Links führen zu DZHW Seite existiert nicht](https://user-images.githubusercontent.com/90899449/133799652-a863777c-c866-46b6-ad3f-4373f56db183.png)

**Comment by JensSoares** [comment]
Bei den Matrizen überlappen sich oft Beschriftungen.
![Matrix mit Einfachauswahl - Beschriftung überlappt](https://user-images.githubusercontent.com/90899449/133799841-f4b6d8ed-3635-4ccb-b50c-258e38e86d4b.png)

**Comment by JensSoares** [comment]
Bei Preloads reagiert der Link gar nicht.
![Preloads - siehe auch Abläufe Preloads - leitet nicht weiter](https://user-images.githubusercontent.com/90899449/133799937-9f4df8b8-6ae5-4a32-9a30-71d022b88552.png)

**Comment by andreaschu** [comment]
@ParmidaZarei could you correct the links in the showroom? And - if possible - it would be great if you find working links for the paper.

> Die folgenden Einträge im Literaturverzeichnis haben einen "kaputten" Link.
> 
>     Informationszentrum Sozialwissenschaften (Hg.) (2003): Online-Erhebungen. 5. Wissenschaftliche Tagung. Bonn. Link online verfügbar, zuletzt geprüft am 08.11.2016.
>     Krosnick, J. A. (1999): Survey Research. In: Annual Review of Psychology 50, S. 537–567. Link online verfügbar, zuletzt geprüft am 08.11.2016.
>     Menold, N.; Kaczmirek, L.; Lenzner, T.; Neusar, A. (2014): How Do Respondents Attend to Verbal Labels in Rating Scales? In: Field Methods 26 (1), S. 21–39. Link online verfügbar, zuletzt geprüft am 08.11.2016.
>     Moors, G.; Kieruj, N. D.; Vermunt, J. K. (2014): The Effect of Labeling and Numbering of Response Scales on the Likelihood of Response Bias. In: Sociological Methodology 44 (1), S. 369–399. Link online verfügbar, zuletzt geprüft am 08.11.2016.
>     Nielsen, J. (2004): Checkboxes vs. Radio Buttons. Link online verfügbar, zuletzt geprüft am 08.11.2016.
>     Pannewitz, J. (2002): World Wide Web-gestützte Befragungen in der empirischen Sozialforschung: Ein Erfahrungsbericht (WZB Discussion Paper, No. FSI 02-105). Link online verfügbar, zuletzt geprüft am 08.11.2016.
>     Smyth, J. D.; Dillman, D. A.; Christian, L. M.; Stern, M. J. (2004): How Visual Grouping Influences Answers to Internet Surveys. American Association for Public Opinion Research. Link online verfügbar, zuletzt geprüft am 08.11.2016.
