### ISSUE TITLE
calendar: show type if "name" is empty

### ISSUE THREAD

**Issue by se-lang** [dzhw/zofar#455]
For episodes not asking for a name (implemented for "Studium" at the moment) there is no label for the episode in the context menu (besides the colored bar on the left). There should be e.g. the Label of the category I think.
The other way round: When entering a name before selecting "Studium" this name is still saved and consequently displayed in the context menu at the moment.

**Comment by se-lang** [comment]
I think it's absolutely plausible not to ask for a name for several types of episodes and I like the vanishing field. I suppose it could be implemented the other way round, too, coudn't it? So e.g. the name field would show up when a specific type of episode is selected.
The only change I would suggest in this regard is a rule that replaces the the possibly existing string in a open text field by "" if the corresponding field is hidden. 
Regarding the first point: I am not completely sure what should be displayed. The "easiest" option in my opinion would be the labels from the dropdown menu. However, most of these labels are presumably too long to serve as a label in the context menu. Two possibilities that occur to me spontaneously: (1) short labels (probably difficult in terms of content); (2) display only a part of the label and fade it out, or display "..." instead of the rest (sounds more complicated to me but possibly easier in terms of content).

**Comment by christian-fr** [comment]
status update for this issue is needed
