### ISSUE TITLE
open fields with search-as-you-type function (unit test)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#456]
For the decision between #369 and #445 an unit test have to be written.
metrics: 
- loading time per page
- loading time until a specific input is recommended

**Comment by dzhwmeisner** [comment]
done.

Page1 = StartWith Searching by JS
Page2 = native html5 fulltext Searching

frontend = loading time consumed by Browser-Side
backend = loading time consumed by Server-Side

**waitedForListItem**

page1 
write "Agraringenieur/in (FS) - Landwirt. Versuchswesen (Tierpr.)" to each input Field and take time until according item exists in suggestion-list which is loaded from an local list



page2
take time until according item to  "Agraringenieur/in (FS) - Landwirt. Versuchswesen (Tierpr.)"  exists in suggestion-list. The List is filled asynchronous after loading of page is done by a remote requested Json object


[timing.csv](https://github.com/dzhw/zofar/files/7380448/timing.csv)
