### ISSUE TITLE
archetype: layout.properties

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#458]
please add layout.properties for questiontext in archetype:

```
QUESTIONTEXT_START=<span class="font_weight" style="font-size: 1.6rem;font-weight: 600">
QUESTIONTEXT_END=</span>
```

**Comment by dzhwmeisner** [comment]
there is already 
QUESTION_START=<span style="font-size: 1.6rem; font-weight:600;">
QUESTION_END=</span> in archetype.

adding neverless?

**Comment by vdick** [comment]
is added

**Comment by vdick** [comment]
new build of archetype is done

**Comment by andreaschu** [comment]
i close it then.
