### ISSUE TITLE
Prozessoptimierung, sodass wir alle besser planen können?

### ISSUE THREAD

**Issue by anneweber** [dzhw/zofar#461]
Hey liebes Zofar-Team,

anknüpfend an die Scrum-Schulung wollte ich fragen, ob wir uns kommendes Jahr vielleicht mal austauschen wollen, ob wir den Prozess zum Fragen-Metadatenexport noch so verbessern können, dass wir alle besser planen können.

Meine Anregung wäre (ich muss aber auch zugeben, dass ich gerade nicht mehr genau auf dem Schirm habe, ob das evtl. schon mal besprochen wurde - wenn ja, sorry schon mal vorab!), dass wir ja vielleicht anpeilen könnten, dass nach jeder fertigen Fragebogenprogrammierung, die ins Feld gegangen ist, immer der Metadaten-Export für das FDZ am Ende des Prozesses steht. Vielleicht mit kurzer Abstimmung dazwischen, ob wir ihn wirklich brauchen - aber in der Regel sollen ja alle Daten früher oder später im FDZ veröffentlicht werden. Ihr könntet dann direkt damit planen, es würde von unserer Seite aus wahrscheinlich keine Eile bestehen (denn bis die Daten dann bei uns landen und veröffentlicht werden, dauert es ja meistens noch ein Weilchen), aber die Metadaten lägen dann immer schon vor, wenn mit einer SUF-Erstellung bei uns begonnen würde. 

Vielleicht gibt's aber auch was, was ich nicht bedacht habe? Ihr könnt ja einfach mal sagen, was Ihr dazu meint (ich bin jetzt erst mal im Urlaub, daher nicht wundern, wenn ich erst im kommenden Jahr reagiere).

**Comment by anneweber** [comment]
@andreaschu 
@AndyDaniel1 und ich haben über diesen Punkt letztens noch einmal gesprochen. Wollen wir dazu mal einen Termin vereinbaren?

**Comment by andreaschu** [comment]
Ich mach das hier mal zu. Den Termin gabs ja schon und ein paar Abstimmungen im Repo-Wiki: https://github.com/dzhw/zofar-fdz/wiki
