### ISSUE TITLE
calendar: logic for child events

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#466]
Sometimes it is needed, that the question flow works different for a new created event by splitting (_child event_), than for the original event (_parent event_).

For zofar programmer a qml-form is needed to extract the information from JSON-object wether it is a child event or a parent event, in the way it can be used for transitions.

![grafik](https://user-images.githubusercontent.com/30111489/155345598-87d8ba54-268a-4c84-9d29-b6c91dc7e051.png)

**Comment by dzhwmeisner** [comment]
working on zofar functions to extract parent/child informations

**Comment by dzhwmeisner** [comment]
Methods added as ZofarFunctions to FunctionProvider

boolean hasSplitChilds(final JsonObject episode)
List<Integer> getSplitChildIds(final JsonObject episode)
boolean hasSplitParent(final JsonObject episode)
Integer getSplitParentId(final JsonObject episode)

Request for integration to qml and testing

**Comment by dzhwmeisner** [comment]
Functions almost integrated to qml. will be commited soon.

**Comment by christian-fr** [comment]
We need a status update for this issue. And, possibly, a refinement / DoD.

**Comment by andreaschu** [comment]
Outdated. 
New method see in https://github.com/dzhw/zofar/issues/497.
