### ISSUE TITLE
calendar: edit events for touchscreens

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#467]
As a respondent I want to edit an already present event on JS-calendar via the touchscreen of my mobile device.

**Comment by dzhwmeisner** [comment]
implemented in current Rollout by open dialog by long tap at month

**Comment by dzhwmeisner** [comment]
request for testing

**Comment by dzhwmeisner** [comment]
fixed for iphone

**Comment by andreaschu** [comment]
Works well. I close this issue.
