### ISSUE TITLE
calendar: add counter to name for child events

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#469]
As a respondent I want to distinguish a splitted event (child event) from the original (parent event) easily.
Since all properties are duplicated except the dates, it is hard to figure out what happenend and what event I am going to edit.

It would be helpful if there is an identifier added to the name, like a counter, e.g.:
- parent-event: [{"name":"abc"}]
- first child-event: [{"name":"abc (1)"}]
- second child-event: [{"name":"abc (2)"}]

**Comment by christian-fr** [comment]
DoD:
If we created a child episode via split, we see the modified name of the child episode with a suffixed `"(1)"`.
If there already is a suffix of pattern `" \([0-9]+\)"` then the number of the child episode will be incremented by 1.

- [ ] We implemented this.
- [ ] We updated the test cases for splitEpisode() accordingly.

**Comment by dzhwmeisner** [comment]
implemented, Test updated, commited and deployed  Request for test
