### ISSUE TITLE
modernizing verifier

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#47]
adjusting the verifier to the current status

**Comment by dzhwmeisner** [comment]
<plugin>
				<groupId>zofar.testing</groupId>
				<artifactId>verifier</artifactId>
				<version>1.0.2-SNAPSHOT</version>
				<configuration>
					<contentPath>${basedir}/src/main/resources/questionnaire.xml</contentPath>
					<svnServer>https://vmvcs.dzhw.local</svnServer> <svnUser>gast0</svnUser> <svnPass>gr7a3v</svnPass> 
					<svnPath>svn/hiob/trunk/zofar/zofar.service/zofar.service.questionnaire/zofar.service.questionnaire.xml/src/main/xsd/de/his/zofar/xml</svnPath> 
					<qmlSchemaFileName>zofar_questionnaire_0.2.xsd</qmlSchemaFileName> <navigationSchemaFileName>navigation_0.1.xsd</navigationSchemaFileName> 
					<displaySchemaFileName>display_0.1.xsd</displaySchemaFileName> <researchdatacenterSchemaFileName>researchdatacenter_0.1.xsd</researchdatacenterSchemaFileName>
				</configuration>
				<executions>
					<execution>
						<id>validate-qml</id>
						<phase>validate</phase>
						<goals>
							<goal>validate-qml</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

**Comment by Miktarbad** [comment]
Modernized.
