### ISSUE TITLE
calendar: logic problem for error messages

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#470]
On pages where dates are filled in for new episodes, we may have a logical pitfall:
While leaving these pages, the conditions are asked if the dates are plausible; when implausible the condition for the same page is fullfilled and the page will be reloaded with loading an error message in view.
On the other hand, while (re-)entering these pages, the variables will be deleted what causes that the conditions for the error-message are not fullfilled

How can we solve that?

![grafik](https://user-images.githubusercontent.com/30111489/155345735-a379acf6-4dbb-4fc7-b303-987dc25b0550.png)

**Comment by christian-fr** [comment]
I just commited a draft version of softforcing within our new JSON-Framework.
It works on this page, a sort of logic template can be derived from this.

**Comment by christian-fr** [comment]
fully implemented in project `lhc_methodentest`, `questionnaire1.xml` on page **vaa01**, revision 20109
