### ISSUE TITLE
calendar: dialog finishing

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#472]
The dialog works well. Maybe the buttons should be repositioned and becom more visible. This issue is open for some points we get as feedback.
- the buttons for 'save' and 'back' are very small.
- I would expect the 'save' button on the left or on the bottom (on the right side)
- The word 'event' is a bit irritating. Maybe we can leave it blanc or we find a more suitable name

**Comment by christian-fr** [comment]
Status quo 2022-04-06:

![grafik](https://user-images.githubusercontent.com/42959832/161949527-2291ff96-ed92-40f0-a786-399addf1760e.png)

**Comment by christian-fr** [comment]
see also: #516

**Comment by vdick** [comment]
optimized and implemented (Test_Modul; lhc_methodentest), should works after next rollout

**Comment by andreaschu** [comment]
looks good. 
Only internationalizing the text elements (title, warning messages) are still open.

**Comment by andreaschu** [comment]
We refactoring the warning messages with bootstrap warning modal (https://jsfiddle.net/54y82xn9/).

**Comment by andreaschu** [comment]
change the order of name and type to first type and then name (with conditional visibility).

**Comment by andreaschu** [comment]
I close this issue, because I splitted it into smaller ones (#532, #533, #534)
