### ISSUE TITLE
calendar: episodes without type?

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#474]
Currently it is possible to define episodes without a type. Since this doesn't makes sense it shouldn't be possible.

As a researcher I would find it usefull to define some informations of episodes that are needed, otherwise the episode will not be saved.
As a respondent I would like to get feedback, if I forgot to indicate the type of an episode.

**Comment by dzhwmeisner** [comment]
Default Type implemented in Test_Modul
Request to test

**Comment by christian-fr** [comment]
Successfully tested, issue can be closed
