### ISSUE TITLE
Zofar-Export: Studienberechtigtenpanel 2018

### ISSUE THREAD

**Issue by anneweber** [dzhw/zofar#477]
Liebes Zofar-Team,

könntet Ihr uns bitte die Metadaten für das Studienberechtigtenpanel 2018 exportieren?

Wenn ich die mir vorliegenden Infos richtig verstehe, war die erste Welle eine PAPI-Befragung und die zweite Welle eine Mixed-Mode-Befragung (PAPI/CAWI) und der CAWI-Part wurde mit Zofar durchgeführt - ist das so korrekt? Dann bräuchten wir den Export also zu Welle 2 mit den folgenden Eckdaten:

- dataAcquisitionProjectId: gsl2018
- studyId: stu-gsl2018$
- instrumentId: ins-gsl2018-ins2$
- dataSetId: dat-gsl2018-ds1$

Könntet Ihr uns neben dem normalen Export bitte auch die gesamte Programmierdatei (QML-File) und - falls vorhanden - die Flowcharts mitschicken?

Und könntet Ihr uns eine kurze Rückmeldung geben, wann das Issue bei Euch voraussichtlich bearbeitet werden kann?

Vielen lieben Dank schon mal und viele Grüße
Anne

---

Falls die dritte Welle auch mit Zofar durchgeführt wurde: Die Metadaten benötigen wir vorerst noch nicht, sondern erst zum Jahresende. Daher könntet Ihr das gerne auch schon irgendwann für den Jahresverlauf bei Euch einplanen, aber das hat dann keine Eile.

**Comment by anneweber** [comment]
@andreaschu Ich hab Dich jetzt hier mal testweise assigned - hat geklappt :)

**Comment by anneweber** [comment]
Hallo @andreaschu , ich glaube, wir haben die Metadaten hierzu noch nicht von Euch übermittelt bekommen, oder? Falls doch, sorry schon mal - durch Personalwechsel bei uns haben die Verantwortlichkeiten zwischendurch mehrmals gewechselt und dann ist es vielleicht untergegangen. (@kleindaniel81 )

**Comment by anneweber** [comment]
@andreaschu Könntest Du uns hierzu noch eine Rückmeldung geben? Lieben Dank!

**Comment by andreaschu** [comment]
@anneweber das mache ich heute. Entschuldige, dass es jetzt so lang gedauert hat.

**Comment by anneweber** [comment]
@andreaschu Super, lieben Dank. 👍 Ich bin ab morgen im Urlaub, aber Du kannst dann @kleindaniel81 Bescheid geben.
(@kleindaniel81 Du kannst den Export dann erst mal hier ablegen: `\\faust\Abt4\FDZ\4_Datenaufnahme\Intern\Studienberechtigtenpanel\gsl2018\v1.0.0\1_Materialübernahme_SIP-Erstellung\Zofar`)

**Comment by anneweber** [comment]
@andreaschu Ich bin nun aus dem Urlaub wieder da. Könntest Du uns noch einmal Bescheid geben, wie es mit dem Export aussieht?

**Comment by anneweber** [comment]
Liebe @andreaschu , kannst Du uns bitte hierzu ein Update geben?

**Comment by andreaschu** [comment]
@anneweber das MDM-Output, questionnaire.xml und FlowCharts (mit und ohne Variablen in .png und .gml-Format) liegen im Austauschordner: \\faust.dzhw.local\Abt4\Austausch\FDZ-zofar\StudPanel18-2

**Comment by anneweber** [comment]
Super, vielen lieben Dank @andreaschu 👍
