### ISSUE TITLE
calendar: white space between month

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#478]
There is a white space between the months within an episode. It would be great if the episodes would be one line over the whole length.

![grafik](https://user-images.githubusercontent.com/30111489/154951768-879ad8f5-417c-41df-98ae-00949aed377d.png)

**Comment by vdick** [comment]
desktop & tablet version implemented

**Comment by andreaschu** [comment]
works good for desktop browser and tablets. Only with view for small screens nothing has been changed yet.

**Comment by christian-fr** [comment]
still to do: add some space inbetween different episodes
