### ISSUE TITLE
calendar: JavaScript features for synchronizing table and calendar

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#479]
As a respondent I want to use the edit-Button to switch into the question list to change the episode details and the delete-button to delete an episode.

![grafik](https://user-images.githubusercontent.com/30111489/155344949-25e8f72c-5eda-4a0b-bb3f-e56c110c659d.png)

**Comment by dzhwmeisner** [comment]
implemented

**Comment by andreaschu** [comment]
Die trigger funktionieren zwar, aber für 'edit' ist der Trigger falsch. Es müsste zur Seite **vaa05** gehen.
![https://media.giphy.com/media/Mn4kr2DjIBUIZdNGBd/giphy.gif](https://media.giphy.com/media/Mn4kr2DjIBUIZdNGBd/giphy.gif)

**Comment by dzhwmeisner** [comment]
added edit buttons for episodes with state done. jumping to vaa05.
Request to test (Test_Modul)

**Comment by andreaschu** [comment]
@dzhwmeisner it works for type:Ausbildung. 
But the edit button for an event of type:Slot1 (Studium) for example also leads to the loop of type:Ausbildung (page vaa05). It should instead lead to the placeholder page: placeholder_module_1 (and placeholder_module_3 for type:Slot3 (Fort- oder Weiterbildung) and placeholder_module_5 for type:Slot5 (Erwerbstätigkeit))

**Comment by christian-fr** [comment]
issue can be closed;
edit button moved to: #494
