### ISSUE TITLE
calendar instrument

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#48]
Is it possible to display the calendar in form of a complete timeline (for mobile devices)? 

- Navigation from one end to another via horizontal scrolling (without scroll bar) or carousel. 
- Selecting events via a 'full screen overlay'-menu. 

![20171221_160438](https://user-images.githubusercontent.com/30111489/34523518-252f19c0-f098-11e7-93e2-b7dc67b9704c.jpg)

- years should be distinguishable while scrolling horizontal

**Comment by andreaschu** [comment]
Is it possible that an event will be filled out automatically when only beginning and end are marked?

**Comment by Miktarbad** [comment]
previous et: 96 (Sprint 7)

Concept done, further development in progress.

**Comment by kastirke** [comment]
RWD for calender [https://survey02.dzhw.eu/dev/](url)
Great draft! Thanks. 

[A] Shorten column texts (here month, e.g. Jan, Feb, ..., Dez; and for the smallest version 01, 02, ..., 12).
[B] In smallest version calender navigation overlay Jan and Feb as well as Nov and Dez. Shall we shift the navigators next to the grid.
[C] In smallest version the calendar borders directly on the DZHW-banner. Will there be a problem with the survey navigators?
![grafik](https://user-images.githubusercontent.com/30147532/37396232-9c2e529a-2778-11e8-9696-036af61e4605.png)

now checked with iPhone SE, iOS 11.2.6, Safari:
[D] Cannot select ""Aktivität auswählen". Buttons grays but selection field does not pop-up.

![img_8069](https://user-images.githubusercontent.com/30147532/37397307-90f36160-277b-11e8-9879-7578df6c46d7.jpg)

**Comment by andreaschu** [comment]
- for a better usability it would be great if the months could be shortened (Jan, Feb, Mrz, Apr, Mai, Jun, Jul, Aug, Sep, Okt, Nov, Dez) for smaller screens and turned upright for very small screens

some questions and suggestions:
1. is it possible to display the button (to select episode type) in the colour of the selected type?
2. is it possible to define a default text for the button (e.g. 'Bitte wählen Sie eine Aktivität aus')?
3. is it possible to omit the header for the displayed year and instead make the years for navigation bigger and more apparant (for small screens)?
4. is it possible to extend the choice option to the months line (for smaller screens)?
5. is it possible to use a swipe feature for the year navigator?

**Comment by dzhwmeisner** [comment]
- for a better usability it would be great if the months could be shortened (Jan, Feb, Mrz, Apr, Mai, Jun, Jul, Aug, Sep, Okt, Nov, Dez) for smaller screens and turned upright for very small screens

==> not implemented up to now

some questions and suggestions:
1. is it possible to display the button (to select episode type) in the colour of the selected type?
=> done

2. is it possible to define a default text for the button (e.g. 'Bitte wählen Sie eine Aktivität aus')?
=> done

3. is it possible to omit the header for the displayed year and instead make the years for navigation bigger and more apparant (for small screens)?
=> done

4. is it possible to extend the choice option to the months line (for smaller screens)?
=> not sure if realizable in the current structure. need to be checked

5. is it possible to use a swipe feature for the year navigator?
=> not sure if realizable in the current structure. need to be checked

**Comment by dzhwmeisner** [comment]
Need to be tested

**Comment by dzhwmeisner** [comment]
[A][B] fixed. need to be tested

**Comment by dzhwmeisner** [comment]
seems to be fixed. (tested on saucelabs) Need to test

**Comment by dzhwmeisner** [comment]
Not working EventType Selection dialog on iOS fixed

**Comment by se-lang** [comment]
Tested Galaxy S5 mini - firefox 60.0.2 - Android 6
[D] Is it possible to reduce the white space between the box for selecting the event type and the calendar (only in landscape mode)?
[E] Even if I just tip on the display these blue signs for selecting text appear and sometimes "alles markieren" covers the months. I didn't manage to get rid of them.
[F] Months are still too long for vertikal mode, perhaps you could turn the text 90°, moreover I would remove the dot after abbreviated months.
[G] Navigation buttons for the years are a little bit too small for the text.
![screenshot_2018-06-18-17-47-21_1529336899609](https://user-images.githubusercontent.com/35341060/41547324-36220386-7320-11e8-8f4e-9d00fcb9b7d8.png)
![screenshot_2018-06-18-17-46-34_1529336900150](https://user-images.githubusercontent.com/35341060/41547325-36423296-7320-11e8-8021-c0ec28bfc995.png)

**Comment by Miktarbad** [comment]
[H] Button Size for the carousel a bit to small
