### ISSUE TITLE
calendar: make table content human readable 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#481]
As a respondent, I want to get the feedback for an episode within the table to get a better overview.

As a zofar-programmer, I want to have as less effort as possible to define the content for the feedback table, so that it is as less as possible prone to error.

![grafik](https://user-images.githubusercontent.com/30111489/165549397-95572459-1820-4124-a00d-6eca7570bd6f.png)

**Comment by christian-fr** [comment]
needed features: show split criteria

**Comment by andreaschu** [comment]
Definition of Done for Sprint 43:
![grafik](https://user-images.githubusercontent.com/30111489/165543564-893dac40-facc-49c0-b972-ff1bb2cd2762.png)
