### ISSUE TITLE
Zofar-Export: DEKiF

### ISSUE THREAD

**Issue by anneweber** [dzhw/zofar#487]
Liebes Zofar-Team,

könntet Ihr uns bitte die Metadaten für das Projekt DEKiF exportieren?

- dataAcquisitionProjectId: decquanti
- studyId: stu-decquanti$
- instrumentId: ins-decquanti-ins1$
- dataSetId: dat-decquanti-ds1$

Könntet Ihr uns neben dem normalen Export bitte auch die gesamte Programmierdatei (QML-File) und - falls vorhanden - die Flowcharts mitschicken?

Und könntet Ihr uns eine kurze Rückmeldung geben, wann das Issue bei Euch voraussichtlich bearbeitet werden kann?

Vielen lieben Dank schon mal und viele Grüße
Anne

PS: Dieser Export https://github.com/dzhw/zofar/issues/477 hat Vorrang.

**Comment by vdick** [comment]
@andreaschu 
https://myshare.dzhw.eu/index.php/f/525053
