### ISSUE TITLE
calendar: automated testing for zofar functions

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#488]
As a developer I need an automated testing strategy for zofar functions to find bugs later more easily.

We need: 
- [x] framework: where? when? how? what? 
- [x] list of zofar functions
- [x] test cases

**Comment by christian-fr** [comment]
list of zofar functions:
- `delJson()`
- `countEpisodesRatio()`

implemented test case `inputJsonString01`/`inputJsonArray01` :
```
[
	{
		"id": 0,
		"name": "123",
		"type": "Slot1",
		"typeColor": "blue",
		"startDate": "2018-01-01T01:00:00.000Z",
		"endDate": "2020-04-20T01:00:00.000Z",
		"state": "new",
		"slot": 0,
		"color": "blue"
	},
	{
		"id": 1,
		"name": "123",
		"type": "Slot5",
		"typeColor": "brown",
		"startDate": "2019-03-01T01:00:00.000Z",
		"endDate": "2021-03-20T01:00:00.000Z",
		"state": "new",
		"slot": 1,
		"color": "brown"
	},
	{
		"id": 2,
		"name": "Arbeiten",
		"type": "Slot2",
		"typeColor": "red",
		"startDate": "2019-03-01T01:00:00.000Z",
		"endDate": "2022-12-20T01:00:00.000Z",
		"state": "new",
		"slot": 2,
		"color": "red"
	},
	{
		"id": 3,
		"name": "sonstwas",
		"type": "Slot6",
		"typeColor": "yellow",
		"startDate": "2021-03-01T01:00:00.000Z",
		"endDate": "2024-03-20T01:00:00.000Z",
		"state": "new",
		"slot": 0
	}
]
```
jUnit-Tests are implemented for both functions. Maven goal `test` not implemented yet.

**Comment by christian-fr** [comment]
Maven goal `test` successfully implemented. 

Unit-tests are run everytime the presentation.surveyEngine is being built.

![grafik](https://user-images.githubusercontent.com/42959832/159897448-932ba20a-ee33-4475-9ce5-83937aaf2388.png)
