### ISSUE TITLE
info-button

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#493]
As researcher I sometimes need space for further explanation of items or answer options. Because the page shouldn't be stuffed with too much text, it should only be pop up if the respondent decide to need more information. 

It could look like this: 
![grafik](https://user-images.githubusercontent.com/30111489/165496981-5aaa2844-5a63-4a38-a89d-089ae4582e9f.png)

**Comment by andreaschu** [comment]
Here is a html-page as mockup with bootstrap tooltip. It works via overlay for first and second answer option.
[Beispiel-TooltipOverlay1.zip](https://github.com/dzhw/zofar/files/8571239/Beispiel-TooltipOverlay1.zip)

**Comment by andreaschu** [comment]
@AndyDaniel1 wir diskutieren gerade über eine neue Funktion in Zofar für erweiterte Erklärungen in Antwortoptionen und ggf. Items. Ich frage mich dabei, ob und wie dieser Text im MDM dokumentiert werden sollte. 
Evtl. habt Ihr Ideen oder Erfahrungen mit anderen Tools. Wenn ja, würde ich mich über Input freuen.

**Comment by vdick** [comment]
@andreaschu wie besprochen :)
https://presentation.dzhw.eu/static_tooltip/zofar_demo.html

**Comment by andreaschu** [comment]
current status as html-page: [Tooltip_Vorlage1.zip](https://github.com/dzhw/zofar/files/8618909/Tooltip_Vorlage1.zip)

it's now this: 

![Screenshot 2022-05-04 at 10-55-20 Zofar Demo](https://user-images.githubusercontent.com/30111489/166651948-d0724b81-b90c-49f3-ad82-4926d2ea0eeb.png)

or that
![Screenshot 2022-05-04 at 10-54-42 Zofar Demo](https://user-images.githubusercontent.com/30111489/166651965-c70defb2-8244-43ba-9c11-7c2d536022b9.png)


Open questions/issues: 
- distinguish click events select radio button from open tooltip
- keep it responsive: adaptive design and usable for touch screens
- enhance layout: the button should be as close on text as possible
