### ISSUE TITLE
monthpicker as question type

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#495]
As a researcher I want to use the monthpicker from within the modal of the calendar as a single question type in the questionnaire (outside of the calendar). 
As a zofar user I need to have a qml representation of the question type monthpicker.

**Comment by vdick** [comment]
file:///home/Dick/Downloads/monthpicker_clearButton.png

**Comment by vdick** [comment]
![grafik](https://user-images.githubusercontent.com/30229065/165738325-b9889318-df23-4b41-bcc7-ed2e2896c475.png)

**Comment by vdick** [comment]
Der "ClearButton" funktioniert wie erwartet. Diese Option wird nur für den standalone Monthpicker-Fragetyp verwendet
