### ISSUE TITLE
calendar: split stack

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#497]
As a researcher I need a function/ a container for saving information to split episodes after finishing one loop.

**Comment by christian-fr** [comment]
first draft of unit tests / test cases is committed as `JSONFunctionsTest.java`

**Comment by dzhwmeisner** [comment]
splitEpisode Method implemented in FunctionProvider.
Method isSplitable in progress

**Comment by dzhwmeisner** [comment]
isSplitable implemented
