### ISSUE TITLE
Bug in Carousel

### ISSUE THREAD

**Issue by dzhwmeisner** [dzhw/zofar#50]
If two Carousels are on one page. Both change header title simultaneous, when slide in one of the carousels is changed

**Comment by Miktarbad** [comment]
which page contains two Carousels?

**Comment by dzhwmeisner** [comment]
need to be tested http://vmtest.dzhw.local:8080/devhtml5/page3.html

**Comment by FineCordua** [comment]
looks good!

**Comment by Miktarbad** [comment]
Tested on multiple displays, is working accordingly.

Issue closed.
