### ISSUE TITLE
calendar: Episoden ohne gültiges Datum via Tabellen-Modal

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#501]
![grafik](https://user-images.githubusercontent.com/30111489/170232712-3bd35128-863c-4ad4-9f1f-3b07a8420919.png)

**Comment by dzhwmeisner** [comment]
deployed. Request to  test

**Comment by andreaschu** [comment]
Die Episoden erhalten den Status "updated", wenn sie über das Modal des Table Calendars erstellt werden. Dadurch greifen ein paar der Transitions nicht.
