### ISSUE TITLE
calendar: "dauert noch an" / "beginnt vor"

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#502]
![grafik](https://user-images.githubusercontent.com/30111489/170233416-9bcc8769-51cb-4f68-b5e6-f38367b96b9e.png)

**Comment by vdick** [comment]
in progress

**Comment by vdick** [comment]
first draft deployed

**Comment by vdick** [comment]
neue Version ausgerollt (Monthpicker werden deaktiviert)
