### ISSUE TITLE
calendar: make graphic calendar configurable

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#503]
As a zofar programmer I want to configure the graphic calendar via Zofar-QML.
I need to configure:
- [x] calendar range
- [x] number and label for Slots
- [ ] modal content
- [ ] …

**Comment by dzhwmeisner** [comment]
in progress

**Comment by dzhwmeisner** [comment]
modal content is know configurable. As example moved the type- configuration to a variable called episode_property_type_value

**Comment by dzhwmeisner** [comment]
request for test

**Comment by christian-fr** [comment]
configuration is working, issue closed
