### ISSUE TITLE
calendar: internationalization of calendar (modal, table calendar and graphic calendar)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#504]
Sometimes the questionnaires are bilingual or multilingual. In this cases I need also the calendar with all its types (graphic and table) and elements (modal) translatable.

**Comment by dzhwmeisner** [comment]
implemented and deployed first draft

**Comment by dzhwmeisner** [comment]
in Test_Modul Language can be switched by 
https://presentation.dzhw.eu/Test_Modul/calendar.html?zofar_lang=en and
https://presentation.dzhw.eu/Test_Modul/calendar.html?zofar_lang=de

**Comment by christian-fr** [comment]
reviewed and tested, issue closed
