### ISSUE TITLE
calendar: functions for evaluate calendar and JSON Array

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#505]
As researcher I need some additional functions to evaluate the JSON Array for transition and plausible checks.

**Comment by andreaschu** [comment]
- [x] Episode bestimmten Typs vorhanden ja/nein 
 - zofar.hasEpisodes()
  - episodePresent(JSON_ARRAY, {"type":"NSET"}) --> bool  ~
  -> UnitTest fehlt noch

- [ ] Episode eines bestimmten Typs unter Zusatzbedingungen vorhanden ja/nein
  ~>>returns bool~
  ~episodePresent(~
	 --> Array of Filter-Maps: [{},{},{}] verodert --> nochmal checken, ob der Funktionsumfang derzeit schon gegeben ist
 
- zofar.hasEpisodes()
     - Flags noch ergänzen
     -> UnitTest fehlt noch
	 

- [ ] Maximum/Minimum eines Datums einer Episode bestimmten Typs unter Zusatzbedingungen; bspw. Minimum des Abschlussdatums wenn Episodentyp Studium und Studium abgeschlossen

	rangeMin / rangeMax als Plausibilierung (oder Ähnliches, wenn wir etwas Besseres finden)

	minValue(JSON_ARRAY, [{},{},{}], "PROPERTY/KEY", "rangeMin"="2020-...", "rangeMax"="2022..") -> minimum value
	maxValue(JSON_ARRAY, [{},{},{}], "PROPERTY/KEY", "rangeMin"="2020-...", "rangeMax"="2022..") -> maximum value

	   Bsp.:
	   minValue(json_array, [{"type": "NSET"}], "startDate") -> "2018-01..."
	
	--> Entwurf ist vorhanden, muss getestet und integriert werden
	-> UnitTest fehlt noch
	
	 
- [ ] Abgleich eines Datums in einer Episode mit einem anderen Datum; Bspw. Enddatum==Exitdatum
  ~--> hier evtl auch noch eine proximity-range (+/-)~
  -> JSONequals(JSON_ARRAY, index1, index2, "PROPERTY/KEY1", "PROPERTY/KEY2")
  -> return: 
      -1 Val1  < Val2
	   0 Val1 == Val2
	  +1 Val1  > Val2
	
	-> Konzeption und Implementation steht noch aus
	-> UnitTest fehlt noch

  
- [ ] Überlappung einer Episode mit einem (gefilterten) JSON_ARRAY -> bool
  -> Array filtern
  -> aktuelle Episode ggf. aus dem Array entfernen
  -> Überlappung bestimmen
  -> return true/false
  ==> Kommunikation ans Projekt: bei allen boolschen Funktionen ist "false" der default-Rückgabewerte bei Fehlern etc.
  
  ~ overlap(JSON_ARRAY, index, [{"type":"NSET", "state":"done"}]) -> bool ~
  
  ~ overlap(JSON_ARRAY, filter1=[{"type":"NSET", "state":"done"}], filter2=[{"type":"STUD", "state":"done"}]) -> bool ~
     ~-> keine Episode doppelt~
  
  -> Konzeption und Implementation steht noch aus

**Comment by christian-fr** [comment]
> * [x]  Episode bestimmten Typs vorhanden ja/nein
> 
>     * zofar.hasEpisodes()
> 
>     * episodePresent(JSON_ARRAY, {"type":"NSET"}) --> bool  ~
>       -> UnitTest fehlt noch
> 
> 
> > edit christian-fr: Testcases fehlen noch.
> 
>     * [ ]  Episode eines bestimmten Typs unter Zusatzbedingungen vorhanden ja/nein
>       ~>>returns bool~
>       ~episodePresent(~
>       --> Array of Filter-Maps: [{},{},{}] verodert --> nochmal checken, ob der Funktionsumfang derzeit schon gegeben ist
> 
>     * zofar.hasEpisodes()
>       
>       * Flags noch ergänzen
>         -> UnitTest fehlt noch
> 
> 
> > edit christian-fr: Können wir damit schon nach vorhandenen Flags sortieren? Testcases fehlen noch. Review fehlt.
> 
>     * [ ]  Maximum/Minimum eines Datums einer Episode bestimmten Typs unter Zusatzbedingungen; bspw. Minimum des Abschlussdatums wenn Episodentyp Studium und Studium abgeschlossen
>       rangeMin / rangeMax als Plausibilierung (oder Ähnliches, wenn wir etwas Besseres finden)
>       minValue(JSON_ARRAY, [{},{},{}], "PROPERTY/KEY", "rangeMin"="2020-...", "rangeMax"="2022..") -> minimum value
>       maxValue(JSON_ARRAY, [{},{},{}], "PROPERTY/KEY", "rangeMin"="2020-...", "rangeMax"="2022..") -> maximum value
>       ```
>        Bsp.:
>        minValue(json_array, [{"type": "NSET"}], "startDate") -> "2018-01..."
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       --> Entwurf ist vorhanden, muss getestet und integriert werden
>       -> UnitTest fehlt noch
> 
> 
> > edit christian-fr: Methode **arrayDateMinMax()** ist implementiert. Testcases sind eingebaut und aktiv. Review fehlt.
> 
>     * [ ]  Abgleich eines Datums in einer Episode mit einem anderen Datum; Bspw. Enddatum==Exitdatum
>       ~--> hier evtl auch noch eine proximity-range (+/-)~
>       -> JSONequals(JSON_ARRAY, index1, index2, "PROPERTY/KEY1", "PROPERTY/KEY2")
>       -> return:
>       -1 Val1  < Val2
>       0 Val1 == Val2
>       +1 Val1  > Val2
>       -> Konzeption und Implementation steht noch aus
>       -> UnitTest fehlt noch
> 
> 
> > edit christian-fr: **compareTimestamps()** ist implementiert. Testcases fehlen noch. Review fehlt.
> 
>     * [ ]  Überlappung einer Episode mit einem (gefilterten) JSON_ARRAY -> bool
>       -> Array filtern
>       -> aktuelle Episode ggf. aus dem Array entfernen
>       -> Überlappung bestimmen
>       -> return true/false
>       ==> Kommunikation ans Projekt: bei allen boolschen Funktionen ist "false" der default-Rückgabewerte bei Fehlern etc.
>       ~ overlap(JSON_ARRAY, index, [{"type":"NSET", "state":"done"}]) -> bool ~
>       ~ overlap(JSON_ARRAY, filter1=[{"type":"NSET", "state":"done"}], filter2=[{"type":"STUD", "state":"done"}]) -> bool ~
>       ~-> keine Episode doppelt~
>       -> Konzeption und Implementation steht noch aus
> 
> 
> > edit christian-fr: Ist als **overlapEpisodeWithArray()** implementiert. Testcases sind eingebaut und aktiv. Review fehlt.

[x] implementation
[x] test cases
[ ] code review

**Comment by christian-fr** [comment]
>     * [ ]  Episode eines bestimmten Typs unter Zusatzbedingungen vorhanden ja/nein
>       ~>>returns bool~
>       ~episodePresent(~
>       --> Array of Filter-Maps: [{},{},{}] verodert --> nochmal checken, ob der Funktionsumfang derzeit schon gegeben ist
> 
>     * zofar.hasEpisodes()
>       
>       * Flags noch ergänzen
>         -> UnitTest fehlt noch

[x] implementiert als **zofar.hasEpisodes()**
[ ] test cases
[ ] code review

**Comment by christian-fr** [comment]
>     * [ ]  Maximum/Minimum eines Datums einer Episode bestimmten Typs unter Zusatzbedingungen; bspw. Minimum des Abschlussdatums wenn Episodentyp Studium und Studium abgeschlossen
>       rangeMin / rangeMax als Plausibilierung (oder Ähnliches, wenn wir etwas Besseres finden)
>       minValue(JSON_ARRAY, [{},{},{}], "PROPERTY/KEY", "rangeMin"="2020-...", "rangeMax"="2022..") -> minimum value
>       maxValue(JSON_ARRAY, [{},{},{}], "PROPERTY/KEY", "rangeMin"="2020-...", "rangeMax"="2022..") -> maximum value
>       ```
>        Bsp.:
>        minValue(json_array, [{"type": "NSET"}], "startDate") -> "2018-01..."
>       ```
>       --> Entwurf ist vorhanden, muss getestet und integriert werden
>       -> UnitTest fehlt noch

- [x] implementiert als **arrayDateMinMax()**
- [x] test cases
- [ ] code review

**Comment by christian-fr** [comment]
>     * [ ]  Abgleich eines Datums in einer Episode mit einem anderen Datum; Bspw. Enddatum==Exitdatum
>       ~--> hier evtl auch noch eine proximity-range (+/-)~
>       -> JSONequals(JSON_ARRAY, index1, index2, "PROPERTY/KEY1", "PROPERTY/KEY2")
>       -> return:
>       -1 Val1  < Val2
>       0 Val1 == Val2
>       +1 Val1  > Val2
>       -> Konzeption und Implementation steht noch aus
>       -> UnitTest fehlt noch

- [x] implementiert als **compareTimestamps()**
- [ ] test cases
- [ ] code review

**Comment by christian-fr** [comment]
>     * [ ]  Überlappung einer Episode mit einem (gefilterten) JSON_ARRAY -> bool
>       -> Array filtern
>       -> aktuelle Episode ggf. aus dem Array entfernen
>       -> Überlappung bestimmen
>       -> return true/false
>       ==> Kommunikation ans Projekt: bei allen boolschen Funktionen ist "false" der default-Rückgabewerte bei Fehlern etc.
>       ~ overlap(JSON_ARRAY, index, [{"type":"NSET", "state":"done"}]) -> bool ~
>       ~ overlap(JSON_ARRAY, filter1=[{"type":"NSET", "state":"done"}], filter2=[{"type":"STUD", "state":"done"}]) -> bool ~
>       ~-> keine Episode doppelt~
>       -> Konzeption und Implementation steht noch aus
> 
> 
- [x] implementiert als **overlapEpisodeWithArray()**
- [x] test cases
- [ ] code review

**Comment by andreaschu** [comment]
Sind alle integriert und sollten funktionieren.
