### ISSUE TITLE
monthpicker: date format

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#506]
Let's change the date format of the monthpicker into a timestamp to harmonize it with other question types for dates and put it into a standardized format that could be internationalized more easily.

The format should be `2020-01-01T01:00:00.000Z`.
Set the day to the first day of month.

**Comment by vdick** [comment]
is ready for testing (test_modul)

**Comment by christian-fr** [comment]
Status quo:
> ![grafik](https://user-images.githubusercontent.com/42959832/175277467-6367fb61-479f-4275-8c2e-f34a3b1a8517.png)

monthpicker produces the following timestamp pattern:
`YYYY-MM-01T00:00:00.000Z`

but, to be consistent with the calendar, the hour should also be set to `01`:
`YYYY-MM-01T01:00:00.000Z`

**Comment by vdick** [comment]
no problem, I'll change it today

**Comment by christian-fr** [comment]
is working, issue closed
