### ISSUE TITLE
calendar: update button

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#507]
We should use the following Icon for the "update episode" event (via modal):

[modal.svg](https://user-images.githubusercontent.com/42959832/174596385-c6be6e77-c08e-4e1a-9704-e59b3b98f2a0.svg)

The edit button (go to edit page / "episodeUpdate" ) should be the edit button, as it is alredy implemented.

![grafik](https://user-images.githubusercontent.com/42959832/174596877-21906788-8a92-4a68-a110-6699a77c2f9f.png)

**Comment by vdick** [comment]
implmented, should works after next rollout of test_modul
