### ISSUE TITLE
calendar: changing episode type -> delete / create new

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#518]
# DoD
When we change the type of an episode:
- display two warning messages (analogous to "delete episode")
- determine maxID of json_array
- create new episode with id = maxID + 1 and some basic information copied from the
old episode:
  - startDate,
  - endDate,
  - name,
  - slot,
  - flags
- type will be set to the new type
- remove the old episode
-------------------------------
- [ ] We implemented a unit test for this.
- [ ] We implemented this on calendar page in both modals in "Test_Modul".

**Comment by christian-fr** [comment]
We need a zofar function to change the episode type. This function should take as arguments:
`JsonArray json_array, int episode_index, List<String> list_of_properties_to_keep`
It should return a `Map<String, Object>` of: 
  `"array": JsonArray; "new_episode_index": int` 
with the new _episode_index_ of the newly created, mostly empty episode.

Maybe we also create a function that only takes
`json_array, episode_index` as arguments and sets the following properties as default:
```
startDate
endDate
name
slot
flags
```

OPEN FOR DISCUSSION! (maybe another way is mor feasible)

**Comment by andreaschu** [comment]
For Javascript free version we need a page (episodeEdit) with basal information of the modal,
configuration of the tableCalendar it need to be adapted: when javascript is deactivated this page (episodeCreate -> episodeEdit) should be targeted when <add episode>-button is clicked as well as when <edit episode> - button is clicked.

**Comment by dzhwmeisner** [comment]
editPage created, Configuration of  episode table modified, Persistence Bug (after changing type in JS) fixed. commited & rolled out.
Request to Test

**Comment by andreaschu** [comment]
since page `episodeCreate` is triggered by button `Episode hinzufügen`, I filled the page (respectively added page and filled) with content and trigger of `editPage`. 

Did it for Test_Modul as well as for lhc_methodentest and adapted types in lhc_methodentest.

Checked with deactivated javascript. Works!
I close this issue then.
