### ISSUE TITLE
function provider: EpisodeFunctions

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#519]
We need a JSF FacesContext (??) mock for unit testing when using FunctionProvider methods in EpisodeFunctions and vice versa.

**Comment by christian-fr** [comment]
maybe this could help?
https://stackoverflow.com/questions/7334868/how-do-i-mock-a-jsf-facescontext-with-a-viewmap-for-unit-tests-outside-an-actual

**Comment by andreaschu** [comment]
Da das schon umgesetzt ist, mach ich hier mal zu.
