### ISSUE TITLE
function: akkordeon

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#53]
New function for presentation of a question/part of a question due to restricted space on mobile devices.

**Comment by Miktarbad** [comment]
Sprint 8: concept stands, wierd problems with existing formats (css structure)

Sprint 9: finding a solution using current framework

**Comment by vdick** [comment]
Please check Page10 on survey

**Comment by FineCordua** [comment]
Page 10 looks weird (according to Viktor); Browser: Chrome

**Comment by kastirke** [comment]
checked functionality with iPhone SE, iOS 11.3, Safari

**Comment by vdick** [comment]
color is optimized, please test

**Comment by Miktarbad** [comment]
i am pleased with the colorscheme

**Comment by Miktarbad** [comment]
@andreaschu @FineCordua is there anything to add concerning the colorscheme or is this matter/function accepted!?

**Comment by FineCordua** [comment]
Accepted!
