### ISSUE TITLE
calendar: modal/ dialog configurable

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#530]
As a zofar user I want to have some individual adaptions within the modal for my questionnaire like dynamic displaying/hiding text elements or input fields (name) or like using preloads for texts.

**Comment by andreaschu** [comment]
Let's keep it in additional.js (instead in qml) and do a documentation that explains it for all zofar programmer.

**Comment by vdick** [comment]
@andreaschu at the moment it isn't possible, because the label are defined in EpisodeRenderer

**Comment by andreaschu** [comment]
@dzhwmeisner and @vdick I guess it isn't achievable in this sprint to make it (labels etc.) configurable within additional-js, right? 
So let's at least add a text field, that is visible depending on the selected type (#531).

**Comment by andreaschu** [comment]
I close this. It's all modifiable and working as discussed.
