### ISSUE TITLE
calendar: additional text elements within modal/dialog with conditional visibility

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#531]
As a researcher I want to add more explanation within the modal that are visible depending on the selected type.

<img width="379" alt="Screenshot 2022-08-09 at 16-59-17 Zofar Demo" src="https://user-images.githubusercontent.com/30111489/183706459-784db167-b8af-4a35-9858-32dd3342ebe7.png">

**Comment by vdick** [comment]
first draft im Test_Modul verfügbar (zunächst konfiguriert für Studium und Erwerbstätigkeit )

**Comment by andreaschu** [comment]
One question regarding the first draft: Is this internationalizable with this solution?

**Comment by andreaschu** [comment]
Looks frighteningly similar to my handcrafted version.
The only thing is, that the text should be between type and name. Would that be possible?

![grafik](https://user-images.githubusercontent.com/30111489/186649157-96783b7b-75db-42eb-ac1a-aaeeafa0acf1.png)
