### ISSUE TITLE
calendar: adapt calendar range (minRange and maxRange) for calendar

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#535]
The calendar range should use at least years and months since otherwise only the whole year can be defined as range_start and range_end.

**Comment by vdick** [comment]
Implemented. To test, define (minMonth="01" and  maxMonth="12") in episodes/episodesTable  in QML

**Comment by andreaschu** [comment]
utilized it by changing minMonth and maxMonth in lhc_methodentest.
Works within modal: monthpicker grey out months out of range. 

![grafik](https://user-images.githubusercontent.com/30111489/185969468-3eaa0e75-eb83-4c4d-a73b-04f7fe88a75b.png)


Only it is not visible in graphic calendar. When user creates an episode with mouseover and crosses a month out of range, it will be interpreted as an episode without start- and enddate, like: 

![grafik](https://user-images.githubusercontent.com/30111489/185969899-e5d29ef2-3c6a-4c26-9305-0cf64168667a.png)

**Comment by vdick** [comment]
first draft:  implementiert und ausgerollt für Test_Modul

**Comment by vdick** [comment]
@andreaschu scrolling-bug fixed! Test-Modul frisch ausgerollt, bitte erneut testen. Die Änderungen gelten für alle Befragungen, müssen nur neu ausgerollt werden

**Comment by andreaschu** [comment]
yep, looks good. I close this issue.
