### ISSUE TITLE
implement "Nachfrage"-pages ("Gab es eine/weitere Episode...")

### ISSUE THREAD

**Issue by christian-fr** [dzhw/zofar#538]
Fully implement the "Nachfrage"-pages.

They shall be displayed for every relevant module after all previosuly created episodes are set to "done". They shall only be displayed until the MinCount of episodes of a certain type has been reached.

After they are answered with "No" once, they shall not be displayed for this type any more.

**Comment by andreaschu** [comment]
is implemented for all modules.
