### ISSUE TITLE
calendar: Darstellung von & in tableCalendar funktioniert nicht richtig

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#541]
Im tableCalendar wird die html-Kodierung nicht in ein Zeichen rückübersetzt. 
![grafik](https://user-images.githubusercontent.com/30111489/190107890-4ce981db-683c-474e-8b2b-1a8b8f911edd.png)

[siehe auch zofar_episode\calendar\#31](https://github.com/dzhw/zofar_episode_calendar/issues/31)

**Comment by andreaschu** [comment]
Methoden zur Darstellung `episode.get(episodeDetailes.get('property').getAsString()).getAsString()` noch mal durch eine function laufen lassen.

**Comment by vdick** [comment]
ist implementiert, einfach die gewünschte Befragung neu ausrollen und testen

**Comment by andreaschu** [comment]
funzt. Ich mach mal zu.
