### ISSUE TITLE
calendar: special characters in open questions

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#542]
When respondents put in special characters in open questions that will put in JSON-Array a message appears that unallowed characters encountered.

`Encountered " <ILLEGAL_CHARACTER> "\' "" at line 1, column 5.`

We need zofar functions for escape/unescape and include those in convienience methods for load and put in JSON-Array. We also need to pay attention on our usual functions/methods for saving variables.

**Comment by andreaschu** [comment]
Für JSON gefährliche Sonderzeichen müssen escaped (unicode-escape) werden und wieder zurück übersetzt werden. 
Konverter für (alle offenen) Textfelder muss geschrieben werden. Dieser Konverter muss mit dem Schadcode-Filter harmonieren.

Integrieren in zofar.toLoad() und zofar.toPersist().

**Comment by vdick** [comment]
ab nächsten Rollout der Befragung verfügbar, bitte ausgiebig  testen

**Comment by andreaschu** [comment]
Ich hab immer noch eine Fehlermeldung. :o(

![grafik](https://user-images.githubusercontent.com/30111489/193020029-e5a0da76-20f1-4049-87b3-1899e2ac30e6.png)

Aber es wurde ausgerollt. 
![grafik](https://user-images.githubusercontent.com/30111489/193020225-ffd27fff-2546-48c4-98fc-655adf998b3d.png)

**Comment by andreaschu** [comment]
Die Zeichen, die keine Fehler erzeugen, werden als `#` dekodiert und gespeichert

**Comment by vdick** [comment]
huch, sorry.. habe vergessen die SurveyEngine neu zu bilden, nun sollte nach einem neuen Bilden der Befragung alles funktionieren

**Comment by andreaschu** [comment]
Jetzt sieht es gut aus. Bleibt noch das \. Alle anderen Zeichen (die ich gefunden habe) habe ich getestet.

**Comment by dzhwmeisner** [comment]
Bugfix commited. Request to test (needs a rebuild of lhc_methodentest or Test_Modul)

**Comment by vdick** [comment]
tested, everything seems to be caught
