### ISSUE TITLE
calendar: add sort function for nextEpisode() 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#544]
Bestehende Funktion wird um Sortierung per Timestamps (startDate, EndDate, id - hard coded!) erweirtert
ggf. Testcases anpassen (neue Episode erstellen/ ergänzen)

**Comment by dzhwmeisner** [comment]
sorting logic added to nextEpisodeIndex. Junit-Test added and builded.
request for test

**Comment by andreaschu** [comment]
works (according to @christian-fr )
