### ISSUE TITLE
datatransfer calendar 

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#55]
transfer of data from calendar to other questions/sources.

**Comment by Miktarbad** [comment]
Sprint 8: a concept has been worked on / further concepts will be researched

Sprint 9: further concepts will be researched

**Comment by dzhwmeisner** [comment]
Methods to analyse Episodes added to page16 based on Data from the Calendarium of page15.
Need to test

**Comment by Miktarbad** [comment]
[A] there seem to be issues concerning the display functions (page16)

![screenshot_2018-06-18 zofar_page16](https://user-images.githubusercontent.com/29864065/41533618-b901e336-72fb-11e8-9ad4-e7450a352179.png)

[B] 'page14pre' doesn't do anything

![screenshot_2018-06-18 zofar_demo_p14pre](https://user-images.githubusercontent.com/29864065/41533721-0df3d174-72fc-11e8-978d-43aa33e7e8a3.png)

**Comment by andreaschu** [comment]
seems not to work (see annex)
[DisplayCalendar_DataTransferTest.pdf](https://github.com/dzhw/zofar/files/2198072/DisplayCalendar_DataTransferTest.pdf)

**Comment by andreaschu** [comment]
closed because of new project LHC
