### ISSUE TITLE
calendar: display of dates in tableCalendar

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#550]
In tableCalendar it would spare a lot of place if startDate and endDate of an episode were in one line, like this:
![grafik](https://user-images.githubusercontent.com/30111489/192762932-f6c8d3ac-e16a-43d3-b808-b1dc9afddb4c.png)

**Comment by vdick** [comment]
ist implementiert, einfach die gewünschte Befragung neu ausrollen und testen

**Comment by andreaschu** [comment]
looks great! I close this issue.
