### ISSUE TITLE
calendar: recording / doppelter Boden

### ISSUE THREAD

**Issue by andreaschu** [dzhw/zofar#553]
Um das Risiko eines Datenverlusts zu minimieren würden wir ggf. das Recording (Angaben der Serverlogs) verwenden.
Um abzuschätzen zu können, dass es keine (relevanten) Auswirkungen auf die Serverlast hat und aussagekräftig genug ist, prüfen wir vorher, was geloggt werden kann und welche Auswirkungen es auf die Performance (#482) hat.

**Comment by dzhwmeisner** [comment]
implemented. complete participant dataset will be written to a record file on Server (after OnExit-Trigger are executed), when participant leave page. Possible TODO: String compression
