### ISSUE TITLE
episoden: missing variables in episodes export

### ISSUE THREAD

**Issue by se-lang** [dzhw/zofar#558]
Im Export der Episodendaten abs21.1 fehlen folgende Variablen (für diese habe ich es explizit überprüft):
- voc014-voc017
- stu022-stu025
- int010-int013
- doc018-doc021
- oth011-oth014
- emp020-emp023
- sem019-sem022
- mpl014
- vermutlich ...

Glücklicherweise sieht das stark nach einem Muster aus: Es handelt sich bei allen fehlenden Variablen bisher um attatched open. Die Sets von Variablen sind z.B. jeweils die offenen Angaben zu unseren Ortsabfragen. Die SingleChoice mit "in Deutschland" und "nicht in Deutschland, sondern" sind immer vorhanden, die offenen Angaben zu Ort, ggf. PLZ, Land und Ort fehlen. Ich gehe also davon aus, dass uns alle attached open fehlen.

**Comment by se-lang** [comment]
Außerdem wäre es gut, wenn ihr noch folge Informationen in den Export aufnehmen würdet:
- parentEpisode
- childEpisode
- flags
- state

**Comment by se-lang** [comment]
> Welche Werte sind in der Variable 'childEpisodes'. Das können ja mehr als eine Child-Episode pro Parent-Episode sein, oder?

So wie ich das bisher immer verstanden habe, enthält `childEpisode` immer die ID der Child-Episode, die aus einer Parent-Episode hervorgegangen ist. Abstrakt:
- Befragter legt Episode 1 mit Split A und Split B an (Split-Datum A < Split-Datum B)
- Split A wird ausgeführt, Ergebnis: `[Episode 1, childEpisode 2], [Episode 2, parentEpisode 1]`
- Split B wird ausgeführt, (End-)Ergebnis: `[Episode 1, childEpisode 2], [Episode 2, parentEpisode 1, childEpisode 3], [Episode 3, parentEpiode 2]`

**Comment by se-lang** [comment]
@dzhwmeisner @andreaschu Wie gerade besprochen hier die Variablen, die laut meiner Syntax im aktuellen Export fehlen:
```
voc027 voc030 voc031 voc025 doc034 doc054 doc055 doc045 doc046 doc047 doc048 doc049 doc050 doc051 doc052 stu043 stu048 stu049 voc009 voc011_date voc019_date emp012_date emp017_date emp025_date emp029_date emp034_date emp038_date emp049 emp051 emp075 doc013_date doc023_date doc027_date doc030_date doc044 sem024_date sem026 stu011_date stu017_date stu033_date stu039_date stu041
```

Und hier etwas differenzierter und besser lesbar:
In keinem Export
```
voc027 voc030 voc031 voc025 doc034 doc054 doc055 doc045 doc046 doc047 doc048 doc049 doc050 doc051 doc052 stu043 stu048 stu049
```
- voc027 
- voc030 
- voc031 
- voc025 
- voc032 
- voc033 
- voc034 
- doc034 
- doc054 
- doc055 
- doc045 
- doc046 
- doc047 
- doc048 
- doc049 
- doc050 
- doc051 
- doc052 
- stu043 
- stu048 
- stu049

Nicht in neuem Export aber im alten
```
voc009 voc011_date voc019_date emp012_date emp017_date emp025_date emp029_date emp034_date emp038_date emp049 emp051 emp075 doc013_date doc023_date doc027_date doc030_date doc044 sem024_date sem026 stu011_date stu017_date stu033_date stu039_date stu041
```
- voc009 
- voc011_date 
- voc019_date 
- emp012_date 
- emp017_date 
- emp025_date 
- emp029_date 
- emp034_date 
- emp038_date 
- emp049 
- emp051 
- emp075 
- doc013_date 
- doc023_date 
- doc027_date 
- doc030_date 
- doc044 
- sem024_date 
- sem026 
- stu011_date 
- stu017_date 
- stu033_date 
- stu039_date 
- stu041

Bei den *_date-Variablen ist mir klar, dass die meisten davon bei regulär abgeschkossenen Fällen irrelevant und leer sind, bei Befragten mit Abbruch sollten sie zum Teil aber noch gefüllt sein. Hier möchte ich lieber im Zuge der Aufbereitung entscheiden sie zu löschen, als das von vornherein zu machen, weil ich so ggf. noch zusätzliche Indikatioren aus den Infos ableiten kann.

**Comment by se-lang** [comment]
@dzhwmeisner Ergänzung zu meinem letzten Kommentar: Es fehlen doch noch eine ganze Menge mehr Variablen. Ich habe alle mir jetzt nochmal alle Variablennamen aus dem xml genommen, die in einem persist-Befehl sind und den Export darauf gecheckt. Folgende Variablen fehlen nach diesen Abgleich:
```
voc009 voc011_date voc019_date voc025 voc026 voc027 voc030 voc031 voc032 voc033 voc034 stu009 stu011_date stu013 stu014 stu015 stu017_date stu020 stu033_date stu039_date stu041 stu043 stu048 stu049 fed009 sco011_date sco019_date sco022 sco023 sco024 sco026 sco027 doc008_date doc011 doc013_date doc016 doc023_date doc027_date doc030_date doc034 doc054 doc055 doc044 doc045 doc046 doc047 doc048 doc049 doc050 doc051 doc052 emp009 emp010 emp012_date emp017_date emp025_date emp029_date emp034_date emp038_date emp049 emp051 emp075 sem016 sem017 sem024_date sem026 typeColor color
```

**Comment by andreaschu** [comment]
@se-lang ein neuer Export (mit neuen Graphiken) wird zu Euch transferiert.
Bis auf die Variablen voc031, voc032, voc033 sowie color und typeColor sind alle Variablen im neuen Datensatz enthalten.
Die Variablen `voc031`, `voc032` und `voc033` gibt es im QML nicht. Da ist ein Unterschied zum lhc_methodentest.xml. Warum, weiß ich nicht (mehr). 

`color` und `typeColor` hatten wir mal rausgeworfen, weil es eine unnötige Episoden-Information ist.

**Comment by se-lang** [comment]
Ok, danke euch! Ich geb nochmal Bescheid wenn der Export "angekommen" ist und aus unserer Sicht alles passt.

Stimmt `voc031`, `voc032` und `voc033` gab es bei der abs21-Variante leider noch einen Fehler, die wurden nicht persistiert... @christian-fr meinte aber, dass ihr die vermutlich aus den Serverlogs rekonstruieren könntet (was zeitaufwendig ist).

Auf `color` und `typeColor` können wir verzichten, richtig.

**Comment by andreaschu** [comment]
Der Export (**abs21_export_2023-04-20.zip**) sollte jetzt im Ordner _P:\SLC\Cycle_2018_2021\Welle_4\02_Datenexporte_ZOFAR_ liegen.

**Comment by se-lang** [comment]
> Ich erinnere mich an die Diskussion. Aber die Fragen sind gar nicht im QML enthalten. Sie können also nicht mal beantwortet werden. Bei Abs17.2 gibt es die Note/bestmögliche und schlechtestmögliche sowohl für Abschlusszeugnis, als auch für Schulzeugnis. Bei Abs21 nur einmal. Die Seite ist etwas anders aufgebaut. Etwa so:
> # Abs21.1
> (...)

Ok, schau ich mir nochmal an, vielleicht bin ich da auch durcheinandergekommen.

Export schau ich mir gleich mal an, danke!

**Comment by andreaschu** [comment]
Ich schließe das Issue, da es aus meiner Sicht fertig ist.
