### ISSUE TITLE
'display'-component responsive

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#56]
convert the 'display'-component into responsive - including the child-elements "text" & "table"

table -> carousel

**Comment by dzhwmeisner** [comment]
basic implementation done, need to be tested http://vmtest.dzhw.local:8080/devhtml5/page13.html

**Comment by FineCordua** [comment]
- Years are missing in large scale
- Monthnames are too long, overwrite eachother in smaller scales
- Year 2017 seems to be not available in large scale but depicted in small scale

**Comment by kastirke** [comment]
using iPhone SE, iOS 11.3 Safari 

[D] I am not sure about what should be checked. Deliever portrait and landscape screenshots from iPhone SE.

![img_9044](https://user-images.githubusercontent.com/30147532/39425600-8bea764c-4c7c-11e8-92cd-005d7b66f8c8.PNG)
![img_9045](https://user-images.githubusercontent.com/30147532/39425601-8c0bf254-4c7c-11e8-9b2f-ba6e270a6ab8.PNG)
![img_9046](https://user-images.githubusercontent.com/30147532/39425602-8c284b2a-4c7c-11e8-96dd-5ae04ee2dc8f.PNG)
![img_9043](https://user-images.githubusercontent.com/30147532/39425603-8c48a514-4c7c-11e8-8b9c-92ab47cb2c1b.PNG)

![img_9058](https://user-images.githubusercontent.com/30147532/39425619-993c8b1e-4c7c-11e8-8ed3-91e18ca05984.PNG)
![img_9059](https://user-images.githubusercontent.com/30147532/39425620-995baba2-4c7c-11e8-8522-c8b5c4873a00.PNG)
![img_9060](https://user-images.githubusercontent.com/30147532/39425622-99814416-4c7c-11e8-8bca-84a7b3b5557c.PNG)
![img_9057](https://user-images.githubusercontent.com/30147532/39425623-999f3070-4c7c-11e8-8448-96cb8aaf2112.PNG)


![img_9050](https://user-images.githubusercontent.com/30147532/39425655-bf17ff6c-4c7c-11e8-98bd-c033ab544e50.PNG)
![img_9047](https://user-images.githubusercontent.com/30147532/39425656-bf344b54-4c7c-11e8-9fcb-51f62b13247e.PNG)
![img_9048](https://user-images.githubusercontent.com/30147532/39425657-bf500e70-4c7c-11e8-81ee-052210f15c32.PNG)
![img_9049](https://user-images.githubusercontent.com/30147532/39425658-bf738134-4c7c-11e8-8a9f-f092773c2476.PNG)


![img_9056](https://user-images.githubusercontent.com/30147532/39425671-d300f5ba-4c7c-11e8-8512-2c2ee9ed3e7a.PNG)
![img_9055](https://user-images.githubusercontent.com/30147532/39425672-d325cc50-4c7c-11e8-8ff6-23bd36026aea.PNG)
![img_9051](https://user-images.githubusercontent.com/30147532/39425676-d5dde018-4c7c-11e8-9cc3-66c1ab895fb7.PNG)
![img_9052](https://user-images.githubusercontent.com/30147532/39425677-d600a86e-4c7c-11e8-8fef-91ee82e1a7ec.PNG)
