### ISSUE TITLE
Matrix Question Open

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#61]
To Do:

- [ ]     Test Infrastructure
- [ ]     Formulate Test Cases
- [ ]     Write Unit Tests

**Comment by dzhwmeisner** [comment]
http://vmtest.dzhw.local:8080/Eurostudent2-0.0.1-SNAPSHOT/p03_18.html

Plugin, Renderer and CSS updated in Eurostudent VII
need to be reviewed
