### ISSUE TITLE
SC Matrix Dropdown/other versions

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#62]
Adjust the SC Matrix for other functionforms like SCM Dropdown etc.

**Comment by Miktarbad** [comment]
further testing via apple etc is needed

**Comment by Miktarbad** [comment]
tested further and:
[A] positioning of the dropdowns within the item seems a little of - its sticky to the top
[B] in light of the size of the drowdown windows, the item might look a little better if the height is increased (larger screen)

![mscdropdown-mobile](https://user-images.githubusercontent.com/29864065/41774120-a98083ce-761e-11e8-9edb-65f557a44ecb.jpg)

![mscdropdown-screen](https://user-images.githubusercontent.com/29864065/41774198-f4528c26-761e-11e8-86b0-bb2c68f64673.jpg)

**Comment by vdick** [comment]
please test again

**Comment by vdick** [comment]
test again

**Comment by Miktarbad** [comment]
on large widths the dropdowns could be closer to the item-texts (up to 770p its fine - more than that is too far away)

**Comment by Miktarbad** [comment]
last comment will be held and adressed seperately, SCM Dropdown functional and ready for useage

**Comment by FineCordua** [comment]
Sorry for the bad news, strange behaviour here: Second SCM looks like its under a magnifier.
[Dok1.docx](https://github.com/dzhw/zofar/files/2249067/Dok1.docx)

**Comment by Miktarbad** [comment]
appears to be a similar text-format problem, which is also seen in other types.

this needs to be adressed seperatly and generally.
