### ISSUE TITLE
button positions

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#63]
'Weiter' 'Zurück' 'Logout' Button Positions

**Comment by kastirke** [comment]
[A] Buttons should be flush with the viewport.

![grafik](https://user-images.githubusercontent.com/30147532/39570665-514a6994-4ec9-11e8-9820-c4a373a3cb13.png)

**Comment by vdick** [comment]
a new version is ready, please test ))

**Comment by Miktarbad** [comment]
looks good

**Comment by Miktarbad** [comment]
if there is no further issue with the buttons this can be closed.

a buttonproblem within the archetype willl be adressed separately
