### ISSUE TITLE
button adjustments

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#68]
repositioning the forward button on the right side of the screen.

logout to be removed for now - repositioning to the top on the right as a second version.

**Comment by FineCordua** [comment]
forward button seems very far away on large screen. Looks nice on small screen though.

**Comment by Miktarbad** [comment]
i would agree with the large screens, but we may need a little time to adjust to the change

**Comment by vdick** [comment]
logout icon replaced with a svg

**Comment by Miktarbad** [comment]
done.
