### ISSUE TITLE
XML modul clone generator

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#69]
a tool to clone and adjust already coded questionnaire loops

**Comment by Miktarbad** [comment]
initial implement done - needs to be tested and bugfixed.

**Comment by Miktarbad** [comment]
programming, documentation done - needs to be tested

**Comment by dzhwmeisner** [comment]
Template_ModulePrefix_cleaned.xml + 
        loopCount * 
            (Template_LoopPrefix_cleaned.xml + 
            splitCount * 
                (Template_SplitPrefix_cleaned.xml + Template_Split_cleaned.xml + Template_SplitPostfix_cleaned.xml) + 
            Template_LoopPostfix_cleaned.xml) + 
    Template_ModulePostfix_cleaned.xml


Platzhalter | Wertebereich | Dynamik | Anmerkung
----------|------------|-------|---------
[[modul]]|Modulname|Modul|Eingabefeld
|||
[[loop00]]|0|statisch|unabhängig von aktuellem Loop und Split
[[split00]]|0|statisch|unabhängig von aktuellem Loop und Split
|||
[[loop0]]|a|statisch|unabhängig von aktuellem Loop und Split
[[loop1]]|b|statisch|unabhängig von aktuellem Loop und Split
[[loop2]]|c|statisch|unabhängig von aktuellem Loop und Split
[[loop3]]|d|statisch|unabhängig von aktuellem Loop und Split
[[loop4]]|e|statisch|unabhängig von aktuellem Loop und Split
|||
[[split0]]|a|statisch|unabhängig von aktuellem Loop und Split
[[split1]]|b|statisch|unabhängig von aktuellem Loop und Split
[[split2]]|c|statisch|unabhängig von aktuellem Loop und Split
[[split3]]|d|statisch|unabhängig von aktuellem Loop und Split
[[split4]]|e|statisch|unabhängig von aktuellem Loop und Split
|||
[[loop]]|(a,b,c,d,e,...,z)|Loop|Startwert a
[[nextLoop]]|(b,c,d,e,...,z)|Loop|[[loop]] + 1, Startwert b
[[split]]|(b,c,d,e,...,z)|Split|Startwert b
[[nextSplit]]|(c,d,e,...,z)|Split|[[split]] + 1, Startwert c

**Comment by dzhwmeisner** [comment]
Deployed at http://vmdevwiki.dzhw.local/Generator/index.html

**Comment by dzhwmeisner** [comment]
placeholder added


Platzhalter | Wertebereich | Dynamik | Anmerkung
-- | -- | -- | --
[[preLoop]] | (a,b,c,d,e,...,y) | Loop | [[loop]] -1, Startwert 0
[[preSplit]] | (a,b,c,d,e,...,y) | Split | [[split]] - 1, Startwert a
