### ISSUE TITLE
pretest comment - class etc

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#77]
- [x] pretest comment area needs a css-class for easy manipulating access

and

- [x] distance between text "Kommentarfeld:" and box should be set on "auto" and there should be a 30 to 50 px top-margin to the rest of the content

- [ ] if possible, we need an easy access to rename the text - if via js or xml doesn't matter

**Comment by andreaschu** [comment]
- distance between text and box looks good to me
- distance between text and previous question could be a bit more

**Comment by Miktarbad** [comment]
distance to main-content could be generally set larger, or we adjust it individually if necessary ? 
@andreaschu

**Comment by Miktarbad** [comment]
resolved, closed
