### ISSUE TITLE
As a MDM user I need one screenshot document for each instrument

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#82]
For the MDM, we need the final instrument to be documented in ~MS Word~ Libre Office. We need a ~Word~ document containing one image of each zofar page per page.

- We need one document per language. 
- We will only document the biggest screen resolution in this document (*) (but NOT part of the header)
- format details
  - Header of page ("Kopfzeile"): subject -> check if this is already part of the screenshot
  - heading 1: Page number
  - ~heading 2: FDZ question number(s) page.Fragenummer~ we only have this for new projects #87 
  - example:
     - heading 1: "Page: 12"
     - ~heading 2: "Frage: 4,5"~
  - page break after each zofar page 
- build up folder structure for the export
- assign to @UteH for testing 
 
(*) we will document multiple screen resolution in `questions`

**Comment by UteH** [comment]
@dzhwmeisner will build the export for libre office. Everything else is ok.

**Comment by dzhwmeisner** [comment]
[Uploading instrument.pdf…]()

**Comment by UteH** [comment]
@dzhwmeisner dzhwis this the proper link  :see_no_evil:  :)?

**Comment by dzhwmeisner** [comment]
I need more patience.
[
[instrument.pdf](https://github.com/dzhw/zofar/files/2383871/instrument.pdf)
](url)

**Comment by dzhwmeisner** [comment]
images are a little bit blurred. Optimizing in progress

**Comment by UteH** [comment]
@dzhwmeisner 
looks good as a first try! Some remarks before official testing.
- We talked about using the 21. Sozialerhebung as a example because it is more complex. Would this be possible to do this for the 21. Sozialerhebung? (only D/BI?)
- We talked about working with .odt? Would this be possible?


### If you are done with developing the "final" version and want me to test this issue, please assign this issue to me and feel free to chance the label to "testing".

**Comment by UteH** [comment]
the images do not need to be searchable.

**Comment by UteH** [comment]
Hi @dzhwmeisner should I plan to be testing this issue today?

**Comment by UteH** [comment]
von @vdick: [instrument.zip](https://github.com/dzhw/zofar/files/2518199/instrument.zip)

I am to decide between odf and pdf

**Comment by UteH** [comment]
@vdick thanks! I am not sure about it as the texts are really hard to read in the odf due to the low resolution. 

I will talk to @anneweber and decide on Monday.

**Comment by dzhwmeisner** [comment]
Try to replace Libre-Office-Framework by a Remote-Framework to generate Document by an installed Instance of Libre-Office instead of headless generation
