### ISSUE TITLE
As a MDM user I need the dropdown lists to be in the questions JSON in order to find it in full text search

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#85]
We need all dropdown lists to be in the question JSON files (`additionQuestionText` #94). Otherwise, the entries of the dropdown menus cannot be foune in the full text search of the MDM.

Currently, only the German (or primary language of the survey) dropdown lists are in the question JSON files. Dropdownlists from other languages are stored in seperate lists and are thus not written into the question JSON files.

**Comment by dzhwmeisner** [comment]
in this issue only for scs2016. ssy21 in a separate issue

**Comment by dzhwmeisner** [comment]
@andreaschu will provide de/en file.

**Comment by dzhwmeisner** [comment]
[messages.zip](https://github.com/dzhw/zofar/files/2487184/messages.zip)

**Comment by andreaschu** [comment]
@UteH here is:
1. the merged translation 
[translation_de-en.xlsx](https://github.com/dzhw/zofar/files/2487734/translation_de-en.xlsx)

2. the deliverd translation by project team
[WB_uebersetzung_final_20160311.xlsx](https://github.com/dzhw/zofar/files/2487735/WB_uebersetzung_final_20160311.xlsx)

**Comment by dzhwmeisner** [comment]
Implemented in https://metadatamanagement-test.cfapps.io/#!/de/studies/stu-zofar221018$

Need to be tested

**Comment by UteH** [comment]
tested within #89
