### ISSUE TITLE
As a MDM user I need the "FDZ question" (now: project question) as QuestionNumber in the QML

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#87]
we need to define the "FDZ question" and how we can identify it in QML.

Each FDZ question needs a FDZ question number. Suggestion from AnneW regarding the format: 
`Page-ID.#` 

edit: regarding the questionNumber: we definitely need to figure out how to work with the project teams on using the same questionNumber format.   
(example: scs2016 delivered the questionnaire with a questionNumber format that the MDM cannot use. Thus, we had to change the questionNumbers but  now the new QuestionNumbers do not match the questionNumbers in the questionnaire).

**Comment by UteH** [comment]
@UteH will define FDZ questions using screenshots from the 21st social surveys.
Then @dzhwmeisner will evaluate if we need to define a FDZ question "manually" in QML or if we can use more automatic/technical aggregation.

**Comment by andreaschu** [comment]
We don't think it is usefull to let the question be defined (and marked) by the research team. 
In Zofar-terms a question is one cell in the PV. 
One question can only be attached to one page of the questionnaire.
The question will be flagged in the QML-document by the programmer. 

@andreaschu / @kastirke: in the "Konventionen für die Erstellung einer Programmieranleitung"  (http://dizi.dzhw.eu/wp-content/uploads/2016/08/Zofar_Programmieranleitung.pdf) should be a suggestion that each cell should only contain one question

**Comment by UteH** [comment]
@andreaschu thanks for the log. Did I get something wrong? pleas have a look at my remarks:

> We don't think it is useful to let the question be defined (and marked) by the research team.

-> I thought we agreed on a "[SISO](https://en.wikipedia.org/wiki/Talk%3ASISO)" which means rather "consitently wrong" than us disimproving something? So we do let the research team define the question (inderectly) by interpreting one cell as one question?  
-> suggestion: "The research team defines the fdz question by using the PV"

> One question can only be attached to one page of the questionnaire.

-> I did not get it in the first place so here my suggestion or am I disimproving?
-> suggestion: "a fdz question can only have one screenshot"? 
 (which means: a question cannot extend over several pages and thus cannot be attached to several images [as is in zofar])

**Comment by andreaschu** [comment]
Our discussion showed, that zofar-programmer need clear rules for tagging the questions.  
The best match to FDZ question would be to tag the zofar-question in QML (like: zofar:[questiontype]). That would lead to some outcomes for the question exports:
- the softforcing and hardforcing messages would not be included in question output
- validation messages of open question-types (like numbers, e-mail-adresses, grades) would be included
- combinations of different question types would be seperated in different questions (e.g. https://presentation.dzhw.eu/devhtml5/page18.html would be: 1. question text and open field as first question/picture and 2. checkbox with "Ich möchte mein Studienfach nicht angeben" as second question/picture) 

@UteH: Could you be more clear about the soft- and hardforcings and how to cope with combinated questions?
@dzhwmeisner: could validation messages of open questions be ignorated for a question screenshot?

**Comment by UteH** [comment]
here our comment:
- as you wrote above "a question is one cell in the PV"
- we **_do_** want the soft and hardforcing as part of the question
  - last week we discussed that we want it as part of the screenshot. For the JSONs it is sufficient to write it into the `additionQuestionText` (attribute for the full text search) (https://metadata.fdz.dzhw.eu/#!/de/questions/que-scs2016-ins1-1.1$?search-result-index=1)
- "validation messages of open question-types (like numbers, e-mail-adresses, grades) would be included" **_Can you give me an example?_**
- we would like these combinations of technical "zofar questions" to be **_one_** fdz question (example page18 would be **_one_** question

@andreaschu @dzhwmeisner I think we **_would_** like to have the validation messages as part of the screenshot - we want to show the MDM users what the survey participant saw. **_Can you give me an example?_**

@andreaschu what is the difference between soft and hard foring? the former will allow the useres to skip an the latter doesn't?

**Comment by UteH** [comment]
we will use the projects definition of questions according to the pv. We need to mark these in the QML. We need to decide how we do this. We talked about 
- naming the zofar questions according to pv if zofar question = project question
- tagging zofar questions with project question if a project question encompasses more than one zofar question
