### ISSUE TITLE
extended features of the calendar component

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#9]
**Participant:**
- i don't want to answer the same question twice

**User:**
- i want more features 
- i want the possibility for answers to be converted into episodes
- i want information given in the calendar to be shown on other questions
- i want to navigate with detailed information from the calendar (e.g. specific time periods)

**Service:**
- we want a process to recieve the requirements from the calendar by the User

**Dev:**
- no involvement, except a ton of work

**Comment by Miktarbad** [comment]
#55 #48

**Comment by andreaschu** [comment]
created to a project and splitted into single issues (e. g. issue #348).
