### ISSUE TITLE
bug: text-/size-format problem

### ISSUE THREAD

**Issue by Miktarbad** [dzhw/zofar#91]
there seems to be a general problem with text- and/or size-formation, mostly when two or more of the same types are used.
e.g. section, SCM Dropdown

possible correlation with uncounted class tags ?

**Comment by Miktarbad** [comment]
![1234](https://user-images.githubusercontent.com/29864065/43701599-14b69664-9957-11e8-82de-dea5a6cd0ed1.png)

**Comment by Brochterbeck** [comment]
Seems to be a renderer problem. In Work.

**Comment by dzhwmeisner** [comment]
renderer fixed. Maybe CSS alignment to left needed? Need to test
