### ISSUE TITLE
Storing paradata in database

### ISSUE THREAD

**Issue by kastirke** [dzhw/zofar#96]

**Comment by kastirke** [comment]
The following paradata should be storable in the SLC and other future project databases: 

- [ ] user agent strings

- [ ] screen resolution, screen orientation, size of the web browser window and/or viewport (depending on the current state of development)

The storage must not be made by default. It must be selectable, since a corresponding informed consent must be present for this.

**Comment by jocarstensen** [comment]
Is this implemented already in the SLC Pretest?

**Comment by kastirke** [comment]
@dzhwmeisner May you please give me the algorithm for the variable "isMobile"?

**Comment by andreaschu** [comment]
Web Browser is within the uas. 
As there is a new repository for paradate, this issue here will be closed.
