### ISSUE TITLE
As a MDM user, I need the Programmieranleitung to correspond exactly to the final instrument

### ISSUE THREAD

**Issue by UteH** [dzhw/zofar#97]
As the documentation of dynamic features proves to be quite difficult, we have come back to the idea to publish not only the final instrument but also the Programmieranleitung. As the Programmieranleitung includes all details of the instrument and its dynamics, we think this is the most efficient way to document this in a human readable way.

The only requirement is that the final Programmieranleitung corresponds _exactly_ to the final instrument. Thus, we need to make sure _only_ when the Programmieranleitung changed, the code changes. No exceptions. None. This way, the Programmieranleitung should correspond exactly with the instrument.

Let's discuss this :)

**Comment by andreaschu** [comment]
The project is responsible to update the Programmiervorlage (PV). Zofar-Team can not check if the PV is up to date. 

@andreaschu / @kastirke: Zofar-Team includes a recommendation into the "Konventionen für die Erstellung einer Programmieranleitung" (http://dizi.dzhw.eu/wp-content/uploads/2016/08/Zofar_Programmieranleitung.pdf) to keep the PV up to date
@UteH: FDZ also adds in the manual that the PV has to be the same as the instrument

In NACAPS the PV will be adapted in GitHub. Let's see this as a pilot for a new process.

**Comment by UteH** [comment]
@andreaschu i added the information to our document. If up have updated your PV we can close the issue :)
